
			How to play Afterburner

The rules for afterburner are quite simple, blow the fuck out of everything
that flies.

Your weapons...

Vulcan Cannon  --  a 20mm rapid-fire cannon capable of tearing opposing
                   aircraft to shreds.  To aim, use the small firing sight
                   on your screen.  When the enemy draw near, line the sight
                   upwith the aircraft and fire away.

Air-to-Air Missiles  --  Your most powerful weapon.  Line up target in your
                         gunsight.  When it starts flashing or a box appears
                         around it, fire a missile.

Refueling  --  When you see a navy fuel tanker above you,guide plane to
               refuling pipe and press button to receive fuel and ammo.

Controls

When game is loaded, keyboard control is default.  Press Ctrl-J for joystick.

Ctrl P- Pause  Ctrl S- Sound on/off  Ctrl Q- Music on/off  Ctrl X- Exit to dos

Arrow keys/joystick to maneuver

Fire cannon -  Space bar or joystick button 0
Fire missiles -  Enter or joystick button 1

To roll, press fire cannon, fire missiles, and direction to roll.

To accelerate, press cannon, missiles, and forward.

To decelerate, press cannon, missiles, and backward.


I hope you enjoy this INC Crack...

					--  JT
