                           INC 90 Presents
                           Battle of Atlantis  
                           Supplied BY: The Jet
                           Packaged By: Cool Hand
                           

Well this is a game Simular to The Game Risk... No copy protection
to speak of. Color I believe is EGA and with mouse support...Enjoy


Greets to my Pal's in Taiwan also to all of the crackers in the world..
Speacial Greets go out to Sewell Good Luck on the career move..

                                 Cool Hand
                                 