                                 Big Business
                                     by
                                   Digitek

Supports   : CGA/EGA/VGA, ADLIB
Supplied by: Jake Pickett
Packaged by: Line Noise

General Info:
                The box in which the game came with said, "No On-Disk
  Copy Protection", which usually means no key disk protection, but
  usually a doc check. After playing this game numerous times, and
  others as well, we have not found a doc check. If one is found, please
  let us know, and we will fix it promptly.

Greets to:  PE, NEUA, Buckaroo Bonzaii, Fire, Island Hacker, Luther,
            Jake Pickett, Cool Hand, Phantom, Bit Manipulator, Null Set.

