Crystals of Arborea                       No protection. * See Game Notes *
    by
      Silmaris

Game notes:   Before I begin, yes this game was released a few months ago by
THG.  But those geniuses over at THG released it in French only.  Here's the
english version of the game. No protection was found on this game, however the
game is poorly written according to Jake Pickett, since it fails to load the
program information properly every time.  This being the case, sometimes
it will run and sometimes it won't.  Let it be known, that if it
doesn't work, it is the companies' fault, and not INC's. In the future,
we may release a fix for this problem, but in the mean time, enjoy.  If
it doesn't work, try it again.

Special Hi's & Ho's
===================

The Stalker - be patient my son. J/k. Continue the good work.
Centurion - you called me once, now call me again.
Rekall - congrats on copylock.  Guess THG has been dethroned from
          copylock heaven.
Belgarion - Geek.
Lord Michael - See ya in two weeks, hehe.
