Double Dribble                               Supplied by Little Nemo
    by                                       Cracked by Jake Pickett
      Konami

Game info:  The game is definately a bad port from the popular Nintendo
version.  It could be worse though.  Game play is not that bad, but the
graphics only go up to EGA.  At least it has Adlib/Roland Support.

Jake's Notes:  On this one you just have to hit return on the doc check screen.
Sorry, but I could find no good way around this. This game has been tested on
all the graphic modes available (Hercules/CGA/EGA/Tandy) which is a good thing
since the protection code was found in all three of the graphic files (CGA/EGA
/TANDY).

Press any key to play Double Dribble...

