F29 Retaliator                               Supplied by Line Noise
    by                                       Cracked by Jake Pickett
      Ocean

Game info:  The game is pretty good if you like flight simulators. Nice
graphics and smooth scrolling but it could definately use better sound
support. Read the Jake's Notes for further relavent info.

Jake's Notes: First off, you MUST run this game from a directory off the root
called Retal. Sorry but this is the subdirectory the game automatically installs
in and apparently the only place the log can be stored. I did not have the time
to get around this slight annoyance.
On this one you just hit any key and enter on the doc check screen. Again I am
sorry but I could find no good way around this.






 