   Fountain of Dreams                        Released by INC on 09/21/90
      by Electronic Arts                     Brought to you by: Line Noise

512k Requried
Supports EGA , MCGA, VGA, and Tandy 16 color.
Supports No Sound Boards! Cheapo IBM Speaker only!

  Well, here's INC's & Electronic Arts' latest game. This one is called
  Fountain of Dreams. Game Play is similar to their old game called Wasteland.
  The question is when will EA release a 256 color RPG game. Who knows?
  This, like the others, is 16 color only, and supports no sound boards.
  You also have to go through a 2 minute installation. Not as bad as some of
  their old installs which took 10-15 mins. Anyways, once again, we beat
  the others on this game. That makes it two in a row. First Oil's Well,
  and now this. Look for much more from INC in the near future.
  I got this game extermely early, so I decided to type up the docs for
  it, which will help you enjoy the game much more. True it is only 16
  color, but this game is extremely well done, and the adventure is
  addicting. Trust me on that one. Spend a little time with it and you
  will be hooked as well. Anyways, docs are on the way, look for them.
  Don't forget to copy these files onto floppy, and install from there.
  Till next time....

