 
                            Decision at Gettysburg
                            Copy Protection: None
                            Supplied by    : Me

General Junk:

              Here's our latest release, Decision at Gettysburg.
    This one is really weird in that is is a total memory hog. For those
    of you who run the newer versions of DOS this should not be a
    problem. For all others remove any TSR's and if that doesn't work
    then let the game make you a bare minimum boot disk. Sorry it has
    to be this way but we don't write them we just get them out.

Typed quickly by: Line Noise [President]