                       -=INC=- Presents GOLDEN AXE
                        Supplied By: Jake Pickett
                         Cracked By: Jake Pickett


This game supports Joystick and is VGA, not to tuff to crack...

Well Greets to everyone; Kings Quest V is Kick Ass I will keep this 
short so I can get back to my game..


                             Cool Hand


Oh Yea Call The Mid-Nite-Oil I  BBS 214-298-4102 Games [INC] Dist Site.
            The Mid-Nite-Oil II BBS 214-255-8059 Utilitys
            Elm Street BBS 214-407-1801 NEUA Dist Site.
