Tony LaRussa's Ultimate Baseball                  Supplied by Bloody Butcher
      by                                          Cracked by Line Noise
        S.S.I.

General notes:  As you know it's been dead out there.  In fact, I don't
  believe an American game has been out for like 2-3 weeks.  The only
  games that have come out, which have been few, have all been European,
  and we all know American games kill European games.  Anyhow, it's a
  great game, and I hope this is only the beginning of the end of the
  dry spell.  See ya with our next crack.

Cracking notes:  Good ole' Norton has worked again!  Come on guys, let's
  give our cracker's some work, and get us some real protections. Just
  hit ENTER at the doc check.  No big deal.

Inductions to INC:  A big ole' welcome to these newest INC members/boards:

Bloody Butcher - The Splatterhouse (408) 263-6806
Honus Wagner + The Gecko - Final Fantasy (713) 568-5908
The Plague - The Vortex (602) 941-4295

give 'em a buzz.  And don't forget to call INC's WHQ:
    Star Frontiers  (305) 935-8834.
