Lorna: Goddess of Destruction             Released on 2/25/91.
    by                                    No protection on the game
      ?                                    that can be found.

General Info:
              Well, here's Lorna: Goddess of Destruction.  The game is from
  France, and therefore is in french, but thank god to all, that this
  game needs no words, and has very few of them.  The game reminds me a
  bit like Stromlord, except in this one, it's Lorna, the hoe, wearing
  practically nothing, searching throughout the jungle. I could not get
  anywhere in this game, which actually is not saying much.  It does
  need a cheat though, and if one of those wonderful groups, or maybe
  we will, make a cheat for this game, I and others playing this game
  would be so gracious.

Hi's & Ho's:
             Special thanks to Optical Illusion, and Many Axe for the
  helping get the game, and of course that nice person in France, who
  originally supplied it.  Give Many Axe's board a ring. It's called
  Banished Corrusive Poison.  Number can be found on most INC boards.
