
                                  I.N.C
                                  ÄÄÄÄÄ
  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³   Release ¯ Fix for Telix v3.20       º        Rating ¯ ²²²²²°°°°°      ³
  ³   Company ¯ Deltacomm                 º         Disks ¯ [1]             ³
  ³  Supplier ¯ Cracker Jack              º          Date ¯ 12/13/92        ³
  ³   Cracker ¯ Cracker Jack              º         Sound ¯ N/A             ³
  ³  Packager ¯ The Reaper                º      Graphics ¯ N/A             ³
  ³ Game Type ¯ N/A                       º    Protection ¯ N/A             ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

			Telix Version 3.20

This crack for the latest version of Telix, removes the beg screens at the 
opening and closing of the program.  It also removes a beg telephone number 
displayed after reading the telix configuration file.

To install the patch, load the Telix program into the directory of choice, copy
PATCHMKR.COM and INC.DAT into the same directory, then run PATCHMKR.  It is 
only necessary to run the patch one time to permanently "adjust" TELIX.EXE.

Enjoy!

  -= Cracker Jack =-


   Greets - Bar Manager, GateKeeper, Line Noise, Cracker Jack, Hellhound,
            The BBS Bouncer, Tj, American Galdiator, Force Ten, Cool Hand!

                              ÚÄÄÄÄÄÄÄÄÄÄÄ¿
                              ³ President ³
                              ÀÄÄÄÄÄÄÄÄÄÄÄÙ
                                Line Noise


                               ÚÄÄÄÄÄÄÄÄÄ¿
                               ³ Members ³
                               ÀÄÄÄÄÄÄÄÄÄÙ
                Bar Manager, The Cracksmith, GateKeeper,
     American Gladiator, HellHound, Dumper, Northwind, TJ
           Big Eddie, Null Set, The BBS Bouncer, The Devestator
             Cyanide, Black Adder, Digital Knight, Force Ten


                               ÚÄÄÄÄÄÄÄÄÄ¿
                               ³ Courier ³
                               ÀÄÄÄÄÄÄÄÄÄÙ
                 Wayne, Skybum, Gandalf, RipWave, The Rave


 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
 The Colisevm    ³  Courier HQ   ³   201-432-2535  ³  American Gladiator
 The Black Gate  ³  Dist Site    ³   212-796-9628  ³  GateKeeper
 Alters of Death ³  Dist Site    ³   416-XXX-XXXX  ³  Digital Knight
 Midnight Oil    ³  Dist Site    ³   214-XXX-XXXX  ³  The Reaper
 Cygnus-X        ³  Dist Site    ³   305-665-9646  ³  Spike
 Point Beyond    ³  Dist Site    ³   404-929-8901  ³  Tomcat
 Waves of Warez  ³  Dist Site    ³   206-644-4137  ³  RipWave
 House of Pain   ³  Dist Site    ³   813-349-9404  ³  Aeon Flux
 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ




