                          Vanna's Wheel of Fortune
                                     by
                                  Gametek

  Protection  - None.
  Supplied by - Anonymous.
  Graphics    - 256 Colors VGA / EGA / CGA
  Sound       - Adlib / Internal
  Packaged by - Line Noise

  Overall description :  Two words fit this game.  Much improved.  This
  version of the game is no means a lame release.  Good graphics, sound,
  and even Vanna herself.  Very addictive, just like the real show.

  Greets & Grunts:

  All Pirate Groups - Ok, you guys had your fun, now it's over.  Enjoy
  this and the many many releases coming from INC in coming days.

  USA/FLT - No, I'm not going to bash you guys for your known problems
  with Sierra games.  Just stop it.

  Razor 1911 - And bad news Brian?  I'm waiting.

