Megafortress                                Supplied by "Anonymous"
  by                                        No protection.
    Three-Sixty

General Notes:  Awesome game!  This is just simply amazing.  One problem
however, this game is extremely complicated.  You must have
documentation to play it.  Either someone has to scan it, which I'm not
even sure is possible with this game, or go buy it!  It's worth it!
Yet another INC great release.  See ya!

Greets -

THG - Don't understand the word of unity, eh?
Fairlight PC - Please, no god damn betas!  I understand you wrote don't
download if you don't want betas, but unfortunetly, you only read that
after you have downloaded it!
COOP - When is some European stuff coming, it's dead over there!
Razor - Best of luck.
Pirate World - Thank our friend and yours, Anonymous, for this and WC2.

You must install this game!
