INC'1990 Presents Stratego by Accolade 10/03/90
VGA version documentation check fixed by Jenetic Bytemare

	Hi this is a game that is based on Milton Bradleys board game.  This
is the 4th or 5th game I have done since I have moved into my new place.  The
byte patch I did was not a total success with a total overlap of 3 bytes which 
is used by the program when running in CGA, EGA, MCGA mode.  However since
most users have VGA monitors and the VGA mode offers the most colors and
highest resolution I have released this one first.  Sorry about this but
I have other things to do also!

-Jenetic Bytemare

To run the game type in GAMEVGA.EXE or type in STRATEGO.EXE for protected
version.  I tested out the save and exit features and they seem to work ok.
Let me know if this beasty needs another fix.

Don't forget to call the following fine boards:

	The Plutonium Mines (International) 716-427-2555
	The Plutonium Mines II (International) 716-334-4288
	Brokendown Palace 716-227-3806
	Infinite Intoxications 508-750-8035

Greets go out to: THG (Fletcher Christian & Eddie Haskel), PE (Terminator),
INC (Line Noise, Invisible Stalker, Bit Manipulator), The Specialist.

Don't forget to write us at our box.

INC'1990/Jenetic Bytemare
PO Box 26914
Rochester New York 14626

INC'1990/Head Quarters
8365 Parklane PO Box # 200
Dallas Texas 75231


