                      International Network of Crackers
                          Canadian / International
                            Member / Distribution
                                   Sites

1. Lost Souls Domain II.  (416) 246-9995.  No new-user password known.
    Running Celerity.  Canadian HQ.  Sysop is Optical Illusion.

2. Inn of the Last Home.  (705) 522-6774. No new-user password known.
    Running Celerity.  Courier Board.  Sysop is Caramon Majere.

3. Banished Corrosive Poison.  (514) 523-3399.  No new-user password known.
    Running Teleguard.  Distribution Site.  Sysop is Frozen Tormentor.

4. The Hellzone.  (+61) 7-849-8424.  No new-user password known.
    Running Celerity.  Distribution Site.  Sysop is Gnarly Beast.

5. Shattered Dreams.  (+31) 79-523-762.  No new-user password known.
    Running PC-Board.  Distribution Site.  Sysop is Xtra Mega.

6. West Side.  (+49) 221-526-072.  No new-user password known.
    Running PC-Board.  Distribution Site.  Sysop is Vic.

7. Fat Cat City.  (613) 830-1229.  No new-user password known.
    Running LSD.  Distribution Site.  Sysop is Magic Man.

8. The Exorcist.  (+49)
