INC'91 - Klax by Tengen - Supplied by Line Noise
Cracked by J.Pickett

	Hi this is J.Bytemare here, the crack was actually done first by
J.Pickett since I was curious as to the encryption routine on this program
I was more or less absorbed into understanding it and its protection rather
then banging out a patch.  Since J.Pickett told me it was a local CALL I
found the questioned CALL and removed it.  Anyways I PKLited the file to
reduce it back down to original size.  I am not sure if J.Pickett cracked it
this way but I was told to release it as is so ... Credit goes to J.Pickett.

-J.Bytemare
