


Always had a comment, question, suggestion, donation, complaint, cough,
             hiccough, sneeze, shit, squirt, splatter, scream, tear,
             or bomb for INC? Well here is yer chance to let it all out!

The International Network of Crackers proudly presents, the DOCS, CHEATS,
             HINTS, WAREZ Box-

             A national PO BOX for you to send all of the above, and to re-
             quest any of our fabulous games! That's right, send a self-abused
             stomped elephant to:

             INC '90 Mailbox
             8365 Park Lane #200
             Dallas, TX 75231

             We would love to hear from you what you think of us, so please send             all your donations and such in ASAP!

          -WHo carez if this aint an INC ware? - INC is Omnipresent
