
                             *** INC Presents ***

                                    Midway
                                      by
                           General Quarters Software

                              Cracked by Null Set

Greetings, kind folk.  Null Set here.  Including packaging, this was about
a half hour deal.  Real pathetic.  But, hey, they all can't be beasts.

The game was written in BASIC, but it looks like it was done better than
most BASIC games.  It has stunning CGA graphics and full IBM speaker sound
support (oooo!).  Read the README.INC file for a list of active keys.
See you all in my next effort.

Greets to: All of my INC brothers, especially Cool Hand (who gave me this one),
Line Noise, The Jet (who supplied us with this one), Bit-Manipulator (got that
one yet?), and Jenetic Bytemare (stage 1 of the challenge is done - working on
stage 2!), and our worthy competition.

