
                            Mystical by Infogames
                            Copy Protection: None
                            Supplied by    : Me
                            Graphics       : CGA/EGA 16 color

General Junk:

              Here's our latest release, Mystical from Infogames.
    Strange game.  I am not really sure what the object of this game is,
    but it doesn't look to hard to figure out.  Not a bad day for the
    pirate world.  THG released Dragon's Lair II, PE released Rick
    Dangerously II, and INC released Mystical, and 4-D Driving.  Not a
    bad day at all.  Sure as hell beats these past couple of weeks.  Any
    how, enjoy it, and have a great time playing these games.

Typed quickly by: Line Noise [President]

