                           -=INC=- 90 Presents
                                Route 66
                          Supplied By: Winplace

Well here is another Road Racing Game, for you old Timers remeber The Show
A long time ago..

Docs out soon from The Jet we are also working on the docs for Eye of The
Beholder...
Go See Silence of The Lambs cool Movie... 

Diont forget to call Winplace's Board
                     Wasteland II
                     (503)667-1101
                     
                     Later Cool Hand
