Slordax                               No protection on the game.
   by                                 Trainer included by Dr. Detergent of INC
     Softdisk

General stuff:  Well, the game itself is not half bad.  EGA, I know, but
after a while you get used to it.  The game is impossible, and even with
the trainer should take you a while to finish.  If you wish to use the
trainer, type TRAINER.COM at the dos prompt.  Also, for help inside the
game, such as to choose keyboard/mouse/joystick or to configure any of
those, hit F1 anytime during game play.  Enjoy it!

