Stratego by Accolade            
 Fixed by R. Bubba Magillicutty
 Info file written by Line Noise

  Well, here's Stratego for EGA, MCGA, and CGA. It will also work with
VGA if you would like to use it. Now, here's instructions on what to do:

1. Take INC's initial crack of Stratego, and copy it to floppy. This game
   does not need to be installed, but it works alot smoother installed.

2. Install whatever version you wish, including the VGA if you would
   like to.

3. Take the STRATINC.COM that comes in this Zip file, and copy it over
   to the directory you installed this game into.

4. Run STRATINC from now on, and you can get all Graphic modes to work.

This game represents alot of hard working time trying to crack it from
Jenetic Bytemare, and R. Bubba Magillicutty. Terminator of PE also
worked on it a bit. In any case, this fix (I guess you could call it
that since it enables you to get EGA/MCGA/CGA. Most people have VGA
anyhow, but this is for those who dont have it. Enjoy the game!

