

  Tiebreak Tennis                 Supplied by: Billy Name
        By                        Packaged by: Billy Name
      Starbyte Tennis


Well, here is another tennis game.  No protection on this one.  Game play
is probably its best feature.  Realistic in the way and how hard you hit the
ball, besides where it goes.  Just like real tennis.  Unfortunately, unless I
am overlooking something, there is no sound support in this game.

Billy's Note:
-------------

Well, this one has been on order for awhile.  And the reason INC got it, is
because Line Noise was the one who told me about it.

Dont Forget to Call:

The Realm of Madness - [714] 837-8821 - INC COURIER SITE - Sysop: The Stalker!
------------------------------------------------------------------------------



