INC'91 - Xenocide by ????
Supplied by Line Noise
Cracked by Jenetic Bytemare

	Hi, here is a game I bypassed the doc check, let me know if you
have any problems since I am rushed for time.

-Mike

Don't forget to call The Plutonium Mines (716) 334-4288 or (716) 427-2555
both lines are HST v.42bis - INC'91 with IBM and Amiga support.

Greets go out to Razor/1911, DefJam/Angels, P.E./Terminator, F.Christian/THG
BitManipulator/INC'91, Null Set/INC'91
Luther/INC'91 - Ranger Rick/TSAN'91

