FDENABLE        .EQU    1	; TRUE FOR FLOPPY SUPPORT
FDMODE          .EQU    FDMODE_SCOTT2 ; FDMODE_DIO, FDMODE_ZETA, FDMODE_DIDE, FDMODE_N8, FDMODE_DIO3
FDTRACE         .EQU    0	      ; 0=SILENT, 1=FATAL ERRORS, 2=ALL ERRORS, 3=EVERYTHING (ONLY RELEVANT IF FDENABLE = TRUE)
FDMEDIA         .EQU    FDM144	      ; FDM720, FDM144, FDM360, FDM120 (ONLY RELEVANT IF FDENABLE = TRUE)
FDMEDIAALT      .EQU    FDM720	      ; ALTERNATE MEDIA TO TRY, SAME CHOICES AS ABOVE (ONLY RELEVANT IF FDMAUTO = TRUE)
FDMAUTO         .EQU    1	      ; SELECT BETWEEN MEDIA OPTS ABOVE AUTOMATICALLY
DSKYENABLE      .EQU    0
