INC'1990 Presents Fix for Initial Buck Rogers

	Run this new BUCK.EXE after installing game - problem with
the bad guys attacking each other is gone.


Don't forget to call the following fine boards:

	The Plutonium Mines (International) 716-427-2555
	The Plutonium Mines II (International) 716-334-4288
	Brokendown Palace 716-227-3806
	Infinite Intoxications 508-750-8035

Greets go out to: THG (Fletcher Christian & Eddie Haskel), PE (Terminator),
INC (Line Noise, Invisible Stalker, Bit Manipulator), The Specialist.

Don't forget to write us at our box.

INC'1990/Jenetic Bytemare
PO Box 26914
Rochester New York 14626

INC'1990/Head Quarters
8365 Parklane PO Box # 200
Dallas Texas 75231


