                        DRACULA (CRL)
                        -------------

Part 1:(From outside the inn) E, PAY COACHMAN, E, S, LOOK
DESK (there is a bell and a book), RING BELL (the innkeeper arrives), SIGN REGISTER, N, E, SIT, READ MENU (your order is taken), LAMB, WATER (you eat...), W, U, UNLOCK DOOR, OPEN DOOR, N, CLOSE DOOR, LOCK DOOR, CLOSE WINDOW, SLEEP (the inn is attacked by birds, but you are safe), WAIT (4 times), UNLOCK DOOR, OPEN DOOR, S, D, W, LOOK AROUND (you find a bench), SIT, WAIT (4 times. A coach appears. The driver asks for your name), HARKER (you board and ride along...)


Part 2: EXAMINE EYES (you wind up with a nightmare), WAKE UP (the woman gives you a cross), WEAR CROSS, WAIT (5 times; it is time to change coach. Are you off to see Dracula?), YES, BOARD COACH (it is very cold), LOOK AROUND, LIFT SEAT, REMOVE CROSS, LOOK DOOR (it has a keyhole), INSERT CROSS, TURN CROSS, OPEN DOOR, LOOK HOLD (you find some blankets and soon arrive at the castle), W, S, LOOK AROUND (here are the stairs), U, EXAMINE FRAME, EXAMINE BAT, TOUCH MOUTH (the bell rings. Dracula leads you inside), LOOK AROUND, LOOK TABLE (you see a tray), GET TRAY, N, GET CLOTH, POLISH TRAY (you get shaved), W, W, N, LOOK AROUND (you see a closet), OPEN DOOR, N, LIFT RAIL, S, MOVE WARDROBE (the is an opening in the floor), S, WAIT (you get some sleep), WAIT (5 times. You eat), LOOK TABLE, GET BOTTLE, SMASH BOTTLE (this gets you a shard of glass), W, S, E, LOOK WINDOW, CUT CORD (with the shard), W, W, GET CORD, N, DROP CORD (you go to sleep), E, W (the day has gone), GET CROSS, WAIT (5 times. 3 girls - vampires! - appear), WAVE CROSS (they vanish), E, S, E, S, W, GET LAMP, W, S, E, N, W, N, W, N, GET CORD, D, D, D, DROP LAMP, W, TIE CORD, LOOK WINDOW, WAIT (you notice the count leaving), D, LOOK AROUND, MOVE CARPET (you see a trapdoor), OPEN TRAPDOOR, D, LOOK ROUND (the count's coffin is here), OPEN BOX, LOOK BOX (yes, he is in it!), DROP CROSS, S, S, S (you have escaped from the castle)


Part 3: W, W, LOOK CHAIR, GET COAT, LOOK POCKET (you find your money), E, S, E, E, N, BUY NEWSPAPER, READ NEWS, TURN PAGE, READ NEWS (it says something about 50 coffins and Hawkins & Co. in Stratford), E, N, W, LOOK S (you find a letter from Harker), E, S, S (the last train has left), N (Renfield follows you), W, W, W, N, E, E, SLEEP, W, W, S, E, E, E, S (the man asks where you are going), STRATFORD, W, S, S (you board a train and enter a cab after arriving), HAWKINS AND CO (you go there and call for Dr. Van Helsing), W, W, W, N, E, E, SLEEP, W, GET NOTES, LOOK DESK, GET KEY, DROP NOTES, W, U, UNLOCK DOOR, LOOK AROUND (you see a net), GET NET, W, W, E, D, S, W, W, W, W, CLIMB TREE (Renfield is below you), THROW NET (and gets caught), W, S, W, W, W, N, W, N, W, S, E, S, S, S, W, N, W, GET STONE, S, E, E, E, E, E, LOOK HUT (it has a window), SMASH WINDOW (you grab an axe), W, W, W, W, W, S, S, E, E, LOOK AROUND (here is a tree), FELL TREE (it falls against the wall), W, S (a woman offers you some garlic flowers in return for the axe), GIVE AXE, N, E, U (up the tree), N, W, LOOK AROUND (you see a wine climbing down the wall), D, GET HANDLE, S, GET SACK, GET
HAY, N, E, E, N, GET DRAWER, LOOK CUPBOARD (you find a knife and take it), SHARPEN HANDLE (till it is VERY sharp!), S, E, E, LOOK AROUND (you see a door), EMPTY SACK, REMOVE MONOCLE, WAIT (until the sun shines on the door), FOCUS MONOCLE (the hay catches fire - the door burns), DROP FLOWERS, D, LOOK AROUND (here are 49 coffins), DROP CORN, WAIT, WAIT, WAIT (the count appears, but cannot pass the flowers), U (you fall through the stairs), LOOK AROUND, EXAMINE TOMB, REMOVE REMAINS, WAIT (3 times. It is now morning), E, E, E, E (you spot Dracula and cut his head off! Exit one vampire - you have solved the game!)

Jacob Gunness - d.2/8-1990.
