               EMPIRE OF KARN (Interceptor S.)
               -------------------------------

   (You begin on the castle Callastheon) SAY TO DARIN "TAKE SWORD", D, TAKE PLANK, TAKE TINDERBOX, N, E, E, E, E, TAKE KEG, LIGHT KEG, PUT KEG IN SEA (you catch a fish), TAKE FISH, W, GIVE FISH TO CAT (you can now pick up the catp), D, W, TAKE RUM, TAKE DATE, E, E, SAY TO DARIN "TAKE CHEST", PUT PLANK IN HOLE (so the ship won't sink!), W, U, U, PUT RUM IN LANTERN, LIGHT LANTERN, D, TAKE CAT, SAIL (you arrive at Vorzdeshaa), D, E, TAKE PLANK, W, U.

   S, E, U, S, E, E, S, GIVE DATE TO KRIZCOKZ (argh! What a name! He asks his son, Lizni, to follow you), N, W, S, S, S, D, S, W, DROP CAT (the mouse is scared motionless), TAKE CAT, TAKE MOUSE, E, N, U, S, DROP CAT, W, DROP MOUSE (the widow runs off), TAKE KEY, E, N, N, N, W, N, W, W, S, OPEN TRAPDOOR, DROP KEY, PUT PLANK IN CRACK an opening appears), LOOK, TAKE TORCH, LIGHT TORCH, E, OPEN SARCOPHAGUS, ATTACK MUMMY WITH TORCH (it burns up!), TAKE RUBY, D, W (the water pours in), DROP CHEST, TAKE SAPPHIRE, SIT ON CHEST (you float upwards), DROP TORCH, LOOK, N, E, E, S, E, S, S, W, GIVE RUBY TO WEAVER (he gives you a carpet - a scroll falls out), TAKE SCROLL, E, E, E, GIVE SAPPHIRE TO SHANET, GIVE SCROLL TO SHANET (she translates it - 'sim zalabim'), DROP SCROLL, W, S, E, E, E, SAY TO DARIN "TAKE FLAGSTONE", W, W, W, N, N, W, N, N, W, W, W, S, SAY TO DARIN "TAKE CHEST", N, E, E, E, S, S, W, TAKE ROPE, E, S, S, W, TAKE MOUSE, E, N, N, E, E, E, E, DROP ROPE, W, S, E, TAKE PIPE, W, N, E, SAY TO LIZNI "PLAY PIPE" (the rope floats up to the hole), U (Eldahli gives you some poison), SAY TO DARIN "ATTACK LIZNI WITH SWORD" (he is a traitor, you see!), DROP CARPET, SIT ON CARPET, SAY "SIM ZALABIM" (you fly into the palace gardens) 

   E, U, GIVE MOUSE TO OWL, TAKE RUSTY KEY, D, N, W, THROW FLAGSTONE AT WINDOW (the parrot flies away - it can't warn its master now), W, TAKE LEAVES (underneath is a grating), OPEN GRATING, D, N, PUT POISON IN WINE (goodbye Zheff!), W, TAKE CHEESE, E, S, U, E, GIVE CHEESE TO MONGOOSE, TAKE MONGOOSE, E, N, SET MONGOOSE ON COBRA (they kill each other), TAKE GLOVE, WEAR GLOVE, S, W, W, D, N, W, DROP BOTTLE, GET GLASS, PUT GLASS IN STEW (the guards are about to experience real stomach pain!), U, W (Eldahli attacks you but), RUB LAMP (...the spirit saves you), TAKE TAPESTRY, E, N, W, N (Lizni is back!), LIGHT TAPESTRY, THROW TAPESTRY AT LIZNI (he dies - again?), DROP CHEST, SIT ON CHEST (you sail downriver - the victory is yours!!)
 
Note: the game is very picky about correct syntax. Whoever wrote the parser did a pretty awful job. All names must begin with a capital.

Jacob Gunness - d.6/8-1989.