

                            F A H R E N H E I T   4 5 1 

EXAMINE  PILE  -  OPEN  GRATING  -  DOWN - SE - UP - SW - ENTER HOTEL - GET
LIGHTER - LEAVE HOTEL - E - S - ENTER HOSPITAL - SAY "STAY ME WITH FLAGONS,
COMFORT  ME   WITH  APPLES,  FOR  I  AM  SICK OF LOVE" - SAY "YES" - WAIT -
EXAMINE  CABINET  -  GET  CLIP  -  OPEN  CABINET  - SAY "DR. FOSTER WENT TO
GLOUCESTER"  - SHOW ID - OPEN CABINET WITH CLIP - LEAVE HOSPITAL - CHECK ID
-  S - S - S - S - S - S - S - S - S - S - ENTER BUILDING - SAY "YES" - BUY
RING  -  SAY  "YES"  -  SAY  "IMAGINATION  BODIES FORTH THE FORMS OF THINGS
UNKNOWN"  -  LEAVE  ROOM  - S - S - S - ENTER BANK - S - SAY "NOTHING COMES
AMISS, SO MONEY COMES WITHAL" - N - SAY "TEMBLOR" - SAY "1000" - LEAVE BANK
-  N  - SLEEP - WAIT - TIME (8.00 P.M) - ENTER BUILDING - USE LIGHTER - ASK
WOMAN  -  SAY  "YES" - PAY MONEY - LEAVE BUILDING - USE FINGERPRINTER - S -
ENTER  WALKWAY  - E - N - N - N - N - N - N - N - ENTER BUILDING - PUSH 43R
BUTTON  -  ASK  UNGAR  -  N - N - ENTER RESTAURANT - WAIT (UNTIL THE WAITER
COMES)  -  SAY  "NO"  -  EAT  FOOD  -  GET  KNIFE  - LEAVE RESTAURANT - USE
FINGERPRINTER  - USE CHEMINDEXER - S - S - S - S - S - S - S - BURN PADLOCK
-  ENTER SHOP - SAY "THE SCENE WAS ALL CHANGED, LIKE THE CHANGE IN MY FACE"
-  SHOW  ID  - PUT FACE IN MASK - LEAVE SHOP - CHECK ID - S - S - S - ENTER
BUILDING - PUT HAND ON PANEL - ENTER BUILDING - SHOW ID - SAY "DIE AND BE A
RIDDANCE"  -  N  -  READ  LABELS - PUSH BUTTON 5 - LEAVE BUILDING - N - N -
ENTER  PIT  - GET BUTTERCUP - NE - DOWN - LEAVE SUBWAY - S - ENTER CENTER -
SHOW ID - ORDER FOOD - PAY FOR FOOD - N - N - N - READ SIGN - INSERT HAND -
SHOW ID - E - E - N - N - W - S - S - OPEN DOOR 212 - USE KNIFE - S - S - S
-  S  - S - S - S - S - S - S - EAT FOOD - ENTER WALKWAY - E - N - N - BURN
PADLOCK  - ENTER SHOP-SAY "THE SCENE WAS ALL CHANGED, LIKE THE CHANGE IN MY
FACE"  -  SHOW  ID- PUT FACE IN MASK - LEAVE SHOP - USE FINGERPRINTER - USE
CHEMINDEXER  -  CHECK ID - S - S - ENTER WALKWAY - W - S - S - S - S - SHOW
ID  -  SHOW  PERMIT  -  SAY "A LIVING DOG IS BETTER THAN A DEAD LION" - N -
(SAVE YOUR GAME HERE, CREATE SAVE DISK) - (NOW WHEN A GUARD APPEARS , FIGHT
GUARD , KICK, PUNCH, HOLD OR TACKLE GUARD) N - N - W - W - ENTER ROOM 210 -
EXAMINE  ROOM - ASK WOMAN - GIVE BUTTERCUP - KISS CLARISSE - ASK CLARISSE -
UP  - (SAVE YOUR GAME, AND WHEN A HOUND APPEARS, FIGHT HOUND, KICK, LEAP ON
OR  HOLD  HOUND)  - S - W - S - E - S - DOWN - ASK CLARISSE - USE WAFER_5 -
OPEN  BOX  -  ASK  CLARISSE  -  ASK CLARISSE - EXAMINE TRANSMITTER - INSERT
MICROCASSETTE!!!!!!!THE END. WAIT ABOUT 30 SECONDS!!!

   ********************************************************************
