                                  GATEWAY
                                (Pryority)


START.......EAST - GET FLUTE - OPEN DOOR - WEST - GET ALL - SIT DOWN - OPEN
DRAWER - GET FLASHLIGHT - EAST - SOUTH - UP - MOVE BOXES - GET ROD - GIVE A
JEWEL TO THE RAT - GET ROD - DOWN - TURN ON FLASHLIGHT - DOWN - OPEN DOOR -
EAST  -  WEST - SOUTH - GET BOTTLE - CLOSE DOOR - TURN VALVE - TURN LEVER -
INSERT ROD IN HOLE - WEST - EAST - EAST - NORTH - EAST - NORTH - EAST - GET
ALL - WEST - SOUTH - WEST - SOUTH - EAST - SOUTH - GROUND THE RADIANCE WITH
THE WIRE - GET CYLINDER - NORTH - WEST - WEST - NORTH - PUT THE CUBE IN THE
CYLINDER - FIRE THE CYLINDER AT T.REX - NORTH - GET RIFLE - SOUTH - SOUTH -
UP - LOOK CORPSE - DROP WIRE - GET TALISMAN - WEAR TALISMAN - DOWN - WEST -
FILL BOTTLE WITH WATER.

EAST  - EAST - NORTH - EAST - NORTH - NORTH - EAST - NORTH - WEST - SOUTH -
WEST  - SAY BERTRAND - WEST - LOOK CRACKS - DROP JEWELS - GET COIN - WEST -
INSERT  COIN  IN  BLUE  SLOT  - PRESS BLUE BUTTON - DROP SWORD - GET OBLONG
OBJECT - EAST - TURN ON OBLONG OBJECT - THROW OBLONG OBJECT IN LAKE - SOUTH
-  WEST  - SEARCH MUD - GET METAL CARD - EAST - NORTH - NORTH - WEST - DROP
ALL - GET TALISMAN - WEAR TALISMAN - EAST - SOUTH - GET JEWELS - WEST - GET
SWORD  -  EAST  -  NORTH  -  WEST - GET ALL - DROP SWORD - GET RIFLE - DROP
CYLINDER  -  SOUTH - WEST - WEST - NORTH - EAST - WEST - GET CLIP - SOUTH -
EAST  -  WEST - NORTH - INSERT CLIP IN RIFLE - SOUTH - SOUTH - GO TO THE 22
STORY BUILDING - INSERT CARD IN THIRD SLOT - GET ALL - INSERT CARD IN FIFTH
SLOT - NORTH - LOOK IN THE SHADOWS - GET ROD.

NORTH  -  TOUCH  ROD TO CELL - PRESS BUTTON ON ROD - EAT VEGETABLES - DRINK
WATER - TOUCH ROD TO DOOR - PRESS BUTTON ON ROD - EAST - EAST - OPEN DOOR -
EAST  -  FIRE  THE RIFLE AT THE DOOR - FIRE THE RIFLE AT THE DOOR - SOUTH -
NORTH  -  NORTH - CLIMB TREE - UP - GET AXE - DOWN - DOWN - LOOK BEHIND THE
HEDGES  - MOVE THE GRATE - DOWN - NORTH - WEST - PRESS BUTTON - PRESS LEVER
-  EAST  -  NOTH - NORTH - NORTH - GIVE THE CREATURE THE JEWELS - OFFER THE
FLUTE  TO  THE CREATURE - GET AMULET - NORTH - UP - POINT THE MIRROR AT THE
ROBOT  -  EAST - PUSH RED BUTTON - PULL LEVER - PRESS BLACK BUTTON - EAST -
WAIT  - WAIT - WAIT - WAIT - WEST - WEST - LISTEN TO BERTRAND - WAIT - WAIT
- WAIT - EAST - THINK EVIL - THINK EVIL!!!!!!!!!!!!


  * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
