                    HAMPSTEAD (Melbourne House)
                    ---------------------------

(You're in your lousy little apartment, watching tv) EXAMINE LOUNGE (you find your unemployment card), GET UB40, U, E, OPEN WARDROBE, GET TRACKSUIT, WEAR TRACKSUIT, W, D, E, SEARCH KITCHEN, GET KEY, E, UNLOCK SHED, S, GET CLIPS, WEAR CLIPS, DROP KEY, GET BIKE, N, OPEN GATE, E, S, DROP BIKE, S, JOIN QUEUE (you receive a giro), GET GIRO, N, GET BIKE, N, E, N, N, E, E, NE, E, E, NE, N, GET LATHE, SW, S, DROP BIKE, S, EXAMINE OPPORTUNITIES (no jobs whatsoever!), N, GET BIKE, E, DROP BIKE, N, CASH GIRO, GET NOTES, S, GET BIKE, E, E, N, SIT BENCH (you find a credit card), GET CREDIT, S, W, S, S, DROP BIKE, W, DROP TRACKSUIT, GET TWEED, WEAR TWEED, E, E, EXAMINE NEWSAGENT (you notice an art magazine), GET MAG, W, S, E, BUY TICKET, GET PASS, SE, BOARD TRAIN (on the way to Waterloo you meet Justin Perrier, the famous arts person. He offers you his card), GET CARD, READ CARD (he will trade his tie for the lathe), GIVE LATHE, GET TIE, WEAR TIE (you get off), N, BOARD BUS (you drive to West End), N, N, E, BUY SUIT, GET
SUIT, WEAR SUIT, W, N, W, N (somebody asks for your name), JUSTIN PERRIER (he offers you a job in the bank), GET JOB (you receive a letter of recommendation), GET LETTER, S, E, S, S, E, E, OPEN DESK (inside is a tool), DROP MAG, GET SCREWDRIVER, W, W, N, N, E, E, E, DROP CREDIT, U, E (and hello to the bank manager, Sir Lionel), W, W, FORCE CABINET (the lock breaks), EXAMINE CABINET, GET REPORT, READ REPORT, DROP SCREWCRIVER, EXAMINE DESK, GET MEMO, READ MEMO, WAIT (you are asked to attend a meeting), E, N (you must vote), OPTION 3 (you must have read the memo in order to do it right. If so, you are given 100000 pounds), DROP PASS, GET DRAFT, S, D, W, W, W, S, S, S, E, EXAMINE DISPLAY (you spot a nice little house), BUY COTTAGE, GET DEEDS, W, N, N, N, E, SE, S, S, S, E, SE (you meet the model Pippa at a party), DROP CARD, GET PIPPA (she accepts!), NW, W, N, N, W, N, NW, E, E, D, GET CAR, N (Pippa talks about her dad, Sir Chubby), N, W, S, DROP CAR, RING BELL (butleren asks about your purpose), MEET CHUBBY, S (Chubby asks you what you want), MARRY PIPPA (he wants something from the meeting), GIVE MEMO, GIVE REPORT (you receive Sir Lionels job and are knighted!), N, GET CAR, N, E, S, S, DROP CAR, U, GET CREDIT, D, GET CAR, N, N, W, W, S, S, S, DROP CAR, W, DROP SUIT, GET TRACKSUIT, WEAR TRACKSUIT, GET DOGS, E, GET BIKE, N, N, E, E (this is the right way to enter Hampstead. Good piece of work!!)


Jacob Gunness - d. 21/3-1990

