                        <+>!<+>!<+>!<+>!<+>!<+>!<+>
                      <+>      HOW TO SOLVE:      <+>
                      <+>   THE INCREDIBLE HULK   <+>
                      <+>                         <+>
                      <+>            BY           <+>
                      <+>    THE UNKNOWN HACKER   <+>
                      <+>       202 ALLIANCE      <+>
                        <+>!<+>!<+>!<+>!<+>!<+>!<+>
      WITH THANX TO: 
                    BETS C. AND DEMUFFIN MAN

 BITE LIP, (GETS HULK MAD), READ SIGN, GET FAN, GET GEM, E, PRESS BUTTON, BITE
 LIP, GO OUTSIDE, GET GEM, N, READ SIGN, DROP GEM, DROP GEM

 FROM THE FUZZY AREA CAN GO A NUMBER OF PLACES, EXCEPT FOR NORTH. DONT GO NORTH
 YET. THERE ARE THREE DIFFERENT DOMES, EACH CONTAINING SOMETHING DIFFERENT.
 DEPENDING UPON WHERE YOU END UP, FOLLOW THESE GUIDELINES:

DOME:
   WITH GRATE: GET GEM, DIG HOLE, GO HOLE, DIG EAST (UNTIL YOU FIND SOMETHING),
               GET GEM, U, LIFT DOME, GET GEM, WAVE FAN, AT MESH, GO DOME, W,
               GET WAX, E, BITE LIP, GO OUTSIDE, N, DROP GEM, DROP GEM, DROP
               GEM
 NORMAL DOME:  DIG HOLE, GO HOLE, DIG EAST (UNTIL YOU FIND SOMETHING), GET GEM,
               U, LIFT DOME, GET GEM, REMEMBER NIGHTMARE, GO DOME, W, PULL
               RING, E, BITE LIP, GO OUTSIDE, N, DROP GEM, DROP GEM
    ANT DOME:  GET GEM, DIG HOLE, DIG EAST (UNTIL YOU FIND SOMETHING), GET GEM,
               U, GO DOME, GET GEM, W, GET GEM, BITE LIP, EXAMINE BASEBOARD,
               EXAMINE OUTLET, PLUG OUTLET, USE WAX, BITE LIP, ASK DR, ASK DR,
               ASK DR, GET GEM, GET WAX, E, BITE LIP, GO OUTSIDE, N, DROP GEM,
               DROP GEM, DROP GEM, DROP GEM, (GO BACK TO THIS DOME AGAIN AND):
               LIFT DOME, N, (BACK TO ANTS), GET GEM, N, DROP GEM
   EXAMINERS:  EXAMINE DESK, GET GEM, YELL, DROP GEM

 (AFTER YOU DO ALL THAT, YOU'RE READY TO GO NORTH.) REMEMBER NIGHTMARE, N, EAT
 EGG, SCRATCH WALL, GO CRACK, GET GEM, GO CRACK, GO HOLE, E, BITE LIP, GO
 OUTSIDE, N, PLUG EARS, USE WAX, (GO FIND THE ANTS AGAIN), HOLD NOSE, CLOSE
 EYES, GET ANTS, N, REMEMBER NIGHTMARE, N, GO CRACK, OPEN EYES, GET GEM, GET
 GEM, GO CRACK, GET BIO, GO HOLE, E, BITE LIP, GO OUTSIDE, N, DROP GEM, DROP
 GEM, DROP GEM, DROP BIO, SCORE.

YOU HAVE NOW SOLVED: THE INCREADABLE HULK!!!
