**************************************
*                                    *
*               WELCOME!             *
*                                    *
*  TO YET ANOTHER TUTORIAL ON HOW TO *
*  GET THROUGH YET ANOTHER INFOCOM   *
*  ADVENTURE....                     *
*                                    *
*         I  N  F  I  D  E  L        *
*                                    *
**************************************


THIS IS REALLY ONE OF INFOCOM'S
EASIEST GAMES TO DATE... AND WITH A
SOMEWHAT DISAPPOINTING ENDING.BUT IT IS
STILL AN INFOCOM PRODUCT AND THAT MEANS
FIRST RATE ADVENTURING!!!

WHEN STARTING OFF,YOU HAVE BEEN LEFT IN
YOUR TENT BY YOUR MUNTINOUS WORKERS. A
CRATE IS AIRDROPPED AS YOU START OUT, BUT
ALL THAT IS IN THERE IS A NAVIGATION BOX
THAT YOU NEED TO LOCATE THE PROPER AREA
TO DIG FOR THE PYRAMID... OF COURSE THIS
AREA IS SPELLED OUT ON THE MAP THAT COMES
WITH THE GAME PACKAGE (SHADES OF STARCROSS)
BUT DON'T WORRY... YOU DON'T NEED THE
CRATE'S CONTENTS IF YOU FOLLOW THIS
STEP BY STEP TUTORIAL....

TO BEGIN:

GET UP, S, S, GET ROCK AND PACK AND
MATCHES, W, W, GET AXE AND SHOVEL, E,
E, S, S, OPEN SACK, PUT PACK AND MATCHES
AND AXE IN SACK, GET CANTEEN, GET SACK,
N, N, N, N, BREAK LOCK WITH ROCK, GET
LOCK, DROP LOCK AND ROCK, OPEN TRUNK, GET
BEEF AND MAP, S, W, W, DRINK, OPEN CANTEEN,
FILL CANTEEN, CLOSE CANTEEN, E, E, E, S, S,
E, E, DIG IN SAND, AGAIN, AGAIN, AGAIN,
AGAIN, UNFOLD MAP, PUT CUBE IN OPENING,
DROP MAP AND SHOVEL, D

==> YOU ARE NOW IN THE PYRAMID AND READY
    TO EXPLORE. YOU FIRST NEED TO EAT,
    DRINK AND LIGHT THE TORCH, SO:

DROP SACK, EAT BEEF, OPEN CANTEEN, DRINK,
CLOSE CANTEEN, DROP CANTEEN, GET ROPE,
TIE ROPE TO ALTAR, THROW ROPE NORTH, GET
TORCH AND JAR AND MATCHES, OPEN JAR,
POUR LIQUID ON TORCH, CLOSE JAR, LIGHT
MATCH, LIGHT TORCH, PUT MATCHBOOK AND
JAR IN SACK, GET SACK, D

==> OK, HERE IS WHERE YOU RACK UP ALOT
    OF POINTS... IF YOU'RE INTERESTED
    IN HOW THE LATER PUZZLES ARE SOLVED,
    NOTE WHAT JEWEL IS FOUND IN WHICH
    ROOM (NW,SW,SE,NE) AND ALSO STUDY
    THE HIEROGLYPHICS IN EACH ROOM.
    IF YOU'RE JUST OUT TO SOLVE THIS
    BUGGER, THEN JUST KEEP FOLLOWING
    THESE STEPS:

PUSH STATUE, GET HEAD, PUSH STATUE NW,
DROP HEAD, SE, SE, SE, GET OPAL, NW, NW,
NW, GET HEAD, PUSH STATUE SE, AGAIN, DROP
HEAD, NW, NW, NW, GET DIAMOND, SE, SE, SE,
GET HEAD, PUSH STATUE NW, PUSH STATUE NE,
DROP HEAD, SW, SW, SW, GET EMERALD, NE,
NE, NE, GET HEAD, PUSH STATUE SW, AGAIN,
DROP HEAD, NE, NE, NE, GET RUBY, SW, SW,
U, DROP ALL BUT TORCH

==> WHEW! WELL THAT WAS A PAIN. ON TO MORE
    INTERESTING STUFF:

S, D, NE, NW, N, E, D, W, PUT TORCH IN
KNOTHOLE, GET SHIM, DROP SHIM, PUSH UP
BEAM, GET TORCH, E, U, W, GET BEAM, S,
W, N, E, N, D, D, N, N, E, S, GET SILVER
CHALICE, N, W, W, S, GET GOLDEN CHALICE,
N, E, S, S, U, U, S, W, S, E, SE, SW, U,
U, PUT RUBY AND DIAMOND AND EMERALD AND
OPAL IN SACK, GET SACK, W, S

==> NOW YOU NEED TO REMOVE THE RIGHT
    COMBINATION OF BRICKS FROM THIS
    PANEL WHICH WILL OPEN THE SECRET
    DOORWAY. THIS COMBINATION IS RE-
    VEALED IN THE PAPYRUS SCROLL FOUND
    ON BOARD THE BARGE (STUDY THOSE
    HIEROGLYPHICS CAREFULLY!)

GET FIRST BRICK, DROP FIRST BRICK, GET
THIRD BRICK, DROP THIRD BRICK, GET
FIFTH BRICK, DROP FIFTH BRICK

==> AND NOW FOR THE FINAL SETS OF
    PUZZLES!

E, N, D, DROP SACK, GET AXE, BREAK
PLASTER WITH AXE, GET SACK, W, W,
W, PUT BEAM IN NICHES, STAND ON BEAM,
BREAK PLASTER WITH AXE, OPEN DOOR, W,
GET BEAM, S, PUT BEAM IN DOORWAY, OPEN
DOOR, W, DROP SACK

==> OK, NOW YOU MUST PUT THE PROPER
    JEWEL CLUSTERS IN THE PROPER HOLES
    ON THE SLAB. THE ROOM DIRECTION IN
    WHICH YOU FOUND THE JEWEL DETERMINES
    WHICH CORNER YOU PUT IT ON THE SLAB:

PUT DIAMOND IN FIRST HOLE, PUT RUBY IN
SECOND HOLE, PUT EMERALD IN THIRD HOLE,
PUT OPAL IN FOURTH HOLE, OPEN SLAB, GET
BOOK

==> NOW'S A GOOD TIME TO REPLENISH YOUR
    TORCH, SO:

GET JAR, OPEN JAR, POUR LIQUID ON TORCH,
DROP JAR, GET SACK, E, GET BEAM, N, N,
PUT BEAM UNDER LINTEL, BREAK SEAL WITH
AXE, DROP AXE, OPEN DOOR, N, E, PUT
SILVER CHALICE ON LEFT, PUT GOLDEN CHALICE
ON RIGHT, DROP SACK, PUT PACK IN SILVER
CHALICE, GET SCARAB, W, PUT BOOK IN LARGE
RECESS, PUT SCARAB IN SMALL RECESS

==> READING THE BOOK (USING THE SPATULA),
    AND EXAMINING BOTH THE BOOK AND THE
    SCARAB GAVE THE CLUES TO THE
    ABOVE ACTIONS WITH THE BOOK AND
    SCARAB. NOW, YOU MUST UNLOCK THE
    STATUES IN A PARTICULAR ORDER. THE
    CLUE TO THAT ORDER WAS IN THE HEADINGS
    TO THE HIEROGLYPHICS IN EACH OF THE
    FOUR ROOMS OF THE GODS. THE ORDER IS:

TURN NEITH, TURN SELKIS, TURN ISIS, TURN
NEPHTHYS, OPEN SARCOPHAGUS

==> YOU'VE DONE IT!!!!! BUT YOU'RE ALSO
    DEAD. OK, INTERESTING ENDING, HUH?
    BUT STILL, SOMEHOW VERY UNSATISFYING...
