   		   KAYLETH (Adventure Int.)
			   ------------------------
(You begin on a conveyor belt) BREAK BANDS, U, U, PULL LEVER (the robot stops), D, EXAMINE MACHINERY (you find some tape), GET TAPE, N, GET FUSE, E, E, EXAMINE CHAIR, TURN KNOB (the chair turns; a couple of gloves appear), GET GLOVES, WEAR IT, S, EXAMINE CABINET (you find a canister), GET CANISTER, OPEN TAPE (the gloves protect you), PUT TAPE ON CANISTER (it dissolves; Dexta, Serta and Masta remain), GET ALL, W, INSERT SERTA, OPEN APERTURE (you pass through), EXAMINE APERTURE (here is an azap code: ROO), U, EXAMINE APERTURE (another a.c.: DHT), OPEN IT, EXAMINE CONTROLS (you notice an a.c.: ELY), D, AZAP CODE ELY (you are teleported), U, OPEN PYXIS, YES (two lenses fall out), GET LENSES, GO ELEVATOR, EXAMINE PANEL (it rides between three floors), PRESS M2, LEAVE, REMOVE SERTA, TALK WITH YAGMOK (because of the missing cartridge he will talk to you), ASK YAGMOK FOR KEY, GET KEY, N, GET PYRAMID, S, GO ELEVATOR, PRESS G, LEAVE, DROP LENSES AND PYRAMID, S, DROP MASTA, INSERT DEXTA, S, GO ZYMOGG (Dexta shields you from the beams), S, GET QNUTS, N, NW, YES, N, EXAMIINE EARTH (you spot a plant), GET NODULE, N, W, D, E, GO TUNNEL, FIRE PLASMA (you blow the door away), E, EXAMINE SHELVES, GET SUIT, WEAR SUIT, GET BAR AND CUBE, D, ENTER SKIMMER, EXAMINE SKIMMER (a fuse is missing), INSERT FUSE IN SKIMMER, RIDE SKIMMER (the suit protects you against the acid. You sail to Yagmok's island), SW, E, EXAMINE RUBBLE (you uncover a hatch), WEAR BAGDE, OPEN HATCH (with badge/key), D, GIVE QNUTS TO DRIBBLE (it turns to stone), D, D, E, DROP NODULE (you are thrown out), E, GET COAT, EXAMINE QUARTERS (you find another a.c.: EPO), W, RIDE HOOP (you make it through safely), U, U, W, NE, BOARD SKIMMER, RIDE IT (back), U, W, D, W, U, E, D, EXAMINE ASH (you discover a ball), GET BALL, U,
S, S, W, SE, W, GET MANUAL, READ IT (a hint about the tree), DROP IT, E, GO ARCHWAY, N, REMOVE SUIT, DROP IT, WEAR COAT (it glows), REMOVE DEXTA, GET MASTA, INSERT MASTA, GO DOME (Masta protects you), GO PLATE (it descends), D, SW, S, EXAMINE POOL (you find a cutter), GET CUTTER, N, NE, D, CUT ORE (with cutter), DROP CUTTER, REMOVE MASTA, DROP IT, INSERT SERTA, GET ORE, U, U, GO PLATE, E, PLACE ORE IN CHUTE, PRESS BUTTON (a tube falls out), GET TUBE, W, SW, N, GET LENSES, N, N, NE, N, E, SPIN BAR (the Mokki-Ray grabs it), E, U, WEAR LENSES, FLIP KNOT, YES (the door opens. The lenses protect you against the light), GET TABLET, REMOVE LENSES, DROP IT, EXAMINE TABLET (you see an a.c.: AKN), BREAK TABLET (inside is a rod), GET ROD, D, W, W, SW, S, S, GET PYRAMID, GO ELEVATOR, PRESS M1, LEAVE, D, AZAP CODE AKN, U, SW, E, WHIRL ROD (the Zemps leave), S, GET DIME, W, GO SOCLE, DROP PYRAMID;CUBE AND ROD (the socle is lowered), D, GET MORTAR AND POD, U, GO SOCLE, E, N, E, NW, D, AZAP CODE ELY, U, GO ELEVATOR, PRESS G, LEAVE, S, S, GO ZYMOGG, S, GIVE DIME TO BROZNAK (he leads you through a secret door), E, GET BOTTLE, W, N, N, W, EXAMINE DEBRIS (you find  Yurek, your other self), GET YUREK, DROP YUREK (he wakes up), GIVE POD TO YUREK, GET YUREK, E, GO ARCHWAY (the pod protects Yurek), N, N, GO ELEVATOR, PRESS M1, LEAVE, D, AZAP CODE EPO, U, DROP YUREK, REMOVE SERTA, DROP IT, INSERT DEXTA, FIRE PLASMA (the passage south is now clear), GET YUREK, D, AZAP CODE ELY, U, GO ELEVATOR, PRESS M2, LEAVE, W, EXAMINE DOME (it is hollow), PUT TUBE IN INDENTATION, PUT YUREK
IN INDENTATION (you are transported into him), GET BOTTLE;BALL AND MORTAR, E, GO ELEVATOR, PRESS M1, LEAVE, D, AZAP CODE EPO, U, S (you are caught by a plant), D, D, PUT BALL IN HOLE (a man appears), TALK TECHNICIAN (he drops a bulb), GET BULB, N, D, AZAP CODE ELY, U, GO ELEVATOR, PRESS G, LEAVE, S, S, E, POUR WATER ON COMPOST, PLANT BULB IN COMPOST (it turns into a flower), WAIT (12 times. The flower runs to seed), GET SEEDS, DROP SEEDS IN MORTAR (it turns into Tae Essence, a very potent poison), W, N, N, GO ELEVATOR, PRESS M1, LEAVE, D, AZAP CODE DHT, U, OPEN KAYLETH DOOR (the azap codes backwards), THROW ESSENCE IN POOL (Kayleth dies. You have saved the planet!!) 


Jacob Gunness - d.1/8-1990.

