                     KENTILLA (Mastertronic)
			  -----------------------


  (You begin outside Oregon's house) E (you are captured by the Urga-Mauls and wind up in a dungeon), SAY KENTILLA (the sword is teleported to you), KILL URGA-MAUL (when he arrives and till he dies), EXAMINE URGA-MAUL (you find a knife), SAY TO ELVA "GET NASTY KNIFE", EXAMINE URGA-MAUL (you find a key), GET LARGE KEY, OPEN DOOR, W, UNLOCK GREEN
DOOR WITH KEY, UNLOCK RED DOOR WITH KEY, OPEN RED DOOR, N, D, EXAMINE CAVE (you spot a torch), GIVE KEY TO CHIEF (you can take whatever you want), GET TORCH, GET ROPE, W (now find the rattling), KILL RATTLING (till he dies), GET RATTLING (now go to the river), THROW ROPE, PULL ROPE, SWING ACROSS RIVER, N, E (Elva makes a bow using the knife), N, E, N, E (the other creatures stay away because of the rattling), E, E, UNTIE TIMANDRA (don't take too long in getting here or Timandra will be dead), S, S, S, W (Timandra introduces you to Zelda the dragon), SAY TO ELVA "GET GREEN SCROLL", CLIMB TREE, GET MUSHROOMS, D, GIVE MUSHROOMS TO ELVA, CLIMB TREE (keep climbing up and down until the mushrooms reappear), GET MUSHROOMS, D, GIVE MUSHROOMS TO ELVA, S, S, DROP RATTLING, WAIT (till Zelda arrives. She will fly you across the moat), CLIMB ZELDA (you land in 'Entrance Hall')

  E, N, W, EXAMINE RAGS (you find a talisman), SAY TO ELVA "GET TALISMAN", PULL ARM (on the gargoyle. The steel door opens), E, S, S, W, LOOK IN DRAWERS, GET GOLD RING, E, E, WEAR RING (a magic doorway appears), E, SAY TO ELVA "GET MIRROR", EXAMINE BEDPOST (you find a gold key), GET GOLD KEY, W, REMOVE RING (or it will turn to iron, too), DIP GOLD KEY IN BARREL (it turns into iron), WEAR RING, E, UNLOCK CHEST WITH IRON KEY, DROP IRON KEY, OPEN CHEST, LOOK IN CHEST,
GET STAFF, GIVE STAFF TO ELVA, GET EMERALD, GIVE EMERALD TO ELVA, GET RED SCROLL, GIVE RED SCROLL TO ELVA, EXAMINE BED, SAY TO ELVA "TAKE BLANKET", W, SAY TO ELVA "GIVE ME TALISMAN, EXAMINE TALISMAN (loaded with diamonds!), REMOVE DIAMONDS FROM TALISMAN, GIVE TALISMAN TO ELVA, GET CRUCIBLE, PUT DIAMONDS IN CRUCIBLE, PUT CRUCIBLE IN FURNACE, TURN DIAL TO ON (the diamonds melt), TURN DIAL TO OFF, GET CRUCIBLE, LOOK IN CRUCIBLE, GET GRAPHITE, DROP CRUCIBLE, W, N, N, E, TURN DIAL TO 16, PUSH BUTTON (you arrive at the waterfall).

  GET CRYSTAL, CLIMB ROPE, E, U, S, OPEN GREEN DOOR, W, GET SACK
(anything inside it is weightless. It contains a chalice), PUT CRYSTAL
IN SACK, PUT GRAPHITE IN SACK, E, D, KILL CHIEF (and any other Urga-Mauler), EXAMINE CHIEF, GET SMALL KEY, U, W, UNLOCK CHEST WITH SMALL KEY, OPEN CHEST, DROP SMALL KEY, LOOK IN CHEST, GET YELLOW SCROLL (heal spell), CAST HEAL SPELL (your wounds heal), GET TINDERBOX, E, E, EXAMINE DUNGEON (you find some wax), SAY TO ELVA "GET WAX", W, N, D, W, W, E, LOOK IN SACK, GET CRYSTAL, WAIT (it glows, because of the sun), PUT CRYSTAL IN SACK, N, EXAMINE RIVER (you find some moss), GET MOSS, GET ROPE, S, S, DROP MOSS (it dries), SAY TO ELVA "GET MOSS", W, D, TIE ROPE TO STALAGMITE, PULL ROPE (the stalagmite breaks), TIE ROPE TO STALAGMITE, PULL ROPE (now it will hold), CLIMB ROPE, GO WATERFALL, GET LAMP, EXAMINE LAMP (right out of Aladdin!), RUB LAMP (the genie will not grant you your three wishes!), GIVE LAMP TO ELVA, W, CLIMB ROPE, UNTIE ROPE, GET ROPE, W, E, N, THROW ROPE, PULL ROPE, SWING ACROSS RIVER, N, N, W, N, N, N, DIG SAND (you uncover a shell), GET
SHELL, LISTEN TO SHELL (it tells you that the beetles hate blue mushrooms), DROP SHELL, S, EXAMINE VEGETATION, EXAMINE VEGETATION (you find a boat and some oars), PUT TINDERBOX IN SACK, GET OARS, LOOK IN SACK, GET CHALICE, SAY TO ELVA "GIVE ME WAX", WEAR WAX (you stuff it in your ears).

  PUSH BOAT, ENTER BOAT, ROW BOAT WEST (it is filling with water!),
BAIL WATER WITH CHALICE, ROW BOAT WEST (because of the wax you can't hear the sirens), LEAVE BOAT, DROP OARS, DROP WAX, W, DROP TORCH, W, SAY TO ELVA "GIVE ME EMERALD", EXAMINE EMERALD (in the darkness you can now see Sagagoo), GIVE EMERALD TO ELVA, E, GET TORCH, W, LOOK IN SACK, W, GET CRYSTAL (it is _still_ glowing! (impressive!) The troll turns to stone), PUT CRYSTAL IN SACK, N, EXAMINE FLOOR, GET ROD, S, WAIT, WAIT (you have caught a disease), SAY TO ELVA "GIVE ME RED SCROLL", SAY TO ELVA "GIVE ME MOSS", CAST CURE SPELL (cured!), SAY TO ELVA "GIVE ME STAFF", U (using the ring you see a ward), SAY SAGAGOO (the staff glows), HIT WARD WITH STAFF, N, LOOK IN DESK, DROP CHALICE, GET SILVER DAGGER, W, EXAMINE IDOL (it has a hole in the shoulder), INSERT ROD (you lock the arm), OPEN TRAPDOOR, D, EXAMINE DEBRIS, GET BOTTLE, OPEN BOTTLE (the genie demolishes the stone door), N, SAY TO ELVA "GIVE ME MIRROR", PUT MIRROR IN CAGE (the Karush attacks its own reflection and gets stuck), OPEN DOOR, N, OPEN SMALL DOOR, E, CLOSE
SMALL DOOR, SAY TO ELVA "SHOOT DARG-VOOL" (he shoots, he scores!), E, E, N, SAY TO ELVA "DROP MUSHROOMS", SAY TO ELVA "GIVE ME MUSHROOMS", W (using the mushrooms you chase the beetles west where they kill the Zalrogs), W, DROP KEY, LOOK IN SACK, GET GRAPHITE, SAY TO ELVA "GIVE ME GREEN SCROLL", CAST FIRE SPELL (you are protected against fire...), U (so the fire demons vanish. You notice another ward), SAY SAGAGOO, HIT WARD WITH STAFF, S, SAY SAGAGOO, GIVE STAFF TO GRAKO (he goes to hell. You have saved the world and scored 100% in the game - which wasn't _that_ easy!!!)

NOTE: One of the Urga-Mauls (it's random who) has Velmista which will cure you.

Jacob Gunness - d.1/2-1990