			     LIFEBOAT (Jack Lockerby)
			     ------------------------

   (You begin in a rowing boat) TALK SHAMUS, SAY GET OAR, GET OAR, ROW (now row on till a dog appears next to the boat), GET DOG (you discover that the woman has been trying to hide a suitcase), GET CASE (Pedro defends her), HIT PEDRO (if he falls into the water, then row on - otherwise start swiiming till you reach a ladder!), CLIMB LADDER, EXAMINE VANE (now you know which direction north is), N, IN, EXAMINE WOMAN, GET BOOK, READ BOOK (a Sleeping Beauty hint), KISS WOMAN, HOLD HAND (a clue about your task), SIT CHAIR (you are teleported to a town).

   LOOK, N, PULL ROPE, PULL ROPE (a cat jumps out), UNTIE ROPE, GET PAIL, S, E, GET PAPER, READ PAPER (a spell recipe), E, S, E, E, IN, GET FORM, FILL IN FORM, OUT, W, W, N, N, IN, TALK BLACKSMITH, SAY WORK, GIVE FORM (you get a job), BLOW BELLOWS (you receive some money), OUT, S, S, S, S (if you find a Yenom, take it), S, EXAMINE KELP (you find the dog from the boat - it is cold), GET DOG, E, EXAMINE WRECKAGE, GET CASE, DROP CASE (it shatters), GET CURDS, N, PUT DOG IN SAND, EXAMINE DOG (there's a number on its name tag - 492 if it is not randomized), S, W, N, N, N, E, GIVE COINS, SAY 492, SAY 492 (or whichever number was on the dog's tag. You win a Yenom-finder), W, N, W, W, E (the cat, which has run to this place, follows you), E, S, S, S, S (when you hear a whine from your Yenom-finder, dig and you'll uncover a Yenom. There are around 20 in all, I think), E, N, IN (the cat finds three mice and leaves their tails behind), GET TAILS, OUT, GET DOG (it runs off - don't worry...), S, W, N, N, N, E, E, E, IN, RAISE HAND (you buy a tuffet), OUT, W, W, W, N, N, N, E, KNOCK DOOR (the woman from the boat lets you inside - if you have the purds and the tuffet), GET SPIDER, OUT, W, S, S (if the shop hasn't opened yet, walk north/south till it does), IN, BUY PIE, GIVE YENOM, OUT, EXAMINE
PIE, PUT THUMB IN PIE (you pull out a plum), E, N, E, BLOW BELLOWS (a crib falls from the tree - a tear remains), GET TEAR, GET STICK, S, W, W, S (the dog which should be around here sees the stick and follows you), N, E, THROW STICK (the dog returns the stick), GET STICK (a key had gotten stuck to it), W, S, IN, WIND CLOCK (the mouse in the clock dies), GET MOUSE, OUT, N, W, W, S, IN, CLOSE DOOR (to prevent the woman in the picture from entering), DROP PAIL, GET KETTLE, FILL PAIL, PUT SPIDER, PUT PLUM, PUT TEAR, PUT TAILS, PUT MOUSE (zzap! some princely garments appear), GET CLOTHES, WEAR CLOTHES, OPEN DOOR, OUT, N, SIT CHAIR (you are teleported back to the cabin), KISS WOMAN (she runs after you), OUT (you have been ill - it was all just a dream - LAME ENDING!!)


Jacob Gunness - d.13/1-1991.

