***************************************
*                                     *
*         MASK OF THE SUN             *
*                                     *
*          A WALK-THRU                *
*                                     *
*              BY                     *
*                                     *
*            SHEREE                   *
*                                     *
***************************************


      COPYRIGHT (C) - 1983
      BY THE MINES OF MORIA


WARNING: THIS WALK-THRU SHOWS HOW TO
SOLVE THIS ADVENTURE STEP BY STEP,
THESE ARE NOT HINTS!

THERE ARE PLACES TO GO, AND THINGS TO
DO IN THIS GAME WHICH ARE NOT NECESSARY
TO COMPLETE THE ADVENTURE, HOWEVER, I
HAVE INCLUDED THEM IN THIS WALK-THRU SO
THAT YOU GET TO SEE THE WHOLE GAME, AND
NOT WHAT IS JUST NECESSARY TO SOLVE IT.

SPECIFIC INSTRUCTIONS ARE ENCLOSED IN
QUOTES, SO TYPE WHAT YOU SEE.

IN THE BEGINNING OF THE GAME, YOU ARE
IN AN AIRPLANE JUST LANDED IN MEXICO.
YOU ARE ON A SEARCH TO FIND THE FAMED
MASK OF THE SUN. HERE IS WHAT TO DO:

"OUT PLANE", "GET MAP", "LOOK MAP",
"GET IN JEEP". YOU THEN START TRAVELING
NORTH AUTOMATICALLY. WHEN STOPPED,
CONTINUE WITH "WEST", "GET ALL",
"OUT JEEP", "GO HUT" "GIVE FOOD". AT
THIS POINT THE OLD WOMAN WILL GIVE YOU
A FLUTE, AND TELL YOU SOMETHING -
REMEMBER IT. THEN "OUT", "GET IN JEEP"
"WEST", "NW".

YOU WILL NOW BE AT THE STATUE OF A CAT
WHOSE HEAD HAS BEEN REMOVED. TYPE
"DROP ALL BUT PILLS", (THESE ARE YOUR
STRENGTH PILLS), "OUT JEEP", "LOOK
STATUE". YOU WILL SEE THE SECRET WORD
XOTZIL. REMEMBER IT. THEN "GET HEAD",
"DROP HEAD ON STATUE". AT THIS POINT
THE STATUE TURNS INTO A JAGUAR AND
DEPARTS.

NOW, "GET IN JEEP", "GET ALL", "NW",
AND YOU WILL FIND YOURSELF AT THE FOOT
OF THE FIRST PYRAMID. SO, "OUT JEEP",
"GO STAIRS", "UP", "LIGHT MATCH",
"LIGHT LANTERN", "GO DOOR". NOW, YOU
WILL FIND YOURSELF IN A ROOM WITH A
SNAKE ATTACKING YOU. YOU MUST TYPE
THE NEXT COMMAND QUICKLY, OR THE SNAKE
WILL KILL YOU. TYPE "SHOOT". THE SNAKE
WILL THEN LEAVE YOU.

YOU ARE NOW IN THE FIRST PYRAMID. SO,
"SEARCH PLATFORM", "OPEN DOOR",
"FORWARD", "GET BOWL","FORWARD". YOU
ARE IN THE BOULDER ROOM. THIS IS A
WORTHLESS ROOM, BUT KIND OF FUN. WATCH
THE BOULDER.  WHEN READY TO CONTINUE,
TYPE "TURN BACK", "LEFT", "MOVE
SARCOPHAGI".  A GHOST WILL APPEAR, DO
NOTHING. AFTER ABOUT 30 SECONDS, THE
GHOST WILL DISAPPEAR, AND WILL LEAVE
BEHIND THE SECOND BOWL. TYPE "GET
BOWL", "TURN BACK", "LEFT", "RIGHT",
"GET BOWL".  THE SKELETONS IN THE ROOM
WILL NOW BE ATTACKING YOU, SO TYPE
"HIT SKELETON WITH AMULET". THEN "GET
BOWL", "GEt URN", "PLACE URN ON RIGHT
PEDESTAL", "GO DOOR", "GO JEEP", "GET
IN JEEP".  YOU HAVE NOW CONQUERED THE
FIRST PYRAMID!

NOW ON TO THE SECOND PYRAMID. GO
"SE", "SOUTH", "WEST". HERE YOU WILL
FIND A PEDDLER TRYING TO SELL YOU A
BOTTLE OF STOMACH REMEDY. DON'T BUY IT!
THEN "WEST", "SW". YOU ARE NOW AT THE
SECOND PYRAMID. SO, "OUT JEEP", "GO
PYRAMID", "RIGHT", "SEARCH DOOR". YOU
FIND A GOLD KEY. THEN "FORWARD", "MOVE
BLOCK", AND YOU FIND A BLACK KEY. NOW,
"OPEN DOOR WITH GOLD KEY", "GO DOOR",
"DOWN", "FORWARD", "LEFT", "FORWARD",
"RIGHT", "LOOK POOL" (MAKE SURE YOU
LOOK!). THEN "TURN BACK", "LEFT",
"FORWARD", "RIGHT", "UP", "OUT",
"FORWARD", "FORWARD", "LEFT", AND YOU
HAVE EXITED THE PYRAMID. NOW ON TO THE
THIRD ONE!

CONTINUE WITH "GET IN JEEP", "NE",
"NW", "FORWARD", "FORWARD", "OUT JEEP",
YOU ARE NOW AT THE THIRD PYRAMID.

YOU NOW HAVE TWO POSSIBILITIES:
YOU EITHER GO "UP" AND "SACRIFICE RAOUL"
WHICH IS NOT VERY NICE, OR YOU CAN
"CLIMB PIT", "FORWARD". AT THIS POINT
IT WOULD BE WISE TO "SAVE GAME" AS THE
NEXT OBSTACLE REQUIRES EXACT TIMING,
AND CHANCES ARE YOU WILL HAVE TO DO IT
A FEW TIMES BEFORE SUCCEEDING. CONTINUE
WITH "FORWARD", "SW". YOU MUST ANSWER
THE SW QUICKLY ALSO, AS IT IS ANOTHER
PLACE WHERE IF YOU ARE TOO SLOW TO
RESPOND, YOU DIE. AFTER YOU HAVE LEFT
THIS ROOM, IT WILL TELL YOU THAT RAOUL
HAS DIED. THIS IS UNIMPORTANT. YOU NOW
WILL FIND YOURSELF HAVING TO JUMP
ACROSS A RIVER OF LAVA. YOU NEED TO
HIT THE RETURN KEY, WHEN THE ROCK IS
UNDER THE LAVA AND READY TO RISE. YOU
SHOULD BE ABLE TO DETERMINE THIS AFTER
WATCHING IT FOR A WHILE.

ONCE YOU CROSS THE RIVER, TYPE "XOTZIL"
THEN "GO DOOR", "FORWARD", "LOOK ALTAR"
"PLACE AMULET ON ALTAR", "GET MASK".
THIS HOWEVER IS NOT THE REAL MASK.
SO YOU MUST CONTINUE SEARCHING FOR
THE REAL MASK.  SO TYPE "SEARCH ALTAR",
"GET MASK", "WEAR MASK", "TURN BACK",
"GO PASSAGE", "FORWARD".  AT THIS POINT
YOU MEET THE SUN GOD, AND  HE ASKS YOU
A RIDDLE. THE ANSWER IS "COFFIN". THEN
GO "R", "L", "L", "L", "R". YOU ARE NOW
IN THE CRUMBLE ROOM.  I WOULD SAVE GAME
AT THIS POINT, AS THE NEXT SET OF
INSTRUCTIONS ARE LONG AND YOU MAY GET
LOST. CONTINUE ONWARD WITH "FORWARD",
"L", "R", "FORWARD","L","R", "FORWARD",

"FORWARD","R","L","R","R", "FORWARD",
"R","L","FORWARD","R","FORWARD","L","R"

"L","R","L","FORWARD","L","R","FORWARD"
"FORWARD","R","L","R","FORWARD", "L"
"R", "FORWARD". NOW TYPE "WEAR MASK",
"L". YOU NOW CONFRONT ROBOFF, YOUR
ENEMY. HE WANTS THE MASK, SO "GIVE
MASK". NOW THE JAGUAR YOU SET FREE
COMES BACK AND KILLS ROBOFF, HOWEVER,
HE NOW STANDS IN FRONT OF YOU.  YOU
MUST "PLAY FLUTE" TO SOOTHE THE SAVAGE
BEAST.  HE THEN WALKS AWAY, AND YOU
EXIT THE PYRAMID.  YOU ARE NOW FINISHED
WITH MASK OF THE SUN!
