       PIRATE ADVENTURE!

GET RUM, GET CRACKERS, GET SNEAKERS, CLIMB STAIRS, GET BOOK,
ENTER PASSAGE, E, GET BAG, OPEN BAG, GET TORCH, DROP BAG, GET
MATCHES, W, W, ENTER WINDOW, SAY YOHO, E, ENTER SHACK, GIVE
BOTTLE, GET PARROT, E, CLIMB PATH, DROP BOOK, ENTER CRACK, GET
SAILS, DROP PARROT, DROP CRACKERS, ENTER CRACK, DROP SAILS, ENTER
CRACK, ENTER SHED, GET HAMMER, GET SHOVEL, GET WINGS, N, DROP
SHOVEL, ENTER CRACK, GET SAILS, D, W, DROP HAMMER, DROP SAILS,
UNLIGHT TORCH, E, CLIMB PATH, GET BOOK, D, W, W, SAY YOHO, ENTER
WINDOW, ENTER PASSAGEWAY, E, GET BOTTLE, W, W, SAY YOHO, SAY
YOHO, E, DROP BOOK, W, ENTER LAGOON, N, GET WATER, GET FISH, S,
S, E, E, ENTER CAVE, D, GIVE FISH, U, E, S, W, GET BOOK, DROP
WINGS, GET HAMMER, DROP MATCHES, DROP BOTTLE, UNLIGHT TORCH, SAY
YOHO, ENTER WINDOW, D, GET NAILS, GET RUG, GET KEYS, SAY YOHO,
SAY YOHO, E, DROP HAMMER, DROP NAILS, DROP RUG, ENTER SHACK,
UNLOCK CHEST, LOOK CHEST, GET PLANS, GET MAP, W, DROP PLANS, DROP
MAP, GET TORCH, GET MATCHES, E, ENTER CAVE, LIGHT TORCH, D,
UNLOCK DOOR, ENTER HALL, E, ENTER CRACK, DROP BOOK, DROP MATCHES,
DROP KEYS, ENTER CRACK, GET SHOVEL, GET LUMBER, GET PARROT, GET
CRACKERS, W, GO PIT, U, E, S, UNLIGHT TORCH, W, DROP TORCH, DROP
PARROT, DROP CRACKERS, DROP LUMBER, DROP SHOVEL, E, CLIMB PATH,
GET BOOK, GET MATCHES, GET KEY, D, W, DROP KEYS, DROP BOOK, DROP
MATCHES, GET HAMMER, GET LUMBER, GET NAILS, GET SAILS, GET PLANS,
W, DROP SAILS, DROP PLANS, DROP HAMMER, DROP LUMBER, DROP NAILS,
E, GET WINGS, GET SHOVEL, W, ENTER LAGOON, WAIT, DIG, GET ANCHOR,
S, DROP ANCHOR, BUILD SHIP, GET PLANS, GET HAMMER, GO BOAT, DROP
PLANS, DROP HAMMER, DROP SHOVEL, GO SHORE, E, GET CRACKERS, GET
PARROT, GET BOOK, GET MAP, W, GO BOAT, DROP PARROT, DROP MAP,
DROP CRACKERS, GO SHORE, E, GET TORCH, GET MATCHES, GET RUG, W,
GO BOAT, DROP TORCH, DROP MATCHES, DROP RUG, GO SHORE, E, GET
KEYS, GET BOTTLE, GET MONGOOSE, W, GO BOAT, DROP MONGOOSE, DROP
BOTTLE, DROP KEY, GO SHORE, SAY YOHO, ENTER WINDOW, ENTER
PASSAGEWAY, E, GET BAG, WAKE PIRATE, SAY YOHO, SAY YOHO, DROP
BOOK, GO BOAT, GET SHOVEL, SET SAIL, GO SHORE, DIG, GET RUM, GIVE
RUM, S, E, WALK 30, DIG, GET BOX, W, N, GET RUM, GO SHIP, DROP
BOX, GET PARROT, DROP SHOVEL, GET CRACKERS, GO SHORE, S, E, ENTER
MONASTARY, DROP PARROT, GET PARROT, DROP PARROT, GET DUBLEONS, W,
W, WAKE PIRATE, N, GO BOAT, DROP CRACKERS, DROP BAG, GET BOX, GET
HAMMER, OPEN BOX, DROP HAMMER, DROP BOX, GET STAMPS, SET SAIL, GO
SHORE, GET BOOK, SAY YOHO, ENTER WINDOW, D, DROP STAMPS, DROP
DUBLEONS, SCORE.

YOU WON!!!!!!
