             ----------------
             PLANETFALL SOLVE
             ----------------

WARNING: THIS IS NOT A HINT SHEET!
THIS IS A STRAIGHT-FORWARD WALK THROUGH
OF THE GAME! EXIT OUT IF TOO MUCH IS
BEING GIVEN AWAY... AFTER ALL, SOLVING
IT ALONE IS MOST OF THE FUN!
MOST OF THE FUN!


DIRECTIONS ARE GIVEN AS SINGLE LETTERS,
AND ANYTHING OUT OF THE ORDINARY WILL
BE INDICATED IN 'QUOTES'. OTHERWISE,
JUST TYPE THE COMMANDS IN THE ORDER
GIVEN.

HERE GOES....


YOU START ON BOARD THE FEINSTEIN, WHERE
YOU ARE SUPPOSED TO BE SCRUBBING THE
DECK... NOT MUCH TO SEE HERE, EXCEPT
THAT MEAN &%$*#$ BLATHER. AN ALIEN MAY
STOP AND GIVE YOU AN AD BROCHURE. IF
HE DOES, JUST DROP IT AS IT'S JUST
INFOCOM'S TRADITIONAL TRADEMARK.

THEREFORE, YOU SHOULD JUST:

WAIT (KEEP WAITING UNTIL THE SHIP BLOWS
UP), THEN GO W INTO THE POD.

GET IN WEBBING, WAIT (KEEP 'WAITING'
UNTIL YOU LAND ON THE PLANET), GET OUT,
GET KIT, OPEN DOOR, EXIT POD, SWIM UP, 
U,U,U.

YOU SHOULD NOW BE IN THE COURTYARD.
YOU MIGHT WANT TO SAVE THE GAME HERE, 
IN CASE YOU GOOF HEREAFTER. NEXT GO:

N,NE,E,E,E (DOWN THE LONG HALL),S,S,S,
SE, TURN ON ROBOT (NOTHING WILL HAPPEN
AT FIRST, BUT HE'LL JOIN YOU SOON),
W,W, DROP BRUSH AND ID CARD, GET BAR,
NE,N,N,N,N, HOLD BAR OVER CREVICE,
DROP BAR,S, OPEN KIT, DROP KIT,W,W,
UNLOCK PADLOCK WITH KEY, REMOVE PAD-
LOCK, DROP KEY AND PADLOCK, OPEN DOOR,
N, GET LADDER, S,E,E,N,N, DROP
LADDER, OPEN LADDER, PUT LADDER
OVER RIFT, N,W,W, OPEN DESK, GET
SHUTTLE CARD, E, OPEN DESK, GET KITCHEN
CARD AND UPPER CARD, E,S,S,S,E, PUSH
BLUE BUTTON, W, EAT BROWN GOO, S,S,S,
SW, GET FLASK, E, PUT FLASK UNDER 
SPOUT, PUSH RED BUTTON, GET FLASK, 
N,N,N,N,E,N.

YOU SHOULD NOW BE IN THE UPPER ELEVATOR
WHERE YOU NEED TO:

'SLIDE UPPER CARD THROUGH SLOT','PUSH 
UP BUTTON'

*** NOW, KEEP WAITING (OR DO ANYTHING
    TO USE UP MOVES. I LIKE USING 'L'
    CONTINUOUSLY) UNTIL THE ELEVATOR
    DOOR OPENS UP. THEN:


S,NE, POUR LIQUID IN HOLE, SW,N, SLIDE
UPPER CARD THROUGH SLOT, PUSH DOWN
BUTTON, ('WAIT' UNTIL DOOR OPENS), 
S,W,S,S,S,S, PUT FLASK UNDER SPOUT,
PRESS GREEN BUTTON, GET FLASK, N,N,N,N,
E,N, SLIDE UPPER CARD THROUGH SLOT, 
PUSH UP BUTTON,(WAIT UNTIL DOOR OPENS),
S,NE, POUR LIQUID IN HOLE, SW,N, SLIDE
UPPER CARD THROUGH SLOT, PUSH DOWN 
BUTTON,(WAIT UNTIL DOOR OPENS), S,W,S,
S,S,S, PUT FLASK UNDER SPOUT, PUSH GRAY
BUTTON, GET FLASK, N,N,N,N,E,N, SLIDE
UPPER CARD THROUGH SLOT, PUSH UP
BUTTON, (WAIT...),S,NE, POUR LIQUID IN 
HOLE, DROP FLASK.

*** O.K., THE COMM SYSTEM IS REPAIRED.
    YOU ARE PROBABLY VERY TIRED BY NOW,
    SO LET'S GET TO BED!...TRY:

SW,N, SLIDE UPPER CARD THROUGH SLOT,
PUSH DOWN BUTTON, (WAIT...), S,W,W,N,
GET IN BED, SLEEP (YOU MAY NEED TO WAIT
A MOVE OR TWO).


*** NOW, IN MY EARLY VERSION, THERE'S
    A BUG THAT TAKES ALL OF THE ITEMS
    THAT YOU AREN'T WEARING AND PUTS
    THEM IN THE ROOM OUTSIDE YOUR BED.
    THEY ALSO AREN'T VISIBLE UNLESS YOU
    'LOOK' OR GO OUT OF THE ROOM AND
    RE-ENTER. IF YOU FIND YOU'RE MIS-
    SING YOUR ACCESS CARDS, THEY ARE
    RIGHT THERE IN THE ROOM NEXT TO THE
    BUNK. O.K., NOW ON TO THE OTHER
    COMPLEX!!! (YOU MIGHT WANT TO SAVE
    THE GAME AGAIN!)


GET UP, (LOOK AND GET YOUR CARDS IF YOU
NEED TO), S,W,S, GET CANTEEN, OPEN 
CANTEEN, SLIDE KITCHEN CARD THROUGH 
SLOT, DROP KITCHEN CARD, S, PUT CANTEEN
IN NICHE, PUSH BUTTON, GET CANTEEN,
N,N,E,E,S,E, GET BEDISTOR, W,S,S,SW,
GET LASER AND PLIERS, NE,N,N,N, EAT RED
GOO, E,N.

*** NOW, THE NEXT THING YOU NEED IS THE
    LOWER ELEVATOR ACCESS CARD. FLOYD
    HAS IT, BUT THE ONLY WAY TO GET IT
    FROM HIM IS TO BE IN THE UPPER
    ELEVATOR WITH HIM AND KEEP SAYING
    'SLIDE UPPER CARD THROUGH SLOT'.
    EVENTUALLY, HE WILL SHOW YOU HIS
    CARD, AT WHICH POINT YOU SHOULD 
    'GET LOWER CARD'. THEN YOU SHOULD:

S, PUSH RED BUTTON, DROP UPPER CARD,
(WAIT UNTIL THE ELEVATOR OPENS), S,
SLIDE LOWER CARD THROUGH SLOT, PUSH 
DOWN BUTTON, DROP LOWER CARD, (WAIT 
UNTIL DOOR OPENS), N,E,S,E.

*** YOU SHOULD NOW BE IN THE SHUTTLE.
    ALFIE CONTROL EAST, TO BE EXACT.
    THIS LITTLE HONEY WILL TAKE YOU TO 
    THE LAWANDA COMPLEX ON THE OTHER
    ISLAND. THE SHUTTLE CONTROLS ARE 
    VERY SIMPLE. THE LEVER CONTINUALLY
    ACCELERATES THE SHUTTLE WHEN IN THE
    UP POSITION. IT MAINTAINS CURRENT
    SPEED WHEN IN THE MIDDLE POSITION
    AND DECELERATES THE SHUTTLE WHEN
    IN THE DOWN POSITION. TO ACTIVATE 
    THE CONTROLS, INPUT:

SLIDE SHUTTLE CARD THROUGH SLOT, DROP
SHUTTLE CARD, PUSH LEVER UP.

*** O.K. NOW, KEEP HITTING 'L' AND
    YOU'LL NOTICE YOUR SPEED INCREASING
    EACH TIME IN INCREMENTS OF 5. KEEP
    HITTING 'L' UNTIL YOUR SPEED HITS
    55 MPH. (NEVER MIND THE SIGN YOU
    SEE). THEN, 'PULL LEVER DOWN'. IT
    WILL NOW BE IN THE MIDDLE POSITION
    AND YOU WILL BE STEADY AT 55 MPH.
    SOON YOU WILL SEE A SIGN MARKING
    THE HALFWAY POINT. WHEN YOU SEE IT,
    HIT 'L' ONE MORE TIME, THEN INPUT
    'PULL LEVER DOWN'. THE SHUTTLE WILL
    DECELERATE (IGNORE THE SPEED LIMIT
    SIGNS) AND SHOULD STOP RIGHT WHEN
    YOU'VE ENTERED THE LAWANDA STAION!

    (THIS IS ANOTHER GOOD TIME TO SAVE
    THE GAME!)


*** O.K., NOW TO FINISH FIXING THE REST
    OF THE SYSTEMS AND FINISH THE GAME.
    NOTE >>> SOMETIME BETWEEN NOW AND
    THE END OF THE GAME (DEPENDING UPON
    HOW LONG IT TOOK FLOYD TO GIVE YOU
    THE LOWER CARD), YOU WILL GET
    HUNGRY. WHEN YOU DO, JUST 'DRINK
    LIQUID' AND DISCARD THE CANTEEN.
    O.K., FROM ALFIE CONTROL EAST GO:

W,N,U,U,NE,N, TELL FLOYD TO GO NORTH,
TELL FLOYD TO GET SHINY BOARD, S,E,N,
OPEN PANEL, REMOVE SECOND BOARD, INSERT
SHINY BOARD IN PANEL, DROP FRIED BOARD.

*** O.K., THE PLANETARY DEFENSES ARE
    REPAIRED! NEXT:

S,E,N, OPEN LID, REMOVE FUSED BEDISTOR
WITH PLIERS, INSERT GOOD BEDISTOR IN
CUBE, DROP FUSED BEDISTOR AND PLIERS.

*** COURSE CONTROL IS FIXED!  NOW GO:

S,S,S,S.

*** YOU SHOULD NOW BE IN THE COMPUTER
    ROOM. YOU MUST NOW WAIT UNTIL FLOYD
    ENTERS AND NOTICES THAT THE COM-
    PUTER IS BUSTED. THEN:

NE, OPEN BIO-LOCK DOOR,SE,E, LOOK IN
WINDOW.

*** FLOYD SHOULD NOW BE WITH YOU AND
    THE BRAVE LITTLE SOUL WILL SEE THE
    MINIATURIZATION CARD IN THE LAB AND
    WILL VOLUNTEER TO GET IT. YOU NEXT
    SHOULD:

OPEN DOOR, CLOSE DOOR, L, OPEN DOOR,
CLOSE DOOR, (DEAR LITTLE FLOYD WILL
PERISH), GET MINIATURIZATION CARD, W,
OPEN DOOR, W,S, REMOVE OLD BATTERY,
DROP OLD BATTERY, INSERT NEW BATTERY IN
LASER, N,SW,S, SLIDE MINIATURIZATION
CARD THROUGH SLOT, TYPE 384, SET DIAL
TO 1, E,N,N, SHOOT BOULDER WITH LASER,
(YOU WILL NEED TO KEEP SHOOTING THE
BOULDER UNTIL YOU DESTROY IT), SET DIAL
TO 6, S.

*** A LARGE MONSTER WILL NOW BLOCK YOUR
    PATH. YOU HAVE TO KEEP TYPING
    'SHOOT MONSTER WITH LASER'. THE
    WOUNDS WILL KEEP HEALING, BUT SOON
    YOU WILL SEE IN THE DESCRIPTION
    THAT THE MONSTER IS ATTRACTED TO
    THE HEAT OF THE LASER. WHEN YOU SEE
    THIS DESCRIPTION, YOU NEED TO
    'THROW LASER INTO VOID'. THE BEAST
    WILL FOLLOW AFTER IT. NEXT:

S,W, (YOU WILL FIND YOURSELF IN AN
AUXILARY BOOTH), N, OPEN DESK, WEAR
MASK, PUSH RED BUTTON, OPEN DOOR, W,
OPEN LAB DOOR, W,W, OPEN DOOR, W,SW,W,
S, PUSH BUTTON.


*** ALL RIGHT, YOU'VE DONE IT!!!!!
    ALL YOU HAVE TO DO IS WAIT FOR THE
    DOOR TO OPEN, THEN GO NORTH AND THE
    REST TAKES CARE OF ITSELF!!!!

(PLEASE REPORT ANY INCONSISTANCIES TO
THE SYSOP SO THIS TUTORIAL CAN BE
KEPT UP-TO-DATE!)
