				 PLUNDERED HEARTS (Infocom)
			         --------------------------

   (You begin in a cabin) STAND UP, Z, Z (a coffer slides out from under a bed), GET COFFER, Z (Crulley enters), HIT CRULLEY WITH COFFER, Z (he is about to get back at you when The Falcon enters), Z (you receive a letter), READ MISSINE, YES, Z (you board The Falcon, Nicholas Jamison's ship...)

   STAND UP, Z, Z, Z, N, OPEN CUPBOARD, IN, GET CLOTHES, REMOVE FROCK, TEAR IT (you remove a strip from it), WEAR BREECHES, WEAR SHIRT, OUT, Z (till Jamison arrives. He gives you a brooch and a coffer), D, N, N (if you're not too late you can not hear Crulley making evil plans), GET BOTTLE, S, S, OPEN COFFER, GET INVITATION, U, S, SMASH WINDOW WITH COFFER, S, CLIMB ROPE, U, U, U, U, N, N, EXAMINE BARRELS (one contains rum, the other water), DIP RAG (from the frock) IN WATER, OPEN HATCH, D, THROW RAG AT FIRE (it extinguishes), U, N, EXAMINE WINCH, RAISE LEVER (you lower the anchor), IN, GET DAGGER, OUT, S, SIT IN CASK, CUT LINE WITH DAGGER (you roll into the ocean)...

   GET PORK, Z, Z, Z (you reach the shore), GET OUT OF CASK, W, N, W, N, E, Z (Lucy hands you a garter), GET GARTER, W, S, NE, U, REMOVE CLOTHES, GET GOWN, WEAR IT, N, E, D, SHOW INVITATION TO BUTLER, S (Jamison appears and invites you to dance), Z, Z, Z, Z (he leaves), E, N (you climb under the table), N, EXAMINE BOOKCASE, GET TREATISE (you hear a click as you pull the book), GET HAT (and other click), PRESS ISLAND (on the globe. The portrait slides away), N, D, E, E, GET KEY AND HORN, W, W, S, EXAMINE BOTTLE, READ LABEL (it is a sleeping potion), PUT LAUDANUM ON PORK, GIVE PORK TO CROCODILE, Z, Z (the beast is asleep now), S, W, UNLOCK DOOR WITH KEY, OPEN IT, N (you meet your father), GIVE GARTER TO PAPA, S, E, N, N, U, S (your dad climbs out the window), S, W, S (you encounter Lafond and have to dance with him), Z, Z, Z, N, Z (oh, no! Jamison is captured!), Z (the butler asks you to go to Lafond's room), U, E, OPEN DOOR, N, DRINK WINE (Lafond turns around), POUR WINE IN GREEN GOBLET, POUR WINE IN BLUE GOBLET, PUT LAUDANUM IN BLUE GOBLET (the food arrives), GET SPICES (Lafond wants YOU to drink the drugged glass of wine!), BLOW SPICES AT LAFOND (he leaves the room), GET TRAY, WAVE IT IN MOONLIGHT (to the ship),
S (du møder butleren), GIVE BLUE GOBLET TO BUTLER, Z, Z, Z (he falls asleep), S, W, D (you meet Cookie), E, N, GET HAT, GET TREATISE, PRESS ISLAND, N, D, S, S (here are Jamison and Crulley), GET RAPIER, ATTACK CRULLEY, AGAIN (he falls through the trapdoor), WAKE FALCON WITH SALTS, UNLOCK CHAIN WITH BROOCH (The Falcon is free!), N, N, U, S, W, U, E, S (Jamison and Lafond get into a fight), UNTIE ROPE, CLIMB DOWN ROPE (you hit Lafond. The two must now duel on the beach), GET ALL, S, S, S, Z, Z, YES (the men start fighting - Lafond drops his pistols), GET PISTOL, LOAD IT (The Falcon finally kills Lafond), SHOOT CRULLEY (now all the bad guys are dead, and The Falcon is all yours. SIGH!!!)


Jacob Gunness - d.6/8-1990.

