         THE PYRAMID OF DOOM

>------------< COMMANDS >-------------<

TAKE POLE, GO POOL, TAKE KEY, E,N,E, DIG, TAKE KEY, S, DIG, TAKE STONE, GO HOLE,
UNLOCK DOOR, DROP KEY, U, UNLOCK DOOR, W, GO POOL, GET WATER, E,E, GO DOOR,
LIGHT FLASHLIGHT, TAKE PISTOL, OPEN SARCOPHAGUS, N,E, TAKE FLUTE, W,S, S, PLAY
FLUTE, LOOK ASHES, TAKE NECKLACE, LOOK FIREPLACE, DROP FLUTE, TAKE COAL, WASH
COAL, N, GO SARCO, D, POUR, WATER, TAKE TAPESTRY, DROP KEY, S, DROP SHOVEL, TAKE
SAW, N, GO ALCOVE, DROP CANTEEN, TAKE SKILL, LOOK SKULL, W,S, DROP SKULL, N, GO
ALCOVE, TAKE BOX, LOOK BOX, LOOK BOX, DROP BOX, WEAR GLOVE, HIT BRICK, S, DROP
GLOVE, GO ALCOVE, TAKE TEETH, W,U,W,N, SAW TABLE, DROP SAW, TAKE NECKLACE, S,S,
GO PASSAGE, N,E, READ HIEROGLUPHICS, DROP STONE.

        < INVENTORY CHECK >

 LIT FLASHLIGHT. * ANTIQUE TAPESTRY *. PISTOL. * GOLD TEETH *. * DIAMOND -
NECKLACE *. * GOLD NECKLACE *. * RUBY *

DROP TAPESTRY, DROP TEETH, DROP NECKLACE, DROP NECKLACE, TAKE JERKY, W,N, DROP
JERKY, TAKE PEARL, W,S, GO SARCO, D,S, GO LADDER, S, TAKE SAPHIRE, THROW RUBY,
W,N, LOOK EXPLORER, TAKE PIN, LOOK RUBBISH, TAKE CARVING, S,W,D,N,U, W,N,E, GO
ARCHWAY, E.

         < INVENTORY CHECK >

 LIT FLASHLIGHT. PISTOL. * BLACK PEARL *. * JADE CARVING *. * SAPPHIRE *. * GOLD
PIN *.

DROP PEARL, DROP PIN, DROP CARVING, DROP SAPPHIRE, W,N,W,S, GO SARCO, D, TAKE
GLOVE, N, TAKE ROPE, S,S, GO LADDER, S, THROW ROPE, CLIMB ROPE, WEAR GLOVE,
OPEN CHEST, TAKE CROWN, PULL CHAIN, GO STAIRS, D,D,W,D,N,U,W, GO DOOR, UNLIGHT
FLASHLIGHT, GO HOLE, TAKE KEY, U, GO DOOR, LIGHT FLASHLIGHT, GO SARCO, D,N, GO
DOOR, FEEL AROUND, TAKE COIN, E, LIGHT FLASHLIGHT, TAKE SCARAB, W,W, LIGHT
FLASHLIGHT, S,S, GO LADDER, S, GO ROPE, GO STAIRS, WEAR GLOVE, UNLOCK COFFER,
LOOK COFFER, TAKE BRACELET, D,D,W,D,U,W,N,E, GO ARCHWAY,E.

         < INVENTORY CHECK >


  FLASHLIGHT. TINE KEY. PISTOL. * GOLD SCARAB *. * GOLD COIN *. * PLATINUM CROWN
*. * EMERALD BRACELET *.

DROP SCARAB, DROP COIN, DROP CROWN, DROP BRACELET, W,N,W, TAKE SAW, S, GO SARCO,
D,S, GO LADDER, S, GO ROPE, GO STAIRS, SAW WINDOW, GO WINDOW, TAKE BARM
W,D,D,W,D,N,U,W,N,E, GO ARCHWAY, E, SHOOT NOMAD, DROP BAR.

       SCORE !!!
       =-------=

written by double density
brought to you by DOCTOR FLORA
