			SCAPEGHOST Part 1 (Level 9)
			---------------------------

(You start next to your own grave) N, GET THISTLEDOWN, W, W, W, NW, GET PETAL, E, E, E, GET LEAF, S, S, GET MATCHBOOK, W, W, EXAMINE HEAP, EXAMINE WREATH, GET CARD, GET TWIG, E, E, E, WAIT (till it gets dark), EXAMINE FIGURE (it is Joe Danby) N, WAIT, N, N, EDNA;HELLO, SW, W, EXAMINE SARCOPHAGUS, ROCK URN (David is impressed), DAVID;FOLLOW ME, NW, COLONEL;HI THERE!, SW, S, VIOLET;HI, S, S, EDITH;NICE WEATHER TODAY, N, WAIT, NE, E, E, EXAMINE SUNDIAL (you see a gnomon), JOE;WAIT THEN PUSH SUNDIAL, PUSH SUNDIAL (it shatters), GET GNOMON, SW, W, W, S (Edith notices the gnomon and the curse is removed), EDITH;FOLLOW ME, N, E, E, EXAMINE LOCK, JOE;WAIT 3 THEN PUSH LONG LEVER, DAVID;WAIT 2 THEN PUSH MEDIUM LEVER, EDITH;WAIT THEN PUSH SHORT LEVER, TURN BARREL (the door is unlocked), E, S, PAT DOG, N, PAT DOG, PAT DOG (the dog becomes your friend), EXAMINE DOG (a bone is stuck in its throat), REMOVE BONE (the dog loves you!), W, W, GET CARD, E, E, E, DAVID;GET WHITE CARD (from New Wreath), PUT YELLOW CARD ON WREATH, WAIT FOR DOG, GET WREATH (the dog grabs it for you), NW, WAIT FOR DOG, N, EXAMINE STONEWORK, EXAMINE PLINTH, HIT STATUE (it comes alive - it is just Alex Pym sleeping), ALEX;FOLLOW ME, NE, WAIT FOR DOG (Edna sees the wreath and the discussion is over), EDNA;FOLLOW ME, BERT;FOLLOW ME, SW, SW, S, WAIT FOR DOG, PULL HANDLE (the dog opens the door), S, DAVID;WAIT THEN PRESS BUTTON, PRESS BUTTON (aided by David you turn off the spotlight. You hear the vandals harassing the colonel), GET BELL, PRESS SWITCH (the vandals flee. You return to your grave), FIND COLONEL, COLONEL;FOLLOW ME, FIND VIOLET, PUT BELL ON BUSH (Violet can hear the bell and agrees to follow you), VIOLET;FOLLOW ME (all the ghosts are gathered now), SE, E, E, S, JOE;WAIT 8 THEN PUSH WALL, EDITH;WAIT 7 THEN PUSH WALL, ALEX;WAIT 6 THEN PUSH WALL, DAVID;WAIT 5 THEN PUSH WALL, EDNA;WAIT 4 THEN PUSH WALL, BERT;WAIT 3 THEN PUSH
WALL, VIOLET,WAIT 2 THEN PUSH WALL, COLONEL;WAIT THEN PUSH WALL, PUSH WALL (with each other's help you make the wall tip over, covering the drugs)



Part 2

(You begin at your own grave) N, N (Joe Danby tags along), E, N, N (a car approaches), S, WAIT, N, N, N, N, W, CONCENTRATE (remember what Joe said a moment ago!), WAIT, DIG (you find the map that you buried), GET CARD, N, E, GET BULB (you drop the map), PRESS SWITCH (Luke's ghost vanishes), W, EXAMINE DISPENSER, GET FOIL, JOE;GET PEARL BULB, PUT FOIL IN LAMPHOLDER, PRESS SWITCH (you short circuit the system), S, EXAMINE DITCH, EXAMINE BRANCH, FREEZE WATER (using your new abilities you freeze the water so you can grab the map), GET MAP, JOE;GO TO LOUNGE AND PRESS WALL, E, E, WAIT (you see Joe's hand coming through the wall, indicating where the chimney is), PRESS WALL, W, N, DROP MAP, E, GET PAPER, W, DROP PAPER, EXAMINE DIRECTORY, JOE;WAIT THEN PULL BOOKMARK, PULL BOOKMARK, U, U, GET PLUG, D, N, SMASH MIRROR, JOE;GET BRIEFCASE;S;D;DROP BRIEFCASE, S, OPEN PANEL, PUT PLUG IN PANEL, CLOSE PANEL, GET SOCKET (which has been dragged along with the plug), U, GET IN TANK (AAAARGGGH!!!! Luke's body is in here!), GET IN TANK (you can now control your nerves), FREEZE SOCKET TO LUKE, D, PUSH CLOCK (the clock drags the body along), D, W, PUSH BOTTLE, LIGHT PUDDLE, PULL CURTAINS, WAIT (the fire department arrives and finds the evidence and the corpse).


Evidence: MAP,PAPER,BRIEFCASE,BOOKMARK,CARD



Part 3

(You begin by your own grave. A priest is trying to exorcise you, aided by Big John and Weasel) W, S, S, E, GET IN VAN, WAIT FOR WEASEL, WAIT 3 (you drive to the gang's hideout), GET OUT OF VAN, W, W, W, EXAMINE HAY, GET SPRAYER, E, NE, N, TOUCH SPRAYER ON CONNECTORS (the wires short circuit), S, SW, N, EXAMINE CUPBOARD, PUSH BREAKER (the fuses are turned off), U, U, W, EXAMINE LAMPHOLDER (you notice a light bulb), WAIT FOR BIG JOHN, WAIT (you see some lights in the village), WAIT, E, D, PULL STAIR (John is startled and doesn't notice the police), U, W, WAIT, WAIT, GET BULB, WAIT (till John looks out for the second time), THROW BULB (he looks away), GET GLASS, WAIT 4, WAIT, WAIT 4 (John is about to notice the police), PULL CURTAINS (he runs down to the kitchen), E, D, D, D, IN (maybe...) WAIT FOR WEASEL,WAIT but he should be here now), N, WAIT (till Weasel leaves), MANIFEST (Sarah is tied to the chair. She is scared, but is soon calm again), WAIT 3, CUT ROPES (Weasel is far away. Sarah puts the hammer on the shelf), S, WAIT FOR WEASEL, PUSH HAMMER (Weasel is knocked out cold), MANIFEST, SARAH;TIE WEASEL, OUT, SARAH;FIND TAXI AND DEFLATE TYRES THEN GO TO LIVINGROOM AND WAIT FOR ME, U, U, U, W, GET FLASK, WAIT, WAIT 3 (you see flashlights on the moor), LIGHT CURTAINS (John hides under the blanket (?)), WAIT 4, WAIT, WAIT 3, FREEZE JOHN (he hides in the corner), WAIT 2, HIT JOHN WITH FLASK (he screams, summoning the others), E, D, BEND KEY (John has it in his pocket. He comes up the stairs), D, N, MANIFEST, SARAH;S;E;GET BRIEFCASE;W;HIDE IN CUPBOARD (Sarah finds the evidence and hides it), S, WAIT 3, OUT, WAIT 10 (till Severian arrives. John tries to escape but can't do so because of the key), GET IN TAXI, WAIT 3 (you get into a fight. The flat tyres cause the car to tip over, so the police can catch all the crooks!!)


Jacob Gunness - d.5/12-1989