SCEPTRE OF BAGHDAD

FULL SOLUTION

SWAP FLUTE FOR HANKY, GO LEFT UNTIL FLYING CARPET, FLY OVER RIVER, ENTER
THE TOWER, CLIMB UP THE ROPE, RIGHT, JUMP UP TO BIRD, SWAP FLUTE FOR WINGS,
JUMP ACROSS NEXT TO BALCONY, WALK UNDER BEES NEST, CROSS RIVER AGAIN, GO
LEFT UNTIL STATUE OF ARCHER, JUMP UP STEPS UNTIL IT FLIES OFF, CROSS BACK
OVER THR RIVER, SWAP WINGS FOR KEYS, GO TO THE ROOM WITH THE BEACHBALLS,
JUMP UP STAIRS AND GO RIGHT, KEEP GOING RIGHT TO GET RID OF THE NAGGING
WOMAN, OPEN WARDROBE, SLIDE DOWN BANISTER AND GET THE BOOK, GO UPSTAIRS AND
SWAP THE KEYS FOR THE FIRE-RING, GO LEFT, GO THROUGH DOORS, SLIDE DOWN THE
BANISTER, GO TO FLYING CARPET AND CROSS WIVER TO WHERE STATUE WAS.
GO DOWN HOLE, GO LEFT UNTIL ROOM WITH BATS, EXIT ROOM AND RETURN TO ROOM
WHERE YOU LEFT THE PURSE. NOW RETURN TO BAT ROOM BY THE SAME ROUTE, THIS TIME
USING THE DOOR OPEN KEY ON THE OPEN ROCK. THIS SHOULD FILL YOUR PURSE.
RETURN TO THE PURSE ROOM, ENTER WARDROBE, DOWN STAIRS, GO RIGHT UNTIL THE
BLUE BRICKED MARKET, ENTER THE SHOW SHOP AND SWAP THE BOOK FOR THE SHOES,
ENTER THE WEAPONS SHOP AND SWAP THE PURSE FOR THE AXE. LEAVE THE AXE AND
SLIPPERS IN A SAFE PLACE. GO LEFT FROM THE SHOPS AND PRESS UP BETWEEN THE
PALM TREES. GO UP STEPS AND TAKE THE SLING, GO BACK TO THE ROOM WITH THE
TRIDENT AND TAKE IT, GO DOWN THE HOLE MADE BY THE STATUE, AND SWAP THE
TRIDENT FOR THE PEARL IN THE OYSTER - THE SLING SHOULD NOW BE LOADED.
USE THE DOOR KEY BETWEEN THE TORCHES IN THE OYSTER ROOM, GO TO THE ROOM WITH
THE COCONUT ON THE PALM TREE AND WLAK UNDERNEATH IT. GO LEFT TO THE DESERT
AND TAKE THE BLUNT TRUNK (KEEPING THE COCONUT), LEAVE THE DESERT AND PUT THE
COCONUT IN A SAFE PLACE. RETRIEVE THE AXE TO SHARPEN THE TRUNK, DROP THIS IN
A SAFE PLACE. GET THE COCONUT AND GO TO THE OYSTER ROOM. GO RIGHT TWICE AND
TAKE THE FISH HELMET (HANG ON TO THAT COCONUT!). GO TO THE DESERT AND GO
DOWN THE WELL. SWAP THE MIRROR FOR THE COCONUT AND GO RIGHT BACK TO THE
OYSTER ROOM. SWAP THE FISH HELMET FOR THE SHARPENED TRUNK.
ENTER THE DOOR IN THE ROOM LEFT OF THE STARTING ROOM, GO DOWN STAIRS, GO
LEFT UNTIL YOU GET PAST THE MEDUSA, KEEP GOING LEFT TO KILL THE CYCLOPS.
RETURN TO THE START ROOM, GET THE WHIP FROM THE BALCONY, GO THE ROOM NEAR
THE SHOPS WITH THE BULL, JUMP INTO THE WAGON'S WHEEL TO GET THE AXLE, GO
TO THE OYSTER ROOM, RIGHT, REPLACE AXLE IN DRAWBRIDGE, TAKE SLIPPERS, ENTER
DRAWBRIDGE, WALK OVER COALS UNTIL YOU REACH AN ISLAND, SWAP WHIP FOR BOW
AND DROP IT IN A SAFE PLACE.
GET THE INSECT NET AND USE IT ON THE BEE FROM THE HIVE, GET THE SWORD, ENTER
THE DOORS IN THE SAME ROOM AND GO DOWN STAIRS, RIGHT, JUMP TO COLLECT THE
STRING. LEAVE THE STRING IN A SAFE PLACE.
GET THE WHISK FROM THE BEACHBALL ROOM, GO TO THE DOOR BETWEEN THE TWO PALM
TREES AND THE GREEN PLATFORM, ENTER PALM TREES AND GO DOWN THE HOLE, GET
THE LAMP AND LEAVE IT SOMEWHERE SAFE.
GET THE BOW AND THE STRING, THEN DROP THE STRING. TAKE THE QUIVER FROM THE
HOLE MADE BY THE STATUE AND GET THE LAMP. GO TO ROOM TO THE LEFT OF THE
START ROOM AND ENTER THE DOORS. GO DOWN AND LEFT UNTIL YOU REACH A SEE-SAW.
WALK TO THE SEE-SAW AND GET CATAPULTED INTO ANOTHER ROOM.
TAKE THE SCEPTRE AND GET TELEPORTED. RETURN TO THE BALCONY AND YOU WILL
HAVE COMPLETED THE GAME WITH 100%!!!