***************************************
*****  HOW TO SOLVE  'SPACE ACE'  *****
*****                 ===== ===   *****
*****  WRITTEN BY <-THE BATMAN->  *****
*****\                           /*****
      \    THE INFO CONTAINED   /
        \  IS HOW TO SOLVE THE  /
        \     ARCADE GAME     /
         \     SPACE ACE     /
          \    ---------    /
           \   COPY WRONG  /
            \ 1984 BAT-CO./
             \  PRODUCTS /
              \   INC.  /
               \-CADET-/
                \LEVEL/
                 \   /
                  \ /


 OK LETS GET STARTED.. YOU BEGIN AT
A ROCKY MOUNTAIN WHERE YOU ARE STARING
AT THE EVIL 'BORF'S' SHIP. KIMBERLY,
YOUR FEMALE COMPANION, TRYS TO GET TOO
CLOSE OF A LOOK AT THE SHIP AND THE
ROCKS BREAK OUT FROM UNDER HER.
SHE IS SUCKED UP INTO BORF'S SHIP, AND
BORF IS ABOUT TO ATTACK YOU.
 YOUR FIRST MOVE WILL BE [RIGHT]
WHEN THE ROCK FLASHES FOLLOWED BY
ANOTHER [RIGHT].  YOUR RUNNING FROM
LAZER SHOOTING ROBOTS. GO [LEFT],
THEN [LEFT] AGAIN AND [ENERGIZE].
[SHOOT], GO [RIGHT], THEN [LEFT],
THEN [RIGHT]. [SHOOT] THE ROBOT,
AND GO [LEFT].
NOW YOU ARE AT THE ROBOT SMASHERS.
WHEN THE LEGS ARE RAISED, GO [LEFT],
[LEFT], [LEFT], AND [LEFT] AGAIN.

 YOUR AT THE SPACE SCENE JUST WAIT
"KIMBERLY, COME IN, ARE YOU OK?"
"OH SURE, I'VE BEEN CAPTURED BY ALIENS,
THATS ALL!!!"
"I'LL SAVE YOU KIMMY."
"GET ME OUT OF HERE!!!!!!"

FUNNY HOW DEXTER CAN COMMUNICATE W/
KIMBERLY EVEN THOUGH SHES CAPUTERD.
MABEY SHE DEMANDED HER RIGHT TO ONE
PHONE CALL BEFORE PROSECUTION.

NOW YOUR AT THE MAZE.  GO [FOREWARD],
[RIGHT], [FOREWARD], [FIRE], [RIGHT],
[FIRE], [BACK], AND [FIRE] AGAIN.
**WARNING THIS BOARD CAN BE BACKWARD**
** THUS MAKING THE TWO RIGHT TURNS  **
** LEFT TURNS.                      **

DEXTER SAYS, "SPACE STATION; REQUEST
PREMISSION TO LAND.  AHAH, BORF IS
HERE"

GO [FOREWARD], [RIGHT], [FOREWARD],
[FOREWARD], [ENERGIZE], "HAHA".
[RIGHT], [FIRE], [FOREWARD], [FOREWARD]
[FIRE], [RIGHT] (THIS LAST MOVE YOU
CAN EITHER GO RIGHT OR LEFT. I GO LEFT.


AFTER HEARING "ALERT!" "ALERT!",
WAIT UNTIL IT SAYS ENERGIZE ON THE
SCRENE AND THEN [ENERGIZE].
[SHOOT] THE GIANT LAZER GUN, THEN GO
[RIGHT] WHEN YOU SEE A GLIMPSE OF
ANOTHER PLATFORM COMMING. THEN GO
[FOREWARD] & [FIRE].
WAIT UNTIL THE GUN FIRES AT YOU. IT
WILL MISS AND THEN IT'S YOUR TURN TO
[FIRE]. NOW GO [RIGHT] AND WHEN YOU
SEE THE GUNS, [FIRE], AND [FIRE] AGAIN.
GO [LEFT] AND NOW YOUR ON TO A
DIFFERENT SCENE.

AFTER THE DOGS SAY, "DEXTER, YOUR A
FOOL" GO  [FOREWARD], THEN [RIGHT],
THEN [LEFT]. [ENERGIZE]. LET THE DOGS
ATTACK YOU AND THEN GO [LEFT].
GO [RIGHT] AT THE CORNER, AND [FIRE]
AT THE NEXT CORNER. AFTER THAT GO
[RIGHT] AND [FIRE]. GO [LEFT] FROM
THERE, AND [FOREWARD]. NOW YOUR DONE
WITH THAT SCENE.

WHILE DEXTER IS AT THE SPACE STATION,
THE ROOM WITH THE PLATFORMS, AND THE
DOGS, THE ROOM MAY BE BACKWARDS IN
WHICH CASE THE MOVEMENTS TO THE
[RIGHT] BECOME MOVEMENTS TO THE [LEFT]
THIS IS TRICKY SO WATCH OUT!!

OK, DEXTER JUST LANDED ON THE PLANET.
WHERE DID HE GET THE SHIP?
WE ARE ONLY PLAYING CADET LEVEL SO
ALOT OF BOARDS ARE LEFT OUT.
AFTER SOLVING CADET YOU SHOULD GO UP
TO CAPTAIN AND THEN SPACE ACE LEVEL.

YOU JUMP OUT OF THE SHIP. [FIRE],
THEN [FOREWARD]. [ENERGIZE], AND
[FIRE] AFTER YOU THROW THE RABBITS
OFF OF YOU. JUST BEFORE YOU RUN INTO
THE MONSTERS HAND, [FIRE] THEN RUN
[RIGHT].  THIS IS ANOTHER BOARD
WHICH MAY BE BACKWARDS.

YOUR FALLING DOWN A PIT. GRAB THE
ROPE BY GOING [RIGHT]. YOU'LL SEE
KIMBERLY, OH GOODIE, WHIT SHE SAID
"BEWARE YOUR DARK SIDE" SHE MUST BE
EVIL, SO [FIRE] AT HER. THEN GO
[RIGHT] AND [BACK]. GO [RIGHT] AND
[RIGHT] AGAIN.
THIS BOARD MAY BE BACKWARDS TOO

NOW YOU ARE AT THE MOTORCYCLES.
GO [RIGHT] AND THEN [LEFT].
[FIRE] AND [ENERGIZE]. YOU WILL
TRAVEL DOWN A RAMP AND SEE KIMBERLY.
[SHOOT] AND [SHOOT] AGAIN. SHE WANTS
TO WALK, WELL SHE CAN'T SO GO
[LEFT] AND [BACK]. GO [LEFT] AGAIN
OVER THE JUMP. NOW [SHOOT], [SHOOT],
[SHOOT]. THEN YOU WILL GO AROUNG A
BEND. GO [LEFT] AND THEN [SHOOT].
MEANWHILE KIMBERLY IS TELLING YOU
ABOUT HOW BORF IF AIMING THE INFANTA
RAY AT EARTH (A RAY THAT TURNS IT'S
TARGETS INTO BABIES) AND THAT HE IS
GEARED FOR BATTLE.
WHILE YOU TALK ABOUT SHOOTING BORF
WITH HIS OWN INFANTA RAY AND
DISCUSSING DINNER PLANS, YOU MUST GO
[RIGHT] AND THEN [LEFT].

WATCH OUT BORF O'L BUDDY, HERE WE
COME!!

NOW YOUR CLOSE TO THE END AND BORF
IS BEGINNING TO REALIZE THAT YOUR NO
PUSH OVER. GO [RIGHT] THEN [FIRE]
[FIRE] AGAIN TO GET OXYGEN AND THEN
GO [BACK]. GO [LEFT] AND THEN [BACK]
FOLLOWED BY [FIRE]. YOU WILL HIT
THE BLACK EEL BUT KEEP [FIRING] UNTIL
YOU HIT THE CLAM. AT THIS POINT,
GO [LEFT] AND [LEFT] AGAIN.
THE MOTERCYCLE BOARD AND THIS BOARD
MAY ALSO BE BACKWARDS.

NOW YOUR IN A ROOM WITH THREE PORTALS
WAIT UNTIL THE PORTAL IN FRONT OF
YOU FLASHES GOLD THEN GO [FOREWARD].
GEE THAT WAS A LONG ROOM.


OK. THIS IS THE TOUGHEST ROOM IN THE
GAME!! LISTEN CLOSELY. IT IS NEVER
BACKWARDS.
[FIRE], [FIRE], GO [RIGHT], THEN GO
[LEFT]. [ENERGIZE] THEN [FIRE].
GO [RIGHT], THEN [FIRE], AND [FIRE]
AGAIN. DURRING THIS TIME KIMBERLY
IS BEING LOWERED INTO A FIRE PIT!!
GO [RIGHT] THEN [BACK]. NOW [FIRE]
AND THEN GO [RIGHT] AND [FOREWARD].
KIMMY SAYS "DEXTER THE INFANTA RAY
IS..." AT THIS POINT (RIGHT WHEN YOU
DROP YOUR STAFF) GO [FOREWARD].
YOU WILL POUND ON A GUYS HEAD FOR
A WHILE, AND THEN GO [LEFT].
SWING ON THE VINE UNTIL YOU GET TO
WHERE KIMMY IS THEN GO [RIGHT].
NOW BORF IS UP ON HIS PEDESTAL TRYING
TO SHOOT YOU. [FIRE] AND [FIRE] AGAIN
THEN GO [LEFT]. FROM THERE GO [RIGHT]
AND GO [RIGHT] AGAIN FOLLOWED BY
ANOTHER [RIGHT]. A SHINNY MIRROR
FALLS FROM THE WALL AND AT THIS POINT
YOU GO [LEFT], PUSHING THE MIRROR INTO
THE AREA WHERE THE RAY'S BEAM WILL
LAND.  IT REFLECTS AND HIT BORF.
BORF IS NOW A BABY AND KIMBERLY WANTS
TO KEEP HIM.  HE TRIED TO KILL ME!!!

                  -----------
                  <-THE END->
                  -----------

NOTES: THE ROOMS WHICH CAN BE BACKWARDS
ARE AS FOLLOWS...

1) THE MAZE WHERE YOU FLY YOUR SHIP
2) THE SPACE STATION
3) THE SLIDING PLATFORMS (DIRECTLY
AFTER THE SPACE STATION)

4) THE AREA WHERE THE DOGS ARE
5) AFTER YOU LAND YOUR SHIP (DIRECTLY
AFTER THE DOGS)
6) THE PIT WHERE THE SPIKED WALLS ARE
CLOSING IN ON YOU.

7) THE SCENE WITH THE GIANT MEN
SHOOTING AT YOU

8) THE SPACE BATTLE (CAPTAIN LEVEL)
9) THE JUNKYARD (SPACE ACE LEVEL)
10) ROLLER SKATING (SPACE ACE LEVEL)
11) THE MOTERCYCLE SCENE
12) THE UNDER-WATER SCENE W/ KIMMY


THIS FILE DOES NOT TELL EXACTLY WHEN
TO MOVE A DIRECTION.  IT ONLY TELLS
ABOUT WHEN TO MOVE WHERE.

THANKS TO STARSHIP VIDEO (UPLAND, CA)

CALL THE 'CROWS NEST'
         209 632 7173
         P.W.= ZORKER

COMMING SOON...DRAGONS LAIR ][ IN
TEXT 'CHEATER' FILE VERSION.

                  C.1984, BAT-COM INC.
         WRITTEN: 2/18/84 BY BATMAN
