%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                   %%
%%          HOW  TO  SOLVE:          %%
%%                                   %%
%%           S U S P E C T           %%
%%                                   %%
%%          PRESENTED   BY:          %%
%%                                   %%
%%  FRIENDLY  MAN  AND  SGT. PEPPER  %%
%%                                   %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


* NOTE: THESE ARE THE EXACT COMMANDS
        NEEDED TO SOLVE INFOCOM'S
        MYSTERY THRILLER, "SUSPECT" -
        THESE ARE NOT HINTS!


=======================================


COMMANDS ARE ENCLOSED IN QUOTES AND
SHOULD BE TYPED IN EXACTLY AS THEY ARE
SEEN.

DIRECTIONAL MOVEMENTS ARE ENCLOSED IN
BRACKETS.

COMMENTS ARE PRECEDED BY '=>' OR
ENCLOSED IN PARENTHESIS.

SAVING THE GAME FREQUENTLY IS STRONGLY
RECOMMENDED

=======================================

=> YOU BEGIN AT THE BAR IN THE BALLROOM
   OF VERONICA ASHCROFT-WELLMAN'S
   COUNTRY ESTATE. MICHAEL WELLMAN WILL
   NOTICE YOU AND WAVE FOR YOU TO JOIN
   HIM AND HIS WIFE... BE ALERT! THINGS
   MAY NOT BE AS THEY SEEM!

[W], "EXAMINE VERONICA", "ASK MICHAEL
ABOUT OSTMANN", [W,W] (HERE YOU'LL BE
ENTANGLED IN A 'CONFUSION' WITH THE
BUTLER AND A GUEST. KEEP GOING SOUTH
UNTIL YOU ARRIVE AT THE LIBRARY), [W],
"UNLOCK FRONT DOOR", [S], "EXAMINE
RAIN", "WAIT"

=> AT ABOUT 9:17 OR SO, ALICIA BARRON
   WILL COME PUFFING UP TO THE FRONT
   DOOR. HER OVERCOAT IS WET. STRANGE.
   THE RAIN IS ONLY A LIGHT DRIZZLE...

"ASK ALICIA ABOUT OSTMANN", "ASK ALICIA
ABOUT COCHRANE", "ASK ALICIA ABOUT
MICHAEL"


=> HOW ODD! ALICIA HAS JUST ARRIVED AND
   SHE SEEMS TO KNOW WHO IS ATTENDING
   THE PARTY AND WHAT THEY'RE WEARING..

[N,N,E,E,N,E,E,NE,N,N], "GET BASKET"
(IF THERE IS NO BROKEN GLASS IN THE
BASKET, WAIT A FEW MOVES AND SMYTHE THE
BUTLER WILL PLACE IT THERE), [S,S,SW,W,
W,W], "GET WET COAT" (AS ABOVE, IF THE
COAT ISN'T HERE, WAIT, AND SMYTHE WILL
HANG IT UP), [E,S,W,W,W,W,S,W,N]

=> GOOD LORD! VERONICA HAS BEEN
   MURDERED! AND WITH YOUR LARIAT! NOW
   HOW DID THAT GET THERE?

"CALL POLICE", "GET FOLDER", "EXAMINE
WASTE BASKET", "LOOK UNDER BODY", "GET
BULLET", "PUT BULLET IN BELT", "GET
CARD", "GET FAIRY MASK", "READ FOLDER",
"LOOK IN  FAIRY MASK", "EXAMINE DARK
HAIR", "EXAMINE VERONICA'S HAIR"

=> IF YOU CHECK YOUR BELT YOU'LL NOTICE
   THERE'S A BULLET MISSING.. SOMEONE
   IS REALLY DETERMINED TO PIN THE
   BLAME ON YOU! AND WHAT ABOUT THE
   DARK HAIR FOUND IN VERONICA'S MASK-
   VERONICA IS BLONDE! THE CARD IS
   WILLIAM COCHRANE'S. (INCLUDED IN THE
   "SUSPECT" PACKAGE") THERE IS A NOTE
   ON THE BACK OF THE CARD WHICH READS:
   "VERONICA- PLEASE CALL ME ASAP.
   DON'T DO SOMETHING YOU'LL REGRET.
   -- BILL"  HMM.. THE PLOT THICKENS...

"WAIT" (UNTIL MICHAEL, MARSTON, AND
COCHRANE ARRIVE), "SHOW FOLDER TO
MARSTON", "SHOW FOLDER TO COCHRANE",
"ASK MICHAEL ABOUT ALICIA"

=> INTERESTING... OBVIOUSLY SOMEONE
   WANTED TO PREVENT THE SALE. BUT WHO?

(WHEN MICHAEL LEAVES THE ROOM GO,) [N,
W], "HIDE BEHIND BMW", "WAIT FOR
MICHAEL", "LOOK"

=> AHA! MICHAEL SEEMS TO HAVE SOMETHING
   TO HIDE! BUT WHAT IS IT, YOU SAY?
   WELL, YOU'LL FIND OUT LATER. RIGHT
   NOW YOU HAVE TO PROVE YOUR INNOCENCE
   TO THE DETECTIVE...

"GET UP", [E,SW], "SHOW WET COAT TO
DETECTIVE", "TELL DETECTIVE ABOUT
WEATHER", "DETECTIVE, FINGERPRINT
GLASS", [S,S,E,E], "HIDE BEHIND CHAIR",
"WAIT FOR MICHAEL", "GET UP", "ASK
MICHAEL ABOUT VERONICA"

=> HMM.. MICHAEL IS ACTING MORE
   SUSPICIOUS BY THE MINUTE... YOU'D
   BETTER FOLLOW HE AND MARSTON AND
   SEE WHAT HAPPENS...

[N,N,N,E,E], "GET PAPER"

=> NOT SO FAST COLONEL! TRYING TO
   DESTROY EVIDENCE, EH? WELL, YOU'LL
   BE DEALT WITH IN DUE TIME...

[W,W,S,W,W,W,W,N,N,N,W], "OPEN CHEST",
"DROP ALL BUT PAPER AND MASK AND
FOLDER AND CARD" (KEEP THE GLASS
ANALYSIS TOO IF YOU HAVE IT AT THIS
POINT), "GET CROWBAR", "PRY BMW TRUNK",
"GET TRUST FOLDER", "EXAMINE TRUST
FOLDER", "READ DOCUMENTS", "EXAMINE
PAPER"

=> WELL... IT LOOKS LIKE MICHAEL AND
   MARSTON WEREN'T MANAGING THE
   ASHCROFT FUNDS VERY WELL... PERHAPS
   THEY DIDN'T WANT VERONICA TO
   INTERFERE...

[E,S,S,S,E,E,E,E,N,E,E]


=> AT THIS POINT THERE ARE SEVERAL
   THINGS YOU SHOULD TRY ON YOUR OWN.
   (IT IS DIFFICULT TO PREDICT WHERE
   THE CHARACTERS WILL BE, SO I WILL
   LEAVE THEM UP TO YOU):

1. SHOW THE MANILA FOLDER TO OSTMANN
2. SHOW THE DARK HAIR TO ALICIA
3. COMPARE THE DESCRIPTION OF VERONICA
   AT THE BEGINNING OF THE GAME TO
   ALICIA'S DESCRIPTION
4. ASK OSTMANN ABOUT MICHAEL
5. SHOW THE TRUST FOLDER TO MARSTON
6. ASK MARSTON ABOUT VERONICA
7. ASK ALICIA ABOUT VERONICA
8. ASK ALICIA ABOUT MICHAEL

   NOW, YOU SHOULD LOCATE THE DETECTIVE
AND RETURN THE GLASS ANALYSIS WHICH HE
SHOULD HAVE GIVEN YOU BY NOW. HE WILL
MOST LIKELY BE BY THE FIREPLACE.

"SHOW MANILA FOLDER TO DETECTIVE",
"SHOW TRUST FOLDER TO DETECTIVE", "SHOW
PAPER TO DETECTIVE", "SHOW CARD TO
DETECTIVE", "DETECTIVE, ANALYZE HAIR",
"WAIT" (UNTIL THE DETECTIVE HANDS YOU
THE ANALYSIS OF THE HAIR FOUND IN THE
MASK), [E], "SHOW HAIR ANALYSIS TO
ALICIA", [W], "GIVE HAIR ANALYSIS TO
DETECTIVE"

=> WELL, IT LOOKS LIKE YOU HAVE A
   PRETTY TIGHT CASE AGAINST MICHAEL
   AND ALICIA. YOU HAVE ESTABLISHED THE
   MOTIVE, MEANS, AND OPPORTUNITY, SO
   ONLY ONE THING REMAINS...

"DETECTIVE, ARREST MICHAEL AND ALICIA"


=> WALA! MICHAEL AND ALICIA ARE
   CONVICTED OF FIRST DEGREE MURDER AND
   LOCKED AWAY. (WHO SAYS THERE'S NO
   JUSTICE IN THIS WORLD?) AND EVEN
   CROOKED OLD COLONEL MARSTON GETS
   NAILED FOR EMBEZZLEMENT...

CONGRATULATIONS! SIT BACK AND ENJOY
YOUR WELL-DESERVED PULITZER PRIZE...

=END=
