#######################################
##                                   ##
##          HOW TO SOLVE             ##
##            SUSPENDED              ##
##                                   ##
##     WRITTEN BY JOHN L. MOSS       ##
##                                   ##
#######################################


THE FOLLOWING IS A LIST OF COMMANDS
THAT WILL ALLOW YOU TO FINISH
SUSPENDED BY INFOCOM.

SUSPENDED IS AN EXCELLENT GAME AND
POSSIBLY THE MOST ADVANCED GAME FOR
THE ADVENTURER TO DATE. THE STORY IS
QUITE SIMPLE. YOU ARE THE FAILSAFE
DEVICE TO PROTECT THE SURFACE WORLD OF
CONTRA SHOULD ANY EMERGENCY DEVOLOP
THAT WOULD CAUSE THE PLANET CONTROL
DEVICES TO FAIL(THESE ARE UNDERGROUND
IN A COMPLEX WHERE YOU LIVE SUSPENDED
IN A CRYOGENIC TUBE AWAITING A
DISASTER)

OF COURSE A DISASTER DEVOLOPS AS SOON
AS YOU BOOT UP THE DISK.

YOU ARE AWAKENED TO FIND THAT THERE
HAS BEEN AN EARTHQUAKE THAT HAS
DAMAGED THE CABLES IN THE PRIMARY AND
SECONDARY CHANNEL.

YOU HAVE SIX DIFFERENT ROBOTS AT YOUR
COMMAND. THESE ROBOTS ALL ENJOY
DIFFERENT SKILLS AND ABILITIES. EACH
ONE REPRESENTS A DIFFERENT SENSE.

IRIS: THE SENSE OF SIGHT
WALDO:THE SENSE OF TOUCH AND DEXTERITY
SENSA:PERCEIVES THINGS MAGNETIC AND
ELECTRONIC
POET:PERCEIVES THINGS ELECTRONIC..CAN
DIAGNOSE ELECTRICAL FLOWS
WHIZ: COMMANDS THE COMPUTER AND CAN DO
ERRANDS
AUDA: THE SENSE OF HEARING

THE TRICK TO WINNING SUSPENDED IS
ASSIGNING THE RIGHT TASK TO THE RIGHT
ROBOT. ALSO THE RIGHT ROBOT HAS TO BE
AT THE RIGHT PLACE AT THE RIGHT TIME.
THIS IS CALLED CRITICAL PATH PLANNING.
AND THIS IS THE SECRET OF SUSPENDED.

IN THE STANDARD GAME THERE ARE A FEW
REAL TIME EVENTS TO BE AWARE OF:

1) AT THE 15TH CYCLE THERE IS ANOTHER
EARTHQUAKE WHICH CAUSES AN ACID SPILL
THAT KILLS IN SHORT ORDER ANY ROBOT
THAT PASSES THROUGH THE CAVERNOUS ROOM
THEREAFTER...UNTIL THE ACID IS SHUT
OFF.

2) AT THE 75TH CYCLE THERE IS ANOTHER
QUAKE WHICH WRECKS THE HYDROPONICS AND
TRANSIT EQUIPMENT ON THE SURFACE
ABOVE. THESE HAVE TO BE FIXXED QUICKLY
OR THE GAME ENDS SWIFTLY DUE TO THE
STARVING POPULOUS ABOVE.

3) AT THE 100TH CYCLE HUMANS ENTER THE
COMPLEX WITH THE INTENT OF TURNING YOU
OFF BECAUSE BY THIS TIME YOUR CLEARLY
SCREWING UP THE ASSIGNMENT. THESE
HUMANS CAN BE THE DEATH OF YOU OR THEY
CAN HELP YOU BY ....WELL I WON'T TELL
YOU YET.

THE FOLLOWING COMMAND GET YOU THROUGH
THE GAME IN LESS THAN 70 MOVES. AS A
RESULT THEY GIVE LITTLE AID IN THE
EVENT THAT YOU FINISH THE GAME IN MORE
THAN THAT TIME. THE GAME CHANGES
CONSIDERABLY AFTER THE 75TH MOVE.

THERE ARE MANY PROBLEMS THAT SURFACE
AFTER THAT TIME...WHICH THESE CLUES DO
NOTHING TO AID.

LETS GET STARTED..

#1 POET,GO TO WEATHER CONTROL
#2 SENSA,GO TO SUB SUPPLY ROOM
#3 WHIZ,GO TO SECONDARY CHANNEL
#4 SENSA,TAKE RAMP
#5 SENSA,GO WEST
#6 SENSA,TAKE CONTAINER AND GRASPER
#7 SENSA,GO TO HALLWAY JUNCTION
#8 WALDO,GO TO HALLWAY JUNCTION
#9 AUDA,GO TO GAMMA REPAIR

THE ABOVE MOVES SET THE GAME UP. POET
IS NEEDED TO TURN THE WEATHER CONTROL
OFF..THIS MINIMIZES DEATHS AT THE
SURFACE...YOUR PRIMARY GOAL. SENSA
GETS THE RAMP THAT IS NEEDED TO ALLOW
THE ROBOTS TO GO FROM ONE LEVEL TO
ANOTHER. AUDA IS SENT TO THE GAMMA
REPAIR AREA BECAUSE SHE WILL BE NEEDED
LATER...AND WITHOUT THE HUMANS COMING
FOR A WHILE THERE IS NOTHING THAT CAN
BE DONE WITH HER ANYWAY. WALDO, IS
SENT TO THE HALLWAY JUNCTION TO MEET
SENSA AND TAKE THE CONTAINER AND
GRASPER ON HIS WAY TO FIXING IRIS WHO
IS REPORTED TO BE OUT OF ORDER.

#10 POET,TURN SECOND DIAL TO 100
#11 POET,GO TO HALLWAY END
#12 IRIS,GO TO MAIN SUPPLY ROOM
#13 SENSA,PUT RAMP AT DROPOFF
#14 AUDA, LISTEN
#15 WALDO,TAKE CONTAINER AND GRASPER
#16 WALDO,GO TO MAIN SUPPLY
#17 WALDO,INSTALL GRASPER
#18 WALDO,TAKE RED IC AND YELLOW IC
#19 SENSA,GO NORTH
#20 SENSA,TAKE RAMP

ONCE POET GOT TO THE WEATHER CONTROL,
HE HAD TO RESET THE FAULTY CONTROL TO
100.  THIS IS ONLY A TEMPORARY FIX
BECAUSE IF YOU LET THE GAME GO ON TOO
LONG, ALL HELL WILL BREAK LOOSE WITH
VARIOUS DISASTERS AND ACCIDENTS
OCCURING WHICH YOU WILL NOT BE ABLE
TO CONTROL. POET IS THEN SENT TO THE
HALLWAY END WHERE HE WILL BE USED TO
GET THE TV CAMERA NEEDED LATER.

IRIS IS SENT TO THE MAIN SUPPLY
ROOM WHERE SHE CAN BE FIXED WHEN
WALDO ARRIVES. SHE WILL ALSO HELP
WALDO REPAIR THE MACHINE THERE.

SENSA...UPON ARRIVING PUTS THE RAMP IN
PLACE SO THAT AUDA CAN GET TO GAMMA
REPAIR AND SO THAT SHE AND POET CAN GET
TO THE OTHER LEVEL. WALDO IS HANDED
THE GRASPER AND CONTAINER WHICH HE
INSTALLS. THIS IS DONE NOW TO SAVE
MOVES LATER.

#21 SENSA,GO TO SMALL SUPPLY
#22 WALDO,OPEN PANEL
#23 WALDO,REPLACE ROUGH DEVICE WITH
    ROUGH OBJECT
#24 WALDO,CLOSE PANEL
#25 POET,GET IN CAR
#26 POET,GET OUT OF CAR
#27 POET,GO TO BIOLOGY LAB
#28 WALDO,TAKE BURNED AND FRIED CHIP
#29 POET,TAKE CAMERA
#30 SENSA,PUT RAMP AT HOLDER

THIS STAGE SETS THE ROBOTS TO THEIR
MAJOR GATHERING TASKS. WALDO HAS
FIXED IRIS, AND IS NOW SET ON FIXING
THE MACHINE AND SALVAGING ITS PARTS.
POET HAS ARRIVED AT THE HALLWAY END ,
GOTTEN IN THE CAR, EXITED THE CAR AND
IS NOW GETTING THE CAMERA. AND SENSA
HAS ARRIVED AT THE SMALL SUPPLY ROOM
TO TAKE THE CABLE CUTTER.

#31 SENSA,GET ON RAMP
#32 SENSA,TAKE CUTTER
#33 SENSA,GET OFF RAMP
#34 SENSA,TAKE RAMP
#35 SENSA,GO TO SLOPING CORRIDOR
#36 POET,GO TO VEHICLE DEBARKATION
#37 WALDO,PUT RED IC IN RED SOCKET
#38 WALDO,PUT YELLOW IC IN YELLOW
SOCKET
#39 POET,GET IN CAR
#40 POET,GET OUT OF CAR

SENSA HAS COMPLETED HER TASK OF
GETTING THE METAL TOOL THAT SHE WILL
NEED SHORTLY. POET HAS GOTTEN THE
CAMERA AND IS NOW COMING BACK AND
WALDO IS IN THE MIDST OF FIXING AND
SALVAGING THE MACHINE WITH IRIS IN THE
MAIN SUPPLY ROOM

#41 POET,GO TO PRIMARY CHANNEL
#42 SENSA,PUT RAMP AT DROPOFF
#43 GO TO GAMMA REPAIR
#44 WALDO,PUSH BUTTON
#45 IRIS,TAKE FUSE
#46 WALDO,TAKE CABLE
#47 WALDO,GO TO THE SECONDARY CHANNEL
#48 IRIS,GO TO MIDDLE SUPPLY
#49 IRIS,TAKE CABLE
#50 IRIS,GO TO MAIN SUPPLY

POET HAS BEEN SENT TO USE THE CAMERA
IN THE PRIMARY CHANNEL (THIS IS A
KAMIKAZE MISSION BECAUSE HE HAS TO
PASS THROUGH THE CAVERNOUS ROOM TO GET
THERE). SENSA HAS GOTTEN TO THE SLOPING
CORRIDOR AND REINSTALLED THE RAMP SO
THAT SHE AND POET CAN GET TO THE LOWER
LEVEL. AND WALDO AND IRIS HAVE GOTTEN
THE MACHINE FIXED AND SALVAGE ONE OF
THE TWO NEEDED CABLES TO SET THE FCS
IN BALANCE.

WALDO IS NOW SET ON A KAMIKAZE MISSION
WHERE WHIZ WILL BE WAITING TO INSTALL
THE CABLE NEEDED IN THE SECONDARY
CHANNEL.

#51 SENSA,EXAMINE OBJECT
#52 SENSA,TURN FLOWSWITCH
#53 BOTH SENSA AND AUDA,MOVE FRED
#54 SENSA, CUT CABLE WITH CUTTER
#55 POET,PLUG TV1 IN
#56 POET,AIM TV1 AT SIGN

(THIS IS THE IMPORTANT RESET
CODE..WRITE IT DOWN..ITS DIFFERENT
EVERY GAME)

#57 SENSA,TAKE CABLE
#58 SENSA,GO TO PRIMARY CHANNEL
#59 IRIS, PUT CABLE IN MACHINE
#60 IRIS, PUT FUSE IN MACHINE

SENSA AND AUDA SALVAGED THE REMAINING
NEEDED CABLE TO FIX THE CABLE IN THE
PRIMARY CHANNEL. SENSA IS NOW ON HER
WAY. POET VALIENTLY DIED TRYING TO
WORK THE CAMERA IN THE PRIMARY CHANNEL
AFTER HAVING CORROSIVE ACID SPILLED ON
HIM. AND IRIS HAS FIXED THE RESET
MACHINE NOW ONLY AWAITING THE
INSTALLATION OF THE CABLES IN THE FCS
TO RESET THE SYSTEMS TO SET THE
SURFACE WORLD ABOVE RIGHT.

#61 WHIZ,GO TO WALDO
#62 WHIZ,TAKE FOURTEEN-INCH CABLE
#63 WHIZ,REPLACE THE NINE-INCH CABLE
WITH THE FOURTEEN-INCH CABLE
#64 WHIZ,DRAG WALDO TO THE EAST END
#65 AUDA,GO TO SLEEP CHAMBER
#66 SENSA,REPLACE FOUR-INCH CABLE WITH
TWELVE-INCH CABLE
#67 IRIS,PRESS ----- CIRCLE
#68 IRIS,PRESS ----- CIRCLE

AT THIS POINT THE GAME IS OVER AND
ONLY 8000 ARE DEAD AND YOU HAVE
SUCCEEDED IN YOUR MISSION. IT SHOULD
BE NOTED THAT THIS DOES NOT ANSWER ALL
THE QUESTIONS AND PUZZLES THAT ARE
PRESENTED IN THE GAME IT JUST TELLS
YOU HOW TO WIN THE GAME IN THE
SHORTEST ORDER.

ENJOY!

JOHN L. MOSS
