*:--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--:*
--:*                               *:--
*:--              HOW              --:*
--:*              T O              *:--
*:--             SOLVE             --:*
--:*                               *:--
*:--    T R A N S Y L V A N I A    --:*
--:*                               *:--
*:--------------WRITTEN--------------:*
--:*              B Y              *:--
*:--         THE ENCHANTOR         --:*
--:*                               *:--
*:--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--:*


        COPYRIGHT (C) - 1983
        BY THE MINES OF MORIA


A LITTLE EXPLANATION BEFORE WE BEGIN.
TRANSYLVANIA HAS SOME THINGS THAT LIKE
TO HAPPEN RANDOMLY, WHICH MADE IT A
PAIN TO TRY TO WRITE A TUTORIAL FOR
IT AND WAS PROBABLY WHY NO ONE ELSE
HAS ALREADY. YOU GOTTA SAVE YOUR GAME
ALOT, SO WHEN A GIANT EAGLE DECIDES
TO SWOOP DOWN AND STICK YOU IN SOME
STRANGE PLACE YOU CAN JUST RE-BOOT
AND START WHERE YOU LAST SAVED YOUR
GAME. OK, LET'S START.

     WHEN YOU START, YOU'RE AT SOME
OLD STUMP, DON'T MESS WITH IT. RIGHT
NOW, WE GOTTA GO GET A SILVER BULLET.

N,W,N,N,
NOW......GO WAGON, OPEN COFFIN,
         GET BULLET, D.

SAVE GAME

NOW WE'RE GONNA GO AFTER A PISTOL,
THIS IS A TOUGH ONE.

GO.....E, E, N, E
NOW....GO HOUSE, U

A WEREWOLF HAS PROBABLY BEEN FOLLOWING
YOU HUH? WELL IF NOT DON'T WORRY HE'LL
BE AROUND SOON. KEEP GOING UP AND DOWN
( 'U' & 'D' ) BETWEEN THE ATTIC AND
THE FIRST FLOOR OF THE HOUSE UNTIL YOU
HAVE A FREE TURN TO GRAB THE PISTOL IN
THE ATTIC. NOW.........GET PISTOL

IF THE WEREWOLF DIDN'T APPEAR AGAIN
TYPE......LOAD PISTOL.....IF HE DID
JUST KEEP GOING UP & DOWN AGAIN UNTIL
YOU GET A CHANCE TO LOAD YOUR PISTOL.
WHEN THE WEREWOLF APPEARS AGAIN, TYPE..
.SHOOT WEREWOLF.....OK NOW IT'S DEAD,
NOW GET BACK TO THE FIRST FLOOR OF
THE HOUSE IF YOU AREN'T ALREADY THERE.

SAVE GAME

NOW GO....E, W, W,
NOW....GET CROSS
GO....S, E, N, N,

NOW THERE SHOULD BE A VAMPIRE, IF NOT,
CRUISE AROND THE CASTLE TIL ONE APPEARS
AND TYPE.....SHOW CROSS, THEN...DROP
CROSS. GET BACK TO THE MAIN HALL IF
YOU AREN'T ALREADY THERE.

NOW GO....N, D, D, D
NOW...OPEN COFFER, GET RING,

SAVE GAME

NOW WE GOTTA GET A POTION

GO.....U, U, U, S, S, S, E, E,
SAY IJNID (TO THE GOBLIN)
GET KEY, N, N, W,
NOW....MOVE GRAVESTONE, UNLOCK GRATE,
GO GRATE, GET POTION.

SAVE GAME

NOW WE HAVE TO GET A WIZARD'S CLOAK.
DROP KEY
GO.....U, S, S,
GO CABIN, PULL HORNS, GET CLOAK, PULL
HORNS,

GO....W, N, N, W,
WAVE RING

NOW YOU'VE FREED SOME ALIEN DUDE AND
HE'S GONNA RETURN WITH SOMETHING.

SAVE GAME

NOW WE'RE GONNA KILL SOME TIME TO
WAIT FOR THAT ALIEN.

S, S, S, E, N, N, N, W, S, S, S, E, N,
N, ALMOST DONE KEEP GOING, N, W, S, S,
N, N, N, W,

THERE! NOW YOU SHOULD BE AT A FLYING
SAUCER OR WHATEVER.

GO SAUCER,
NOW YOU GOT A LITTLE BLACK BOX,
GO...E, S, E, N, N, N, U,
NOW....CLIMB LADDER, GET VINES, PUSH
BUTTON, WAVE POTION, POUR POTION,
CLAP,

NOW THE PRINCESS IS AWAKE!

GET PRINCESS,
GO..D, D, S, S, S, W, S, S, S,

SAIL BOAT................

YOU WIN!

LATER--     ENCHANTOR

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
