SOLVE FOR: ULTIMA III-THE EXODUS


ABILITY POINTS: (STRENGTH,DEXTERITY,INTELLIGENCE,WISDOM)
A HIGH STRENGTH IS HIGHLY DESIRABLE NO MATTER WHAT YOUR CLASS IS.
A HIGH DEXTERITY IS NEEDED FOR THIEVES.
A HIGH WISDOM IS NEEDED FOR CHARACTERS THAT USE CLERICAL SPELLS.
A HIGH INTELLIGENCE IS NEEDED FOR CHARACTERS THAT USE WIZARD SPELLS.

GOLD:
 GOLD IS FOUND IN CHESTS. GOLD CAN BUY WEAPONS,ARMOR,FOOD,HEALING,
  AND ABILITY POINTS (SEE TEMPLES).
 TO GET A LOT OF GOLD,YOU CAN DO IT SEVERAL WAYS:
   1.  CREAT A LOT OF DUMMY CHARACTERS. FORM THE PARTY. JOURNEY
        ONWARDS. JOIN GOLD TO ONE CHARACTER. HAND ALL THE FOOD TO THAT
        ONE CHARACTER. QUIT OR SAVE GAME. DELETE THE "DUMMY"
        CHARACTERS,EXECPT FOR THE ONE WITH ALL THE FOOD AND GOLD.
        USE THAT CHARACTER AS A PERMANENT ONE.
   2.  GO OUT AND KILL MONSTERS (THIS METHOD ALSO INCREASES YOUR
        EXPERIENCE AND YOUR CHANCES OF KICKING THE BUCKET).
   3.  LOCATE YOUR CASTLE (YOU START NEAR IT). GO TO THE DUNGEON
        EAST OF IT. MAT THE 2ND,3RD,AND 4TH LEVELS USING A GEM.
        USE A WIZARD SPELL "D" OR A CLERIC SPELL "D" TO GET DOWN TO
        THE 3RD LEVEL. GET ALL THE GOLD THERE. DESCEND DOWN TO THE
        4TH LEVEL GET ALL THE GOLD THERE. KLIMB BACK UP TO THE 3RD
        LEVEL. CAST WIZARD OR CLERIC SPELL "E" TO GET TO THE 2ND LEVEL.
        GO TO THE FOUNTAIN OF HEALING AND HEAL ALL THE
        DAMAGE DONE. CAST SPELL "E" AGAIN. CAST IT AGAIN TO GET
        OUT OF THE DUNGEON. THIS WAY PROVIDES ABOUT 3000 GOLD
        AND SOME EXPERIENCE EVERY TIME.
ESTALISHING A HOME BASE:
 LOCATE YOUR CASTLE. WAIT ON TOP OF IT UNTILL A MONSTER ATTACKS YOU.
 KILL THE MONSTERS. **DON'T TAKE THE CHEST OF GOLD**. KEEP MOVING
 AROUND YOUR CASTLE AND KILLING MONSTERS UNTIL YOU HAVE CREATED A
 SOLID MASS OF CHESTS AROUND YOUR CASTLE. MAKE IT BIG ENOUGH SO
 THAT FIRE FROM BOATS AND DRAGON-LIKE MONSTERS CAN'T HIT YOU.
 THIS CAN BE DONE ANYWHERE IN SOSARIA. THIS ALLOWS YOU TO HAVE A
 SAFE SPOT WHERE YOU CAN REST AND KILL MONSTERS ONE AT A TIME AT
 YOUR LEISURE.

GO TO THE KING IN YOUR CASTLE WHEN YOU HAVE ACQUIRED 100 EXPERIENCE
 POINTS. TRANSACT WITH HIM. YOUR # OF HIT POINS IS INCREASED.
 DO THIS EVERY 100 EXPERIENCE POINTS.

TRY TO GET KEYS,POWDERS,GEMS,AND TORCHES AS SOON AS POSSIBLE.
 KEYS UNLOCK DOORS.
 POWDERS NEGATE TIME.
 GEMS ALLOW YOU TO VIEW THE ENTIRE WORLD,TOWN,DUNGEON YOU ARE IN.
 TORCHES LIGHT UP DUNGEONS.

>>> BOATS:
THERE ARE TWO KINDS OF BOATS. THE BOATS YOU OWN, AND THE BOATS OF
  PIRATES.
TO GET A BOAT, YOU MUST ENTER THE COMBAT STAGE WITH THE BOAT.
 TO GET THE BOAT WITH MINIMUM DAMAGE, MOVE AROUND UNTIL THE PIRATE
 FROM ONE SIDE. WAIT OUT OF REACH OF ITS GUNS AND OBSERVE HOW BAR
 AND WHERE ITS CANON FIRE GOES. PLOT A ROUTE THAT WILL LEAD YOU TO
 THE SIDE OF THE BOAT. THE BOAT WILL NOT FIRE UPON YOU ON THIS
 LAST MOVE. AT THIS POINT YOU SHOULD ENTER THE COMBAT MODE. IF
 YOU DON'T ATTACH THE BOAT. KILL THE PIRATES. YOU NOW HAVE A
 BOAT. BOARD IT. TO USE THE CANON, FIRE. KILLING MONSTERS WITH
 CANON FIR DOESN'T GIVE YOU EXPERIENCE OR GOLD.

>>> CHESTS:
 CHESTS CONTAIN GOLD AND MAYBE ARMOR OR WEAPONS.
 TO OPEN A CHEST, STAND ON TOP OF IT AND GET CHEST. THIS METHOD CAN
 BE DANGEROUS BECAUSE MANY CHESTS ARE TRAPPED WITH ACID,POISON,GAS,
 OR BOMBS.
 ANOTHER WAY TO OPEN A CHEST, THAT IS LESS DANGEROUS, IS TO CAST
 CLERIC SPELL "B". SOMETIMES THSI SPELL FAILS. IT ALLOWS YOU TO
 OPEN A CHEST WITHOUT TRIGGERING THE TRAP. MONSTERS CANNOT MOVE OVER CHESTS.

>>> TEMPLES:
TEMPLES RAISE ABILITIES.
TO GET TO A TEMPLE: BOARD A SHIP. SEARCH FOR THE WHIRLPOOL (IT
 IS THE WEIRD-LOOKING SWIRLING THING IN THE WATER AND IT IS CONSTANTLY
 MOVING). MOVE YOUR SHIP ON TOP OF IT. IT SHOULD LEAVE
 YOU ON THE SHORES ON A STRANGE LAND. PEER AT A GEM TO GET AN
 IDEA OF WHAT KIND OF PLACE YOU'RE IN. LOOK AT THE MAP AND SEARCH
 FOR 4 BUILDINGS (THEY SHOULD BE IN THE MIDDLE OF A LARGE OPEN
 SPACE). PLAN A ROUTE TO ONE OF THE BUILDINGS. GO THE THE BUILDING.
 IT IS THE TEMPLE/SHRINE. LOOK AT THE BUILDING. IT SHOULD BE A
 SHRINE. ENTER IT. OFFER ONLY ONE HOULDRED GOLD PIECES AT A TIME.
 FOR EVERY 100,ONE OF YOUR ABILITIES SHOULD GO UP ONE POINT,
 ACCORDING TO WHICH ONE OF THE SHRINES YOU ARE IN. SEACH THE SHRINE
 (USING THE OTHER COMMAND) TO GET CARDS. LET ALL OFYOUR CHARACTERS
 SEARCH IT. THE AREA IS THE SAME EVERY TIME YOU GO INTO WHIRLPOOL.
 TO GET OUT OF THAT WORLD AND BACK TO SOSARIA, YOU MUST SEARCH FOR A BOAT
 IN THE SOUTHERN PART OF THE WORLD. THEN ONCE YOU GET
>>> DUNGEONS:
DUNGEONS ARE VERY DANGEROUS. THEY HOLD TRAPS. WINDS MAY PUT OUT
 YOUR SOURCE OF LIGHT,FOUNTAINS MAY POISON YOU OR JUST CAUSE DAMAGE
 TO YOU,AND MONSTERS ABOUND. FOOD MUST BE CONSIDERED ALSO. HOWEVER,
 GOING INTO DUNGEONS IS NECESSARY IN ORDER TO GET ARKS.
 EVERY TIME YOU GO TO A NEW LEVEL,PEER AT A GEM. MAP THE LEVEL,
 INCLUDING THE QUESTION MARKS. NOW YOU HAVE THE QUESTION MARKS TO
 YOU THAT SOMETHING IS THERE. GO TO WHERE THE QUESTION MARDS ARE.
 FIND OUT WHAT THEY REPRESEND AND MARK IT ON YOUR MAP.
 FOUNTAINS:
  FOUNTAINS HEAL,POISON,DAMAGE,OR DON'T AFFECT YOU AT ALL WHEN
   YOU DRINK FROM THEM.
 TRAPS:
  TRAPS CAUSE DAMAGE. THEY MAY BE AVOIDED IF YOU HAVE A GOOD DEXTERITY.
 MONSTERS: THESE ABOUND IN DUNGEONS. THEY DO LEAVE CHESTS WHEN KILLED.
 CHESTS: THESE ARE OFTEN FOUND LYING ABOUND IN DUNGEONS.
 MARKS: THESE ARE NEEDED TO SOLVE THE GAME. THE MARK OF KINGS IS
         FOUND ON THE 1ST LEVEL OF THE DUNGEON EAST OF THE CASTLE.
         OTHER MARKS ARE FOUND ON THE 8TH LEVEL OF DUNGEONS.
 WIND: PUTS OUT YOUR SOURCE OF LIGHT
 GREMLINS: THESE LITTLE BUGGERS STEAL YOUR FOOD. THE WORST THING IS
            THAT YOU CAN'T FIGHT THEM.
 
>>> MARKS:
MARKS ARE NEEDED TO SOLVE THE GAME.
 THE MARK OF KINGS-THIS MARK IS NEEDED TO GET THE KING TO GIVE YOU
  MORE THAN 500 HIT POINTS. IT ALLOWS YOU TO GET 2500 HIT POINTS.
  YOU SHOULD GET THIS MARK FIRST.
 
 THE MARK OF FIRE-THIS MARK ALLOWS YOU TO GET THROUGH FIRE WITHOUT
  BEING DAMAGED.
 
 THE MARK OF FORCE-THIS ALLOWS YOU TO GO THROUGH FORCE FIELDS WITHOUT
  BEING DAMAGED.

 THEH MARK OF THE SNAKE-THIS MARK ALLOWS YOU GO GET PAST THE SNAKE
  AT THE MOUTH OF THE ENTRANCE TO EXODUS. TO GET PAST THE SNAKE
  YOU MUST HAVE THE MARK AND YELL "EVOCARE".

 THE MARKS OF FIRE,FORCE, AND SNAKE ARE FOUND ON THE 8TH LEVEL OF
  DUNGEON SURROUNDED BY FIRE.
 THE MARK OF KINGS IS FOUND ON THE 1ST LEVEL OF THE DUNGEON EAST OF
  YOUR CASTLE.

>>> EXOTICS:
 THESE ARE WEAPONS AND ARMOR THAT CAN BE USED BY ANY RACE AND CLASS.
  THESE ARE REQUIRED TO DEFEAT EXODUS. THEY ARE FOUND ON TWO ISLANDS.
  ONE ISLAND IS A TWO SPACE (MEANING THAT IT TAKES TWO SPACES
  UP-A MONSTER TAKES UP ONE SPACE,A TOWN TAKES UP ONE SPACE).
  IT IS NEAR THE TOWN OF FAWN. IT IS NORTH AND WEST
  OF THE CASTLE. THE OTHER ISLAND IS SOUTH OF THE CASTLE.
  IT IS ALSO A TWO SPACE. IT IS WEST OF THE ROW OF "A'S".
 
>>> HORSES:
 THESE ARE  A GREAT AID TO YOU. THEY LET YOU MOVE ABOUT TWICE AS FAST
  AS MONSTERS. HOWEVER THEY DON'T APPEAT IN THE COMBAT MODE. MOVING
  TWICE AS FAST AS MONSTERS MAY NOT SEEM LIKE A GREAT THING,BUT
  YOU'LL BE THANKFUL FOR IT WHEN YOU HAVE TEN MONSTERS BEHIND YOU
  WHILE YOU'RE ON THE OTHER SIDE OF THE WORLD FROM YOU HOME BASE,
  YOU'RE DOWN TO A LOW NUMBER OF HIT POINTS,AND YOUR OUT OF
  FOOD.
 HORSES COST ABOUT 800 GOLD PIECES AT STORES.
 YOU CAN GET FREE HORSES BY GOING TO FAWN. 1ST,GET THREE BOATS.
  LINE THEM UP IN A BOAT BRIDGE FROM THE MAINLAND TO FAWN. NEXT,
  USING THE BOAT BRIDGE,WALK TO FAWN. THEN ENTER FAWN AND CROSS
  THE BRIDGE ACCROSS THE WATER. NOW HEAD NORTH. GET ON THE HORSE
  YOU SEE AT THE NORTHERN PART OF THE ISLAND BY BOARDING IT. GO
  BACK THE WAY YOU CAME WITH THE HORSE. GALLOP OVER THE BOAT BRIDGE
  TO THE MAINLAND. EXIT THE HORSES. GO BACK TO FAWN AND GET THE
  HORSE AGAIN. KEEP DROPPING THE HORSES ON THE MAINLAND UNTIL YOU
  THINK YOU HAVE ENOUGH.
 HORSES ARE DESTROYED IF THE PARTY IS DISPERSED.
 
>>> DAWN:
 THIS TOWN IS THE CITY OF MYTH AND MAGIC. IT HAS MAGICAL WEAPONS AND
  ARMOR FOR SALE AT ITS STORES. IT HAS A THIEVE'S TOOLS,HEALING,
  RATIONS,STABLE,WEAPONS,AND ARMOR STORES. IT HOLDS CLUES AS TO
  WHERE TO DIG FOR EXOTICS. IT HAS ALL OF ITS GUARDS AT ITS ONE
  ENTRANCE/EXIT.
 THIS TOWN ONLY APPEARS ONCE IN A MOON CYCLE. WHEN THE TWO NUMBERS
  AT THE TOP OF THE SCREEN SHOW "0,0",THEN DAWN APPEARS. IT IS
  35 SPACES SOUTH AND 8 WEST OF THE CASTLE. COUNT THE ROW OF "A'S"
  AS A SPACE. WHIN IT FIRST APPEARS,YOU HAVE 3 MOVES TO GET IN.
 
>>> EXODUS:
 TO WIN THE GAME YOU MUST KILL OFF EXODUS. EXODUS IS A COMPUTER
  COMPRISED OF 4 IN 1. TO DEFEAT EXODUS YOU NEED THE 4 CARDS.
  THESE CARDS ARE FOUND AT THE 4 SHRINES. LOCATION OF EXODUS-
  EXODUS IS LOCATED IN A CASTLE. THIS CASTLE IS WEST OF FAWN.
  LOOK FOR THE CHANNEL WITH THE SILVER SNAKE BLOCKING THE WAY.
  YOU NEED A BOAT TO GET TH THE SILVER SNAKE. TO GET PAST THE
  SILVER SNAKE YOU MUST HAVE THE MARK OF THE SNAKE. TO GET PAST
  THE SNAKE HAVE THE CHARACTER WITH THE MARK OF THE SNAKE YELL
  "EVOCARE" WHILE HE IS ON THE BOAT DIRECTLY SOUTH OF THE SNAKE.
 BEFORE ATTACKING EXODUS:
  MAKE SURE ALL OF THE ATTACKING CHARACTERS HAVE AT LEAST 300
  RATIONS EACH.
  MAKE USE OF ALL FOUR SPACES FOR CHARACTER (BRING 4 CHARACTERS).
  MAKE SURE ALL FORU CHARACTERS HAVE 2500 HIT POINTS.
  MAKE SURE ALL SPELL USERS HAVE MAXIMUM INTELLIGENCE AND/OR
  WISDOM.
  MAKE SURE ALL SPELL USERS HAVE MAXIMUM SPELL POINTS READY.
  MAKE SURE ** EVERYONE ** HAS EXOTICS.
  ARM ** EVERYONE ** WITH EXOTICS. THE ONLY THAT WILL HIT
  ANYTHING INSIDE OF THE CASTLE IS EXOTICS.
  HAVE ** EVERYONE ** WEAR EXOTIC ARMOR.
  SPELLS WORK AS USUAL. HOWEVER NEGATING TIME EITHER WITH A SPELL
  OR A POWDER DOESN'T WORK.
  MAKE SURE THAT YOU HAVE A LOT OF KEYS AND GEMS.
  MAKE SURE THAT AT LEAST ONE OF YOUR CHARACTERS CAN CAST CLERIC
  SPELL "B".
  MAKE SURE THAT YOU HAVE AT LEAST ONE CHARACTER WITH A LOT OF MONEY
  THAT YOU'RE NOT TAKING INSIDE THE CASTLE. HE CAN PAY THE
  HEALERS TO RAISE THE OTHER CHARACTERS FROM THE DEAD WHEN THEY
  DIE.
  MAKE SURE THAT EVERYONE HAS THE MARK OF FORCE AND THE MARK OF
  FIRE.
  MAKE SURE THAT EVERYONE HAS THE CARDS OF DEATH,LOVE,MOONS,
  AND SOL.
  MAKE SURE THAT SOMEONE IN THE PARTY HAS A LOT OF MONEY.
  MAKE SURE THAT THE PARTY IS COMPRISED OF YOUR BEST CHARACTERS.
  MAKE SURE THAT YOU HAVE A BOAT.
 
>>> INSIDE THE CASTLE:
 WHEN YOU FIRST ENTER THE CASTLE,GET INSIDE THE CASTLE AWAY FROM
  THE GRASS AS SOON AS YOU CAN. THE GRASS IS ALIVE AND IT WILL
  ATTACK YOU.
 YOU WILL NOTICE THAT THE BRICK FLOOR LIGHTS UP ONE SPACE AT A TIME
  JUST ABOUT EVERYTIME YOU DO SOMETHING. WHEN YOU ARE HIT BY IT
  ALL PARTY MEMBERS WILL BE DAMAGED AS IF BY A SHIP.
 ONCE YOU'RE INSIDE,AWAY FROM THE GRASS,PEER AT A GEM. EXODUS
  IS AT THE VERY TOP MIDDLE OF THE SCREEN. SOUTH OF IT IS A
  LARGE AMOUNT OF FIRE AND FORCE FIELD. PLAN THE MOST DIRECT
  ROUTE TOWARD IT. YOU'LL HAVE TO ONE SIDE BEFORE YOU HEAD NORTH
  (I.E. YOU CAN'T GO STRAIGHT NORTH. THERE'S SOMTHING CALLED
  A WALL IN YOUR WAY). TO THE EAST THERE'S A FORCE FIELD WITH
  TWO TRAGON-LIKE MONSTERS BEHIND IT.
  YOU'LL HAVE TO ALLOW THEM TO HIT YOU WITH THEIR BREATH WEAPONS
  WHEN YOU APPROACH THEM. DON'T BOTHER TAKING THE CHESTS ONCE YOU KILL THEM.
CONTINUE TO HEAD EAST THEN FOLLOW THE CORRIDOR NORTH.
A BALRON WILL START TO FOLLOW YOU AFTER YOU'VE BEEN GOING NORTH
  FOR A WHILE. KEEP HEADING NORTH. THE BALRON WILL CATCH UP TO
  YOU UNLESS YOU'VE SOMEHOW MANAGED TO BRING A HORSE WITH YOU.
  DON'T BOTHER GOING INTO THE END OF THE CORRIDOR THAT THE BALRON CAME FROM.
  IT'S A DEAD END.
KEEP HEADING NORTH. WHEN YOU GET TO THE POINT WHERE YOU CAN GO
  WEST, GO WEST.
KILL OFF THE DRAGON IN THE WAY. IT SHOULD BE IN BETWEEN TWO
  FORCE FIELDS RUNNING NORTH AND SOUTH.
KEEP HEADING WEST UNTILL YOU'RE DIRECTLY SOUTH OF A LARGE AMOUNT
  OF FORCE FIELDS AND FIRE. GO THROUGH THEM.
STOP WHEN YOU GET TO THE POINT WHERE THE BRICK FLOOR AND THE
  FIRE MEET. WAIT THERE UNTILL THE FLOOR ATTACKS YOU. YOU
  SHOULD KILL OFF THE FLOOR ABOUT 3 TIMES. YOU MAY HAVE
  TO MOVE AROUND A LITTLE BIT BEFORE THE FLOOR ATTACKS YOU 3 TIMES.
AT THIS POINT, ** YOU ARE DIRECTLY SOUTH OF EXODUS **. DON'T START
  CELEBRATING YET. JUST BECAUSE YOU'VE SPENT MONTHS TRYING TO
  SOLVE ULTIMA III, AND YOU'RE STILL THANKING GOD THAT SOMEONE
  WAS NICE ENOUGH TO GIVE YOU THIS CHEAT-SHEET,THATS NO
  REASON TO GET EXCITED. ESPECIALLY WHEN YOU'LL PROBABLY DIE
  TRYING TO FIGURE OUT HOW TO KILL EXODUS. I MEAN,WHY SHOULD
  I TELL A SCUM LIKE YOU HOW TO SOLVE THIS? JUST BECAUSE I
  SPENT LONG,AGONIZING HOURS GETTING EXPERIENCE AND GOLD
  AND MARKS AND LITTLE CLUES THAT WERE SPREAD OUT ALL OVER THE
  PLACE,WHILE A FREELOADER LIKE YOU GETS A SHEET LIKE THIS,
  I MEAN,I'VE TOLD YOU ** EVERYTHING ** ABOUT HOW TO SOLVE ULTIMA III.
  EVERYTHING THAT IS,EXCEPT HOW TO KILL EXODUS. WOULDN'T
  YOU LIKE TO KNOW? GUESS WHAT? IF YOU INSERT THE WRONG CARD
  INTO THE WRONG PANEL,IN THE WRONG SEQUENCE,THE CHARACTER
  INSERTING THE CARD WILL DIE. OF COURSE IF YOU HAVE A CLERIC
  OR SOMETHING THAT CAN RESURRECT OR RECALL PEOPLE,THAN YOU CAN
  KEEP ON GOING. OF COURSE,THE FLOOR WILL KEEP ON LIGHTING UP
  AND YOU'RE FOOD MIGHT RUN OUT,BUT IF YOU DON'T HAVE ANYONE
  WHO CAN RAISE THE DEAD,THEN AT LEAST YOUHAVE THE GUY WITH
  A LOT OF MONEY WHO WASN'T WITH THE PARTY IN THE CASTLE TO
  PAY THE HEALERS TO RAISE YOU GUYS FROM THE DEAD. AND I BET
  THAT A SCUM LIKE YOU PROBABLY HAS A CHEAT DISK,SO THAT YOU
  DIDN'T EVEN HAVE TO GO INTO THE DUNGEONS,OR TO THE SHRINES,
  OR EVEN HAVE TO GO OUT AND GET EXPERIENCE AND EXOTICS,
  WHILE I ON THE OTHER HAND,SPENT MONTHS TRYING TO SOLVE THIS.
  AND THING OF THE POOR GUY WHO HAD TO FIGURE OUT HOW TO MAKE
  A CHEAT DISK FOR ULTIMA III,JUST THINK OF LORD BRITISH AND
  ALL OF THE TIME HE SPENT MAKING THIS PROGRAM,AND YOU PROBABLY
  HAVE A PIRATED VERSION. YOU'RE AN ENEMY TO CAPITALISM,
  YOU'RE A LAW-BREAKER,YOU'RE A STINKING,NO-GOOD,DIRTY,LOUSY,
  S.O.B. (SON OF A BALRON). GUYS LIKE YOU MAKE GOOD COMMIES.
  WELL GUESS WHAT,YOU STINKING TRAITORTO THE UNITED STATES OF
  AMERICA,I'M NOT GOING TO TELL YOU HOW TO DESTROY EXODUS.
  I'M SICK OF SCUM LIKE YOU UNDERMINING THE GREAT NATION OF
  THE UNITED STATES. SCUM LIKE YOU HELPED ORGANIZE THE ANTI-
  NUKE RALLIES. SO I HOPE YOU GO CRAZY TRYING TO SOLVE THIS
  PROGRAM,JUST LIKE I DID. HA,HA,HA,HA,HA,HA,HA,HA,HA,HA,
  HA,HA,HA,HA,HA,HA,HA,HA,HA,HA,HA,. THEY'RE COMING TO GET ME NOW.
  LONG LIVE THE FREE WORLD.
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
FINIAL STEPS...
INSERTING CARDS INTO EXODUS:
 I'M ALL RIGHT KNOW. THEY LET ME OUT OF THE INSTITUTION. NOW I
  CAN TELL YOU HOW TO SOLVE THE VERY LAST PART OF ULTIMA III.
  AFTER KILLING THE FLOOR,GO RIGHT UNDER EXODUS. LOOK AT IT
  JUST TO MAKE SURE THAT YOU'RE IN THE RIGHT PLACE. IF IT SAYS
  "EXODUS" THAN YOUR THERE! LOOK AT FIG. 1

:---:---:---:---:
: 1 : 2 : 3 : 4 :
:---:---:---:---:

 GO TO THE SPACE DIRECTLY UNDER BOX 1. THE FIGURE REPRESENTS
  EXODUS. BOX 1 IS THE WESTERMOST PART OF EXODUS. HAVE THE
  CHARACTER WITH THE CARDS TO THE FOLLOWING...
    1) INSERT (THIS IS AN OTHER COMMAND) NORTH
    2) WHEN IT ASKS "D,S,L,M",TYPE IN "L"
    3) MOVE TO EXODUS SPACE #2 AND INSERT CARD "S"
    4) MOVE TO EXODUS SPACE #3 AND INSERT CARD "M"
    5) MOVE TO EXODUS SPACE #4 AND INSERT CARD "D"

 AT THIS POINT EITHER EXODUS IS DESTROYED,IN WHICH CASE A PARAGRAPH
  STATING THIS WILL APPEAR ON THE SCREEN,OR,ONE OR MORE OF
  YOUR CHARACTERS IS DEAD. IF THE LATTER HAS HAPPENED,I CAN'T
  DO ANYTHING EXCEPT EXPRESS MY CONDOLENCES TO THEIR NEXT OF KIN.

=END=
