                               THE UNINVITED
                               (Mirrorsoft)


LEAVE  CAR  -  OPEN MAILBOX - OPEN LETTER - GET AMULET - READ LETTER - OPEN
DOOR  -  ENTER  HOUSE  -  ENTER THE LIBRARY EAST - GET MAGIC BOOK - WEST -
NORTH - UP - ENTER THE FIRST DOOR ON THE RIGHT - TAKE HERE THE SPIDER CIDER
AND  THE  BOTTLE:NO  GHOSTS - LEAVE THE ROOM - ENTER THE SECOND DOOR ON THE
RIGHT - GET AXE - LEAVE ROOM - ENTER THE SECOND DOOR ON THE LEFT - OPEN THE
NIGHTSTAND  -  OPEN  SCROLL  - (SPECAN HEAFOD ABRAXAS,INSTANTUM ILLUMINARIS
ABRAXAS)  -  LEAVE  ROOM  -  DOWN - OPEN NO GHOSTS - OPEN FIRST DOOR ON THE
RIGHT  -  OPERATE NO GHOSTS ON WOMAN -  ENTER FIRST ROOM ON THE RIGHT - N -
WAIT FOR THE SPIDER - IF SHE'S GONE:OPERATE SPIDER CIDER ON RAILING - S - N
-  GET SPIDER - S - S - ENTER SECOND DOOR ON THE LEFT - GET FLOWERS - ENTER
LEFT  DOOR  (KITCHEN) -  ENTER LEFT DOOR - OPERATE LAMP - OPERATE SPIDER ON
GHOST  -  GET  DIARY OUT SAFE - LEAVE ROOM - ENTER RIGHT ROOM - GET MATCHES
AND BIG KITCHEN KNIFE - LEAVE ROOM - S - E - ENTER SECOND DOOR ON THE RIGHT
- OPERATE KNIFE ON CHAIR - GET KEY - LEAVE ROOM.

N - ENTER FIRST DOOR ON THE LEFT -  OPERATE KEY ON CABINET - OPEN CABINET -
SPEAK TO DOLL:SPECAN HEAFOD ABRAXAS - CLOSE CABINET - OPERATE RECORD PLAYER
-  LEAVE  ROOM  - S - UP - ENTER FIRST DOOR LEFT - OPERATE KEY ON CABINET -
OPEN  CABINET  -  OPEN  SCROLLS  -  READ SCROLLS - GET WOODEN BOX - S - S -
ENTER  SECOND  DOOR  RIGHT - TURN FIRE ON AND DROP WOODEN BOX IN THE FIRE -
GET PENTAGRAM - LEAVE ROOM - ENTER SECOND DOOR LEFT - ENTER DOOR AT THE TOP
RIGHT - OPEN DESK - SPEAK SELF:GOLD,SILVER AND MERCURY,TOGETHER THEY FORM A
KEY  -  LEAVE  ROOM  -   S - S - ENTER FIRST DOOR LEFT - N - DROP KNIFE AND
SPIDER  CIDER  AND  NO  GHOSTS - GET CAGE - N - ENTER THE MOST RIGHT DOOR -
SPEAK  DOG:INSTANTUM  ILLUMINARIS  ABRAXAS  -  OPEN DOOR - N - LOOK CROSS -
SPEAK  TO  MARBLE  BUST:SPECAN HEAFOD ABRAXAS - DROP CAGE - LIGHT CANDLES -
GET CANDLES -  ENTER SECRET PASSAGE - DROP LANTERN.

S - GET CAGE - ENTER PASSAGE (CHURCH GROUNDS} - N - N - W - W - N - N - W -
W  - N - N - N - N - E - E - E - E - OPERATE TALISMAN ON ZOMBIE - E - E - S
- S - OPERATE FLOWERS ON GRAVE - W - OPEN CAGE - GET KEY AND OPERATE ON THE
THREE OTHER CAGES - OPERATE CAGE ON THE BIRD - GET CAGE - S - S - OPEN CAGE
- DROP CAGE - GET DIAMOND - N - N - E - N - N - W - W - W - W - W - W - S -
S - S - S - E - E - S - S - E - E - S - S - S - S - S - NOW ENTER THE GREEN
HOUSE  IN THE MIDDLE FROM THE SCREEN - GIVE PLANT WICH IS ON THE LEFT TABLE
IN  THE FRONT - SPRINKLE THE PLANT - (IF YOU HAVE THE WRONG ONE,YOU MUST GO
TO  THE  BATHROOM FOR WATER) - GET PLANT - GO TO THE BATHROOM - PLACE PLANT
IN  BATH  -  GIVE WATER TO THE PLANT CA.10 TIMES - NOW GO BACK TO THE GREEN
HOUSE  AND  PLACE  THE  PLANT  ON THE FLOOR - LEAVE ROOM AND WAIT UNTIL THE
PLANT IS GROWING UP - THE PLANT MUST HAVE FRUIT ON IT NOW - GET PLANT.

LEAVE  GREEN  HOUSE - NOW GO TO THE LEFT DOOR -  OPERATE THE DIAMOND IN THE
NICE  AT  THE  TOP  OF THE DOOR - ENTER DOOR - GIVE PLANT TO CREATURE - N -
OPEN  SAFE  -  79  47 80  - GET JAR - OPERATE AXE ON JAR - GET COOKIE - NOW
LEAVE  THE  LABO AND GO TO THE TROPHY ROOM - FROM TROPHY ROOM S - S - ENTER
SECOND  DOOR LEFT - DROP COOKIE -  EXAMINE BOTTLE - GET KEY - S - ENTER THE
DOOR  IN  THE  NORTH - GO BACK TO THE LABORATORY - OPEN THE TRAPDOOR LEFT -
ENTER W LEFT - OPERATE PENTAGON ON CAVE - N - PUSH THE MAN IN THE PIT - N -
UP  -  OPERATE  KEY ON DOOR - ENTER DOOR - ENTER LEFT PASSAGE - S - N - N -
ENTER  RIGHT  PASSAGE  -  N  -   GET CROSS - S - S - S - GO TO THE BATHROOM
UPSTAIRS - OPEN THE HOT AND THE COOL KNOB FROM THE BATH - EXAMINE THE LIGHT
UNTIL YOU CAN OPEN IT -  OPEN LIGHT - ENTER LIGHT - HIT BOY - OPERATE CROSS
ON DEMON - ENTER WINDOW....TURN YOUR PRINTER ON!!!
