*******  WELCOME, ADVENTURERS! *******

TO AN EASY TO USE TUTORIAL TO GET YOU
THROUGH INFOCOM'S SECOND GREAT MYSTERY
GAME....

        T H E   W I T N E S S !

(TUTORIAL (C) 1983 BY DOOBIE PRODS.)

"THE WITNESS" IS A PRETTY STRAIGHT-
FORWARD LITTLE MYSTERY. IT'S NOT AS
COMPLICATED OR INVOLVED AS DEADLINE,
YET ITS ATMOSPHERE AND DETAIL MORE
THAN COMPENSATES FOR ITS QUICK SOLV-
ABILITY.

ACTUALLY, "THE WITNESS" CAN BE SOLVED
BY NEVER HAVING TO LEAVE THE SITE OF
THE MURDER! HOWEVER, A LOT OF THE FUN
FUN AND INTERESTING NUANCES OF THIS
GAME CAN BE MISSED BY FOLLOWING THIS
QUICK-FINISH, SO BEFORE I REVEAL IT
STEP-BY-STEP, I'LL GIVE YOU A FEW
"THINGS TO TRY". THIS IS FOR ALL THOSE
TRUE ADVENTURERS WHO MIGHT JUST BE
LOOKING FOR A LITTLE NUDGE IN THE
RIGHT DIRECTION.

THE GAME IS SUPPOSED TO BE PRETTY
AUTOMATIC FOR THE FIRST PART, SO
UNLESS YOU'RE WANDERING ABOUT OUT-
SIDE THE HOUSE FOR MAPPING PURPOSES,
START THE GAME BY DOING THE FOLLOWING:

N,N, "RING THE BELL"

LINDER'S BUTLER, PHONG, WILL ANSWER
THE DOOR. YOU CAN NOW DO ANYTHING FOR
ONE MOVE, THEN PHONG WILL SHOW YOU INTO
THE LIVING ROOM, WHERE YOU WILL MEET
LINDER AND HIS DAUGHTER, MONICA.

IT MIGHT HELP HERE TO ASK MR. LINDER
AND MONICA ABOUT ALL THE OTHER CHAR-
ACTERS IN THE GAME (THIS IS A MUST
IN ALL INFOCOM MYSTERIES!). DO THIS
BY SAYING "ASK LINDER ABOUT (MONICA
OR MRS. LINDER OR PHONG, ETC.).

AFTER A BIT (10-12 MINUTES), LINDER
WILL TAKE YOU INTO HIS OFFICE. HERE
YOU SHOULD "SIT IN THE WOODEN CHAIR"
WHEN HE ASKS YOU TO. HE WILL THEN FILL
YOU IN ON THE BACKSTORY OF THE GAME
AND WILL SHOW YOU A NOTE, WHICH YOU
MIGHT BE POLITE ENOUGH TO READ.


NOW, IF YOU SIT THERE AND WAIT, MONICA
WILL ENTER AROUND 8:35 AND STICK
AROUND FOR A MOMENT TALKING TO HER
FATHER BEFORE HEADING OFF TO GO
TO THE MOVIES. IF YOU WAIT UNTIL
AROUND 9:03, LINDER WILL HEAR THE
DOORBELL; PUSH THE BUTLER'S BUTTON
TO SIGNAL PHONG; THEN DIE FROM A
BULLET SHOT THROUGH THE OFFICE WINDOW.

BEFORE LINDER IS KILLED, YOU MIGHT
WANT TO TRY THE FOLLOWING AND SEE
WHAT HAPPENS (OR DOESN'T...):

   1. TRY PUSHING THE BUTLER'S BUTTON
      AND SEE WHAT LINDER DOES.

   2. EXAMINE THE WINDOW AND ASK
      LINDER ABOUT WHAT YOU FIND THERE.

   3. EXAMINE THE CLOCK AND TRY OPEN-
      ING IT.

   4. TRY STANDING UP AFTER YOU'VE
      FIRST SAT DOWN IN THE CHAIR.
      THEN WAIT UNTIL 9:03 (I'D SAVE
      THE GAME FIRST!).


AFTER THE MURDER OCCURS, TRY THE
FOLLOWING:

   1. EXAMINE THE WINDOW AND ANALYZE
      WHAT YOU FIND THERE.

   2. EXAMINE THE KEYHOLE IN THE CLOCK.

   3. TRY PUSHING THE BUTLER'S BUTTON
      RIGHT AFTER THE MURDER. THEN TRY
      PUSHING IT AGAIN AFTER MONICA
      GETS HOME (AROUND 11:00).

   4. IF YOU "SEARCH PHONG", YOU WILL
      FIND THE KEYS YOU NEED TO UNLOCK
      ALL THE LOCKED DOORS IN THE HOUSE


   5. GO INTO PHONG'S ROOM AND EXAMINE
      THE BOOK HE'S READING. HE'S USING
      A VERY INTERESTING BOOKMARK. SHOW
      THIS TO PHONG AND MONICA AND THE
      TIED-UP STILES (HE'S IN THE
      LIVING ROOM.

   6. FOR FUN, TRY CALLING THE RESTAUR-
      ANT'S PHONE # THAT'S ON THE
      MATCHBOOK (ADELINE 1308).

   7. ANALYZE THE FOOTPRINTS YOU FIND
      IN THE MUD OUTSIDE THE OFFICE
      PORCH.. THEN COMPARE THE PLASTER
      CAST DUFFY MAKES TO STILES'
      SHOES AND ALSO TO THE MUDDY BOOTS
      YOU FIND ON THE PLATFORM BY THE
      FRONT DOOR. ALSO, SHOW THE MUDDY
      BOOTS TO PHONG.

   8. SHOW STILES THE: MATCHBOOK;
      THE NOTE LINDER GAVE YOU; AND
      THE MUDDY HANDGUN (YOU FIND
      THIS OUTSIDE BY THE OFFICE PATH.)

   9. BEFORE MONICA GETS HOME (11:00),
      UNLOCK AND OPEN THE WORKSHOP
      DOOR (IN THE GARAGE) THEN GO IN-
      SIDE THE WORKSHOP AND "WAIT FOR
      MONICA'. WATCH WHAT SHE DOES WHEN
      SHE DRIVES IN AND ENTERS.

  10. OF COURSE, ASK EVERYBODY ABOUT
      EVERYBODY ELSE; SHOW EVERYTHING
      OF INTEREST TO EVERYONE; AND
      TRY ACCUSING PHONG, MONICA AND
      STILES.

NOW, FOR THOSE OF YOU LOOKING FOR A
QUICK FINISH, HERE'S THE STEP-BY-STEP:

(BREAK OUT IF YOU DON'T WANT THE ANSWER)

SOLUTION:

N,N, "RING BELL", (DO ANYTHING FOR ONE
MOVE, SUCH AS 'I'), (PHONG WILL LEAD
YOU INTO THE LIVING ROOM), "ASK MONICA
ABOUT HER MOTHER", "WAIT", (LINDER WILL
SOON TAKE YOU TO HIS OFFICE), "SIT IN
THE WOODEN CHAIR', 'WAIT UNTIL 9:04'
(ANSWER YES WHENEVER IT ASKS IF YOU
WANT TO KEEP WAITING), (LINDER WILL
BE SHOT AND KILLED), "GET UP",
"HIDE BEHIND THE LOUNGE", "WAIT UNTIL
12:05" (ANSWER YES EVERYTIME IT ASKS),
(SOMEWHERE AROUND MIDNIGHT, MONICA
WILL COME BACK INTO THE OFFICE, GO OVER
TO THE CLOCK, UNLOCK IT AND REMOVE
SOMETHING), "STAND UP", "ACCUSE MONICA",
"WAIT FOR DUFFY", "ARREST MONICA".

THE PROGRAM WILL THEN OFFER YOU A
SYNOPSIS OF THE ACTUAL EVENTS.


THAT'S ALL FOLKS!!!!!!
