
Date:  02-17-89  11:56
From:  Jeff Bordeaux
To:    All
Subj:  Dragonheim

   SEEKING THE SIGN TO DRAGONHEIM
 -
   Mighty wings once carved the cumulus
    sowing storm filled clouds and reaping rain.
   Soaring, we bounded the radius
    of the peak crowned heights of our domain.
 -
       How long is the road to Dragonheim?
       The length of a dreamer's call.
       How number the miles to Dragonheim?
       It is none, I say, and all.
 -
   And the sky roared when touched by our flames
    it sang to words wrought in fume and smoke.
   Firey visions dwelt within the names
    of numberless tribes of dragon folk.
 -
       Where winds the path to Dragonheim?
       Hidden in a name; a secret sound.
       Where stands the entrance to Dragonheim?
       In the place never lost, though seldom found.
 -
   Majestic mountains once housed our young
    born from crystal eggs that caught the light.
   In strong shadowed heights our dwellings hung
    ne'er crossed by the foes who feared our might.
 -
       What shapes the trail to Dragonheim?
       A maze of dreams, pointing streight.
       How travels the way to Dragonheim?
       On paths of heart, devoid of hate.
 -
   Now the lands are gone, scourged by the ire
    of the modern day people's decree.
   But spirits live on, look to the fires.
    You must catch our souls to set us free.
 -
       In what age stands the halls of Dragonheim?
       Time beyond time, between the worlds.
       Where dwell the inhabitants of Dragonheim?
       They smile as your spirits soar and curl.
 -
 **   -  J.A. Bordeaux (Steorra Rokraven) ,  17 Feb 89
--- QuickBBS v2.03
 * Origin: InterVisioN "The ParaNormal Connection" 603-547-6485 HST
(1:132/123)

