

; STRINGS ARE DEFINED HERE

STRBEG::

	.GSTR STR?14,""
	.GSTR STR?25," has no effect."
	.GSTR STR?61,"Float"
	.GSTR STR?76,"yellow sphere"
	.GSTR STR?77,"grue"
	.GSTR STR?155,"An old wooden chest sits in the corner."
	.GSTR STR?173,"You have made it to the top. Well done. There are etchings on the well. A crack runs across the floor at the doorway to the east, but it can be crossed easily. Another doorway leads northeast."
	.GSTR STR?32,".
"
	.GSTR STR?218,"Lord Dimwit's crown is here."
	.GSTR STR?12,"Oh, no! You have walked into the slavering fangs of a lurking grue!"
	.GSTR STR?16,"    "
	.GSTR STR?106,"a dim cave, its floor piled with furs and old bones"
	.GSTR STR?107,"On the table sits a blue crystal sphere."
	.GSTR STR?122,"On the floor is a neat stack of 200 zorkmid bills."
	.GSTR STR?149,"Dragon hide is tough as steel, but you have annoyed him a bit. He looks as if deciding whether or not to eat you."
	.GSTR STR?195,"On the floor lies a moby ruby."
	.GSTR STR?206,"On the floor is a priceless gold zorkmid (a valuable collector's item)."
	.GSTR STR?222,"Now you've done it. It seems that the brick is an explosive and you have been blown to bits."
	.GSTR STR?43,"It doesn't fit the lock.
"
	.GSTR STR?59,"Fall"
	.GSTR STR?20," and devoured you!"
	.GSTR STR?44," the Great Underground Empire"
	.GSTR STR?150,"That captured his interest. He stares at you balefully."
	.GSTR STR?152,"That did no damage, but he turns his smoky yellow eyes in your direction."
	.GSTR STR?165,"The air is cool and damp. A path from the southeast splits here; north toward a stone bridge, and west into a narrow tunnel. It is from the latter that the chill originates."
	.GSTR STR?72,"pile of jewels"
	.GSTR STR?196,"The balloon floats majestically out of the volcano, revealing a breathtaking view of a forest clearing with a white house. High winds carry you into the snow-capped (and jagged) cliffs of the Flathead Mountains!"
	.GSTR STR?201,"descends."
	.GSTR STR?212,"The book details the use of the so-called ""magic wand"". Apparently, these work by pointing them at the object to be ensorcelled, and then chanting the appropriate magic word. (Amazing how credulous these ancients were.)"
	.GSTR STR?3,"begin"
	.GSTR STR?30,"What a concept!"
	.GSTR STR?52,"You plunge down the well."
	.GSTR STR?53,"You plunge down the volcano."
	.GSTR STR?94,"Filling the northern half of the room is a huge aquarium."
	.GSTR STR?115,"This is a huge limestone cavern, glowing with dim, phosphorescent light from far above. Narrow paths wind south and northeast."
	.GSTR STR?117,"This smooth-walled tunnel runs northeast to southwest. A faint whirring sound comes from the latter direction. Another opening, choked with leaves, leads southeast."
	.GSTR STR?121,"This is a small chamber carved from the western end of a short crawl. On the wall is crudely chiseled the number ""8""."
	.GSTR STR?125,"This was once a kennel for a large dog (some of the bones would fit a dinosaur). The only exit is northeast."
	.GSTR STR?128,"This is the entrance to a huge tomb. A passage leads north."
	.GSTR STR?140,"This is a gazebo in the midst of a formal garden. It is cool and restful here. A tea table adorns the center of the gazebo."
	.GSTR STR?143,"This is the southern end of a garden, where fantastically shaped hedges are arrayed with geometric precision. Though recently untended, the bushes have clearly been shaped: There is a dragon, a unicorn, a great serpent, a huge misshapen dog, and several human figures. To the west is a tunnel."
	.GSTR STR?168,"This is a tall, damp room with brick walls. There are some etchings on the walls. A passage leads west."
	.GSTR STR?176,"This robot was trained at GUE Tech to perform simple household functions. To activate, say:
        >ROBOT, <thing to do>
A product of the Frobozz Magic Robot Company."
	.GSTR STR?177,"This room is full of assorted machinery, whirring noisily. On one wall is a triangular button labelled, ""DANGER -- HIGH VOLTAGE."" There are exits to the south and southwest."
	.GSTR STR?179,"This is a former broom closet. A larger room lies to the north. Chiselled on the wall are the words ""Protected by the Frobozz Magic Alarm Company."""
	.GSTR STR?207,"This octagonal coin reads ""1000 Zorkmids"" and ""In Frobs We Trust""."
	.GSTR STR?208,"This must have been a large library, probably for the royal family. All of the shelves have been gnawed to pieces by unfriendly gnomes. To the north is an exit."
	.GSTR STR?210,"This book is written in an unfamiliar tongue."
	.GSTR STR?214,"This three zorkmid stamp portrays Lord Dimwit Flathead the Excessive."
	.GSTR STR?26,"A valiant attempt."
	.GSTR STR?33,"The demon is gone for a moment. "
	.GSTR STR?46," comes to a stop.

"
	.GSTR STR?85,"The demon crushes you with his enormous hand."
	.GSTR STR?146,"The dragon hisses and blocks your way."
	.GSTR STR?151,"The dragon is surprised and interested (for the moment)."
	.GSTR STR?192,"The depressed area is filled with water. There is something hazy at the deepest part of the pool."
	.GSTR STR?42,"The edge of a place mat is visible under the door."
	.GSTR STR?132,"Before you are the earthly remains of the mighty Flatheads, twelve somewhat flat heads mounted securely on poles. There is writing carved on the crypt. To the north and south are dark doorways."
	.GSTR STR?134,"""Here lie the Flatheads, whose heads were placed on poles by the Dungeon Master for amazing untastefulness."""
	.GSTR STR?147,"A huge red dragon is lying on the rocks, watching."
	.GSTR STR?148,"A huge red dragon is blocking the north exit. Smoke curls from his nostrils."
	.GSTR STR?160,"west"
	.GSTR STR?217,"The excessively gaudy crown of Lord Dimwit Flathead sits in the safe."
	.GSTR STR?7,"You should have looked before you leaped."
	.GSTR STR?38,"You see only darkness.
"
	.GSTR STR?71,"You sink quietly down again."
	.GSTR STR?95,"A shattered aquarium fills the northern half of the room."
	.GSTR STR?159,"east"
	.GSTR STR?162,"out"
	.GSTR STR?191,"The far half of this room is depressed. The only exit is west."
	.GSTR STR?50,"The guardian greedily devours "
	.GSTR STR?54,"You trip on something and fall over the edge of the bridge."
	.GSTR STR?74,"basilisk"
	.GSTR STR?129,"The huge dog snaps at you."
	.GSTR STR?136,"north"
	.GSTR STR?36,"Look around you.
"
	.GSTR STR?101,"almost monkish in its austerity"
	.GSTR STR?161,"in"
	.GSTR STR?185,"The icing spells, ""Eat Me."""
	.GSTR STR?9,"Pushing the "
	.GSTR STR?31,"What's tall as a house,
  round as a cup,
    and all the king's horses
      can't draw it up?""
"
	.GSTR STR?55,"and the resulting fall does you in."
	.GSTR STR?86,"A dejected and fearful Wizard watches from the corner."
	.GSTR STR?109,""""
	.GSTR STR?211,"Beside the purple book is a white one."
	.GSTR STR?83,"Inscribed on the floor is a great pentagram drawn with black chalk. In its center is a black circle."
	.GSTR STR?49,", almost as though an invisible hand had tipped it over.
"
	.GSTR STR?60,"Ferment"
	.GSTR STR?112,"The lamp appears a bit dimmer."
	.GSTR STR?113,"The lamp is definitely dimmer now."
	.GSTR STR?114,"The lamp is nearly out."
	.GSTR STR?47,"""Buzz, whirr, click!"
	.GSTR STR?65,"All at once you feel very tired."
	.GSTR STR?37,"It's too dark to see."
	.GSTR STR?45,"It's not clear what you're referring to.
"
	.GSTR STR?164,"It's a long way down."
	.GSTR STR?174,"It's a long way down!"
	.GSTR STR?183,"Only a mouse could fit."
	.GSTR STR?105,"a suburban bedroom out of the 1950's, complete with bunk beds"
	.GSTR STR?181,"The poison gas takes effect."
	.GSTR STR?88,"Very nice, but not enough!"
	.GSTR STR?93,"Here a dark hallway turns a corner. To the south is a dark room, to the east is fitful light."
	.GSTR STR?137,"south"
	.GSTR STR?142,"""Visit Exotic ZORK I! Consult the Frobozz Magic Travel Agency, or visit your local computer store for details."""
	.GSTR STR?199,"lifts off."
	.GSTR STR?6,"Kicking the "
	.GSTR STR?131,"A grinning, three-headed dog, wearing a huge collar, wags its tail here."
	.GSTR STR?154,"The rock walls are scarred by flame, and a blackened doorway leads south."
	.GSTR STR?188,"The room is now too small to hold you, and the walls are tougher than your body."
	.GSTR STR?209,"In one corner sits a blue book."
	.GSTR STR?221,"The room is cluttered with debris from an explosion. The walls seem ready to collapse."
	.GSTR STR?223,"The room trembles and 5000 tons of rock fall on you."
	.GSTR STR?24," isn't notably helpful."
	.GSTR STR?90,"Almost halfway there, oh worthy one!"
	.GSTR STR?21,"There is some water here."
	.GSTR STR?80,"The text is in an obscure tongue."
	.GSTR STR?82,"There is a strange black sphere here."
	.GSTR STR?84,"There is a demon floating in midair here."
	.GSTR STR?97,"There is a baby sea serpent swimming in the aquarium."
	.GSTR STR?108,"There is a clear crystal sphere lying in the sand."
	.GSTR STR?120,"There is a Stradivarius here."
	.GSTR STR?141,"There is a matchbook saying ""Visit ZORK I"" here."
	.GSTR STR?144,"The topiary animals attack! You are crushed by their branches and clawed by their thorns."
	.GSTR STR?171,"There is a wooden bucket here, 3 feet in diameter and 3 feet high."
	.GSTR STR?187,"Taste: yum. Effect: massive dehydration."
	.GSTR STR?193,"There is a package of candied insects here."
	.GSTR STR?202,"There is a blue label here."
	.GSTR STR?203,"""FROBOZZ MAGIC BALLOON COMPANY! Hello, Aviator!

To land your balloon, say LAND. Otherwise, you're on your own! (No warranty expressed or implied.)"""
	.GSTR STR?215,"There is a card with writing on it here."
	.GSTR STR?219,"There is a square brick here which feels like clay."
	.GSTR STR?220,"There is a coil of black, braided string here."
	.GSTR STR?104,"overhung with palm-trees and lianas. The only furniture is a hammock"
	.GSTR STR?133,"The Flatheads foresaw that someone might tamper with their remains, and took steps to punish such actions."
	.GSTR STR?135,"Strands of light vibrate toward you, as if searching for something. One by one your possessions glow bright green. Finally, you are attacked by these magical wardens, and destroyed!"
	.GSTR STR?205,"I wouldn't jump from here."
	.GSTR STR?35,"As you peer into the sphere, a strange vision takes shape"
	.GSTR STR?103,"decorated in the Louis XIV style"
	.GSTR STR?8,"Playing in this way with the "
	.GSTR STR?13,"Waving the "
	.GSTR STR?40,"The wand stops glowing, but there is no other apparent effect.
"
	.GSTR STR?58,"Freeze"
	.GSTR STR?145,"The walls of this large cavern are scorched and a sooty dry smell is very strong here. A stone bridge leads the south, and a smokey tunnel opens to the north. To the east is a small opening."
	.GSTR STR?169,"The walls cannot be climbed."
	.GSTR STR?1,"leave the game"
	.GSTR STR?118,"An Elvish sword of great antiquity is here."
	.GSTR STR?153,", but you barely feel the heat. The dragon is puzzled, but not too puzzled to crush you in his jaws."
	.GSTR STR?156,"Nestled in the chest is a gold statuette of a dragon."
	.GSTR STR?200,"lands."
	.GSTR STR?89,"Ah, truly magnificent! Keep them coming."
	.GSTR STR?123,"Each bill is worth 100 zorkmids and bears the legend ""In Frobs We Trust""."
	.GSTR STR?22,"Poof, you're dead!"
	.GSTR STR?57,"Fumble"
	.GSTR STR?127,"Bad idea. As you unfasten the collar, the monster rends you into little doggy biscuits."
	.GSTR STR?10,"Fiddling with the "
	.GSTR STR?75,"bulging chest"
	.GSTR STR?79,"copy of ZORK I"
	.GSTR STR?111,"A familiar brass lantern is lying on the ground."
	.GSTR STR?29,"An interesting idea..."
	.GSTR STR?81,"Halls lead west and south. The Wizard's workbench dominates the room. It is stained from years of use, and is deeply gouged as though some huge clawed animal was imprisoned on it. In the center of the bench, three stands - ruby, sapphire, and diamond - form a triangle."
	.GSTR STR?172,"If you insist."
	.GSTR STR?190,"A chasm blocks your way."
	.GSTR STR?96,"rends you limb from limb before he drowns in the air."
	.GSTR STR?216,"Warning: This room was constructed near weak rock strata. Detonation of explosives here is strictly prohibited!"
	.GSTR STR?63,"Fence"
	.GSTR STR?28,"Not bloody likely."
	.GSTR STR?66,"Your limbs suddenly feel like stone. You can't move a muscle."
	.GSTR STR?69,"Your little finger begins to twitch, and then your whole body is free again."
	.GSTR STR?70,"Your head is clearer now."
	.GSTR STR?78,"convention of wizards"
	.GSTR STR?91,"Your generosity overwhelms me!"
	.GSTR STR?130,"A vicious-looking dog guards the entrance to the south. It's your usual dog, except that it has three heads and is the size of an elephant."
	.GSTR STR?138,"A path of crushed white stone winds among bushes and flower beds of this garden from south to north. Almost hidden by the shrubbery is a small white gazebo."
	.GSTR STR?182,"An oblong table here is set for afternoon tea. It is clear that the users were indeed mad. To the east is a small hole (perhaps four inches high). A doorway leads west."
	.GSTR STR?197,"ascends."
	.GSTR STR?198,"floats, ascending due to its light load."
	.GSTR STR?56,"Feeble"
	.GSTR STR?15,"  "
	.GSTR STR?62,"Fireproof"
	.GSTR STR?73,"gold ingot"
	.GSTR STR?158,". ""Fry!"" he intones, and a bolt of lightning reduces you to a pile of ash. (Serves you right, too, if you ask me.)"
	.GSTR STR?17,"      "
	.GSTR STR?18,"        "
	.GSTR STR?19,"          "
	.GSTR STR?39,"It already is!
"
	.GSTR STR?98,"He takes you instead. ""Uurrp!"""
	.GSTR STR?110,"You are in an ancient barrow which opens to the southwest."
	.GSTR STR?116,"You are ankle deep in a stream. To the southwest is a dark tunnel, and to the north a dim cavern."
	.GSTR STR?119,"You are waist deep in a cold stream. On the northern bank, the walls rise to a small ledge. A ""whir"" comes from an opening to the south."
	.GSTR STR?124,"You are trying to walk through an enormous rock."
	.GSTR STR?163,"You are on a north-south bridge spanning a deep ravine. Water flows far beneath."
	.GSTR STR?170,"       o  b  o

       A  G  I

        E   L

       m  p  a"
	.GSTR STR?175,"       o  b  o
   r             z
f   M  A  G  I  C   z

c    W  E   L  L    y
   o             n
       m  p  a"
	.GSTR STR?178,"You are instantly electrocuted."
	.GSTR STR?180,"You are trapped in a solid steel cage."
	.GSTR STR?186,"You are blasted to smithereens (wherever they are)."
	.GSTR STR?194,"You are at the base of a dormant volcano. High above, light enters the cone of the volcano. The only exit is east."
	.GSTR STR?204,"You are about one hundred feet above the bottom of the volcano."
	.GSTR STR?4,"end"
	.GSTR STR?67,"You begin to feel lightheaded."
	.GSTR STR?87,"Most fine, master! But 'tis not enough. I will do a great service, and are not great services bought at great price?"
	.GSTR STR?92,"Wondrous fine, master! But one treasure is yet to be given!"
	.GSTR STR?102,"an opulently furnished seraglio out of an Arabian folktale"
	.GSTR STR?2,"restart"
	.GSTR STR?27,"You can't be serious."
	.GSTR STR?41,"You can't go that way.
"
	.GSTR STR?100,"You cut yourself severely on the broken glass."
	.GSTR STR?5," it at the time."
	.GSTR STR?48,"The Wizard waves his wand "
	.GSTR STR?51,"The Wizard of Frobozz is here, eyeing you warily."
	.GSTR STR?99,"You drop into the aquarium with a splash, which attracts the serpent. Being a hungry baby, he greedily eats you."
	.GSTR STR?166,"You don't even have an ice-pick."
	.GSTR STR?64,"Fantasize"
	.GSTR STR?126,"A gigantic dog collar lies amidst the dust."
	.GSTR STR?139,"A beautiful unicorn is munching grass here."
	.GSTR STR?157,"A beautiful princess sits on a rock in the corner. Her hair is unkempt and she appears to be in a trance."
	.GSTR STR?184,"A rare portrait of J. Pierpont Flathead hangs on the wall."
	.GSTR STR?23," doesn't seem to work."
	.GSTR STR?34,"You feel a rush of air as something moved nearby.
"
	.GSTR STR?68,"You feel more energetic now."
	.GSTR STR?213,"Lying in the dust, covered with mold, is a purple book."
	.GSTR STR?11,"."
	.GSTR STR?167,"A mass of ice fills the western half of the room."
	.GSTR STR?189,"In the center of this enormous room, four wooden posts support a huge oblong roof. To the east is a large hole; to the west a gaping chasm."

	.ENDI
