#! /bin/bash

if [ $# -eq 0 ]; then
  echo 'usage: install /dev/<disk_name>'
  exit 1
fi

lsblk | grep disk

echo 'Can you confirm the disk is correct?'
read response

if [ "$response" = "y" ]; then
  sudo dd if=./solarium.img of=/dev/"$1" status=progress 
  sleep 1
  echo "unmounting $2"
  sudo umount "/dev/$2"
fi


