25395


Msg#:25395 *COMMUNICATIONS*
01/06/87 18:03:03 (Read 71 Times)
From:  MONGEL
To: ALL
Subj: 800

Not much but here goes anyway.

1-800-222-4334 - Order entry service
517-224-6818 - Clinton National bank

To those of you who don't already know

XXX+101 - TOLL SWITCHING
XXX+121 - LOCAL OPERATOR
XXX+131 - INFORMATION
XXX+141 - RATE & ROUTE
XXX+160 - OVERSEA OPERATOR
XXX+181 - COIN REFUND OPERATOR
XXX+11501 - MOBILE PHONE OPERATOR
XXX+11521 - MOBILE PHONE OPERATOR
XXX+11511 - CONFERENCE OPERATOR
XXX+099121 - INWARD FOR STATES WHO CANNOT VERIFY

Does anyone have the alliance teleconferencing code for the B-box?

Heres a tip on getting a coference started without alliance (Remember you saw
this on P-80!)

1. Call up information for any city (We will say New Orleans) and ask for Mary
Smith (Any common name)
2. Call up Mary Smith and tell her you are with bell telephone company and you
are testing out your conference lines, and say as follows: Hi this is (Name)
from Bell (And/or AT&T) and we are testing out our conference lines and I will
have a operator call you shortly asking if you would accept a conference, now
in order to test out our lines we will need your participation, Please say yes 
when the operator calls and you will here a number of voices on the lines, upon
hearing the voices please set the receiver next to the phone, you will not be
billed for this and for participating you will be credited with two free long
distance calls.

(Now you of course call up the conference operator tell her you are Mary Smith
and give her Mary Smiths phone number and all of those you want in the
conference)

More Later,
Mongel

The System has Msg's 24600 to 25784 
Number to Read, <CR> to Quit: OR LOSE IT..