 ===================================================================
 ZORK I, BY INFOCOM
 ===================================================================
 
 "S","E","OPEN WINDOW","ENTER HOUSE","W","GET LAMP","MOVE RUG","OPEN TRAP
 DOOR",  "TURN ON THE LAMP","D","S","E","GET PAINTING",  "N",  "U",  "U",
 "GET KNIFE AND ROPE",  "D",  "W",  "OPEN CASE",  "PUT PAINTING IN CASE",
 "DROP KNIFE", "GET SWORD", "OPEN TRAP DOOR", "D".
 
 ...................................................................
   SAVE THE GAME NOW. IF YOU BUY THE FARM, WE GOT THIS FAR ANYWAY...
 ...................................................................
 
 "N",  "KILL TROLL WITH SWORD" UNTIL YOU KILL HIM,  DROP SWORD, "E", "E",
 "SE", "E",  "TIE ROPE TO RAILING",  "CLIMB DOWN ROPE",  "S",  "E",  "GET
 COFFIN",  "W",  "S",  "PRAY", "TURN OFF THE LAMP", "S", "N", "E", "D" TO
 THE CANYON BOTTOM,  "N",  "DROP COFFIN",  "OPEN COFFIN",  "GET SCEPTRE",
 "WAVE SCEPTRE",  "LOOK",  "GET GOLD AND COFFIN", "SW", "U" TO THE CANYON
 VIEW", "NW", "W", "ENTER HOUSE",  "OPEN BAG",  "GET GARLIC",  "W",  "PUT
 COFFIN, SCEPTRE, AND GOLD INTO CASE".
 
 ...................................................................
 SAVE THE GAME AGAIN. THIS IS CHECKPOINT 2. HOPE YOU GOT THIS FAR CORRECTLY.
 ...................................................................
 
 "OPEN TRAP DOOR",  "TURN ON LAMP",  "D",  "N", "E", "N", "NE", "E", "N",
 "GET MATCHES", "N", "GET WRENCH AND SCREWDRIVER",  "PUSH YELLOW BUTTON",
 "S",  "S",  "TURN THE BOLT WITH THE WRENCH",  "S",  "D", "W", "SE", "E",
 "CLIMB DOWN ROPE", "GET THE TORCH", "TURN OFF LAMP", "S", "GET THE BELL,
 BOOK,  AND CANDLES",  "GO HOLE",  "D",  "RING THE BELL",  "LIGHT MATCH",
 "LIGHT THE CANDLES WITH THE MATCH", "READ THE BOOK",  "DROP BOOK",  "S",
 "GET SKULL",  "N",  "U", "N", "PUT OUT CANDLES", "RUB MIRROR", "N", "W",
 "N", "W", "N", "E", "PUT TORCH IN BASKET", "TURN ON LAMP", "N", "D".
 
 ...................................................................
     SAVE THE GAME. THIS MAZE IS A PAIN, AND IF YOU LOSE YOUR WAY,
     MAY THE GOOD LORD HAVE  MERCY ON YOUR POOR SOUL.
     THIS IS CHECKPOINT 3. WELCOME!!
 ...................................................................
 
 "E",  "NE",  "SE",  "SW",  "D", "D" TO THE LADDER BOTTOM.  IF YOU AREN'T
 THERE, RESTORE THE GAME.  YOU MESSED UP.  IF YOU ARE,  "S",  "GET COAL",
 "N", "U" TO THE LADDER TOP, "U", "N", "E", "S", "N", "U", "S", "PUT COAL
 AOD SCREWDRIVER IN BASKET", "LOWER BASKET", "N", "D", "E",  "NE",  "SE",
 "SW",  "D",  "D",  "W",  "DROP ALL",  "GO C^!1K",  "GET COAL, TORCH, AND
 SCREWDRIVER", "S", "OPEN THE LID",  "PUT COAL INTO MACHINE",  "CLOSE THE
 LID",  "TURN  SWITCH WITH SCREWDRIVER",  "OPEN THE LID",  "GET DIAMOND",
 "DROP SCREWDRIVER",  "N",  "PUT TORCH AND DIAMOND IN THE  BASKET",  "E",
 "GET SKULL,  LAMP,  AND GARLIC",  "E", "N" TO THE LADDER BOTTOM, THROUGH
 THE COAL MINE (SEE ABOVE IF YOU FORGOT) TO THE GAS ROOM, "GET BRACELET",
 "U", "S", "RAISE BASKET", "GET TORCH AND DIAMOND", "TURN OFF LAMP", "W",
 "GET JADE",  "S",  "E",  "S",  "GO  SLIDE",  "U",  "PUT  DIAMOND,  JADE,
 BRACELET, AND TORCH IN CASE", "DROP GARLIC".
 
 ...................................................................
  SAVE THE GAME. WELCOME TO CHECKPOINT 4. HALFWAY DONE NOW!
 ...................................................................
 
 "TURN ON LAMP", "N", "E", "N", "NE",  "N",  "GET TRUNK",  "N",  "GET AIR
 PUMP",  "N",  "GET TRIDENT",  "S" TO RESERVOIR SOUTH, "E", "E", "INFLATE
 BOAT WITH PUMP", "GET IN BOAT", "SAY LAUNCH".
 
 ...................................................................
     SAVE THE GAME. YOU COULD MESS UP. WELCOME TO CHECKPOINT 5...
 ...................................................................
 
 "WAIT" UNTIL YOU SEE A BUOY.  "GET BUOY", "E" TO THE BEACH", "GET OUT OF
 BOAT", "GET SHOVEL", "NE".
 
 ...................................................................
    SAVE THE GAME. YOU MIGHT GET BURIED ALIVE. CHECKPOINT 6 HERE!!
 ...................................................................
 
 "DIG WITH SHOVEL" UNTIL THE SCARAB SHOWS UP.  IF YOU GET BURIED, RESTORE
 THE GAME.  IF YOU DIDN'T AND YOU FOUND THE SCARAB,  "DROP  THE  SHOVEL",
 "GET SCARAB",  "SW", "DROP BUOY", "OPEN BUOY", "GET EMERALD", "S" TO THE
 FALLS, "CROSS RAINBOW", "TURN OFF LAMP",  "SW" TO CANYON BOTTOM,  "U" TO
 CANYON VIEW",  FROM THERE, GO BACK TO THE HOUSE AND ENTER IT.  GO TO THE
 LIVING ROOM.  "PUT SCARAB, EMERALD,  CHEST,  AND TRIDENT IN CASE",  "E",
 "E",  "N",  "N",  "CLIMB UP TREE", "GET EGG", "CLIMB DOWN", "S", "E", GO
 BACK TO THE LIVING ROOM, "TURN ON LAMP", "D", "N".
 
 ...................................................................
   SAVE THE GAME. ANOTHER MAZE. THIS TIME, WE FIND THE THIEF'S LAIR!
   CHECKPOINT 7
 ...................................................................
 
 "W", "S", "U", "TAKE COINS AND KEY", "SW", "E", "S", "SE" TO THE CYCLOPS
 ROOM.  NOW,  THE CYCLOPS HATES PEOPLE,  BUT YOU CAN GET HIM OUT OF HERE.
 "ULYSSES", (OR "ODYSSEUS" IF YOU PREFER), "U", "GIVE EGG TO THIEF", "D",
 "E", "PUT COINS IN CASE", "GET KNIFE", "W".
 
 ...................................................................
    SAVE THE GAME!!! THE THIEF IS A KILLER!!! WELCOME TO CHECK POINT 8.
 ...................................................................
 
 "U","KILL THIEF WITH KNIFE" UNTIL YOU ACTUALLY KILL HIM, "GET ALL", "D",
 "NW", "S", "W", "U", "D", "NE", "UNLOCK GRATE", "OPEN GRATE", "U",  "S",
 "CLIMB TREE",  "WIND UP CANARY",  "CLIMB DOWN",  "GET BAUBLE", GO TO THE
 LIVING ROOM AGAIN, "REMOVE CANARY FROM EGG", "PUT EGG,  CANARY,  BAUBLE,
 STILETTO IN CASE", "D", "N", "E" UNTIL YOU GET TO THE LOUD ROOM, "ECHO",
 "GET BAR", "W" TO THE TROLL ROOM,  "S",  "U",  "PUT ALL EXCEPT LAMP INTO
 CASE", YOU SHOULD THEN GET A MESSAGE.  FOLLOW THE ADVICE OF THE MESSAGE,
 AND YOU WILL GET A MAP.  "GET MAP",  GO TO THE MAILBOX,  AND FROM THERE,
 YOU SHOULD HAVE NO TROUBLE GETTING TO THE BARROW
 
 ......................................................................
 YOU'VE SOLVED THE FIRST OF THE FOUR ZORKS. IF YOU THOUGHT THIS WAS TOUGH,
 WAIT TILL YOU MEET THE WIZARD! AND THEN YOU GET TO MEET THE TOUGHEST OF
 THEM ALL...THE DUNGEON MASTER!
 ...................................................................
  MASTER!
 ...................................................................
 
 -=-=-=-=-=-=-=-=-=-=-=-
 
 /-[^]-:/:-[^]-:/:-[^]-:\:-[^]-:\:-[^]-\
 <=---=====---=====---=====---=====---=>
 <<^<<                             >>^>>
 <<^>                               <^>>
 <<^>     THE COMPLETE SOLUTION     <^>>
 <<^<<                             >>^>>
 <=---=====---=====---=====---=====---=>
 \-[^]-:\:-[^]-:\:-[^]-:/:-[^]-:/:-[^]-/
 
 -> NOTE: THE WIZARD MAY APPEAR ONCE AND
    A WHILE AND CAST A SPELL ON YOU,
    DON'T WORRY. THE SPELL WILL WEAR OFF
    AFTER A WHILE. IF YOU CAN'T DO
    ANYTHING ELSE, JUST WAIT IT OUT.
    IT WOULD BE WISE TO SAVE THE GAME
    PERIODICALLY, AS A PRECAUTION IN
    IN CASE YOU MAKE A MISTAKE.
 
 "TAKE ALL", [S,S,S,SW,S], "LIGHT LAMP",
 [SE], "ENTER GAZEBO", "TAKE TEAPOT",
 "EXIT", [N,NE], "FILL TEAPOT", [S,SE],
 [S,S,W]
 
 -> YOU ARE NOW IN THE CAROUSEL ROOM.
    BECAUSE OF ITS RAPID SPINNING, YOU
    ARE DISORIENTED IN DIRECTION. YOU
    ARE TRYING TO GET TO THE RIDDLE ROOM
    WHICH LIES TO THE SE, BUT YOU MIGHT
    END UP SOMEWHERE ELSE. JUST MAKE
    YOUR WAY BACK TO THE CAROUSEL ROOM
    AND KEEP TRYING UNTIL YOU GET THERE.
    WHEN YOU GET TO THE RIDDLE ROOM, YOU
    WILL NEED TO SOLVE THE RIDDLE BEFORE
    YOU CAN GET TO THE PEARL ROOM. JUST
    SAY "A WELL", WHICH IS THE ANSWER
    TO THE RIDDLE.
 
 [EAST], "TAKE PEARLS", [EAST], "GET
 INTO BUCKET", "POUR WATER", "GET OUT",
 [EAST], "TAKE RED, BLUE, AND GREEN
 CAKES", "EAT GREEN CAKE", [EAST],
 "THROW RED CAKE INTO POOL", "TAKE
 CANDY", [WEST], "EAT BLUE CAKE", [NW]
 
 -> INSTRUCTIONS ON OPERATING THE ROBOT
    CAN BE FOUND IN THE SAME ROOM AS THE
    ROBOT IS. DO THE FOLLOWING:
 
       TELL ROBOT "GO EAST"
       THEN GO [EAST] YOURSELF
       TELL ROBOT "PUSH TRIANGLE"
       TELL ROBOT "GO SOUTH"
       THEN GO [SOUTH] AND "TAKE SPHERE"
       TELL ROBOT "LIFT CAGE"
       THEN "TAKE SPHERE" AND GO [N,W]
 
 -> IN THE LOW ROOM, YOUR COMPASS WILL
    BE QUITE UNRELIABLE, SO JUST DO WHAT
    YOU DID IN THE CAROUSEL ROOM, EXCEPT
    THIS TIME YOU'RE TRYING TO GET SE
    TO THE TEA ROOM.
 
 [WEST], "GET INTO BUCKET", "FILL
 TEAPOT", "GET OUT", "DROP TEAPOT", [W],
 [W,NW], "OPEN BOX", "TAKE VIOLIN", [E],
 [N,N], "ENTER GAZEBO", "DROP ALL BUT
 LAMP AND SWORD", "TAKE MAT AND OPENER",
 "EXIT", [S,S,W,N], "TAKE BRICK", [N,N],
 [UP], "PUT MAT UNDER DOOR", "OPEN LID",
 "PUT OPENER IN HOLE", "TAKE MAT", "TAKE
 KEY", "TAKE OPENER", "UNLOCK DOOR WITH
 KEY", "OPEN DOOR", [NORTH], "TAKE
 SPHERE", [S,DOWN,S,S,S,E,N,N], "ENTER
 GAZEBO", "DROP ALL BUT LAMP, SWORD, AND
 BRICK", "TAKE NEWSPAPER AND MATCHES",
 "EXIT", [S,S,W,SW], "TAKE STRING", [N],
 [DOWN,E,N,N], "ATTACK DRAGON", [SOUTH],
 "ATTACK DRAGON", [SOUTH], "ATTACK
 DRAGON", [W,W], "TAKE RUBY", [SOUTH],
 "GET INTO BASKET", "OPEN RECEPTICLE",
 "PUT PAPER IN RECEPTICAL", "LIGHT
 MATCH", "LIGHT PAPER WITH MATCH",
 "WAIT", "WAIT", [WEST], "TIE WIRE TO
 HOOK", "GET OUT", "TAKE COIN", [SOUTH],
 "OPEN PURPLE BOOK", "TAKE STAMP", [N],
 "GET INTO BASKET", "UNTIE WIRE",
 "WAIT", "WAIT", "WAIT", "WAIT", [WEST],
 "TIE WIRE TO HOOK", "GET OUT", [SOUTH],
 "PUT STRING ON BRICK", "PUT BRICK IN
 HOLE", "LIGHT MATCH", "LIGHT STRING
 WITH MATCH", [N,S], "TAKE CROWN", [N],
 "GET INTO BASKET", "UNTIE WIRE", "CLOSE
 RECEPTICAL", "WAIT"
 
 -> KEEP WAITING UNTIL THE BASKET
    REACHES THE VOLCANO BOTTOM.
 
 "GET OUT", [N,E,E,SE,E,N,N], "ENTER
 GAZEBO", "DROP ALL BUT LAMP", "EXIT",
 [S,W,SW,N,N,N,W,N,N], "TAKE CHEST",
 "KISS PRINCESS", [S,S,S,SE,E,N,N],
 "ENTER GAZEBO", "WAIT"
 
 -> KEEP WAITING UNTIL THE PRINCESS
    GIVES YOU THE GOLD KEY FROM THE
    UNICORN.
 
 "OPEN CHEST", "AGAIN", "TAKE DRAGON",
 "DROP CHEST AND ROSE", "TAKE CANDY, RED
 SPHERE, BLUE SPHERE, AND PEARLS",
 "EXIT", [S,S,W,S,S,DOWN,S], "TAKE
 CLUB", [SE,NE,NW,SW,S,UP,N,N,SW,SW],
 "FEED LIZARD CANDY", "UNLOCK DOOR WITH
 GOLD KEY", "OPEN DOOR", [S,W], "DROP
 ALL BUT LAMP", [E,N,N,NE,N,N,N,W,N,W],
 [W,NE,E,S], "TAKE PORTRAIT", [NORTH],
 "ENTER LIGHT", "ENTER SOUTH WALL",
 "ENTER LIGHT", "TAKE BILLS", "KILL",
 [W,W,W], "TAKE LAMP", [S,S,S,SW,S,SE],
 "ENTER GAZEBO", "TAKE VIOLIN, RUBY,
 COIN, STAMP, AND CROWN", "EXIT", [S,S],
 [W,SW,SW,S,W], "DROP ALL BUT LAMP",
 "TAKE CLUB", [WEST], "THROW CLUB AT
 GLASS", "TAKE WHITE SPHERE", [EAST],
 "PUT WHITE SPHERE ON DIAMOND STAND",
 "PUT RED SPHERE ON RUBY STAND", "PUT
 BLUE SPHERE ON SAPPHIRE STAND", "TAKE
 BLACK SPHERE", [SOUTH], "PUT SPHERE IN
 CIRCLE", [NORTH], "TAKE RUBY, COIN,
 STAMP, AND VIOLIN", [SOUTH], "GIVE ALL
 BUT LAMP TO DEMON", [NORTH], "TAKE
 ALL", [SOUTH], "GIVE ALL BUT LAMP TO
 DEMON"
 
 -> NOW, TELL DEMON "GIVE ME WAND".
    GUESS WHAT?
 
 "TAKE WAND", [N,E,N,N,NE,S], "POINT
 WAND AT MENHIR"
 
 -> NOW, SAY "FLOAT". FEELS GREAT,
    DOESN'T IT?
 
 [SOUTHWEST], "TAKE COLLAR", [NE,S,D,D],
 "PUT COLLAR ON DOG", [E], "OPEN DOOR",
 [SOUTH], "TURN OFF LAMP", "OPEN SECRET
 DOOR", [SOUTH]
 
 -> CONGRATULATIONS!! YOU HAVE SOLVED
 
 -=-=-=-=-=-=-=-=-=-=-=-
 
 ==========================================================================
 ==========================================================================
 WELL,  YOU'VE COME A LONG WAY SINCE  YOU  FIRST  STOOD  BY  THE  MAILBOX
 OUTSIDE  THE HOUSE IN THE FOREST.  YOU'VE DEFEATED THE THIEF,  OUTWITTED
 THE WIZARD OF FROBOZZ,  AND NOW,  YOU STAND AT THE FOOT OF  THE  ENDLESS
 STAIRS,  READY TO EMBARK ON THE FINAL PART OF YOUR JOURNEY.  SO, PICK UP
 THE LAMP,  TURN IT ON,  AND HEAD ALONG DUE S UNTIL YOU COME TO THE SHORE
 OF  THE LAKE.  DROP THE LAMP <SAY GOODBYE TO IT;  YOU WON'T BE SEEING IT
 AGAIN>, AND JUMP INTO THE LAKE.  BRRRR!  PRETTY COLD!  SO, DON'T STAY IN
 THERE      LONG;      SWIM      W      AND     THEN    GO   S .
 
 GET  THE TORCH,  AND WAIT FOR THE NUMBER TO CHANGE TO "II." THEN,  TOUCH
 MATTER OF FACT.  HOWEVER,  YOU DON'T HAVE MUCH TIME TO SIGHT-SEE, SO GET
 THE CAN OF GRUE REPELLANT, THEN TRY MOVING E, AND YOU WILL FIND YOURSELF
 BACK IN SCENIC VISTA AGAIN.  NOW WAIT FOR THE NUMBER TO CHANGE TO "III,"
 THEN TOUCH THE TABLE AGAIN.  THIS TIME,  YOU'RE IN A DAMP PASSAGE.  DROP
 THE TORCH, AND JUST WAIT THERE UNTIL YOU'RE PULLED BACK TO SCENIC VISTA.
 OKAY, YOU'RE FINISHED HERE, SO MOVE ALONG N TO THE SHORE, AND AGAIN JUMP
 IN  THE LAKE.
 
 SPLASH!  IT HASN'T GOTTEN ANY WARMER;  IN FACT, YOU JUST DROPPED THE CAN
 OF REPELLANT. SO, GO DOWN, AND YOU WILL BE ON THE LAKE BOTTOM. AH, THERE
 IT IS! BUT, COULD THERE BE SOMETHING ELSE THERE, TOO? "GET ALL," AND YOU
 WILL HAVE NOT ONLY THE REPELLANT BUT ALSO AN  AMULET.  THIS  IS  ONE  OF
 THOSE "WONDERFUL" VARIABLE THINGS; IT MAY TAKE MORE THAN ONE TRY ON YOUR
 PART TO GET BOTH ITEMS.  IN THE MEANTIME,  YOU CAN'T  STAY  IN  THE  ICY
 WATERS TOO LONG, AND SOONER OR LATER A HUNGRY FISH WILL COME LOOKING FOR
 YOU.  THEREFORE,  IT'S BEST TO SAVE THE GAME BEFORE YOU JUMP IN FROM THE
 WERN  SHORE.  SO IF YOU DIE IN THE WATER,  OR GET EATEN BY THE FISH,  OR
 PICKED UP BY THE ROC <WHILE YOU'RE SWIMMING ON THE SURFACE>,  YOU  DON'T
 HAVE TO START ALL THE WAY BACK AT THE BEGINNING. BY THE WAY, THIS IS THE
 ONLY ONE OF THE ZORKS WHERE YOU DON'T LOSE POINTS IF YOU DIE.  BUT,  ALL
 THE  ITEMS  YOU'VE  COLLECTED SO FAR GET SCATTERED ALL AROUND,  AND IT'S
 TIME-CONSUMING TO GO LOOK FOR THEM.
 
 OKAY,  NOW YOU HAVE THE CAN AND THE AMULET,  SO HEAD UP TO THE  SURFACE,
 THEN S TO THE SERN SHORE. YOU CAN SEE A CAVE TO THE S, AND IT LOOKS KIND
 OF DARK.  IN FACT,  IT *IS* DARK IN THERE,  WHICH IS WHY  YOU  HAVE  THE
 REPELLANT.  SO,  SPRAY THE SMELLY STUFF ON YOURSELF,  AND GO S,  AND YOU
 WILL FIND YOURSELF IN A DARK PLACE.  GO S AGAIN, THEN E, AND YOU WILL BE
 IN  THE  KEY ROOM.  WHEW!  AT LE THERE'S"SOME LIGHT IN HERE!  AND BY THE
 LIGHT YOU CAN SEE A STRANGE KEY. lGED THE KEY,  THEN  MOVE  THE  MANHOLE
 COVER AND GO DOWN.  HERE YOU ARE ON AN AQUEDUCT. SINCE YOU CAN'T GO BACK
 <THE GRUE REPELLANT WOULDN'T HAVE LASTED THAT LONG>,  YOU MIGHT AS  WELL
 GO FORWARD. SO, JUST HEAD ALONG N AND YOU WILL COME TO THE WATER SLIDE.
 
 GO  N  DOWN  THE  SLIDE,  AND GUESS WHERE YOU ARE?  IN THE DAMP PASSAGE!
 THERE'S THE TORCH, SO PICK IT UP, BECAUSE YOU'RE CERTAINLY GOING TO NEED
 A  LIGHT  SOURCE...ESPECIALLY WHEN YOU THINK OF WHERE YOU'RE GOING NEXT.
 SO,  FROM THE DAMP PASSAGE HIKE ALONG W TO THE JUNCTION <YOU  CAN'T  GET
 THE SWORD OUT OF THE ROCK, SO DON'T EVEN TRY>, THEN S INTO CREEPY CRAWL,
 AND SW INTO THE SHADOW LAND. HERE WE COME TO ANOTHER VARIABLE PORTION OF
 THE  GAME.  YOU  WILL  HAVE  TO WANDER AROUND IN THE SHADOW LAND UNTIL A
 CLOAKED AND HOODED FIGURE APPEARS.  WHEN THAT HAPPENS,  THE  SWORD  WILL
 SUDDENLY  MATERIALIZE  IN  YOUR  HAND,  AND  YOU  WILL BE ABLE TO FIGHT.
 HOWEVER, SINCE THERE'S NO WAY OF TELLING WHEN THAT WILL HAPPEN, YOU JUST
 HAVE      TO      KEEP      MOVING      AROUND       UNTIL    IT   DOES.
 
 AT LE YOU WILL GET A CHANCE  TO  PRACTICE  SOME  ELEMENTARY  MAP-MAKING!
 ALSO,  THIS  IS  THE  MOST DANGEROUS PART OF THE GAME,  AS THE FIGURE IS
 QUITE CAPABLE OF KILLING YOU,  TOO!  SO,  BEST TO SAVE BEFORE YOU  ENTER
 SHADOW LAND. WHEN THE MYSTERIOUS FIGURE FINALLY APPEARS, ATTACK HIM WITH
 YOUR SWORD UNTIL HE IS BADLY WOUNDED AND CANNOT DEFEND HIMSELF.  AT THAT
 POINT,  GET HIS HOOD.  THE FIGURE WILL THEN DISAPPEAR, LEAVING THE CLOAK
 BEHIND.  GET THAT ALSO.  NOW,  YOU HAVE TO GET OUT OF HERE,  AND I CAN'T
 TELL YOU EXACTLY HOW,  SINCE THERE'S NO WAY OF KNOWING EXACTLY WHERE YOU
 WERE WHEN THE FIGHT STARTED.  HOWEVER,  IF YOU GO EWARDS,  YOU WILL EXIT
 THE  SHADOW  LAND  AT  EITHER  THE CREEPY CRAWL OR THE FOGGY ROOM.  FROM
 EITHER PLACE,  GO N  TO  THE  JUNCTION.  FROM  THE  JUNCTION,    IT'S  W
 THROUGH   THE   BARREN   AREA,   AND   W  AGAIN .
 
 
 YOU JUST CAN'T WAIT TO CLIMB DOWN THE ROPE, HUH? WELL, PICK UP THE BREAD
 FIRST, THEN GO DOWN TO THE LEDGE. WELL, WELL, A CHEST! TOO BAD YOU DON'T
 HAVE  A  KEY TO OPEN IT.  IN FACT,  THERE'S NO WAY FOR YOU TO OPEN IT AT
 ALL. BUT DON'T DESPAIR, THERE'S A WAY OF DOING IT.  JUST WAIT AROUND AND
 SOMEONE  WILL COME ALONG THE TOP OF THE CLIFF.  YOU MAY NOT REALLY TRUST
 HIM,  BUT TIE THE ROPE TO THE CHEST WHEN HE ASKS,  AND WAIT AROUND  SOME
 MORE. EVENTUALLY, HE WILL RETURN AND HELP YOU BACK UP THE CLIFF. HE WILL
 ALSO GIVE YOU A STAFF, WHICH IS WHAT YOU'RE REALLY AFTER HERE.  TAKE THE
 STAFF,  THEN  GO  BACK DOWN TO THE LEDGE,  AND FROM THERE,  TO THE CLIFF
 BASE.
 
 TREK S TO THE FLATHEAD OCEAN,  AND DO A LITTLE MORE WAITING.  SOONER  OR
 LATER A SHIP WIL OKAY, NOW W, W, W, N, N, N, E, E, AND PUSH THE S WALL TWO TIMES.
 
 08.  FROM  THERE,  W,  S,  S,  E,  E,  N  AND PUSH THE W WALL TWO TIMES.
 
 09 . NOW, S, W,  AND PUSH THE N WALL UNTIL IT WON'T MOVE ANY MORE.
 
 10.  THEN W AND N. FINALLY! YOU HAVE MANEUVERED THE LADDER UNDER THE HOLE
 
 <WHICH WAS THE PURPOSE OF ALL THIS PUSHING AND RUNNING AROUND>,  AND NOW
 YOU CAN JUST GO UP AND OUT! WHEW!
 
 OKAY,  YOU'VE SOLVED THE ROYAL PUZZLE AND YOU HAVE THE BOOK,  SO GO N TO
 THE MUSEUM ENTRANCE,  THEN OPEN THE E DOOR AND GET YOUR OTHER STUFF FROM
 THE JEWEL ROOM.  THEN IT'S BACK W TO THE GREAT DOOR, AND FROM THERE BACK
 TO THE JUNCTION.  NOW, E INTO THE DAMP PASSAGE, AND NE TO THE ENGRAVINGS
 ROAM.  WELL,  WE  HAVE  HERE  YET  ANOTHER <!> OF THOSE VARIABLE EVENTS:
 SOONER OR LATER, AN OLD MAN WILL BE SLEEPING HERE. IF HE ISN'T THERE THE
 FIRST TIME YOU ARRIVE, WALK AROUND A LITTLE AND RETURN. WHEN YOU FINALLY
 DO SEE HIM, WAKE HIM UP AND GIVE HIM THE BREAD.  HE WILL EAT IT AND THEN
 MAKE VISIBLE TO YOU A SECRET DOOR.  HE WILL THEN VANISH.
 
 OKAY,  YOU'RE GETTING CLOSER TO THE END!  OPEN THE DOOR, AND GO INTO THE
 BUTTON ROOM, THEN N TO THE BEAM ROOM. PUT THE SWORD IN THE BEAM, THEN GO
 BACK  TO  THE BUTTON ROOM AND PUSH THE BUTTON.  NOW,  BACK N TO THE BEAM
 ROOM AND N AGAIN INTO THE MIRROR ROOM.  THERE WILL BE AN OPENING IN  THE
 MIRROR,  SO GO N ONE MORE TIME,  AND YOU WILL BE INSIDE.  NOW, DON'T LET
 THE LONG AND COMPLICATED DESCRIPTIONS SCARE YOU!  IT'S NOT REALLY AS BAD
 AS YOU THINK <IT'S WORSE!  HEHEHEHEH..JUST KIDDING!>.  FIRST,  RAISE THE
 SHORT POLE. THEN, PUSH THE WHITE PANEL TWICE.  NOW, PUSH THE PINE PANEL,
 AND GO N.
 
 OKAY,  SO  HERE YOU ARE,  STANDING A LITTLE TOO CLOSE FOR COMFORT TO THE
 GUARDIANS OF ZORK.  IF I WERE YOU,  I WOULDN'T TRY GOING PAST THEM QUITE
 YET!  OPEN THE VIAL, THEN DRINK THE LIQUID.  WHILE NOTHING SEEMS TO HAVE
 HAPPENED,  YOU HAVE IN FACT BECOME INVISIBLE.  NOW YOU CAN WALK N  UNTIL
 YOU COME TO THE LOCKED DOOR.  KNOCK ON THE DOOR,  AND THE DUNGEON MASTER
 WILL OPEN IT AND LET YOU IN.  ALL RIGHT, HANG IN THERE, YOU HAVE REACHED
 THE END GAME!  GO N, THEN W, THEN N AGAIN. THE DM WILL BE FOLLOWING YOU.
 GO N TO THE PARAPET, SET THE DIAL TO 4, AND PUSH THE BUTTON.  NOW, GO S,
 OPEN THE CELL DOOR, AND STEP INSIDE.  THE DM WILL NOT FOLLOW YOU IN.
 
 ONCE INSIDE, YOU WILL NOTICE A BRONZE DOOR IN ONE OF THE WALLS. HOWEVER,
 YOU CAN'T OPEN IT YET!  SOMETHING ELSE HAS TO BE DONE,  AND IT WILL HAVE
 TO BE DONE BY SOMEONE ELSE.  SO, FIRST TELL THE DM TO GO TO THE PARAPET.
 THEN TELL HIM TO TURN THE DIAL TO 1,  AND THEN  TELL  HIM  TO  PUSH  THE
 BUTTON. ALL RIGHT!! THE MAGIC MOMENT HAS ARRIVED! UNLOCK THE BRONZE DOOR
 FINISHED!  YOU HAVE SURVIVED ALL THE PERILS,  PITFALLS, AND PUZZLES, AND
 NOW, *YOU* ARE THE NEW DUNGEON MASTER.
