Solution for:  Zork II, submitted by The Doctor (R1DEC@AKRONVM)
------------------------------------------------------------------------
 
 /-[^]-:/:-[^]-:/:-[^]-:\:-[^]-:\:-[^]-\
 <=---=====---=====---=====---=====---=>
 <<^<<                             >>^>>
 <<^>            ZORK II            <^>>
 <<^>                               <^>>
 <<^>     THE COMPLETE SOLUTION     <^>>
 <<^<<                             >>^>>
 <=---=====---=====---=====---=====---=>
 \-[^]-:\:-[^]-:\:-[^]-:/:-[^]-:/:-[^]-/
 
 -> NOTE: THE WIZARD MAY APPEAR ONCE AND
    A WHILE AND CAST A SPELL ON YOU,
    DON'T WORRY. THE SPELL WILL WEAR OFF
    AFTER A WHILE. IF YOU CAN'T DO
    ANYTHING ELSE, JUST WAIT IT OUT.
    IT WOULD BE WISE TO SAVE THE GAME
    PERIODICALLY, AS A PRECAUTION IN
    IN CASE YOU MAKE A MISTAKE.
 
 "TAKE ALL", [S,S,S,SW,S], "LIGHT LAMP",
 [SE], "ENTER GAZEBO", "TAKE TEAPOT",
 "EXIT", [N,NE], "FILL TEAPOT", [S,SE],
 [S,S,W]
 
 -> YOU ARE NOW IN THE CAROUSEL ROOM.
    BECAUSE OF ITS RAPID SPINNING, YOU
    ARE DISORIENTED IN DIRECTION. YOU
    ARE TRYING TO GET TO THE RIDDLE ROOM
    WHICH LIES TO THE SE, BUT YOU MIGHT
    END UP SOMEWHERE ELSE. JUST MAKE
    YOUR WAY BACK TO THE CAROUSEL ROOM
    AND KEEP TRYING UNTIL YOU GET THERE.
    WHEN YOU GET TO THE RIDDLE ROOM, YOU
    WILL NEED TO SOLVE THE RIDDLE BEFORE
    YOU CAN GET TO THE PEARL ROOM. JUST
    SAY "A WELL", WHICH IS THE ANSWER
    TO THE RIDDLE.
 
 [EAST], "TAKE PEARLS", [EAST], "GET
 INTO BUCKET", "POUR WATER", "GET OUT",
 [EAST], "TAKE RED, BLUE, AND GREEN
 CAKES", "EAT GREEN CAKE", [EAST],
 "THROW RED CAKE INTO POOL", "TAKE
 CANDY", [WEST], "EAT BLUE CAKE", [NW]
 
 -> INSTRUCTIONS ON OPERATING THE ROBOT
    CAN BE FOUND IN THE SAME ROOM AS THE
    ROBOT IS. DO THE FOLLOWING:
 
       TELL ROBOT "GO EAST"
       THEN GO [EAST] YOURSELF
       TELL ROBOT "PUSH TRIANGLE"
       TELL ROBOT "GO SOUTH"
       THEN GO [SOUTH] AND "TAKE SPHERE"
       TELL ROBOT "LIFT CAGE"
       THEN "TAKE SPHERE" AND GO [N,W]
 
 -> IN THE LOW ROOM, YOUR COMPASS WILL
    BE QUITE UNRELIABLE, SO JUST DO WHAT
    YOU DID IN THE CAROUSEL ROOM, EXCEPT
    THIS TIME YOU'RE TRYING TO GET SE
    TO THE TEA ROOM.
 
 [WEST], "GET INTO BUCKET", "FILL
 TEAPOT", "GET OUT", "DROP TEAPOT", [W],
 [W,NW], "OPEN BOX", "TAKE VIOLIN", [E],
 [N,N], "ENTER GAZEBO", "DROP ALL BUT
 LAMP AND SWORD", "TAKE MAT AND OPENER",
 "EXIT", [S,S,W,N], "TAKE BRICK", [N,N],
 [UP], "PUT MAT UNDER DOOR", "OPEN LID",
 "PUT OPENER IN HOLE", "TAKE MAT", "TAKE
 KEY", "TAKE OPENER", "UNLOCK DOOR WITH
 KEY", "OPEN DOOR", [NORTH], "TAKE
 SPHERE", [S,DOWN,S,S,S,E,N,N], "ENTER
 GAZEBO", "DROP ALL BUT LAMP, SWORD, AND
 BRICK", "TAKE NEWSPAPER AND MATCHES",
 "EXIT", [S,S,W,SW], "TAKE STRING", [N],
 [DOWN,E,N,N], "ATTACK DRAGON", [SOUTH],
 "ATTACK DRAGON", [SOUTH], "ATTACK
 DRAGON", [W,W], "TAKE RUBY", [SOUTH],
 "GET INTO BASKET", "OPEN RECEPTICLE",
 "PUT PAPER IN RECEPTICAL", "LIGHT
 MATCH", "LIGHT PAPER WITH MATCH",
 "WAIT", "WAIT", [WEST], "TIE WIRE TO
 HOOK", "GET OUT", "TAKE COIN", [SOUTH],
 "OPEN PURPLE BOOK", "TAKE STAMP", [N],
 "GET INTO BASKET", "UNTIE WIRE",
 "WAIT", "WAIT", "WAIT", "WAIT", [WEST],
 "TIE WIRE TO HOOK", "GET OUT", [SOUTH],
 "PUT STRING ON BRICK", "PUT BRICK IN
 HOLE", "LIGHT MATCH", "LIGHT STRING
 WITH MATCH", [N,S], "TAKE CROWN", [N],
 "GET INTO BASKET", "UNTIE WIRE", "CLOSE
 RECEPTICAL", "WAIT"
 
 -> KEEP WAITING UNTIL THE BASKET
    REACHES THE VOLCANO BOTTOM.
 
 "GET OUT", [N,E,E,SE,E,N,N], "ENTER
 GAZEBO", "DROP ALL BUT LAMP", "EXIT",
 [S,W,SW,N,N,N,W,N,N], "TAKE CHEST",
 "KISS PRINCESS", [S,S,S,SE,E,N,N],
 "ENTER GAZEBO", "WAIT"
 
 -> KEEP WAITING UNTIL THE PRINCESS
    GIVES YOU THE GOLD KEY FROM THE
    UNICORN.
 
 "OPEN CHEST", "AGAIN", "TAKE DRAGON",
 "DROP CHEST AND ROSE", "TAKE CANDY, RED
 SPHERE, BLUE SPHERE, AND PEARLS",
 "EXIT", [S,S,W,S,S,DOWN,S], "TAKE
 CLUB", [SE,NE,NW,SW,S,UP,N,N,SW,SW],
 "FEED LIZARD CANDY", "UNLOCK DOOR WITH
 GOLD KEY", "OPEN DOOR", [S,W], "DROP
 ALL BUT LAMP", [E,N,N,NE,N,N,N,W,N,W],
 [W,NE,E,S], "TAKE PORTRAIT", [NORTH],
 "ENTER LIGHT", "ENTER SOUTH WALL",
 "ENTER LIGHT", "TAKE BILLS", "KILL",
 [W,W,W], "TAKE LAMP", [S,S,S,SW,S,SE],
 "ENTER GAZEBO", "TAKE VIOLIN, RUBY,
 COIN, STAMP, AND CROWN", "EXIT", [S,S],
 [W,SW,SW,S,W], "DROP ALL BUT LAMP",
 "TAKE CLUB", [WEST], "THROW CLUB AT
 GLASS", "TAKE WHITE SPHERE", [EAST],
 "PUT WHITE SPHERE ON DIAMOND STAND",
 "PUT RED SPHERE ON RUBY STAND", "PUT
 BLUE SPHERE ON SAPPHIRE STAND", "TAKE
 BLACK SPHERE", [SOUTH], "PUT SPHERE IN
 CIRCLE", [NORTH], "TAKE RUBY, COIN,
 STAMP, AND VIOLIN", [SOUTH], "GIVE ALL
 BUT LAMP TO DEMON", [NORTH], "TAKE
 ALL", [SOUTH], "GIVE ALL BUT LAMP TO
 DEMON"
 
 -> NOW, TELL DEMON "GIVE ME WAND".
    GUESS WHAT?
 
 "TAKE WAND", [N,E,N,N,NE,S], "POINT
 WAND AT MENHIR"
 
 -> NOW, SAY "FLOAT". FEELS GREAT,
    DOESN'T IT?
 
 [SOUTHWEST], "TAKE COLLAR", [NE,S,D,D],
 "PUT COLLAR ON DOG", [E], "OPEN DOOR",
 [SOUTH], "TURN OFF LAMP", "OPEN SECRET
 DOOR", [SOUTH]
 
 -> CONGRATULATIONS!! YOU HAVE SOLVED
    ZORK II, WITH A LITTLE HELP. ONWARD
    TO ZORK III, THE DUNGEON MASTER!!D
    ZORK II, WITH A LITTLE HELP. ONWARD
    TO ZORK III, THE DUNGEON MASTER!!
