<ROUTINE THIS-IT? (OBJ TBL "AUX" SYNS) 
	#DECL ((OBJ) OBJECT (TBL) TABLE (SYNS) <OR FALSE TABLE>)
	<AND <NOT <FSET? .OBJ ,INVISIBLE>>
	     <OR <NOT ,P-NAM>
		 <ZMEMQ ,P-NAM
			<SET SYNS <GETPT .OBJ ,P?SYNONYM>>
			<- </ <PTSIZE .SYNS> 2> 1>>>
	     <OR <NOT ,P-ADJ>
		 <AND <SET SYNS <GETPT .OBJ ,P?ADJECTIVE>>
		      <ZMEMQB ,P-ADJ .SYNS <- <PTSIZE .SYNS> 1>>>>
	     <OR <0? ,P-GWIMBIT> <FSET? .OBJ ,P-GWIMBIT>>>>

<ROUTINE I-LANTERN ()
	 <LIGHT-INT ,LAMP I-LANTERN LAMP-TABLE>>




