/*
 * This file is automatically generated.  Do not edit.
 */
#define VERSION "0.7.3"
#define GIT_BRANCH "refs/keep-around/9ffffbac99e3b3be8ecdf77dbe49ebfac67d86a0"
#define GIT_HASH "9ffffbac99e3b3be8ecdf77dbe49ebfac67d86a0"
#define GIT_DATE "2025-06-12 11:20:26 +0200"
#define SHARE_INSTDIR "/usr/local/share/minipro"
