No Exit                                      Supplied by Many Axe
   by                                        Cracked by Jake Pickett
     CVS

Game info:  A karate game with a difference. To see the difference press
the up arrow when fighting! Remember though, you only get three magics.
To play two players press 2 on the character setup screen. Press escape to
exit the game. To fight use the arrow keys and the shift key for action.

Jake's Notes: This one was weird in that the call to doc check was apparent
but you could not nop it out properly. The last 2 bytes would change
depending on what debugger you were running. Without a debugger it would
lock up completely. So I said to hell with it and decided to leave the doc
check in and when I did this the check mysteriously disappeared. Weird.
Anyway, the game itself is not that bad as far as karate games go. Enjoy.