 
:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
:                                     :
:          -HINTS ON HACKING-         :
:                                     :
:      SPRINT,MCI,TELENET NUMBERS     :
:      --==--==--==--==--==--==--     :
:                                     :
:       COMPILED BY: THE RAMBUG       :
:                                     :
:    SPECIAL THANXS TO CAPT. BLOOD    :
:                                     :
:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:
 
  FIRST, I WILL TOUCH ON WHAT KIND OF
HARDWARE IS HELPFUL TO HAVE. A MODEM IS
NICE TO HAVE, ALTHOUGH IT IS A LITTLE
KNOWN FACT THAT ONE IS NOT NEEDED. A
PUSHBUTTON PHONE IS REQUIRED TO HACK AT
MCI AND SPRINT CODES, BUT NOT FOR
TELENET NUMBERS, BUT A MODEM IS RE-
QUIRED FOR TELENET NUMBERS. OKAY, NOW
THAT I HAVE GOTTON THAT OUT OF THE WAY,
I WILL BRIEFLY TOUCH ON WHAT EACH
SERVICE IS USED FOR.
 
MCI
-=-
 
IS A LONG DISTANCE SERVICE LIKE AT&T,
BUT HAS CHEAPER RATES, AND REACHES MORE
PLACES. POINTED MORE AT SMALL CORP-
ORATIONS, IT CAN ALSO BE USED IN THE
NORMAL, EVERYDAY HOUSEHOLD.
 
SPRINT
--==--
 
BASICALLY IS THE SAME AS MCI, EXCEPT,
IT IS MORE POINTED AT THE HOME THAN THE
CORPORATIONS. BUT UNLIKE MCI, IS MORE
EXPENSIVE AND IS ONLY AVAILBLE IN SOME
STATES.
 
TELENET
--===--
 
THIS IS A LIKE A SUB-DIAL PORT FOR
CHAINS OF BUSSINESSES TO TRANSFER
INFORMATION BACK AND FORTH ON THE
COMPANY'S EXPENSE. REQUIRES A MODEM
TO HACK AT, BUT WHEN YOU GET A PASSWORD,
YOU END UP BEING VERY SATISFIED.
 
 
OKAY, NOW THAT I HAVE EXPLAINED EACH OF
THE SERVICES, I WILL EXPLAIN WHAT WE
CAN USE THEM FOR AND HOW THEY WORK.
 
LET'S SAY THAT YOU HAVE A SISTER IN
NEW YORK, AND YOU WANT TO MAKE A FREE
PHONE CALL TO HER. YOU LIVE IN
VICTORIA, B.C. AND CAN'T (OBVIOUSLY)
AFFORD TO PAY $1.35 A MINUTE. SO, LET'S
SAY YOU HAVE A PUSHBUTTON PHONE AND
DIAL A MCI SWITCHBOARD THAT A BUSSINESS
IS RENTING. OF COURSE THIS IS ILLEGAL,
AND I WILL AT THE END OF THIS FILE LIST
SOME MCI, SPRINT, TELENET SWITCHBOARDS
FOR YOU TO HACK AT. ANYWAYS, ON WITH
IT, YOU DIAL IT, AND GET THIS REALLY
WIERD BEEP, AND THE EVERYTHING GOES
SILENT. THAT IS YOUR CUE TO PUSH SOME
BUTTONS ON YOUR PHONE FROM 6-8 NUMBERS.
LET'S SAY YOU PUSH 82929372 AND SUDDEN-
LY HERE ANOTHER SET OF BEEPS. THIS IS
YOUR CUE TO DIAL THE NUMBER YOU WANT.
FOR INSTANCE, LET'S SAY YOU DIAL:
201-341-2311 (THE NUMBER FOR YOUR
SISTER). LOW AND BEHOLD, YOU HERE A
DIAL TONE AND THEN A PHONE DIALING.
THAT IS THE SWITCHBOARD DIALING THE
NUMBER YOU PUNCHED IN. THEY YOU HEAR
THE LINE RINGING (MIGHT BE BUSY) AND
YOUR SISTER ANSWERS AND GIVES YOU SHIT
FOR MAKING A LONG-DISTANCE PHONE CALL.
BUT, THE POINT IS, YOU JUST MADE A L.D.
PHONE CALL AT SOME COMPANIES EXPENSE!
NOW, YOU SAY, HOW DO I GET SOME OF
THESE CODES? WELL, IF YOU HAVE A
PUSHBUTTON PHONE WITHOUT A MODEM, GOOD
LUCK! YOU JUST WOULD HAVE TO DO IT
MANUALY. BUT IF YOU HAVE A MODEM WITH
A TONE LINE (FOR ALL YOU LOSERS THAT
DON'T KNOW THAT PULSE IS OLDER THEN
YOUR GRANDMA) YOU PRATICALLY HAVE THEM
ALREADY. JUST MAKE A DIALER WHICH 
PHONES THE SWITCHBOARD AND THEN SENDS
THOSE BUTTON CODES (JUST MAKE IT DIAL
RANDOMLY WHILE IT IS HOOKED UP TO THE
SWITCHBOARD). LEAVE IT ON ALL NIGHT,
AND CHANCES ARE, YOU WILL HAVE IT IN
THE MORNING. BUT, THEN YOU ASK, WHY
DON'T MORE PEOPLE HACK AT THEM? WELL,
BECAUSE, SOME OF THE SWITCHBOARDS ARE
PLAGUED WITH TRACERS. MOST PEOPLE JUST
DON'T WANT TO TAKE THE CHANCE OF
GETTING BUSTED. UNFORTUNATLY, THERE IS
NO POSSIBLE WAY OF FINDING OUT IF A
SWITCHBOARD IS BUGGED OR NOT BEFORE
HAND, BUT LIKE THEY SAY, IF THERE IS
A WILL, THERE IS A WAY, AND BELIEVE ME,
THERE IS LOTS OF WILL! SOME PEOPLE HAVE
ASKED ME, IS IT POSSIBLE TO CALL BBS'S
VIA SWITCHBOARDS. WELL, IT DEPENDS. IF
THE SWITCHBOARD IS WAS MADE BEFORE
1979, THE FORGET IT. IT WON'T BE ABLE
TO HADLE THE TWO CARRIERS, AND EVEN IF
IT COULD, 110 BAUD WOULD BE THE MOST IT
COULD HANDLE, BUT WHO GIVES A SHIT, IT
IS FREE ISN'T IT. NOW, ON THE OTHER
HAND, IF IT WAS MADE AFTER 1980, THE
YOU CAN USE IT WITH BBS'S AND THE SORT,
WITH 4800 BAUD MAXIMUM. UNFORTUNATLY,
THERE ARE STILL ALOT OF "OLD" SWITCH-
BOARDS OUT THERE, BUT ARE BEING
UPGRADED MORE AND MORE. WELL, THIS
CONCLUDES THIS FILE. LOOK FORWARD TO
MCI,SPRINT,TELENET HINTS VOL. ][.
 
HERE ARE SOME MCI SWITCHBOARD NUMBERS:
--------------------------------------
 
201-676-7070
301-384-9820
203-789-6815
402-345-0231
218-942-8312
519-961-9231
 
SPRINT SWITCHBOARD NUMBERS:
---------------------------
 
702-876-3928
416-761-9421
509-245-2304
707-813-9147
603-471-6152
 
TELENET NUMBERS VIA LOCAL DIAL PORT:
------------------------------------
 
31240
40420
909487
30330
796009
613221
95611
61732
909821
85621
972316
 
 
WELL, THAT'S IT. I HOPE THIS FILE HELPS
YOU, AND KEEPS YOU HACKING!
 
:CALL THESE RIGHT ON BOARDS:
 =------------------------=
 
THE NEUTRAL ZONE ][ (604) 478-1363
10 MEGS ON-LINE
 
TCL ][ (604) 384-3085
 
METAL A.E. (201) 879-6668
PASSWORD: KILL
 
/\/\ETALLAND 1 (503) 538-0761
10 MEGS ON-LINE/AE/BBS/CAT-FUR
 
/\/\ETALLAND ][ (503) 253-5300
20 MEGS ON-LINE/AE/CAT-FUR
 
 721-0693
THE PROVING GROUNDS...................(604) 478-1363
 

