Article 1468 of eunet.jokes:
Path: santra!tut!draken!kth!enea!mcvax!hp4nl!dutrun!rcdsdgx
From: rcdsdgx@dutrun.UUCP (Dik Groot)
Newsgroups: eunet.jokes
Subject: Re: Strange Error Messages
Keywords: Philosophy and Computers
Message-ID: <561@dutrun.UUCP>
Date: 1 Dec 88 09:37:08 GMT
References: <7741@boring.cwi.nl>
Reply-To: rcdsdgx@dutrun.UUCP (Dik Groot)
Distribution: eunet
Organization: Delft University of Technology, The Netherlands
Lines: 13

- .- .- .- .- .- .-
How about this message: (upon scheduling a job named TOMORROW on an
IBM370 under MVS:

***TOMORROW HAS BEEN CANCELLED DUE TO JOBCONTROL ERRORS

- .- .- .- .- .- .- 

-- 
{ - - - - - - - - - - - - - - - - - - - disclaimer : I usually lie. }
Dik Groot,   Delft University of Technology,   Rekencentrum,   DUneT.
Postbox 354, 2600 AJ Delft.  ptt: (31)-15-781938  fax: (31)-15-786522
BITNET/EARN: RCDSDGX AT HDETUD1          usenet/eunet: rcdsdgx@dutrun


