#define stderr 1
#define STDERR 1

#define FILE char

extern char *stdin, *stdout ;

#ifndef EOF
#define EOF (-1)
#endif

#asm	
	GLOBAL	CCAND
	GLOBAL	CCASR
	GLOBAL	CCASL
	GLOBAL	CCCDR
	GLOBAL	CCCAR
	GLOBAL	CCCMP
	GLOBAL	CCCMP1
	GLOBAL	CCCOM
	GLOBAL	CCDCAL
	GLOBAL	CCDIV
	GLOBAL	CCEQ
	GLOBAL	CCGE
	GLOBAL	CCGO
	GLOBAL	CCGCHAR
	GLOBAL	CCGINT
	GLOBAL	CCGT
	GLOBAL	CCLE
	GLOBAL	CCLNEG
	GLOBAL	CCLT
	GLOBAL	CCMULT
	GLOBAL	CCNE
	GLOBAL	CCNEG
	GLOBAL	CCOR
	GLOBAL	CCPINT
	GLOBAL	CCSUB
	GLOBAL	CCSWITCH
	GLOBAL	CCSXT
	GLOBAL	CCUCMP
	GLOBAL	CCUGE
	GLOBAL	CCUGT
	GLOBAL	CCULE
	GLOBAL	CCULT
	GLOBAL	CCXOR
	GLOBAL	CURRENT
	GLOBAL	ERR2
	GLOBAL	QABS
	GLOBAL	QALLOC
	GLOBAL	Q_ARGCNT
	GLOBAL	QAVAIL
	GLOBAL	QCPM
	GLOBAL	QERR
	GLOBAL	QEXIT
	GLOBAL	QFCLOSE
	GLOBAL	QFOPEN
	GLOBAL	QFREE
	GLOBAL	QGETB
	GLOBAL	QGETC
	GLOBAL	QGETCHA
	GLOBAL	QGETS
	GLOBAL	QPUTB
	GLOBAL	QPUTC
	GLOBAL	QPUTCHA
	GLOBAL	QPUTS
	GLOBAL	QFPUTS
	GLOBAL	QUNLINK
	GLOBAL	_END
; printf and scanf entry points
	GLOBAL	QPRINTF
	GLOBAL	QFPRINTF
	GLOBAL	QSPRINTF
	GLOBAL	QUTOI
	GLOBAL	QITOD
	GLOBAL	QITOU
	GLOBAL	QITOX
	GLOBAL	QFTOA
	GLOBAL	QFTOE
	GLOBAL	QSCANF
	GLOBAL	QFSCANF
	GLOBAL	QSSCANF
#endasm

extern double atof() ;
extern char *fputs() ;
