
Date:  12-01-88  23:42
From:  Sourdough Jackson
To:    Paul Seymour
Subj:  Re: gays in traditional craft

***** Quoting message from Paul Seymour to Michael Harismides *****

In my experience of observing may circles, the ones that included "gay"
people without careful attention to the balancing of energies between them
had some serious problems.  While my somewhat limited experience may have
little bearing on the subject, it has suggested something that has not been
discussed thoroughly: The necessity of a balancing of male vs. female
energies in a circle, regardless of sexual preferences.  Any body want to get
into this one?

***** End Quote *****

   In my experience, a 'balancing of energies' can take a number of forms. 
One of them that seems to work no matter how the circle is composed is a
matching of resonances.  Everyone grounds & centers first, and then either
the circle is cast and everyone matches resonances or you do it the other way
around.  To match resonances:  stand or sit in a ring with hands nearly
touching, with each person's right hand directly above the left hand of the 
person's neighbor to the right, to the point where each person can feel
his/her neighbor's energy field.  Let a GENTLE current flow (sorry, this is
the only way I know how to describe this) deosil until everyone feels in
balance.  You are just trying to balance the energy of the circle, not raise
any power just yet.  We don't always do this in Birdsnest; last time, a
simple kiss on the cheek passed deosil with the words "Perfect love and
perfect trust.  Blessed be." was sufficient.  However, Birdsnest is the
barest minimum size for a coven (3), and we are a well-matched psychic
circle.  Non-psychic circles may have more difficulty matching resonances,
and may have to resort to other more symbolic ways of balancing the energies.
Try various methods and see what works.  My guess is that any method that
will balance the energies of a circle for Dianics ought to work for anyone,
as we are supposed ;-) to be inherently unbalanced.  Incidentally, I learned
how to match resonances from a Christian psychic, and she learned it from a
touch therapy course.  Talk about non-sectarianism!
           BB, Sourdough

PS--The original message had to do with balancing of male & female energies.
 I might add that we have REAL case of potential unbalance in Birdsnest, as
all three of us are lovers of women--and when I am in circle, my anima is
doing most of the work for me.  This seems to create no problems whatever for
us.  The one time we did have problems, we broke every rule in the book
because we were doing an emergency working when we were all physically and
emotionally messed up with initial grief shock.

--- Gnome v1.20
 * Origin: The Lizard King-"I am the Lizard King; I can do
anything."(1:104/45.5)

