
Date:  03-04-89  18:11
From:  Lady Phoenix
To:    Brigid Dragonchild
Subj:  Re: HARD COPY

>Be gentle...
        
        I like that poem.  Are you sending me some hard copy?  PLEASE?
        
   And, since we are waxing poetic...
        
        To Greyshield, with love
        
        The circle cast about us.
        The Gods bear witness to our love.
        The Watchtower Guardians keep
        silent vigil.
        Our brothers and sisters stand with us.
        The Lord and Lady have granted 
        us audience.
        The candlelight reflects the love
        in your eyes.
        A love that we have shared before,
        Not even death to come between us.
        We stand together, hand in hand.
        Our paths have merged again.
        The Moon beckons us to join Her,
        gladly we go.
        The Lady smiles upon us.
        
                        Phoenix
        
   Needs work, maybe someday when I have some time.  Ha!
--- QuickBBS v2.03
 * Origin: InterVisioN "The ParaNormal Connection" 603-547-6485 HST
(1:132/123)

