
" Where the secrets start, the republic stops. "
                         --Norman Thomas

THE QUARANTINE
By Moses Domingo

          Welcome to the good old U.S.A.!! Land of the gangs, land of the
ignored and the deprived; the land of dead soil, nuclear weapons and an
illiterate population.It feels just great to be an American---to go outsideand
walk upon the dead and trampled; to stretch your arms out and inhale the dry
air; to walk through a field and pretend there are trees---doesn't it just feel
great ?
          Where are my manners ? Hello, my name is Joe Simmons, and I'm a
drummer. Please---enter " JOE'S WORLD  OF 2053 "---where nightmare is a reality
!
          It has been over a month since my suicide attempt, and I still shudder
at the thought of my trying to blow my brains out. That same day, I went to the
cemetery and  visited the graves of my family and my girlfriend. As I stood
there,I would occasionally look up at the sky--- rather, the atmospheric-shield
simulation of a sky---and prayed that it would actually rain. Not just to set
the  perfect mood, but to give everyone on Earth a big break.
          I waited in silence. It seemed like decades.....
          Nothing....nothing but my foolish imagination. I mean, why would it
ever rain on Earth again ?
          Like the "sky", I did nothing and began the slow journey home.
          That was Secondmonth.

          This is Thirdmonth. There was a riot of tremendous numbers of people
not far from the cubicle where I live. Some of the rioters had techno-machine
guns, but they weren't really using them.
          Well, that's what I thought.
          In full view, I witnessed two people drag out the sector's
ration-distributor onto the street. There was an  argument between the three of
them. The two gun-toting people proceeded to place the ration-distributor
against a wall. It appeared as though he pleaded with them. One of them
literally shoved his pistol into the ration-distributor's mouth; the other, in
his chest.
          I watched in horror as, simultaneously, they pulled their triggers.
          They blew the body into oblivion---a headless man
quivering and swimming in blood.
          " Holy shit," I thought. I didn't know what I was going to say next
because I suddenly keeled over.
           Catching sight of me, the rioters started and,  pointing their guns,
ran towards me but halfway they stopped in horror. One of them said " Look ! "
and then ran away, the others right behind him.
          In turn, I got up and spun around--only to find  something standing
in my way. I practically ran into it--- whatever it was---and fell down in the
process. As I looked   up, a dim glare covered my face.
          It was the glare of an Order-droid.
          Seven feet of metal leaned over me and scanned me with an intelligence
so cunning and evil that I broke into a cold sweat. Its' infra-red scanning
light panned down me a couple of times. I wanted to run, but the same thoughts
must have been relayed to the Order-droid because it suddenly  lashed out one
of its clamp arms around my ankle.
          " I am self-named S'neta, Order-droid/Riot controller model numbered
8892467122215983117. You have been witnessed and observed as a provoker of this
food riot---"
          " What do you m---"
          "---Do not attempt to escape or to avoid me in any way."
          " What the fu--"
          "--Now I must prepare you for interrogation." With these words, it
extended an internal "hand". It looked like  a closed fist which was now opening
up---its fingers fully extended. Needles popped out of their ends, dripping with
some kind of transparent fluid. With a quick swing of its  forearm, the
Order-droid punctured the area around my chest.
           Instantly, I blacked out into what I thought was  death.


         
          " What is the subject's name ?"
          " DNA Identification-Print is verified. The subject's name is Joseph
Berkin Simmons, age is unknown due to inaccuracy of true birthdate, although
external features suggest that the subject is between 20 to 30 years old. Joseph
Berkin Simmons is the only remaining member of the  Simmons---it is believed
that his parents died the first year of The Quarantine; the death of his two
brothers and  one sister, named respectively Johnathan Jacob Berkin Simmons,
aged 10; Isaak Berkin Simmons, aged 21; and Catherine Fletcher Simmons, aged 28,
occurred in the following month. Joseph Berkin Simmons' girlfriend, Jeanine
Henors Forrester, who was coincidentally the last member of her family, was
trampled upon during The Great Food Riot of 2048. 
          " Subject's profession is founder/percussionist of New Chicago's
predominant band, Genital Leprosy. Information on accompanying members was found
to be unnecessary at this   time. End of scanalysis and report."
          " Continue to administer  internal-convulsion  ejections until further
notice. If subject Joseph Berkin Simmons awakens from his subconscious state,
have him sedated immediately."
          " Understood."
          Order-droid/Riot controller S'neta left the  Examination/Sedation room
with the clanging of its feet.  

          The boat I was in lightly tapped the dock. I woke up and looked
around. It was my summer house by the lake, in Galena, Illinois. Then I realized
that I wasn't alone. I  looked up and saw a beautiful woman standing in front
of me.
          It was Jeanine, smiling brightly as always.
          My head hurt, but I got up and embraced her tightly then kissed her
lightly on the lips. Dumbfounded that the things around me were real, I actually
pinched  myself just to make sure. Just then my standing up in the boat tipped
it over, sending Jeanine and I into the frigid  lake.
          The water wasn't as deep as I thought it was.  Jeanine was kneeling
right next to me---laughing like a little kid but dripping wet. At first, I was
quiet and suddenly I laughed so hard that I pulled her down with me into the
water.
          " You bastard, " she giggled. " You got me all  dirty again just after
I showered. Now I'll have to take  ANOTHER one."
          " Oh, damn, ' I said. " I SWEAR I didn't mean  it."
          She then put up her index finger and "shushed" me up. Our lips didn't
let go for a long time. Then I  looked into her eyes and spoke to her quietly.
          " You know what?  I've got to tell you a little  secret, " I said.
          " And what is it ? " she insisted.
          " I think that I'm in love, " I replied.
          " And ??? "
           " And I've got to ask you a question that's been  burning my heart
for ages."
          " If I'm thinking about what you're thinking, then my answer is a
`yes'," she said enthusiastically. If looks could kill, then her smile was
murderous.
          She raised her right arm and then...
          And then she SLAPPED me !!!!
          " Jeanine, what the hell are you doing ?" My face was twisted up like
play-dough just waiting to be formed. Then, her fingers seemed to stretch right
in front of me--- her face glowing almost like metal; her smile unnatural.
          And evil.
          Needles protruded from her now-extended fingers, dripping with a
transparent fluid that was somehow familiar. I stared in horror as she
penetrated my wrists and WITHDREW from my body a yellowish-liquid. She slapped
me again as she removed the needles....

           I woke up in the old reality. The Order-droid, S'neta, the one who
had arrested me near the food riot, was actually tapping my face instead of
slapping it.
          " Please wake up, Joseph Berkin Simmons. You  will be briefed shortly.
Meanwhile, you will be shown to your new quarters as soon as you are
decontaminated and released from The Quarantine. " S'neta spoke without emotion
or pattern.
          " The what ?" 

          I was taken into a room as big as the entire building that my cubicle
was a small part of. One wall  had nothing but open windows. S'neta was standing
a few  feet from me, just waiting patiently. I turned to talk  to it. 


          " Now tell me the flippin' truth. You guys grab me from a food-riot
I had nothing to do with, knock me out for no reason, give me a scrubbing and
a shower, and  then take me to a place that looks like a fuckin' hotel suite !
Why ?" I looked S'neta straight into its' eyes.
          " First of all, Joseph Berk----"
          " It's `Joe'. Okay ?"
          " First of all, Joe, you have been sighted and  subsequently chosen
as one of the few who are eligible and proper for The Reward. `The Reward' is
our version of being  released from The Quarantine."          
          " Hold it one goddamned minute.
       " S'neta was really trying my patience. 
       " You mean to tell me that I have been living my entire life in a
holographic-situation ? Kissing an illusion of my mother, making love to a
holographic woman---all the people and places that I've ever known are nothing
but techno-computer simulations ?"
          " No, " it sighed. " Unfortunately the life that  you've been leading
was for real---the death of your loved ones, the situations of your
lifestyle---EVERYTHING. And  you've been living in there." Its' right limb was
pointing out the windows.
          I ran toward the windows and pressed my face up against them. What I
saw looked exactly like the birthday gift my grandfather gave me when I was 10,
the last birth- day present I received from him before he died. It was a little
glass dome with a white-colored base, and inside was the city of his boyhood
Chicago.
          The object outside the windows looked exactly the  same, except that
there were many new buildings and struc- tures.
          But it was no miniature model. It was the real thing.
          Suddenly my gaze was fixed outside the domed city upon the scenery
that reflected through the windows of this structure.
          A distance from the domed New Chicago was a lush  greenery that I had
never seen before in my entire life. It was definitely no match for the
flexi-grass or the other plastic-green substances used as mockeries of grass and
trees. There in front of me, outside the barriers of my  in-born curiosity, were
REAL trees,REAL grass,REAL animals  and insects.
          " The Quarantine," said S'neta, disturbing my  peace of mind, " is a
term The Order uses to describe the domes or `atmospheric shields' that ones
like yourself have  been living in."
          " Bullshit ! I was told that in the 21st century, something called
`The Greenhouse Effect' nearly destroyed everything that once belonged to
nature, which is why we lived within atmospheric-shields. " My concentration was
still outside, in the "Hanging Gardens of Babylon".
          " False information given by the ruling government of the 20th
century. Their scientists had physically---and quite cleverly, I might
add---created the so-called hole over Antartica by the use of silver iodine and
some other  nitrogen-based components, then passed along this false information
to the circulating media of the time. It was  decided that Operation Greenhouse,
as it was called, was to take place in the years between 1999 and 2011.
Skeptical scientists of the time were taken and re-educated, whereas   those who
had originally cooperated were put under the  Witness Protection Program. The
Year of THe New Order followed, and the building of the atmospheric-shields and
domes began as predicted, following the plans of Operation Greenhouse perfectly.
No one complained because all conspirators were dealt with  simultaneously. And
this is how it's been for the past 53 years. I was created in 2001, so you
aren't the first person whose situation I've dealt with. So do not feel that you
are alone."
         Dumbfounded, I slumped down to the floor. S'neta tried to help me up
but I refused. I sat there, thinking of what had just been said to me.        
 " Governement lies---a tradition that dates back almost a hundred years." I
pondered deeply at this statement. All of us have been living a great lie. I
began to think  that life itself was a big lie. Was God pulling a prank on us
?
         And then there were flashes of light outside. Thunder. Like a huge
brontasaurus taking a morning stroll. And then it began to rain.
         It began to rain.
         All natural, all thirst-quenching rain.
         S'neta opened one of the windows for me and picked  me up like a child
to let me touch the rain. THe clouds cried, the brontasaurus-lightning growing
louder and louder, the water-gates of Heaven opened,the buckets of the wishing
well overturned. I felt, absorbed, and jerked to every rain-drop that fell on
my body. I screamed with delight as the rain soaked my body through my clothes.
I looked at my newly-wrinkled fingertips, an experience I had only felt  after
washing a sink loaded with dirty dishes. When I turned to see S'neta's face, I
could've sworn I'd seen it smile. Maybe it wasn't a real smile, the true
physical act, but it definitely was some really subtle emotional expression.
         S'neta put me back down on the floor as gently as a mother would her
own baby.
         " As they say, `Since you've been a good little  boy' here is The
Reward. From now on, you shall live here doing whatever you like. Since the
Order has no need for money, neither do you. In fact you do not HAVE to work 
again, unless you want to. Everything you need will be provided for
you.Uh---(this is the first time S'neta  stuttered)---think of your place as
being the entire  apartment complex that you used to live in, except only on a
larger scale. In fact, you do not have to live here at all; the Rewarded can
choose where they want to live, and it shall be prepared for them." It then
stopped, as if to take a deep breath, but possibly waiting for my expected
response.Finally, I spoke.
         " But...But why the hell are you doing all this ! What's your game ?"
         S'neta stayed silent for a moment, its "eyes" panning down me a couple
of times.
         " There is a famous quote," it said, " that gives a perfect explanation
for all of this `richness'. It  says, `Never question a miracle, just let it
happen and be happy.' My memory bank is not adequately informed about the     
      originator of this quote. `Making all the wrongs right'. It was fortunate
of us to have such compassionate human beings as leaders of the Order---many of
them felt that mankind was too destructive and violent and that its love for
killing uselessly was becoming too apparent in the known universe. They
especially wanted to isolate the more populous, crime-plagued cities of the
world, New Chicago being one of them, with others such as New New York, Altered
Alberta, New Detroit, Greater Los Angeles, S'an Francisco, and all the other
major metropolitan cities in the States. Another reason I can offer you is that
the majority of the Order were born as environmental-extremists, concerned about 
pollution, starvation and all the little goodies that go along with a now
non-existent `human rights list'. It is even said among the older generations,
that mankind is thirsty for war and that it is a last-resort for population
control---"
          " Speaking of war, what the hell ever happened to the one we were in
? Is it The Oil War we're fighting or is it some other shitty vendetta---forgive
me, I `lost track'."
          Here, S'neta laughed---a loud, mechanical laugh.
          " There never was a war," it said. " After The Oil War of 1991, all
the other wars were...how do you say...`bullshit', but for the good,
nonetheless. As some of your past ancestors would say,`Kill 'em all and let God
sort 'em out.'" 
          " But what about the bodies....the bodies--I saw them on the HDTV !
All the countless----"
          S'neta "sneered" at me. " You SHOULD know the  answer to THAT by NOW."
          " Sigh! The magic of a techo-matte. So what the hell happens to me now
? What happens to my friends and  property back in----back in there ?? "
          " The Order will most likely clear out your cubicle as if you were
killed or taken for re-education. And your friends will have to learn to live
without your presence---"
          " Wait one fuckin' minute, metalmouth !! " Even though I was to lead
the life of Reilly, I still didn't forget about my friends.  They were there for
me ever  since my girl was trampled upon during The Great Food Riot. And I will
NEVER forget them because of that."
          S'neta looked at me and paused. " Yes, I know." It started out for the
door, but stopped suddenly. " But I am truly sorry--as much as I may have the
ability to occasionally resent my job, I still have to do it."
          I paused for a minute, then spoke. " Yeah,yeah. Yeah---I understand.
And I'm sorry, too."
          S'neta looked at me, seemingly confused at my response. " Joe, we are
each built for some sort of purpose  in life. And that goes for everyone...and
everything."
          I didn't look at S'neta as it walked silently and casually out of the
"room".   


          After looking around for a few minutes, I finally found the
clothes-dryer and shoved my wet garments into it. I then walked into another
room and was confronted by my familiar drum set, nicely cleaned and perfectly
arranged, with all my other musical necessities. I turned on the  elaborate
array of synthesizers and synth-drums and chose my  drumming sticks from a very
familiar-looking bag. I put in one of my favorite techno-tapes and waited for
the music to start.
          I looked outside and smiled for a long time.
          " Bitchin'" I said.
          And then I began to play----very loudly.
 