Sent at: 2/5/87 at 10:00 pm

The MSBASIC Compiler is offline(like many files) at this time. Norton Utilities
are good for Hard drives(I know it won't accept 30 meg though) and might do the
trick for 20 meggers. If you plan to do the SN Zapping on a floppy, try the
Ultra-Utilities(MY PERSONAL FAVORITE). They are PD and can be easily found
almoost anywhere. The Listarchive thing, is actually a routine in Pascal that
goes to read the file. It errors out because the file isn't there. Currently, I
have not been able to get the Drives restored and we had problems with another
30 megger so we are down to only 30. Hopefully some positive things happen soon
for the future here. It's pretty tough keeping up with all the heavy shit that
is happening. Anyways, Hang in there and we should be back up to par in a
couple weeks or so......

                                The Mad Hacker
                               Phortune 500\BOD
______________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                               THANKS For Calling
                             The Private Connection

                        Call These Other Fine Boards Also
                   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
                   ³ Shadowspawn              ³ 219-659-1503 ³
                   ³ The Free World II        ³ 301-668-7657 ³
                   ³ The Castle               ³ 301-654-6872 ³
                   ³ The Undergraduate Lounge ³ 602-990-1573 ³
                   ³ Hemispheres              ³ 215-489-2768 ³
                   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

      ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
      ³ NOTE: YYZÿWill Be Available Soon As System No. 2 At 219-322-7266 ³
      ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
______________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Title:   Shit..
Sent by: Epsilon III
Sent at: 2/10/87 at 4:45 pm


  Pez,

  You hit * then # in succession then it'll say 'Enter your user ID'..
After that, you enter your password..

-Epsilon-
Marauders
______________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Bulletin 94
Title:   Allnet
Left by  Computer Wiz Kid (Level 50)
When:    3/12/87 at 11:19 pm


I was wondering. Since i don;t assoicate myself with Allnet. I am looking for
some ports in the Los Angeles Area, but have yet to find any? Anyone got any?
Also, what is the situation with metro? have they gone to 9 digits on all
ports? down here 213-202-6117 (metro port) seems to still be working with 6
digits? O'Yeah why i am at it, a friend at school ran into a Pbx.

1-800-262-5771? What is it? Or is it even a Pbx. Codes are 4 digits?

Let me know!

Cwk-
______________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Read Command [44] 1 - 57, * :
#45  14 31 Mar 87  16:07:08
From: The Jeff
To:   Mr. Pez
REPLY TO #35
Subj: 313 Dial-Backz


This is going to sound stupid:

1.) Dial '711'
2.) Wait for dial-tone
3.) Dial '6'
4.) Hang Up!

It'll ring in about 20 seconds.                                                
______________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|-) <-sleepy
|:-|) <-Liddy                       |D__\\
|:-) <-Liddy ][                     |D  //
                                             -\|/-\|/
 >:-) <-Satan beckons!               o__/
                                     o~~\
 8-(:-) <-Propeller head

  :-@ <-bleah!

 :-Q <-smoking d00d

  :-H <-AndrewLips(tm)

 :-() <-AndrewLips ][(tm)

  :-O <-AndrewLips ///(tm)

 B-I <-Sunglasses d00d

 ³:-) <-Jason Scott (not omitting the "UniBrow(tm)"
___________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#88  4 06 Apr 87  00:57:22
From: Branwen Maddox
To:   All
SEE ALSO #89
Subj: Thats better

Ok, although I love you all financial responsibility is beating down the door
and I will have to let go of a few nicities on my computer until I can get a
job and replace or upgrade them.
 So I gotta sell
   1 very nice Hayes Micromodem //e (300 baud auto answer/dial pulse/tone on
board for slotted apple compatables) with original
software and documentation complete. $85 or best offer.
  Also a Mockingboard (music  sound effects) with cables,
documentation, and Music Construction Set. $100

  Respond now and I'll throw in a paisley tie.
Call me at 375-5907 or 375-2807 if you cant get through on 5907,
And if you dont need it prod somone who does.  Thank you
                       Andy Bristol

___________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Qs> Post here?

Checking [#2: Chemical Lounge]..

 Msg #221: ATTENTI0N!
  Box 006: The Stranger
   Lvl ? : My grammar is getting worse.
  Written: 15-Mar-87 at 10:50 am



OFFICIAL DARK SIDE PHOTO SESSIONS WILL BE HELD ON MONDAY APRIL 6th
AT 6:29 PM ON MCMLXXXVII !

For the simple reason that people who send self-addressed envelopes
to PO Box 36, Cupertino California, 950150036, will be sent these
particular photos. The Slipped Jason will be the first to recieve
said photos. Thank U.

h
___________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CATALOG   Directory of current vol
DATE      Display/change Date
DELETE    Delete file on current vol
DISK      Hard Disk Command Utility
EDIT      Edit file on current vol
EJ0       Logoff without traces
EVENTS    Display events log
EXPERT    Toggle expert mode
HISTORY   Show what a mess you made
HOME      Load root account profile
LOAD      Load user profile
LOGIN     Login to another account
NODE      Node currently logged in at
PAGE      Clear screen for modesty
PENIS     Can't get it up yet
SAVE      Save user profile
SPY       Look at who has mail
STATUS    Quickscan number and calls
TYPE      Type file on current vol
VERSION   Current software
___________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Yeah, it's been fine.  I've been chatting witha lot of people lately, it seems.
 First I talked to Thomas Covenant (a good pal) voice, then Harrison, The
Stranger, of the Darque Side.  (GREAT board.)

Hmmm...sounds like it's chatting season or something huh?  (that was stupid).
ANyways, Vortac is over here.  We just got back from throwing the ole softball
around (boy are we out of shape) and before that we were looking at the new
IBM's....again.  They are nice!  I'm probably looking at the model 60.  Man, we
took a dir of the thing on the Model 50/60 and it fucking cooked!  Talk about
fast!  It's like s-l-o-w on this damn thing in zoooomm   fucking fast!

Yeah, I wonder who IBM got to make the drives.  The 60's the floor-standing
286, right?

Yep, they're 286 processor, 32 bit bus(!!), 44/70meg HD built in, 1.44mg 3 1/2
floppy, 1 MG memory, room for another floppy/tape streamer (which?...hmmm) and
another HD.  VERY VERY VERY nice.

Yeah, I'm glad to see IBM going with the streamer.  Laterly, as a hobby, I've
been searching the PCmag's for a cheap tape backup...if you're going to run a
board, you should use that.  (And I do plan to run a board, probably off this
software, too.)

hold...phone
___________________________________________________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Msg #953: Information
  Box 666: Evil Bunny
  Lvl 666: Fuck the Phone Company
  Written: 07-Apr-87 at 12:02 pm

If you wish to recieve a "DARK SIDE CARE PACKAGE", otherwise known as a
"DARK SIDE VAL-U-PAK", then you should send us one as well. We don't really
care what you send, but I'm sure it will be all very welcome. Oh silly.

    Send your bullshit to..

    [] Dark Side International
       PO Box 36
       Cupertino CA 95015-0036

Have good day.

_________________d_i_v_i_d_y_-_d_0_0_d_!_____________________________________
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

       