




 * Use S to Stop, and P to Pause *

***********************************
*  Welcome to the Compost Heap    *
* 24 Hours a day,   7 days a week *
*  auto scanning. 8 bits, 1 stop, *
*            No Parity            *
***********************************

    Sysop     : David Martin
    Computer  : BBC Model 'B'
    Software  : Mostly Mine









 First Name ?GERRY


 Last Name ?MACRIDIS


   Calling From NEW ZEALAND
   Is this correct (Y/N):Y



   Enter Your Password: *******




   TCH Welcomes GERRY MACRIDIS
   Calling From NEW ZEALAND
   Your last call was 21/05/87 02:23:17
   Last message then was 3888
   Last Message Now is 3889
   You have called this system 24
   times before.
   You are caller number 5534

   You Are Authorized 45 Minutes
   This Call.


   Active Combined Sigs are:-
 
   Sales & Wants       Lonely Hearts
   Problems
   Music 500           TRS80 User group
   Nascom user group
 


   Do you want a message check?N


   ** S to stop, P to pause listing **

             ** 17/1/86 **

   ** New Files and Downloads! **

At last I here you say? (I agree!).
Its the first time in ages that i have
had some free time,  so i have updated
things around the place,  you'll have
to find them yourself tho'!

   ** Hackers Kingdom **

Its a game for all to hack!
Happy Hacking.

   ** Sponsors **

 Does Any one out there know of any
company that would sponser me.?


   ** ADULT Jokes Section **

 Due to the resent 'dieing' of the
Adult jokes section,  I've desided to
boost the number of jokes left there by
allowing all REGISTERED users to access
this section,  Please contribute or
this privalage will be withdrawn!....

   Mid Kent Micro Club

 Those of you who live in the the
Maidstone and Medway or there abouts
ares have no excuss for not coming to
this exciting Club.  The first meeting
is free for you to see just how good it
really is!  If you are interested in
poping along or just plain interested
then send a Message to MICHAEL GATES,
for more information on the MKMC see
the information section

   Winchester Fund.

The fund is going very well so far,
plse keep it up!....


              ** Dave. **


   Press any key!

 
           THE COMPOST HEAP
 
            Top Level Menu
            ##############
(R) egister         (W) inny!?
(+) Slag Off
(N) ew Utils        (U) tilities
(O) pen Files (D&U)
(M) essaging        (P) age Sysop
(F) eatures         (T) erminate
(E) prom section
(H) ackers          (!) ???
(0) Hackers Kingdom




   For a laugh Phone (0898) 600706
   Enter your choice Gerry :

H

      ****************************
      * The Compost Heap Hackers *
      *    Editor :  MC SPINE    *
      ****************************
 
      <R> ead Hackers Msgs
      <L> eave Hackers Msgs
      <S> end Private Msg to Editor
      <K> ill Msg's in this section
      </> Top Level   <M> essages
      <P> age Sysop   <T> erminate
 
 

   For a laugh Phone (0898) 600706
   Enter your choice Gerry :

R
   <F>orward
   <R>everse.
   <N>ew message(s)
   <I>ndividual retrieval
   <S>can message(S)
   <A>bort reading Messages.

   Choose Please:



   Enter starting Number,<CR>=first:

   S to Stop,N To goto Next message,
   and P to Pause.

   Reply To Message Option(Y/N):N




   Message # 00661
   **Hacker's section**
   From: JONATHAN BARBER
   To: ALL
   Subject:EUCLID
   Date: 6/3/86
Fob all of you who want an easy
hack heres how to get onto the
EUCLID computer.First di!l up'
JANET gn 01 831 6181 for 1200/75
or try 01 388 2333.Type PAD
and RETURN as soon as your connected
Then type HELP ADDRESS.Then type
CALL UCL.EUCLID*If nothing happens
hit RETURN a few times.You should
get a request for your account
number.Type in WMAPB00 W.The
password is PROJECT.
 
          Have fun!




   Message # 00688   (Received)
   **Hacker's section**
   From: JONATHAN BARBER
   To: JONATHAN BARBER
   Subject:Reply to message number 661

   (EUCLID)
   Date: 8/5/86
Must have been line noise but
the password in my last message
should have read WMAPB00 WM.
Then type PROJECT.
 
          Cheers.




   Message # 00766   (Received)
   **Hacker's section**
   From: JOHN RAYFIELD
   To: JONATHAN BARBER
   Subject:Reply to message number 661

   (EUCLID)
   Date: 0/0/86
01-388-2333 IS OK FOR 300/300 WITH PARI
-TY (EVEN).IT IS A GOOD IDEA TO HAVE
YOUR SYSTEM SAVE THE OUTPUT AND READ
IT LATER.THIS SYSTEM GIVES QUITE A
LOT OF OUTPUT!
IT ALSO SOUNDS THE <BELL>> FOR EVERY
PROMPT,WHICH GETS A BIT ANNAOYING.
... REGARSDS




   Message # 00767   (Received)
   **Hacker's section**
   From: JOHN RAYFIELD
   To: JONATHAN BARBER
   Subject:Reply to message number 688

   (EUCLID)
   Date: 0/0/86
NOTE THAT NO PROMPT IS MADE BETWEEN
ACCOUNT AND PASSWORD!!!!!




   Message # 00790
   **Hacker's section**
   From: NOBBY THE BIG ONE
   To: ALL
   Subject:NUMBERS
   Date: 16/3/86
well here's a few numbers:-
poly..637-7732/3/4/5 - probably 9am-5pm
not sure
Imperial College 581-1366 9am-5pm prob
tell me how you get on!!
seeya
****Nobby****
+++++++++++++




   Message # 00808
   **Hacker's section**
   From: ASIF KHAN
   To: ** HACKERS **
   Subject:** CAN'T YER GUESS**
   Date: 17/3/86
Hi Ace King here,
 I am a now on this board and am
willing to give help where possible.
 Sum of u don't know me but soon will
 if u r stuck on a Hack ask me ,I ma
be able to help.
 Cheers
 ASIF <ACE KING> KHAN
 Bbyyee
P.S
 I hate to admit it but I'm stuck
and need help on the following:-
How to get onto:-
(i) The Times Network for schools
(ii) Telcom Gold
(iii) PRESTEL.
 If u can help please mssg. me &
tell me.I am willing to swop info
and data etc.
 Thanx
P.S.S (excuse the pun) !!!
If u r London based leave a mssg on:-
Mega-Anchovey:01-747-4662 (same bd)
or TUG/TBBS:01-200-7577 (same bd)



   Message # 00811
   **Hacker's section**
   From: ASIF KHAN
   To: ** HACKERS **
   Subject:** - **
   Date: 17/3/86
Do exactly as follows:-
Phone 01-388-2333
Type 'PAD'
Type 'LOGON 1111,1111'
Type 'CALL 00000700900104'
Type '7' when connected
Type 'TS2' or <CR>
Userid='UST2033'
PWD='RUNTIME'
Try the following when in system:-
EXPL NEWS|EXPL NEWS OLD|EXPL NETWORKS|
MAIL;L|MAIL;P|EXPL MISSCELLANEOUS|
MAIL:C|EXPL SERVICEINDEX|
|=New command.!!!
_______________________________________
MORE PAD & PSS Stuff later(sooooonnnnn)
_______________________________________
Cheers
ASIF <ACE KING>$KHAN
Bbyyee
P.S See msgg.'808'
Thanx
Mssg. ME & Tell me anything bout Hackin
HAPPY HACKING ------------------------>



   Message # 01003
   **Hacker's section**
   From: MICHAEL BATES
   To: ALL
   Subject:HACKING
   Date: 2/0/86
Hi just thought you would like to know
 I work for B.T.




   Message # 01008   (Received)
   **Hacker's section**
   From: PINEAPPLE JOLLY
   To: PINEAPPLE JOLLY
   Subject:Reply to message number 1007

    (HACKING!)
   Date: 4/4/86
HI ALL!
 
PRESTEL GOODIES FOR YOU.
4827675497 PW KATY
5176158231 PW ???
 
ALSO A HACKERS BOARD
0634 41397 NAME HACKERS CLUB
PW :  HCBTS
 
TTFN




   Message # 01410
   **Hacker's section**
   From: THE REAL PHANTOM
   To: ALL
   Subject:POLYTECHNICS
   Date: 6/0/86
Does anybody have the phone nummber
for the Huddersfield
Polytechnic??????????




   Message # 01577
   **Hacker's section**
   From: PINEAPPLE JOLLY
   To: ALL
   Subject:AUTO ANSWER
   Date: 16/5/86
Ok, for those interested in starting
up a bb with a nightingale, I have
some
news for you, if you just want to run
at 1200/75, you dont need an auto
answer board.(waste of money unless
you want 600/600 and auto
dial(useless) ok). Just get your comms
software and select your modem to
75/1200 and hey presto, when the phone
 rings the computer answers on about
the 2nd or 3rd ring. Good huh!
 
So if you wanna start a bb but a bit
short on cash you know what to do cos
uncle pineapple told you so.!!!




   Message # 01636
   **Hacker's section**
   From: PINEAPPLE JOLLY
   To: ALL
   Subject:RTTY'ING
   Date: 18/0/86
do you know anything about radio tele
types for beebs? inc. sw radio with
ssb demod.?




   Message # 01750
   **Hacker's section**
   From: THE SYSOP
   To: ALL HATERS OF BT!
   Subject:SOME BT NODE!??
   Date: 25/5/86
Ok,  I bet U all hate Bt,  Like me!,
well.  Try this number below.  Its
some BT port I think,  havn't tryed it
 yet,    If you don't bring up a
carrier,  It talks to you using a
SP0256 Speech proccessro.
 
01 631 2105..   Tell me what its like.
        ** Dave **




   Message # 01823   (Received)
   **Hacker's section**
   From: THE SYSOP
   To: PINEAPPLE JOLLY
   Subject:Reply to message number 1821

    (SOME BT NODE!??)
   Date: 28/5/86
The Difference between bell and ccitt
is the carriers for each baud rate,
Bt disallow Bell because in somecases
it affects there comms between
exchanges because they use tones near
to that of bell,  but not of ccitt!
    Does that answer your question.
        ** Dave **




   Message # 01824
   **Hacker's section**
   From: DAVID WISDOM
   To: ALL
   Subject:PORTFINDER
   Date: 28/5/86
Hi, has anyonemanaged to write a
portfinder program for their modem
that works??.If so,can u leave me
a message telling me what modem u
r using etc..
          thanks,dave




   Message # 01827   (Received)
   **Hacker's section**
   From: PINEAPPLE JOLLY
   To: THE SYSOP
   Subject:Reply to message number 1823

    (SOME BT NODE!??)
   Date: 28/5/86
I KNOW THAT! What I meant is what is
the difference in the sound a bell
1200/75 and a ccitt 1200/75!  And
anyway, whats the real reason for not
being allowed to use bell in Europe?




   Message # 01843
   **Hacker's section**
   From: PAUL BRADE
   To: ALL
   Subject:OPEN UNIVERSITY
   Date: 29/5/86
Hi..
Why not try  the Open University
Computer in Milton Keynes on:-
(0908) 71188, 300/300 baud. When in
type '?' for a list of commands,
if you then type in 'OPTEL' then I
think the password is '0000000000'
(ten zeros) but I'm not sure.
If you find anything interesting or if
 the 10 zeros work then let us know on
 this board...
              Have fun..Paul.




   Message # 01864
   **Hacker's section**
   From: JEFF GOODWIN
   To: ALL
   Subject:CASPER
   Date: 30/5/86
724 8000 seems to be CASPER, & it
likes an 80 col. display. 300 &
1200/75. It offers a 'demo' with
passwords & ID's but I can't get very
far. See if anyone gets further.
Cheers.......Jeff.




   Message # 01935
   **Hacker's section**
   From: STUART PETERS
   To: EVERYONE
   Subject:GRENDEL
   Date: 1/6/86
 The Gallery             323000174b
 0p919992633
         Grendel (ABBS) access
information       Grendel (ABBS)
access information
                         Number:
Leeds (0532) 620334           Speed:
  1200/75 V23 or 300/300 V21
Protocol: 8 data + 1 stop + No parity
  Terminal: ASCII Scrolling terminal,
              VT100 or 80 col. if
possible  Times:    9.00PM (night) to
9.00AM                (morning) only
please!        Login:    Use usercode:
 GUEST and                 password:
WELCOME             Problems: If you
have problems with
getting in then Mbx me here.
 
 
 
                                    !
 
   1 BACK                    2 FORWARD



   Message # 01936
   **Hacker's section**
   From: STUART PETERS
   To: EVERYONE
   Subject:PSS
   Date: 1/6/86
 The Gallery             323000033e
 0p463231334
        PSS Numbers
 
                          300 baud
1200/75 baud  Aberdeen(0224)  642242
  642484        Birmingham(021)
2145139   2146191       Bristol(0272)
  216411    216511
Cambridge(0223) 82511     82411
  Edinburgh(031)  3379141   3379121
    Glasgow(041)    2042011   2042031
      Leeds(0532)     470711    470611
        London(01)      8259421
4078344                       9289111
  9283399       Luton(0582)     8181
    8191          Manchster(061)
8330242   8330091
 
 
                              key _ to
 continue
                                    1




   Message # 01938
   **Hacker's section**
   From: STUART PETERS
   To: EVERYONE
   Subject:COMPUNET
   Date: 1/6/86
 The Gallery             323000033f
 0p463231334
        Compunet Numbers
 
          Andover(0264)      3444
            Birmingham(021)    6435201
              Bristol(0272)
277678               Edinburgh(031)
  3433475              Glasgow(041)
    3320173              Leeds(0532)
      454636               London(01)
        6371422
          4821000
uton(0582)        452989
  Newcastle(0632)    615537
    Leicester(0509)    508961
      Warrington(0925)   827575
 
 




   Message # 01939
   **Hacker's section**
   From: STUART PETERS
   To: EVERYONE
   Subject:BB'S
   Date: 1/6/86
Following I've just heard of, but they
 may not be too good...
Patnet - COLCHESTER (0206) 867134
Betelguese Five - (300/300) 0463
231339 (10pm-9am)
Honeywell Themis - 0482 869184 24hrs
IBM :-North London 01 995 7821
      South London 01 928 0660
      Manchester   061 969 381
 More as I find them....Stu.




   Message # 02125
   **Hacker's section**
   From: HUGO FIENNES
   To: PINEAPPLE JOLLY
   Subject:Reply to message number 1949

    (HACKING)
   Date: 12/6/86
OH COME ON...system X is no more
diffcult than any US system!!!
All it is is a bunch of micros...and
some a/d d/a bits...how about the
phone
number for that one then....redirect
calls,disconnect them....intercept
call{,etc......hehehehe!
 
/// The Captain ///




   Message # 02210
   **Hacker's section**
   From: JOHN RAYFIELD
   To: EVERYONE
   Subject:NUMBERS
   Date: 18/6/86
Here is a repeat of Stuarts msg
with the lines tidyed up:
   Message # 01936
   From: STUART PETERS
   To: EVERYONE
   Subject:PSS
   Date: 1/6/86
 
        PSS Numbers
 
 
               300      1200/75
Aberdeen(0224)  642242     642484
Birmingham(021) 2145139   2146191
Bristol(0272)   216411    216511
Cambridge(0223) 82511     82411
Edinburgh(031)  3379141   3379121
Glasgow(041)    2042011   2042031
Leeds(0532)     470711    470611
London(01)      8259421   4078344
                9289111   9283399
Luton(0582)     8181      8191
Manchster(061)  8330242   8330091
 



   Message # 02211
   **Hacker's section**
   From: JOHN RAYFIELD
   To: EVERYONE
   Subject:MORE NUMBERS
   Date: 18/6/86
Here is another msg from
Stuart,tidyed up:
   Message # 01938
   From: STUART PETERS
   To: EVERYONE
   Subject:COMPUNET
   Date: 1/6/86
 
        Compunet Numbers
 
 
Andover(0264)      3444
Birmingham(021)    6435201
Bristol(0272)      277678
Edinburgh(031)     3433475
Glasgow(041)       3320173
Leeds(0532)        454636
London(01)         6371422
 
                   4821000
Luton(0582)        452989
Newcastle(0632)    615537
Leicester(0509)    508961
Warrington(0925)   827575



   Message # 02216
   **Hacker's section**
   From: Mr Anon
   To: ALL
   Subject:HOT INFO
   Date: 18/6/86
There is some hot info on the Beeb
music section go to it and check it
out leave a message and you wont be
sorry! Rock me! I am Vk{ if you dont
I cut you with mesh!
 
 
Try it cos Im rockin the line go there
now and youll die happily and
peacefully, if you dont youll die a
dead man!




   Message # 02225
   **Hacker's section**
   From: DAVID WISDOM
   To: ALL
   Subject:MILNET
   Date: 18/6/86
 Has anyone on this board heard of
MILNET??  if so could u please contact
 me
        thanx




   Message # 02375
   **Hacker's section**
   From: SEAN WITHAM
   To: ALL
   Subject:SHADES
   Date: 26/6/86
SHADES IS A NEW VERSION OF M.U.D ,I
HEAR CRIES OF NOT THAT SLOW THING,WELL
 THIS ONE HAS A VERY FAST ,ALL MOST
INSTANT REPLY SYSTEM.BUT AS NORMAL
THRE IS A CATCH THERE ARE ONLY THREE
LINES BUT THE GAME IS FREE WITH FAR
MORE INTERACTIVE COMMANDS BETWEEN
PLAYERS INCLUDING BODY LANGUAGE ,YOU
CAN SOB , CRY BLUSH ETC. FIND OUT WHO
IS PLAYING CAST SUMMON SPELLS THER ARE
 FIND SPELLS ETC..ALL IN ALL IT LOOKS
VERY PROMISING BUT IT STILL BEING
DEVELOPED SO NOT EVRYWHERE IS
READY.THOUGH THERE ARE STILL LOTS OF
MOBILES,I MEAN LOTS, AND THERE ARE NO
GAME CHARGES.THE NO. IS
                      0342810905(NEAR
GATWICK)  AND USE PRESTEL DATA BITS ON
,AND BUAD RATES,A NORMAL 80 COLUMN
DISPLAY NOT VIEW DATA.I TRIED TO LOG
ON TODAY BUT THERE WAS NO ANSWER IF
ANYONE CAN TELL ME WHY PLEASE DO.HAPPY
 HUNTING RADRIC.




   Message # 02416   (Received)
   **Hacker's section**
   From: LEGAL EAGLE
   To: SEAN WITHAM
   Subject:Reply to message number 2375

    (SHADES)
   Date: 29/6/86
Hi sean, as a seasoned (almost) player
 I think I can comment on your msg.
The reason the phone did not answer
was because the system is still being
developed and so it goes down once in
a while. A NOTE for all players, Once
you are sure of yourself then attack
the mobiles with a weapon but NEVER
NEVER attack the suit of amour or the
Bear, the are lethal. I was an
Enchanter with about 40,000 points
when i got killed by the Bear, I got
back to Enchanter only to be killed
again but never mind....
The mobiles become very strong at
about 3.00 in the morning, but im not
sure why, but it only lasts about one
hour.
If anyone wants a hint on what to do
with an objcect, the brick or rope Etc
 then ill be pleased to give cryptic
hints, so far as I can..
P.S. if you havnt been in then all i
can say is start dialing NOW!!!!



   Message # 02537
   **Hacker's section**
   From: DAVID WISDOM
   To: ALL
   Subject:HELP
   Date: 8/7/86
 Does anyone know what type of system
this is:
     MILLON TAC 112#:12
 If so could you please contact me
         thanx
          Dave the Brave




   Message # 02557
   **Hacker's section**
   From: HUGO FIENNES
   To: ALL
   Subject:BBS
   Date: 8/7/86
Phreak C P U - 04 584 7608
1200/75 and 300/300 10pm-8am




   Message # 02591
   **Hacker's section**
   From: DAVID WISDOM
   To: ALL
   Subject:IBM'S
   Date: 13/7/86
 does anybody know any operator
commands for an IBM VM 370 SJ or SJX?




   Message # 02788
   **Hacker's section**
   From: MC SPINE
   To: ALL DAMN HACKERS
   Subject:HACKING OF DAMN COURSE
   Date: 11/8/86
This is MC SPINE rocking the line!
Check this out super listeners!
If you call 631 2105 and wait till
after the recorded message youll be
amazed at what you hear! Gosh! Oh
yes....
 
british oxygen on pss is A275312212
the times network on PiSS is:
NUI? NTIMESN208CZY
ADD? A21230021001
type in LOGIN
then TCD100042
then pw is TTNS! Have fun
 
erm. what have you got to show for
yourself! Feeble earthing, you cant
rap and you cant hack!




   Message # 02950
   **Hacker's section**
   From: JOHN RAYFIELD
   To: EVERYONE
   Subject:BRAINBOX BOARD UPDATE
   Date: 21/8/86
  BRAINBOX BOARD UPDATE
    ------------------
 
As from 18:00 on 22/08/86 this board
will be on auto-answer!!!
 
There is a fair bit on the board right
 now,but we need you out there to
leave som msgs.!!!
 
The times are :
 
 Mon - Fri : 00:00 - 09:00
             18:00 - 00:00
 Sat - Sun   24 hrs
 
Tel # is : 0622-76928 (Maidstone)
 
Software Upload/Download coming
soon,ring board for details
 
Regards     J.R.




   Message # 02992
   **Hacker's section**
   From: RICHARD ELLS
   To: ALL
   Subject:HACKING
   Date: 27/8/86
SOME NUMBERS .. SEEBOARD I THINK.
01 248 0964 VIEWDATA
090339944 VIIIE
96460775 V/DATA
BULLITEN BOARD .. 060532949




   Message # 03048
   **Hacker's section**
   From: JASON BRYANT
   To: EVERYONE
   Subject:HACKER
   Date: 30/8/86
YEAH,GREAT!
GOT ANY PRESTEL CODES TO SWAP???
SEEE YAAAAAA




   Message # 03050
   ****
   From: RICHARD ELLS
   To: ALL
   Subject:SEX
   Date: 30/8/86
Help!!!!
  I am in desperate need of the above
subject!!!
anybody female who is (mad enough)
interested should contact:
      A doctor Imediately!!!!!!




   Message # 03181   (Received)
   ****
   From: ANDY THORPE
   To: KEITH ANDERSON
   Subject:Reply to message number 3153

    (SEX)
   Date: 17/9/86
BB's and prestel... Land of the
no-hopers, poofs, and other abnormal
folk, including myself... (SEE! - AT
LEAST I'M HONEST!)
 Andy.




   Message # 03264   (Received)
   ****
   From: JULIAN ANDERSON
   To: KEITH ANDERSON
   Subject:Reply to message number 3250

    (SEX)
   Date: 29/9/86
A agreee that bloke is an utter
creap..
Julian.




   Message # 03346   (Received)
   ****
   From: ANDY THORPE
   To: JULIAN ANDERSON
   Subject:Reply to message number 3342

    (SEX)
   Date: 2/11/86
Fair enough.




   Message # 03568
   **Hacker's section**
   From: JOHN RAYFIELD
   To: EVERYONE
   Subject:BRAINBOX
   Date: 15/12/86
Hi everyone,The BRAINBOX board is now
running XRAS software.The details are:
 
300/300 buad   phone: 0622-76928
 
00:00-09:00 &Rj=9I%
24hrs sat-sun
 
Board runs most days,except when
software is being updated!!!!
 
Reagards    John Rayfield




   Message # 03695
   **Hacker's section**
   From: Mr Anon
   To: ALL
   Subject:TRY THIS
   Date: 14/1/86
    ABTA.....6818535
    BARIC....8441401




   Message # 03848
   **Hacker's section**
   From: KEVIN DIXON
   To: EVERYONE
   Subject:HCKING?
   Date: 1/5/87
Try this number on 300/300 8N1
0908 71188
I don't know what it is ,but any
hacks in it greatly received!!
DiKo




   Message # 03863
   **Hacker's section**    (Redrctd)
   From: KEVIN DELL
   To: MC SPINE
   Subject:Reply to message number 1577

    (AUTO ANSWER)
   Date: 8/5/87
GOOD TO HEAR THAT SOMBODY CAN HELP ME,
 BUT HOW DO YOU DO IT? PLEASE LET ME
KNOW. ONLY THING IS I'VE GOT A DEMON
MODEM. DOES THIS MAKE ANY DIFFERENCE?
TTFN
KEVIN




   Message # 03875
   **Hacker's section**
   From: HACKER'S APPRENTICE
   To: ALL
   Subject:HACKING
   Date: 21/5/87
ANYONE WANNA GET INTO THE EUROPEAN
SPACE AGENCY COMPUTER WELL HERE'S THE
NUMBER 630-9466 1200/75 BAUD
IBM BELFAST 0232-245124 ACCOUNT
01811111 PW 11111 TRY PAGES *2 *20000
*40000 *50000 *100000
ISTEL 061-941-5111
HOPE THE NUMBER'S ARE USEFULL IF
YOU'VE GOT ANY YOU WANT TO SWAP
CONTACT ME ON THIS BOARD OR DRAGON'S
LAIR
BYE!!!!



   No More Messages Here.
   <R>ead more here
   <A>bort            A



   Returning to previous Menu..

