Found: PSAT'S ARE OVER
Msg left by:
Posted: SAT OCT 20 11:48:52 AM

THE PSAT'S ARE OVER!!!!  NOW ALL THE JUNIORS CAN RELAX AGAIN.  NOW THATTHIS
IMPORTANT TEST IS OUT OF THE WAY I HAVE A QUESTION FOR YOU.  CAN SOMEONE PROVE
THE SYSOP OF THIS BOARD IS ALIVE?  HE NEVER ANSWERS FEEDBACK OR LEAVES COMMENTS
AND I KNOW I AM BEGINNING TO WONDER IF HE IS STILL AMONG US.  IF ANYONE KNOWS
HIS CONDITION, PLEASE INFORM THE REST OF US

			     THE ARROW


Found: WAY TO GO MCP!
Msg left by: THE WIZARD
Posted: SAT OCT 20  3:26:37 AM

WAY TO GO MCP!!!!!

ALL OF US ON THE HOJ'S SO CALLED 'HITLIST' SHOULD GET TOGETHER AND SQUASH THOSE
CARTOON FAGGOTS INTO THE DIRT!	BEING ON THEIR HITLIST DOESN'T SCARE ME IN THE
LEAST!	THEY MAY KNOW MY #, BUT THEN, ALMOST EVERYONE DOES, AND I DON'T MIND!
THEY'LL *NEVER* FIND OUT WHERE I LIVE, THAT'S FOR DAMN SURE!!!!!

HOJ, GO FUCK YOURSELVES!!!!!

KEEP ON PHREAKIN'!
<< THE WIZARD >>
* THE ONE AND ONLY! *


Found: TONES FOR C-64
Msg left by: SECRET SQUIRREL
Posted: SAT OCT 20  3:58:21 AM



hey people,
a few messages back some one aske d for some info on how to get a number of
frequencys out of the c-64.  i.e.  260 0hz.
i wrote a program that gives you the pokes needed for any tone you would car e
to have for any reason.  it is not very long (about 40 lines or so ).  if any
one is instrested in it, leave me word in E-mail.

		    happy pheaking

	   ><><><><><><><><><><><><
	   ><			 ><
	   ><  SECRET		 ><
	   ><			 ><
	   ><		SQUIRREL ><
	   ><			 ><
	   ><><><><><><><><><><><><
/ex


Found: POSTIT
Msg left by: THE SERPENT
Posted: SAT OCT 20  5:52:45 AM

If it isn't that long, take a couple
of messages and post it please.

		  The Serpent

<< The Anarchist Triangle >>


Found: COUPLE OF THINGS
Msg left by: THE SERPENT
Posted: SAT OCT 20  5:55:39 AM

You know the old recording you get from 914-359-9901 and a few other prefixes?
Well you don't get the same recording in EVERY prefix, found one.

914-654-9901 goes like this

"You have reached code 654 in area code 914"
weird huh?
what about this!?
914-654-9972 Answers, then makes lots of clicks.



		       The Serpent

<< The Anarchist Triangle >>


Found: ANOTHER!
Msg left by: THE SERPENT
Posted: SAT OCT 20  5:57:30 AM

Another one!  914-528-9901

"Your call requires a 25c deposit...etc"


Found: VERY INTERESTING SHIT!
Msg left by: THE SERPENT
Posted: SAT OCT 20  7:55:17 AM

914-232-9901

RECORDING SAYS
"NINE-ONE-FOUR..TWO-THREE-TWO..KATONA(SP),NEW YORK..
PMS ONE HUNDERED, VERIFICATION"
		  ^^KEY WORD, WHAT THE
		  HELL IS THIS, CAN SOMEONE
		  TELL US?


		  THE SERPENT

<< THE ANARCHIST TRIANGLE >>


Found: SORRY.I MADE AN ERR
Msg left by: THE SERPENT
Posted: SAT OCT 20  8:18:19 AM

I just read Bioc's Telcom II and thats DMS100 not PMS100.  But I would still
like to know what KIND of verification is it and why is it there?

		   The Serpent

Incidentally, DMS100 is the type of equipment, this is briefly explained in
Bioc's file, found the Phreak I section in general files on this system.

<< The Anarchist Triangle >>


Found: TO SIMON AND ALL OTHERS
Msg left by: THE SILVER SABRE
Posted: SAT OCT 20 10:41:15 AM

QUESTION:
"WHAT HAPPENED TO PICC NET, TSS?"

ANSWER:
HOW MANY OF YOU ELITES REMEMBER THE PRIVATE BBS 'THE INNER SANCTUM'?  SIMON,
YOU SHOULD.  REMEMBER CRYPTO CRIMINAL, THE SYSOP.  WELL I HOPE YOU HEARD ABOUT
HIM AND ALL THE THINGS THAT HAPPENED..	ANYWAYS, PICC-NET IS GOING TO CHANGE TO
THE PRIVATE INNER SANCTUM.  SHARP RAZOR IS THE RECRUITER AND REMOTE SYSOP.  AND
IT WILL BE JAMMED WITH INFO ........  SO YOU WILL BE GETTING A CALL SOON IF YOU
WERE ON THE OLD SYSTEM AND YOU BE A USER ON MINE.
=======================================
TO THE "HALL OF JUSTICE", PLEASE DON'T DO ANYTHING HARSH TO ME!  I ALWAYS
SCARED OF THE HALL OF JUSTICE, WE MUSNT BETRAY THEM FELLAS!!  I KNOW I AM A
GEEK, AND I HAVE NO KNOWLEDGE OF PHREAKING (IS THAT WHAT IT IS CALLED?) I WISH
I COULD BE A MEMBER OF YOUR CLUB !!!!!!  I ADMIRE YOU H.O.J.!!
=======================================

IF YOU BELEIVE THAT YOU ARE ALREADY A MEMBER OF HOJ OR SHOULD BE!

FUCK OFF HALL OF JUSTICE!

YOU REALLY MUST WANT TO GET SOME ATTENTION, OR ELSE YOU ARE 10-12 YEARS OLD!

WHATCHA GONNA DO?  DO A CNA ON ME OR SOMETHING?  YOU CAN'T DO MUCH MORE THAN
PUST ME ON YOUR STUPID "HIT-LIST!" LATER..  TSS

Found: TO ALL
Msg left by: Anonymous
Posted: SAT OCT 20 10:20:13 PM


TO ALL,

I THINK THAT U ALL SUCK SHIT.
U CANT FREAK 4 SHIT.
U POST ABOUT BULLSHIT.
ALSO U DONT NOE WHAT U R TALKING ABOUT.

SO FUCK OFF.

       "ANONYMOUS"
	---------
	   ^^

HA HA HA HA HA HA
HA HA HA HA HA HA

HM SUX
BN SUX
U ALL SUCK

/W


Found: I AM SO PISSED!!!!!!


Msg left by: THE HACKMAN
Posted: SUN OCT 21  1:00:39 AM

I AM SO PHUCKING PISSED OF!!!!!!!!  I CAN'T HANDLE SHIT LIKE THE LAST
MSG.!!!!!!  I AM GONNA' TRY TO GET THE SYSOP TO DELETE IT!!!!!!!  AND THE
PHUCKING HALL OF JUSTICE ZS GONNA' DIE!!!!!  YOU HAVE PUSHED AND PUSHED AND NOW
YER' DEAD!!!!!!!  OR AT LEAST I AM GONNA' TRY(WITH A HELL OF A LOTTA'
HELP)!!!!!  AND IF I AM AS GOOD AS DEAD DO SOMETHING!!!I AM WAITING!!!!!!!!!!
JESUS THIS BOARD IS GETTING RUINED BY THEM,THOUGH SOME RAD DUDES LIKE SHARP
RAZOR AND OTHERS HAVE KEPT IT COOL!!!!!!!!!!!!!!!!!!!!!!!  SORRY IF YA' DIDN'T
WANNA' READ IT YA' COULD ALWAYS SMACK THE BAR TO SPLIT!!!
LATERON,
---->THE<----
-->HACKMAN<--



Msg left by: SECRET SQUIRREL
Posted: SUN OCT 21  2:52:42 AM


hey people,
Hackman is right there is to much of this shit on this board.  what ever
happened unity and cooparation?!  let turn are efforts back to pheaking..


here are a few newly hacked codes to ge t people back to what they should be
doing!!!!!

	 <800-255-2255>

	  692146
	  692165
	  692191

these codes may have a little noise now and then but there are great for voice
and not bad for carries (i am usi ng on now).


		    later,


	    ><><><><><><><><><><><><
	    ><			  ><
	    ><	SECRET		  ><
	    ><			  ><
	    ><		SQUIRREL  >>
	    ><			  ><
	    ><~<><><><><><><><><><><

p.s.  i will post the tone finder next time i log on , i am out of time now.



Found: MORE NEWSNET
Msg left by: PRINCE TANA
Posted: SAT OCT 20  5:21:55 AM

Well I Havent tried it yet but if the Newsnet Pass 'SHRWD2' Works, then whoever
changed it in the first place decided to share with the rest of you.  Glad to
see it working.  The Newsnet Pass 'Phreak' Did not work because I Havent set it
as that yet.  It Will work tommorow.  I Still have Publisher Accts for Newsnet
if anyboby wants them, Ill trade for Box Info (Dialing....) I Also Still have
Coompuserve Accts (Starter Kits) Which I will Also trade for Box Info.

SYSOP:	Hows about G-2 Access so I can read all those nifty Articles Agent 003
mentioned in his Telcomm stuff?

Bye!
Prince Tana
    of
  Marik

Send E-Mail to: First> Prince
		 Last> Tana


Found: D/FW AIRPORT SCANNING
Msg left by: THE SILVER SABRE
Posted: SAT OCT 20 10:45:56 AM

DALLAS/ FT. WORTH AIRPORT
-------------------------
SCANNING:  817-456 XXXX
[][][][][][][][][][][][][][][][][][][][
GET ON THE SABRE SYSTEM AND HELP ME GET
THRU!

TRY IT! ALSO, THERE IS A PREFIX THAT
HAS THE COSMOS DIAL-UP.

817 787 XXXX.

FOUND PRETTY LAME CEPT FOR THE COSMOS.
ALL THE LOCAL RADIO STATIONS HAVE THE
787 PREFIX, BUT THERE WAS ONLY THAT
ONE COMPUTER.

LATER ALL..

T/S/S


Found: WIERD CARRIERS
Msg left by: Anonymous
Posted: SAT OCT 20  2:48:03 PM

WE HAVE BEEN SCANNING THE (405)799-XXXX
AND FOUND THE FOLLOWING WIERD CARRIERS:

    799-0931 (GIVER A CARRIER BUT
		 THE CARRIER DISCONECTS
		 WHILE THE PHONE IS
		 STILL OFF HOOK ON
		 THEIR END)
       799-1046 CONNECTS BUT NO DATA
		RECEIVED.
       799-1799 SAME AS 799-0931
       799-2021 CONNECTS AND SENDS
		SOMETHING...

WE HAVE A 300 BAUD MODEM, SO IF ANY OF THESE ARE 1200 BAUD, WE DON'T KNOW.
LEAVE MAIL TO DOCTOR JEFF IF YOU FIND OUT ANYTHING.  THANX.


Found: HELP NEEDED!!
Msg left by: THE ARTFUL ARMADILLO
Posted: SAT OCT 20  9:27:34 PM

O ANYONE, I LIVE IN THE 914-462 AREA CODE.  I NEED A WAY TO PHREAK ONTO THIS
BBS.  I HAVE BEEN USING 1-800-322-1415 BUT IT DOESN'T SEEM TO WORK FOR BBS (IT
DOES WORK FOR VOICE) I CAN GET THE CARRIER TONE BUT WHEN I FLIP THE SWITCH ON
MY COMPUTER THE COMPUTER DOESN'T RESPOND.  CAN ANYONE GIVE ME SOME NEW #'S &
CODZ THAT WORK AND ARE SAFE.  ALSO, CAN ANYONE GIVE ME ANY INFO ON THE TAP
MAGAZINE?

THANX

/EX



Found: HEY PHUCK UP!!!!!!
Msg left by: THE HACKMAN
Posted: SUN OCT 21  1:06:03 AM

DUMBDUMBDUMBDUMBDUMB!!!!
THE 415-327-5220 ARPANET DIAL-UP
WORKS AGAIN YOU DICKHEAD!!!!
USE IT WELL FELLOW HACKERS!!!!!
LATERON,
---->THE<----
-->HACKMAN<--



Found: MICRO MAFIA WANTS YOU!!
Msg left by: PETER GUNN
Posted: SAT OCT 20 12:56:57 PM

      TO ALL:

STILL SOME SPOTS LEFT.	THE MIC RO MAFIA IS GROWING EVERYDAY.  JOIN NOW!
CONTACT CAP'N BYTE, DARK KNIGHT OR M E.  LEAVE YOUR ADDRESS TO GET YOUR FREE
NEWS LETTER....  JOIN UP NOW ........




	   PETER GUNN ----------><
	  (THE MICRO MAFIA -----><

/EX


Found: I ROCK IT
Msg left by: THE LOAN SHARK
Posted: SAT OCT 20 10:12:31 PM

--------
  =
  =
  =
------- GOT ALL THE LATEST WARES DUDEZ.
	MEBLES MAINSION,MONTEZUMAS REVNEGE
	EARTHLY DELIGHT.

LATER0N
-------

THE LOAN SHARK




Found: POGO CURRENT WARES
Msg left by: POGO JOE
Posted: SAT OCT 20  8:56:45 AM

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C OK:				      C
C				      C
C      I got some of those wares I    C
C promised.  They are:		      C
C				      C
C	    Tapper		      C
C	  Spy vs Spy		      C
C				      C
C Short Review of each: 	      C
C				      C
C TAPPER:			      C
C ------			      C
This is a very close adaption from the arcade.	There are only a few flaws,
which is very good, since the arcade is a top quality game.  The flaws are:
The background isn't as detailed as the arcade, and the drinkers have to finish
their beer before you can serve them another.  All you arcade addicts won't be
dissapointed, it has every board including the punk rock and the space bar.  C
C				      C
C Spy vs Spy:			      C
C ----------			      C
C This game has nice graphics, nice   C
C music, and is slightly complex.  I  C
C haven't played it a lot, so I do    C
C not have it entirely figured out.   C
C I will write another review when    C
C I find out more.		      C
C				      C
C Luego,			      C
C				      C
C Pogo Joe			      C
C (312) 537-3052		      C
C Ask for Jeff. 		      C
C				      C
C --- Boing --- 		      C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC



Found: WIZ CHEATER


Msg left by: PETER GUNN
Posted: SAT OCT 20  6:55:42 PM

      TO ALL WIZARDRY NUTS:

I HAVE A PROGRAM THAT LETS YOU CHEAT ON WIZ II.  YOU CAN THEN MOVE YOU R
CHARACTERS ACORDINGLY.

	  ANOTHER TRICK: ITS PRETTY OLD

       ON WIZ I:

1 MAKE A BISHOP
2 TAKE HIM IN THE DUNGEON
3 WHILE IN CAMP. IDENTIFY ITEM #9
4 THERE IS NO 9
5 KEEP TRYING UNTIL SUCCUSESFUL
6 THEN YOU GET A MILLON EXP.

      GO BACK TO HOTEL AND GAIN LEVELS!



	  HAPPY ADVENTURING!!!!!!!

	   PETER GUNN -------><
	  (THE MICRO MAFIA --><



Found: NEW SYSTEM
Msg left by: DELTA-MASTER
Posted: SAT OCT 20  9:39:39 PM

OK, THERE IS A NEW BOARD(KIND OF) OPEENING.
RIGHT NOW IT IS A CHAT WITH THE SYSOP,DELTA-MASTER, it also lets you access
disk files on my disk. I will have up g-philes,codes,and some games.
also if anyone has a cool bbs program send me mail an i will trade
phor it.
it's no is
914-337-5830
it runs between 9pm and 7 am.

DELTA-MASTER
BX-00-HACKERS
THE DRAGON CLAN
PHK
LTD SOFTWARE
FOUNDER OF PHK,BX-00-HACKERS,&TRADE-A-LOT!
TRADE-A-LOT
/EX
I NEW THAT


Found: NIGGER
Msg left by: THE SPOILER
Posted: SAT OCT 20  3:38:21 PM

what do you call a black lady with braces?

	 a black and decker
	       pecker wrecker



Found: TO CALAFAG
Msg left by: Anonymous
Posted: SAT OCT 20  1:02:51 PM

CALIFORNA IS FOR THE QUEERS!!  YOU FAGS WEAR EARINGS IN RIGHT EAR S.  THAT
PROVES YOU ARE A FAG....  BY THE I HOPE YOU CATCH AIDS YOU LITTLE FAG FUCKER
PIN DICK.  YOU COULDN 'T GET TRIM FROM YOUR DINNER!!!!!!


FUCK YOU # 22 WHY DO YOU CALL A NY BOARD NO GOOD B B'S IN GAY LAND ONLY COCK
SUCKERS!!!


Found: BUSH???
Msg left by: Anonymous
Posted: SAT OCT 20  5:34:46 PM

You think Mondale should take on Bush????  Nonsense..  Bush really scares me...
I wouldn't want to be around if he was president..  He talks like one of those
"Sunday morning TV Preachers"...  He would be for people like Jerry Farwell,
even more than Ronnie!	His views are like those of Reagan's, only he is
insecure, and would act with bursts of rash judgement..  If I were you, I'd
take back that statement..

A Federalist !
= ========== =



Found: TO-------33


Msg left by: PETER GUNN
Posted: SAT OCT 20  6:46:31 PM
NOW DONT GET ME WRONG #33.  FERRARO WAS NO GOOD AT THAT DEBATE.  SHE COULDN'T
KNOW WHAT ITS LIKE TO WANT PEACE.  SHE HAS NEVER SIRVED IN THE MILITA RY.  SHE
IS NOT A GOOD SPEAKER AND IS A A LOSER WITH IRS!!!  HER MOTHER BOOTLEG S BOOS.
TAKE OFF YOU HOSER!!!!!!  BUSH MAY BE NOT THE BEST MAN FOR THE JOB.  BUT HE IS
A MAN!!!!!

	   PETER GUNN -------><
	  (THE MICRO MAFIA --><
