Q
 
)=-> Quick-Scan <=-(

 <M>ulti,[T]his board (General)
 )=->M

Start Board  [1-31] )=->1

  End Board  [1-31] )=->33

Quick-Scan From General to Elite Phreak
Express Scan Mode? [Y] <N> ->Y

General board
 status: 104 blocks. Please wait...

  Please post!!

Found: /\] THE OCTAGON [/\


Msg left by: THE BULLET
Posted: SAT NOV 17  9:51:55 AM

..................IS FINALLY BACK!
 
AND AT A NEW NUMBER......YOU MUST CALL
 
 
.........../ THE OCTAGON \.............
 
       4 1 5 - 8 6 5 - 6 0 1 2
 
         THE OCTAGON PROMPTLY
          AWAITS YOUR CALL...
 
SEE YOU IN THE DARKNESS.....
415-865-6012
SYSOP: THE ROCKER
 
OTHERWISE KNOWN AS THE BULLET
T/R
OR
T/B


Found: MODEM FOR SALE


Msg left by: STAR SAPHIRE
Posted: SAT NOV 17  1:30:49 PM

O ALL,
       MY NAME IS JORDAN SPARER
ANYONE INTERESTED IN BUYING A
TRS-80 ACOUSTIC COUPLER MODEM
IM SELLIN MINE FOR ONLY $100.00
IT INCLUDES ALL CABLES,2 TERMINAL PROGR
AMS, AND 2 CASSETTER GAMES
IF YOU WERE TO BUY ALL THAT IN
A STORE IT WOULD COST ALMOST
$250.00 NOW YOU CAN GET IT
FOR ONLY $100.00 THE MODEM IS
IN MINT CONDITION. IT WAS 
USED ONLY 4-5 AT THE MOST
THE REASON IM SELLING IS I
NEED A AUTO/ANSWER MODEM
SO EITHER LEAVE ME E-MAIL OR
CALL ME AT 623-2104 ASK FOR
ME(JORDAN SPARER) ILL BE GLAD
TO ANSWER ANY QUESTIONS ABOUT
THE TRS-80 ACOUSTIC COUPLER MODEM
THANK YOU.
            JORDAN SPARER
 



Phreak/General board
 status: 103 blocks. Please wait...

  Please post!!

Found: STRANGE XTENDER


Msg left by: THE SERPENT
Posted: SAT NOV 17  3:43:32 AM

1-800-942-7111
THE CODE IS 83
 
ITS A 1+ SYSTEM SO TO DIAL YOU
DIAL 1=AC=LOCAL NUMBER
TO DIAL ANYTHING IN 312 JUST DIAL
THE 7 DIGIT NUMBER.
 
                  The Serpent
 


Found: BLUE BOXED


Msg left by: THE MYSTERY
Posted: SAT NOV 17  4:39:43 AM

 
I meant to say 'BLUE BOXES'.. Oh well
 
 
I have the Osuny Plans, and I also have the schematics too (yeah!) but
the plans are still a little complicated, and I think it would be better
to make your own box (with your own plans)...
 
I have made a Blue Box using the LM3909 Led Flasher/Oscillator and
so far it works fine, But, i don't have the plans in a text file yet,
the osuny file looks ok, but it seems too complicated (like I said before)..
Anyway, when you get good plans (you get something like a tone generator
mthat can make tones from 700hz to 2600hz and not go off freqency) you
can make a simple Blue Box, look in Radio Shack's book: Engineer's Notebook
][ for a bunch of different tone-generators that can be tuned in to make
almost any freq.
 
When you do, go get a freq. counter and measure the resistances with it
, and get fixed resistors withthe same amount of Ohms.....
 
Then hook switches up so when you press a switch, it goes to that resistor
(for MF tones you have to buld two, and use a double-pole switch so that
when you press the button it will go to both of the oscillators.)
 
Whatever
 
 
I hope this helps some of you in your quest to make a BB....
 
 
/a

 
 
     (=-%> The Mystery
 
        (=-*> Cat HAckers
 
 
          (=-*>  Call The Awesome Cat's Den!!! 617/655-8935 <*-=)


Phreak/Computers board
 status: 104 blocks. Please wait...

  Please post!!

Apple Pirate board
 status: 104 blocks. Please wait...

  Please post!!

Found: ALL THE LATEST...


Msg left by: THE BULLET
Posted: SAT NOV 17  9:55:20 AM

IF YOU LIKE THOSE WAREZ CALL:
 
415-865-6012
 
LOG ON
CHAT
TRADE
 
THE BULLET/NEON KNIGHTS


Found: PENGUIN STUFF


Msg left by: CAP'N BYTE
Posted: SAT NOV 17 10:51:57 AM

DUDES....PLEEEAAASSEEE SEND ME E-MAIL IF U HAVE ANY OF THE NEW 
GAMES FROM PENGUIN SOFTWARE....THESE INCLUDE:
 
XYPHUS
 
 
 
AND
 
 
 
CAT GRAPHICS
 
(I HAVE EXPEDITION AMAZON IF ANY ONE WANTZ IT!)
 
 


Found: )-(WOLF WAREZ)-(


Msg left by: IRON WOLF
Posted: SAT NOV 17  1:16:46 PM

 
THE LATEST->
 
 AGENT:USA
 TIME SHIP
 DOUBLE FEATUZE
 TIMES SQUARE CROSSWORD
 
ALL THE REST!!! 