FOUND: COPYING RDF1985
MSG LEFT BY: PETER GUNN
POSTED: SUN OCT 07 12:38:04 PM

***************************************
*      TO ALL,			      *
*	  HERE IS HOW TO COPY RDF 198 *
* 5 BY SSI			      *
*	 1) RUN NIBBLES AWAY II       *
*	 2) RUN THE SECTOR/TRACK EDIT *
* OR				      *
*	 3) TURN OFF THE CHECKSUM AND *
* USE THE FORMAT 13		      *
*	 4) THE LISTING OF TRACK 11:  *
*      B5 4A D8 8A		      *
*   1  58 38 AF 33		      *
*   2  84 A8 8D 7E		      *
*   3  E8 B6 70 5C		      *
*   4  E4 F0 F0 A8		      *
*   5  E5 A0 08 A6		      *
*   6  93 FC 7F 6B		      *
*   7  57 5F 14 2C		      *
*   8  7F 87 D8 AC		      *
*   9  0B 09 A6 15		      *
*				      *
*	 5) USE THE ADDRES MARKS:     *
*	     D5 AA B5		      *
*	 6) COPYIT!!!!		      *
*				      *
*	   I HOLD NO RESPONSIBLITY FO *
* R DAMAGE TO ORAGINAL....	      *
*				      *
*	    PRESENTED BY	      *
*	    <=PETER GUNN=>	      *
***************************************


FOUND: CRACK FSII?
MSG LEFT BY: ULYSSES
POSTED: SUN OCT 07  3:22:07 PM

  DOES ANYONE KNOW HOW TO CRACK OR COPY FSII I CANT PLEASE SAY HOW ULYSSES


FOUND: C-64 SOFTWARE
MSG LEFT BY: X-MAN
POSTED: SUN OCT 07  5:14:15 PM

Here is some new software that I have
recently obtained:


Crisis Mountain
Blueprint
Impossible Mission
Adept (Archon ][)
Alligata Blagger
Boulderdash
Pitfall ][
Pharoah's Hunter

and much more. (All of above except
Boulderdash cracked). Please leave
E-Mail if interested in a trade.

	    X-Man
       The Legion Of Doom!


FOUND: HAYES 300 TERMINAL
MSG LEFT BY: X-MAN
POSTED: SUN OCT 07  5:19:00 PM

  I really need a terminal program for the Hayes Smartmodem 300, which will
dial DTMF as well as pulse dialing.  I will trade a lot of good software, so if
someone has what I need, or knows someone who can get it, please send me
E-Mail/

	    X-Man
       The Legion Of Doom!


FOUND: C-64 STUFF
MSG LEFT BY: BLUE BEARD
POSTED: SUN OCT 07  6:14:11 PM

ALL:
   ANYONE OUT THERE:

DO ANY OF YOU (MAINLY C-64ER'S) KNOW OR HAVE A 'WAR GAMES' DIALER.

    I HAD ONE BUT LOST IT (SCRATHED)

    I WILL TRADE ANYTHING FOR IT.

    PLEASE LET ME KNOW IF YOU CAN HELP ME OUT.




THX.

	     BLUE BEARD





FOUND: FOR SALE
MSG LEFT BY: JOHN DE LELLO
POSTED: SUN OCT 07  7:05:06 PM

  FOR SALE!! I HAVE A 2 YEAR OLD COMPOUND ARCHERY BOW I OUT GREW.
IT'S IN GREAT CONDITION. THE POUNDAGE RANGE IS 25lbs. TO 35lbs> I'M
ASKING $50.00 PAID $90.00. IF YOU INTERESTED JUST LEAVE ME SOME MAIL.

				  THANX,

					JOHN DE LELLO


FOUND: LAST MESSAGE FOR A WHILE
MSG LEFT BY: UNKNOWN PIRATE
POSTED: SUN OCT 07  8:13:31 PM

CALL THIS AE

914-634 9042 PW PIRATE

DOWN 4-8 WEEKDAYS
DOWN 10AM TO 8PM WEEKENDS


FOUND: WARE ><FINALLY><
MSG LEFT BY: MASTER HOUDINI
POSTED: SUN OCT 07 11:03:54 PM

FINALLY A MESSAGE ABOUT.............


WAREWAREW A R E S
 A R EES A
  R  -----
   E-------
-------------S	  S



I GOT .................................


///////////////////////////////////////
M O V I E   M A K E R
///////////////////////////////////////

CRACKED OCT 6 1984 BY THE DISK JOCKEY!
--------------------------------------



LATER0N DUDES.

		MASTER
		HOUDINI


FOUND: WAR GAMES DIALER
MSG LEFT BY: RAMIL BHATNAGAR
POSTED: MON OCT 08 11:59:17 AM

111111111111111111111111111111111111111
1 TO ALL:			      1
1				      1
1   I AM LOOKING FOR A WAR GAMES      1
1				      1
1   DIALER FOR THE APPLE.  I HAVE A   1
1				      1
1   MICROMODEM IIE.  IF YOU HAVE      1
1				      1
1   ACCESS TO THIS PROGRAM PLEASE     1
1				      1
1   LEAVE ME  E-MAIL.		      1
1				      1
1				      1
1   THANKSM			      1
1				      1
1				      1
1		 ---------	      1
1		 MR. MICRO	      1
1		 ---------	      1
111111111111111111111111111111111111111


FOUND: TRADING APPLE STUFF
MSG LEFT BY: LORD SCALAWAY
POSTED: MON OCT 08  9:41:08 PM

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^ If you are interested in trading    ^
^ Apple wares leave me some mail.     ^
^ I am getting some new stuff and     ^
^ I have quite a lot of business      ^
^ and utilities. Thanks.	      ^
^	     Lord Scalaway	      ^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



FOUND: TRADE ANYONE ????
MSG LEFT BY: THE TROJAN HORSE
POSTED: TUE OCT 09  6:36:26 PM

+++++++++++++++++++++++++++++++++++++++
+	   If you would like to trade +
+ leave me your name and # or just    +
+ E-mail and I will get back to you   +
+ as soon as possible.		      +
+				      +
+ EITHER HAVE OR CAN GET VERY EASY :  +
+ SKY FOX			      +
+ RUN FOR IT			      +
+ HES GAMES			      +
+ XYPHUS			      +
+ TAKE ONE			      +
+ DONKEY KONG JR.		      +
+ GELFLING ADV. 		      +
+ COMPITITION KARATE		      +
+ BRUCE LEE			      +
+ ARCHON			      +
+ BOULDER DASH			      +
+ CHAMP. LODE RUNNER		      +
+ FLAK				      +
+ MICRO LEAGUE			      +
+ WAR IN RUSSIA 		      +
+ 50 MISSION CRUSH		      +
+ ET				      +
+ INCREDIBLE HULK		      +
+ RINGSIDE SEAT 		      +
+ SNOOPY			      +
+ BEER TAPPER			      +
+ ARCADE BOOT CAMP		      +
+ JUMPMAN JR.			      +
+ DEATH ON THE CARRIBEAN	      +
+ MURDER ON THE ZINDERNEUF	      +
+ BLADE OF BLACKPOOL		      +
+ DOUBLE TAKE			      +
+ WIZARDRY 3			      +
+	      AND MORE......	      +
+				      +
+	 (-=+> THE TROJAN HORSE <+=-) +
+				      +
+ A MEMBER OF THE INNER CIRCLE OF THE +
+ ALLIED PIRATES ASSOCIATION.	      +
+++++++++++++++++++++++++++++++++++++++


FOUND: WAREZZZZ
MSG LEFT BY: THE LOAN SHARK
POSTED: TUE OCT 09  8:11:39 PM






GOT ALL THE LATEST


WARESWARESSSSGOT EM ALL



STICKEM STICKEMAHAHA STICKEM




THE  LOAN SHARK
----------------*********<><><><>


CALL THE ARABIAN DEZERT THR ROCKINEST BOARD
AROUD ARABIAN DEZERT



212-543-3923

SYSOP ALI BABA

IT ROX THE HOUSE
-----------------------------***=====------*



FOUND: PROBLEMS
MSG LEFT BY: UNKNOWN PIRATE
POSTED: TUE OCT 09  9:03:14 PM

PEOPLE HAVE BEEN CALLING MY AE
LINE WHEN ITS DOWN
WITCH DEFEATS THE PURPOSE.........
CALL 914-634-9042
ITS DOWN
    ----
4PM-8PM WEEKDAYS
10AM TO 7PM WEEKENDS
UP ALL OTHER TIMES

THANKS BUT PLEASE DON'T CALL WHEN
THE LINE IS DOWN

RIGHT NOW Q-DAM IS
UP WTIH SOME OTHER SHIT

914-634-9042 PW/PIRATE


FOUND: NINJA MASTER NEEDS BUDDY
MSG LEFT BY: ANONYMOUS
POSTED: WED OCT 10  7:49:34 AM

***************************************
* I THE NINJA MASTER,I AM IN NEED OF  *
* COMPUSERVE CB FRIENDS MY REAL NAME  *
* IS JAMES SEXTON AND PLEASE LEAVE ME *
* A EMAIL MEESSAGE HERE 	      *
***************************************


FOUND: MICROMAFIA
MSG LEFT BY: CAP'N BYTE
POSTED: SAT OCT 20 11:07:14 AM

HEY DUDES ,
  I DON'T KOW WHAT HAPPENED TO ALL THE MM MESSAGES BUT JUST IN CASE YOU HAVEN'T
HEARD OF THE HOTTEST CLUB TO HIT THE NY AREA..HERE IT IS....THE MICROMAFIA...
THE MM IS A TRADING/PIRATING/PHREAKING/ ETC...CLUBN WHICH REQUIRES ABSOLUTELY
NOTHING:  NO MEMBERSHIP DUES NO REAL NAMES (JUST HANDLES) NO ADDRESSES (UNLESS
U WANT TO RECEIVE "KRAKPOTS" OUR NEWSLETTER) NO NOTHING...  JUST DROP ME AN
E-MAIL TO JOIN WITH ANY INFO YOU WISH TO GIVE ME...  MEANWHILE CALL (623-1939)
TO GET MAILING LIST (OPTION "3") AND 238-3160 (THE CEMETARY) ON WHICH OUR
SUB-BOARD IS ON (YOU MUST BE A MEMBER,THOUGH) FOR THE REST OF THE INFO JUST
CONTACT CAP'N BYTE......

AYE!

THE CAP'N


FOUND: WANT NEW WARES
MSG LEFT BY: CAPTAIN AMERICA
POSTED: SAT OCT 20 10:20:15 PM

  I NEED NEW WARES.I HAVE SPYHUNTER AND ALOT OF OLD WARES TO TRADE LEAVE E-MAIL
IF INTERESTED THANX, CAPTAIN AMERICA

FOUND: PIRATES - <<READ THIS>>
MSG LEFT BY: THE TROJAN HORSE
POSTED: SUN OCT 21 12:29:23 AM


	    HEY YOU,  YEAH YOU!!!

   IF YOUR INTERESTED IN TRADING, AND GOT ANYTHING NEW OR NOT WIDELY
DISTRIBUTED THEN CONTACT ME. WILL MAKE IT WORTH YOUR WHILE!!!!


       (-=+> THE TROJAN HORSE <+=-)

THE ALLIED PIRATES ASSOCIATION
THE MM






FOUND: MCI.....
MSG LEFT BY: UNKNOWN PIRATE
POSTED: SUN OCT 07 10:53:51 PM

this may make me seem pretty dumb
but i need the 914 access number
for mci.

always used sprint and the 80
sevices.


	 later,



ex


FOUND: TO ALL
MSG LEFT BY: DOCTOR WHO
POSTED: MON OCT 08  4:44:06 PM

  ok , i will belive a gold or platinum box when i see it.  or i will take
sharp razor's word for it.  but i have to know how it works.  that telenet
stuff posted is very old!!  why don't you try doing some of your own telenet
hacking instead of getting the list off of timecore?  like this
50921 primenet 19.1.1 ais
20652 locke tops-20
 that should read "20651"
20652 primenet 19.2 cadi3
20646 ??
20659 primenet 19.2.7

31520 enter system id:
      t = vm/cms
      b = brs

ok??
  this was all hacked out an hour ago.	it should still be good, at least until
tommorrow, becuase after that the luser s here will make it go dead.  oh well.
easy-come + easy-go.

-----------=?> doctor who <?=----------


FOUND: TO KEYMASTER
MSG LEFT BY: ARYAN TIGER
POSTED: MON OCT 08  6:45:40 PM

  SORRY MAN, MY MIND WAS STUCK BACK A FEW DOZEN YEARS, CAUSE I HAD JUST WATCHED
THE DIRTY DOZEN OR SOME SUCH MOVIE.  BY THE TIME YOU READ THIS, I WILL PROBABLY
HAVE CALLED YOU...


	   ARYAN TIGER



FOUND: COME ON!!!
MSG LEFT BY: THE DICTATOR
POSTED: MON OCT 08  7:28:14 PM

  Come on!!!  This is a phreak board,and messages like the last one shouldnt be
up on this board at all...  I still need a reply pretaining to my last message
on 800#.  Please respond!!

	    The Dictator


FOUND: 800'S !!!
MSG LEFT BY: PETER GUNN
POSTED: MON OCT 08  8:40:21 PM

***************************************
*      TO ALL			      *
*				      *
*	   I HAVE SOME 800 CODES. IF  *
* INTERESTED LEAVE EMAIL..	      *
*				      *
*	   THANX		      *
*				      *
*	      PETER GUNN-------->     *
***************************************


FOUND: TO PETER GUNN/ALL
MSG LEFT BY: BLUE BEARD
POSTED: MON OCT 08 11:57:38 PM

PETER:
   THE NEXT TIME YOU LEAVE A PUBLIC MSG. PLEASE DON'T USE THE AUTO-BOARDER, IT
TAKES UP SO MUCH OF MINE AND OTHER USERS LIMITED TIME (MAYBE YOU GET NO E*MAIL
TO RESPOND TO. WHICH IS WHY U HAVE SO MUCH TIME (WELL I AND OTHERS DON'T)


    PLEASE TRY TO USE THE AUTO BOARDER ON THINGS OF IMPORTANCE OR THINGS THAT
TAKE UP NO EXTRA TIME TO PRINT THE BOARDER.  I'M SURE I'M NOTTHE ONLY ONE THAT
FEELS THIS WAY.


	 RIGHT!!!!!!


BLUE BEARD





FOUND: REPLIES TO ALL


MSG LEFT BY: BLACKBEARD
POSTED: TUE OCT 09 10:37:51 AM

Well, All, MASS/HAX has been watching
over and we have these short, but sweet
words to say to u all:

    Dictator-If u haven't called sf ][
in a while <I left u some 800 extenders
> I will print them Again here

     800-547-6754
	 986113
	 986115
	 986110
  There is another one, but i can't find it right now, Have phun!

Unknown Pirate- The mci # in the
White plains/Rockland County area is

       914-683-1840
The #'s are 5 digits long,
  here are some to start u off

  mci-->

56140	38892	81811	19982  54174

have phun!

If there are any questions, please
leave me E-mail.

	**** MASS/HAX ****
       (C)opyright 1984, 1985
      (C) All Rights Reserved!

    Call the best board in Bedford!
     **** A L P H A  F I V E ****

	   (617)-999-3210

***************************************



FOUND: FROM THE MASTER
MSG LEFT BY: THE MASTER
POSTED: TUE OCT 09  2:21:37 PM

  TO HACKMAN:  YOU HAVE NOT BEEN AROUND THE PHRACKING WORLD LONG ENOUGH TO BE
MAKING STATEMENT TO JUDGE ANOTHER PERSON THAT IS AND HAVE BEEN INTO THIS SHIT
FOR OVER 8 YEARS....TAKE IT FROM A OLD HACKER:	SHUTT THE FUCK UP BEFORE I
REALLY BUST YOUR SORRY ASS SHITT OUT ON THIS BOARD!

  TO THE BLACK NIGHT:  IF YOU HAD BEEN AROUND THE PHRACKING WORLD LONG ENOUGH
YOU WOULD KNOW WHERE I LIVE AT HAS THE MOST UPDATED ESS SYSTEM AROUND...  YOUR
THEORIES HOLDS WATER LIKE A CUP WITH A HOLD IN IT....GO TO SCHOOL....LEARN
SOMETHING ABOUT THE SUBJECT AND THE PEOPLE YOU TALK ABOUT!  AND IF I EVERY HEAR
THAT YOU HAVE THREATEN THE LIFE OF SOMEONE I KNOW OR ANYONE ON ANY BOARD...YOU
BETTER BE READY TO BACK IT UP!...WITH ME!

  TO WAVE LENGTH:  MYGOD...YOU THE STUPIDEST OF THE BUNCH!  A IC AND A DTMF
CHIP CAN BE REPROGRAMED!  IF YOU DON'T THINK THEY CAN...HOWQ COME THE GOVERMENT
STOPS PEOPLE FROM TAKING GAMES OUT OF THE COUNTRY SO THAT CHINA AND OPTHER
COUNTRIES CAN NOT...AND GET THIS AIR HEAD....REPROGRAM T THE CHIPS!  LIKE THEIR
GO GOVERMENT NEEDS THE CHIPS TO PLAY PAC-MAN?!

  LISTEN UP PEOPLE!  LET'S LEAVE THE SUBJECT ALONE...OKAY BECAUSE IF YOU
BELIEVE IT OR NOT DOESN'T MAKE A DIFFENCE WITH ME...I AM NOT THE ONE WHO HAVE
TO CALL A OPERATOR OR USE A BLUE BOX TO START A CONFERENCE!

THE MASTER IS BACK AGAIN!

MEMBER OF THE FOLLOWING:
VENGENLANTY FORCE
STATES OF ART
THE PHONE CREW
THE BLACK TRIANGLE
2506...I MENT 6205
I CAN'T LEAVE OUT THE THE BEST OF THE
BUNCH.........
THE PHONE PHREAKERS OF AMERICA
 AND A BUCH OF PROVATE SHITT
I CAN'T MENTION.....
TO ALL...SOO LONG FOR NOW

 THE MASTER

P.S. SHARP...CALL ME..WE'LL
HAVE LUNCH!



FOUND: ALL 800'S
MSG LEFT BY: PETER GUNN
POSTED: TUE OCT 09  5:10:25 PM

      TO ALL GREAT PHREAKERS

  ARE ALL 800 NUMBERS SAFE?  LEAV E EMAIL OR POST REPLY

	     THANX

	    PETER GUNN ------><


FOUND: I HAVE COMPUSERVE!
MSG LEFT BY: URIS ITUEY
POSTED: TUE OCT 09  7:44:55 PM

All right ladies, gentleman, and Mass/Hax:
------------------------------------------

  I just hacked out a CompuServe password a little while ago, so if you have
something worthwhile to offer, leave E-Mail and I'll give you the ID and
password right away.  If it lasts like the last one I got, I'd give it around 2
weeks, so hurry!  [Forget about Apple stuff, I have a TRS-80]

			   ))-Uris->



FOUND: NICE JOB!!!!
MSG LEFT BY: THE HACKMAN
POSTED: TUE OCT 09  8:35:46 PM

  to master:  nice spelling of phreaking...  also,get real!this board is for
phreaking and shit.  i mean short insults and minor shit is all right but
jesus!!!!  leave me e-mail calling me a sorry ass or whatever neat thing you
called me.also,is asking sharp razor out to lunch a really valid use of this
board?

lateron,
---->the<----
-->hackman<--


FOUND: ***AGRIDATA***
MSG LEFT BY: THE DICTATOR
POSTED: WED OCT 10  3:59:48 PM

Heres an oldie but goodie still around.
Dialup:  414 271 7827

Id:	 A*
security:01-6709
Password:RSHACK

Have Phun if your interested in the
hogs report!!!

	    The Dictator


FOUND: HEY SHARP
MSG LEFT BY: PETER GUNN
POSTED: WED OCT 10  4:51:25 PM

     TO SHARP RAZOR AND ALL...


	  WILLING TO TRADE 800'S..

	  SHARP RAZOR LEAVE ME EMAIL

	     PETER GUNN-------><

	BY THE IS 800 547 6754 SAFE TO
USE FROM HOME?


FOUND: POST EM GUNN
MSG LEFT BY: THE HACKMAN
POSTED: WED OCT 10  7:35:28 PM

hey guy,like don't be tight about
putting up 800 codez.i am sure
sharp razor has oodles.
lateron,
---->the<----
-->hackman>--
p.s.read my e-mail to you several
times to let it sink in.
/q


FOUND: CHANGE OF LIFESTYLE
MSG LEFT BY: SHARP RAZOR
POSTED: WED OCT 10  8:14:49 PM

  This phone # can permanently change the lifestyle of your phone...
....305-994-9966....  call it now!

  Also..The Hackman the word "PHRACKING"= a combinatation of phreaker and
Hacker...I myself use the as it is more descriptive then calling someone just a
phreaker or hacker..  ..also, i am virtually unreachable,so T .  Master prob.
wanted to make sure i git his msg by posting it..

..Later..
..Sharp Razor>>
 The legion Of Doom!
 The Legion Of Hackers

 AT&T is in Oral Sex!


FOUND: OK HERE THEY ARE
MSG LEFT BY: PETER GUNN
POSTED: THU OCT 11  2:58:17 PM

     TO ALL:

       HERE ARE SOME CODES FOR

	     <800 322 1415>

	  637209 637190 637185 637211
	 637170........

	     HAVE FUN....

	     PETER GUNN -----><


FOUND: HELP!!!
MSG LEFT BY: KILROY MUNCHER
POSTED: THU OCT 11  5:30:22 PM

TO ALL;
  I NEED HELP HERE.  DOES ANYBODY KNOW THE FONE # TO THE RAMAPO HIGH SCHOOL
COMPUTER?  IF SO, PLEASE LEAVE E-MAIL TO KILROY MUNCHER.  HERE IS SOMETHING
ELSE, 1-914-347-5540.  ITS A SCHOOL COMPUTER.  MY MODEM DOESN'T EVEN WORK ON
IT.  LIKE I SAID, HELP!!!


	     LATER,

	      ///   ///
	     ///  ///
	    /// ///
	   //////
	  /// ///
	 /// ////ILROY ]]
PS: IF YOU GET ON LINE WITH THAT SUCKER
    LET ME KNOW BY E-MAIL.

=^=^=^=^=^=^=^=^=^=^=^=^=^=^=^=^=^=^=^=



FOUND: CALL NOW!
MSG LEFT BY: DR. DISECT-IT
POSTED: SUN OCT 07  9:02:59 PM

!  !  !  !		  !   !   !  !
!  !  ! 		   !   !   !
  !---! 		      !---!
 !   !			     !	 !
 !   !			     !	 !
 !   !-----------------------!	 !
 !	       CALL THE 	 !
  !	THE KRACKER'S KASTLE      !
  !				  !
  !	     212-631-1788	  !
  !  THE BOARD THAT WAS ONCE ONE  !
  ! OF THE BEST IN 212 IS BACK BUT!	  !				  !
 !NEEDS A LOT OF MEMBERS TO GET  !	 ! BACK TO ITS ORIGINAL GREATNESS!
 !    SO CALL IT TODAY!!!!	 !
	212-631-1788			 AND TELL'EM DR. DISECT-IT SENT 'YA
 ---------------------------------


FOUND: LOOKING FOR JEDI
MSG LEFT BY: DR. DISECT-IT
POSTED: SUN OCT 07  9:06:29 PM

THIS IS DR. DISECT-IT HERE...LOOKING	FOR A COPY OF THE MOVIE.........
     "RETURN OF THE JEDI"!
     (ON VHS FORMAT VIDEO TAPE)
YES...I KNOW THAT "EMPIRE" HASN'T EVEN  BEEN OFFICIALLY RELEASED YET BUT I WAS
ONDERING IF ANY OF YOU SNEAKY/CRAFTY   GUYS HAVE A BOOTLEG COPY OF IT YET?!
F YOU DO, OR KNOW OF SOMEONE WHO MIGHT E-MAIL ME OR CALL ME:914-693-5941
SK FOR BRIAN!
HANX
==========>>DR. DISECT-IT<<============


FOUND: IRON MAIDEN
MSG LEFT BY: BLUE BEARD
POSTED: MON OCT 08 12:29:30 AM

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^				      ^
^				      ^
^				      ^
^ .				      ^
^ HEY ALL:			      ^
^     ARE THERE ANY HEAD BANGERS/     ^
^ METAL HEADS OUT THERE.	      ^
^     ITS SUNDAY NIGHT I JUST CAUGHT  ^
^ THE MAIDEN SPECIAL ON MTV (SUCKS)   ^
^ AND IT WAS GREAT... TO DAMN GOOD TO ^
^ JUST WRITE ABOUT THIS IS THE KIND   ^
^ OF THING YOU HAVE TO EXPERIENCE FOR ^
^ YOURSELF.			      ^
^				      ^
^				      ^
^     THEY SHOULD BE HERE IN NOVEMBER ^
^ OR SO I'VE HEARD, IF YOUV'E HEARD   ^
^ ANYTHING ELSE LET ME KNOW.	      ^
^				      ^
^				      ^
^      MAIDEN NUMBER 1		      ^
^				      ^
^				      ^
^ IRON MAIDEN////IRON MAIDEN////IRON  ^
^ MAIDEN////IRON MAIDEN////IRON MAID  ^
^ EN////..........		      ^
^				      ^
^ METAL RULES THE LAND. 	      ^
^ IF YOUR WONDERING WHY THE HELL I'M  ^
^ DOIN' THIS, WELL I'M JUST F*CKED UP ^
^ RIGHT NOW WITH NOTHIN' TO DO.?!?!?? ^
^				      ^
^				      ^
^ WHAT THE HELL DO THE REST OF YOU    ^
^ GUYS(?) LIKE??? HUH LET ME KNOW???  ^
^ THIS IS YOUR RESIDENT METAL HEAD    ^
^ SIGNING OFF......BLUE BEARD.	      ^
^ ONCE AGAIN... METAL RULES THE LAND  ^
^    (ROB HALFORD::JUDAS PRIEST^^^^^) ^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


FOUND: MAIDEN ROCKS


MSG LEFT BY: JASON TANENBAUM
POSTED: MON OCT 08 12:09:27 PM

  I SAW THE MAIDEN SPECIAL AND IT WAS AMAZING!!!!!!  I DONT KNOW WHEN THEY ARE
COMING HERE OR WHERE THEY ARE GOING TO BE BUT IF ANYBODY KNOWS WHERE TO GET
TICKETS TELL US.

	   METAL
	   RULES



	<----THE---->
      <----ASSASIN---->

  JASON TANENBAUM



FOUND: UP THE IRONS
MSG LEFT BY: BLUE BEARD
POSTED: MON OCT 08  6:20:45 PM



HEY IF YOUR A METAL MANIAC LET ME HERE FROM YA.



ALL METAL HEADS MUST UNITE.

LETS HERE SOMETHIN' FROM YA




IRON MAIDEN
TWISTED SISTER
JUDAS PRIEST
MOTLEY CRUE
RATT
MOTOR HEAD
ACCEPT
Y&T





LED ZEPPELIN



MSG LEFT BY: PETER GUNN
POSTED: MON OCT 08  8:55:38 PM

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^     TO ALL			      ^
^				      ^
^     LOOKING FOR SOME BOOTLEG ZEP,U2 ^
^ ,ELP,YES			      ^
^	SOME NEWS FOR PLANT FANS: N


FOUND: CALL THE A D


MSG LEFT BY: THE LOAN SHARK
POSTED: TUE OCT 09  8:17:56 PM

------------------------------------------------------------------
==
==
==
== CALL THE ARABIAN DEZERT:212-543-3923
------------------------------------------------------------------

	 <><><><>     <>
	 <>    <>     <>
	 <><><><>     <>
	 <>    <> <><><>
	 <>    <> <>  <>
		  <>  <>
		  <><><>  212 543 3923
-----------------------------------------
				 ------------------------
				      -------------------------------
							    -------------------
 --
