
#: 144057 S15/Open Forum
    04-Jul-92  11:33:19
Sb: #Independence Declaration
Fm: William F. Zachmann 72241,43
To: All

I can think of no better occasion than the Fourth of July to declare
independence from those who would dictate the content of what I write.  Over
the past several months, I have been repeatedly subject to what I feel to be
inappropriate and improper pressure from PC Week in regard to my views on
Microsoft and Windows, IBM and OS/2.

I had hoped that this was a temporary aberration that would soon be corrected.
Unfortunately, that does not seem to be the case.  I have therefore sent
notice to the Ziff-Davis Publishing Company that I do not intend to renew my
agreement with them when its current term expires at the end of September.

I believe that Mr. William Ziff, Jr. is genuinely committed to editorial
integrity and independence.  Unfortunately, I think Mr. Ziff is being
ill-served by some of his employees who do not share that commitment.  I am
concerned that the regretable tendency to shape editorial content to please a
major advertiser (Microsoft in this case) which I have noted in some competing
publications is being imported into the Ziff-Davis Publishing Company.

If you share my concern, you may want to write to Mr. William Ziff, Jr., Ziff
Davis Communications, One Park Avenue, New York, NY, 10016 and let him know
what you think. Please feel free to repost this messages elsewhere if you
wish.

William F. Zachmann

* Replies:  144092, 144177, 144202, 144227, 144359, 144366, 144440, 
            144542, 144689, 144908

#: 144092 S15/Open Forum
    04-Jul-92  12:47:15
Sb: #144057-#Independence Declaration
Fm: Michael H Galpin 70734,356
To: William F. Zachmann 72241,43 (X)

William,

Thank you for putting the record straight on this subject. I trust that we can
expect to see your talents put to use in other publications. Good luck to you.

Mike <<TEAM OS/2>>

* Reply:  144194

#: 144194 S15/Open Forum
    04-Jul-92  17:15:29
Sb: #144092-Independence Declaration
Fm: CyberSim [E. Pinnell] 70031,435
To: Michael H Galpin 70734,356

Michael,

    I don't know about you, but I'm going to write Ziff.  As far as I am
concerned, if Sam Whitmore is going to bow to MS pressure, I am not going to
renew my subscriptions.

Eric Pinnell

* Replies:  144335, 144441

#: 144335 S15/Open Forum
    05-Jul-92  00:13:14
Sb: #144194-#Independence Declaration
Fm: Raymond Chuang 72441,3652
To: CyberSim [E. Pinnell] 70031,435

Eric,

Personally, I think I would like to hear what Microsoft managers have to say
about this.

I want both Brad Silverberg and Steve Ballmer (both of whom are well-known CIS
users even if they spend most of the time "lurking") to clarify just WHAT did
happen between Microsoft and Ziff-Davis that resulted in Will Zachmann turning
in his resignation.

Raymond Chuang

* Replies:  144346, 144462, 144721

#: 144346 S15/Open Forum
    05-Jul-92  01:47:18
Sb: #144335-Independence Declaration
Fm: Bruce Leiwant 72456,777
To: Raymond Chuang 72441,3652

 >Personally, I think I would like to hear what Microsoft managers have to say
 >about this.

I don't see how they could say anything objective if it's true, and if it is
not, then Will would not have hung up his hat.

Personally, I believe Will Z 1,000%.  He backed his decision with his job!

                                               Bruce/2

* Reply:  144448

#: 144448 S15/Open Forum
    05-Jul-92  11:16:34
Sb: #144346-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Bruce Leiwant 72456,777 (X)

Bruce,

I definitely want to see if Brad and Steve (or at least someone from Waggoner
Edstrom, Microsoft's PR firm) make a statement regarding Will accusations
against Ziff-Davis and Microsoft.

Raymond Chuang

#: 144462 S15/Open Forum
    05-Jul-92  12:04:45
Sb: #144335-#Independence Declaration
Fm: Bruce Biermann 72241,261
To: Raymond Chuang 72441,3652 (X)

Raymond,

Microsoft is only acting rationally.  If it can influence PC Week or other
publications, it will.  The fault doesn't lie with Microsoft, but with the
individuals at PC Week who would allow its editorial integrity to be
questioned.

    Bruce

* Replies:  144477, 144519, 144556

#: 144477 S15/Open Forum
    05-Jul-92  13:09:34
Sb: #144462-Independence Declaration
Fm: Ben Sano 72401,2736
To: Bruce Biermann 72241,261 (X)

Bruce

And with what ever people at Z-D who didn't rectify it when it was possible.

--Ben

#: 144519 S15/Open Forum
    05-Jul-92  13:41:51
Sb: #144462-Independence Declaration
Fm: Rob Burton 70323,1105
To: Bruce Biermann 72241,261 (X)

I doubt it takes any action by MS to generate such behaviour at PC Week. Hope
of favour should be all it takes to grovel for advertisers. Just look at
almost any newspaper chain.

#: 144556 S15/Open Forum
    05-Jul-92  14:54:10
Sb: #144462-#Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Bruce Biermann 72241,261 (X)

Bruce,

One thing I can say about PC Magazine--they have balanced out their coverage
of Windows and OS/2 2.0 nicely, especially in the last few issues.

I myself think that PC Magazine Editor-in-Chief Michael J. Miller does a very
good job at giving a free reign to all PC Mag writers and columnists; after
all, John C. Dvorak has done his share of potshots at MS, too <grin>.

Raymond Chuang

* Replies:  144651, 144722

#: 144651 S15/Open Forum
    05-Jul-92  19:21:16
Sb: #144556-#Independence Declaration
Fm: David Coffin 76200,674
To: Raymond Chuang 72441,3652 (X)

>> Michael J. Miller does a very good job at giving a free reign to all PC Mag
writers and columnists;

IMO, Miller is part of the problem.  I've got the proof in print.  I certainly
have not seen proof of the balance you mentioned.

* Reply:  144702

#: 144702 S15/Open Forum
    05-Jul-92  20:58:30
Sb: #144651-Independence Declaration
Fm: Ben Sano 72401,2736
To: David Coffin 76200,674 (X)

David

I'm not so sure of Michael J. Miller's being part of the problem. He is and
has said that he prefers Windows however it seems to me that his magazine
(different from the articles he writes himself) is NOT forced to any view.

It is true that if your boss has a view many will follow but I don't think
anything more then that is at work there.

--Ben

#: 144722 S15/Open Forum
    05-Jul-92  21:23:23
Sb: #144556-Independence Declaration
Fm: Warren Zeigler 70662,1710
To: Raymond Chuang 72441,3652 (X)

 >One thing I can say about PC Magazine--they have balanced out their coverage
 >of Windows and OS/2 2.0 nicely, especially in the last few issues.

You've got to be kidding?!?!?!?

PC Week has LONG articles on NT that are just rehashes of OLD press releases -
not new news, and some minor OS/2 coverage. Headlines ALWAYS skew for MS. PC
Magazine does the same.

PC XXX coverage of OS/2 is worse than PC Week's coverage of Apple.

Warren

* Reply:  144762

#: 144762 S15/Open Forum
    05-Jul-92  23:15:03
Sb: #144722-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Warren Zeigler 70662,1710

Warren,

I don't think so. The latest issue of PC Magazine talking about how to select
a high-end machine does make fairly liberal mention of OS/2 2.0.

Raymond Chuang

* Replies:  144853, 145170

#: 144853 S15/Open Forum
    06-Jul-92  07:08:00
Sb: #144762-Independence Declaration
Fm: Marvin Nipper 70142,3166
To: Raymond Chuang 72441,3652 (X)

<<The latest issue of PC Magazine talking about how to select a high-end
machine does make fairly liberal mention of OS/2 2.0.>>

Raymond,

This hardly makes them "balanced".  I've written numerous letters to them
regarding their blatant bias.  When an "unsuspecting user" writes to the
Windows Advisor column and asks "what is OS/2, and should I get it?", and the
reply from the "so called ADVISOR", doesn't mention multi-tasking, or WPS
"drag and drop" (and a truckload of other things that I have long since
forgotten), and basically says "they're the same thing, stay with Windoze", I
HARDLY think that's balance.  AND, of course to be balanced, they printed all
those letters that were written to challenge Fran's TOTALLY BIASED viewpoint
(and if you believe that last sentence, I have some nice property in Florida
that I'd like to sell to you....it only LOOKS like a swamp).

All the ZDC pubs are sucking up to M$.  It's YELLOW JOURNALISM of the absolute
worst kind.  If this were the dark ages, ZDC would be the "keeper of the
faith", and they'd be advocating the burning of OS/2 users by the thousands.
..............Marvin

#: 145170 S15/Open Forum
    06-Jul-92  18:38:53
Sb: #144762-Independence Declaration
Fm: Warren Zeigler 70662,1710
To: Raymond Chuang 72441,3652

Again - One article on OS/2 for probably 100 mentions of Windows. You prove my
point.

Warren

#: 144721 S15/Open Forum
    05-Jul-92  21:23:17
Sb: #144335-Independence Declaration
Fm: Warren Zeigler 70662,1710
To: Raymond Chuang 72441,3652 (X)

Raymond -

Where are you comming from? Who knows where in MS the pressure us comming from
or how many people it goes through? This has been a public issue for a few
months now, and if MS wanted to retain ANY credability here they should have
acted before now. ANY statement by MS now would be proof of a self-serving
attitude. Who here would even listen to Steve Balmer any more anyway?

How can anyone trust ZD, ZD Labs, or any write-up about MS? (And not just from
this. This is just one raindrop in a big storm.)

Warren

* Reply:  144854

#: 144854 S15/Open Forum
    06-Jul-92  07:08:06
Sb: #144721-Independence Declaration
Fm: Marvin Nipper 70142,3166
To: Warren Zeigler 70662,1710 (X)

YEAH!

If ZD bows to M$ pressure on their writings about Windoze and OS/2, what does
that mean about all those EVALUATIONS they do??  If Gateway 2000 gets a few
good PC picks, is it because they make a good PC, or because they spend a
fortune on those Ads in PC Mag??  Does HP PAY for some of those LaserJet picks
that the "evalutaters" make??  Whose to know??  Once someone submits to
prostitution of any kind, then ALL their activities become suspect.
.............Marvin

#: 144441 S15/Open Forum
    05-Jul-92  10:57:52
Sb: #144194-#Independence Declaration
Fm: Michael H Galpin 70734,356
To: CyberSim [E. Pinnell] 70031,435

Eric,

Yes, I'll be writing to Ziff, PC Mag (UK) was launched recently I had hoped
their attitude would be different. They Win 3.1 vs. OS/2 2.0 comparison they
published this month shot down any hopes of that. Mind you they published John
C. Dvorak's column on the back page :

        'Personally, I've chosen OS/2 because it runs DOS programs quite fast
and all at once. I know that you guys in England can hardly find a copy (IBM
UK only had 2000 copies at 1 Apr - Mike). If you can, buy it!
But not unless you have a fast 386/486 and 16 megs!'

it concludes with a nice comment from a Lotus employee. Is there any chance
this story can get a wider audience than us CISers ? Quite apart from our
feelings about M$, the idea that a large corporation can interfer with the
free press in this way is worrying.

Mike <<TEAM OS/2>>

* Reply:  144563

#: 144563 S15/Open Forum
    05-Jul-92  15:16:33
Sb: #144441-#Independence Declaration
Fm: Mike Miller 72567,3425
To: Michael H Galpin 70734,356

 > Is there any chance this story can get a wider audience than us CISers ?

As of Saturday evening, it was posted on the OS/2 conference of SmartNet.


Mike.

* Reply:  144652

#: 144652 S15/Open Forum
    05-Jul-92  19:21:22
Sb: #144563-Independence Declaration
Fm: David Coffin 76200,674
To: Mike Miller 72567,3425

I have posted Zach's letter on BIX.  I would like to see it in some major
newspapers. Hmm, time to hit the phone and Fax.

* Replies:  144763, 144962

#: 144763 S15/Open Forum
    05-Jul-92  23:15:06
Sb: #144652-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: David Coffin 76200,674 (X)

David,

Given the fact that Will's message was posted on a PUBLIC board (any CIS
member can read it), I won't be surprised if this story ends up in NewsBytes
within 2-3 days.

Raymond Chuang

#: 144962 S15/Open Forum
    06-Jul-92  12:02:39
Sb: #144652-Independence Declaration
Fm: CyberSim [E. Pinnell] 70031,435
To: David Coffin 76200,674

David,

    What about InterNet?

Eric Pinnell

#: 144177 S15/Open Forum
    04-Jul-92  16:43:03
Sb: #144057-#Independence Declaration
Fm: Claude Biron 75330,2517
To: William F. Zachmann 72241,43 (X)

I applaud your resolve and I hope your opinions find voice elsewhere!

* Reply:  144214

#: 144214 S15/Open Forum
    04-Jul-92  17:43:31
Sb: #144177-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Claude Biron 75330,2517

Claude,

Thank you.  Your support is appreciated.

All the best,

Will Zachmann

* Reply:  144740

#: 144740 S15/Open Forum
    05-Jul-92  21:39:24
Sb: #144214-Independence Declaration
Fm: Toby Pennycuff [AMR] 70007,6267
To: William F. Zachmann 72241,43

Will,

     Rest assured, you have 1,000% of my support.  As we have discussed on the
phone in the past, the bias you have noted is quite evident.  My hope is that
you will find a new home quickly for your column as I will sorely miss your
comments and perspective.  Please keep us all posted as to your landing spot!
All the best to you and your efforts!   And thanks for reminding us about our
heritage and why freedom is such an important part of each of our lives!
Happy 4th! <SMILE>

Toby Pennycuff American Airlines Team OS/2 - Texas

* Reply:  144787

#: 144787 S15/Open Forum
    06-Jul-92  00:47:31
Sb: #144740-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Toby Pennycuff [AMR] 70007,6267

Toby,

Thanks.

Will

* Replies:  144821, 144963

#: 144821 S15/Open Forum
    06-Jul-92  04:13:38
Sb: #144787-Independence Declaration
Fm: Patrick Pearce(SCUDMAN) 70662,2714
To: William F. Zachmann 72241,43 (X)

Will,

Response to "WEASELGATE" via private E-Mail is very high!  I expect it to
increase considerably this week.

I'm making a trip into the city on Thursday to drop off the first batch. Next
week too if necessary.

Patrick

#: 144963 S15/Open Forum
    06-Jul-92  12:02:45
Sb: #144787-Independence Declaration
Fm: CyberSim [E. Pinnell] 70031,435
To: William F. Zachmann 72241,43 (X)

Tally ho! Bogeys at six o'clock low! Fire are letters as they bear!<G>

Fidel

#: 144202 S15/Open Forum
    04-Jul-92  17:20:49
Sb: #144057-#Independence Declaration
Fm: Raymond Chuang 72441,3652
To: William F. Zachmann 72241,43 (X)

Will,

As I said in ZNT:EDITORIAL, I am sorry that you have turned in your
resignation to Ziff-Davis.

However, I think you should still be around, but instead of "Will Zachmann
[PCMAG]" you'll call yourself "Will Zachmann [Canopus]".

BTW, I followed your suggestion from a recent PC Magazine and dumped my 2400
bps modem--I now am using a ViVa 9642i V.32/V.42/V.42bis 9600 bps modem on my
home machine. ;-)

* Reply:  144215

#: 144215 S15/Open Forum
    04-Jul-92  17:43:35
Sb: #144202-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Raymond Chuang 72441,3652

Raymond,

Well, my agreement with Ziff-Davis Publishing does not run out until the end
of September.  Whatever my relations (or lack thereof) with them after that,
I'm sure I'll still be around one way or another.

Will

#: 144227 S15/Open Forum
    04-Jul-92  18:33:24
Sb: #144057-Independence Declaration
Fm: Rob Burton 70323,1105
To: William F. Zachmann 72241,43 (X)

"I believe that Mr. William Ziff, Jr. is genuinely committed to editorial
integrity and independence.  Unfortunately, I think Mr. Ziff is being
ill-served by some of his employees who do not share that commitment" WF
Zachman says.
For what it's worth, I believe you have to judge a man by the company he keeps
- or hires and fires.
In this affair, the buck stops at the top - and it's tainted.

#: 144359 S15/Open Forum
    05-Jul-92  05:47:58
Sb: #144057-#Independence Declaration
Fm: Mike Miller 72567,3425
To: William F. Zachmann 72241,43 (X)

Hi Will,

With great sadness I have read your Independence Declaration.  There are times
when one must make decisions regarding the level of ethics one aspires to.
Decisions of that nature never come easy, but once they are made, remove a
burden.

Please let us know where we can continue to read your columns.  Hopefully it
will be a forum that places a higher value on journalistic integrity than
PCWeek.


  "You will find that the truth is often unpopular and the contest between
  agreeable fancy and disagreeable fact is unequal.  For, in the vernacular,
  we Americans are suckers for good news."

                                  - Adlai E. Stevenson (9jun1958)


Mike.

* Reply:  144376

#: 144376 S15/Open Forum
    05-Jul-92  08:00:28
Sb: #144359-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Mike Miller 72567,3425 (X)

Mike,

Thank you for the kind words of support.

All the best,

Will Zachmann

#: 144366 S15/Open Forum
    05-Jul-92  07:08:56
Sb: #144057-#Independence Declaration
Fm: Scott Mack 70611,2713
To: William F. Zachmann 72241,43 (X)

Will- FYI this letter went in the mail today. Will you be writing for some of
the OS/2 publications? Let us know which ones so I can signup for
subscriptions, as you and Dvorak are the only people I believe anymore. I
applaud your integrity and honesty.

Dear Mr. Ziff;

  I recently read a message on Compuserve by William Zachmann, regarding
pressure by your executives to slant editorial coverage in your publications
in favor of a major advertiser (Microsoft). I was aware of the obvious bias
with most of your editorial staff, but Zachmann's comments confirm my
suspicions.

  I have been a subscriber to PC Magazine and PC Week for many years. I read
these publications to get unbiased opinions regarding the latest in PC
technology. I do not need misinformation and propaganda from a major
advertiser, in this case Microsoft.

Were you aware of this conspiracy between your publications and Microsoft
against IBM? How could you have allowed this to happen?

I am as of today cancelling all my Ziff Communications subscriptions, and will
advise others to do likewise. If I want to be force fed the Microsoft party
line I would just turn to the MS ads.


Sincerely yours,





Scott W. Mack, M.D.

* Reply:  144377

#: 144377 S15/Open Forum
    05-Jul-92  08:00:34
Sb: #144366-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Scott Mack 70611,2713 (X)

Scott,

I appreciate your support.  I would urge you (and others) not to cancel
subscriptions to Z-D publications over this.  It ain't over 'til it's over.
Maybe things will turn out all right in then end after all.  I am not
optimistic about that, but I haven't given up on the possiblity, either.

Will

* Replies:  144390, 144724

#: 144390 S15/Open Forum
    05-Jul-92  08:38:34
Sb: #144377-Independence Declaration
Fm: Scott Mack 70611,2713
To: William F. Zachmann 72241,43 (X)

Will,

In your honor I will let my subscriptions expire by not renewing. To be honest
however the only articles I read any more are by you and Dvorak.

Perhaps things will change but I'm not holding my breath waiting.

Scott

#: 144724 S15/Open Forum
    05-Jul-92  21:24:16
Sb: #144377-Independence Declaration
Fm: Mike Kiser 72510,710
To: William F. Zachmann 72241,43

I've had it with M$ trying to monopolize the PC world (isn't that why the FTC
is after them???).  I'm cancelling ALL my ZIFF-D subscriptions immediately due
to Z-D caving in to M$'s whims....( and Will's resignation) !!!

MIke

* Reply:  144788

#: 144788 S15/Open Forum
    06-Jul-92  00:47:35
Sb: #144724-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Mike Kiser 72510,710

Mike,

Please do not cancel your Z-D subscriptions.  Please do let them know what you
think, though.

All the best,

Will

#: 144440 S15/Open Forum
    05-Jul-92  10:44:07
Sb: #144057-#Independence Declaration
Fm: Howard Weatherly [CTG] 71327,1575
To: William F. Zachmann 72241,43 (X)

Will,

Congradulations! on taking your stand on this particular day. Sort of sends a
double message. Like many others I believe that Ziff publications PC Mag in
particular has been bent in a direction that does not serve the readership to
it's former potential. I may or may not as time permits follow your suggestion
to write to Mr. Ziff, but no matter if I do or do not, I will not be renewing
my subscription. Letters are good but I believe the pocketbook will bring
change about more quickly. Of course I know that I am only one and it will be
like p---ing in the wind, but I will feel much better not supporting the
current policies!

--Howard

* Reply:  144703

#: 144703 S15/Open Forum
    05-Jul-92  20:59:12
Sb: #144440-Independence Declaration
Fm: Rick Harris 70224,1256
To: Howard Weatherly [CTG] 71327,1575

Howard...

     I am only one, but I AM one.
     I can not do everything, But I CAN do something.

That's a quote that has managed to stick in my brain and continue to motivate
over the years.  I have no idea where I saw it or who authored it. It is
particularly appropriate in Will's case.  I hope he sees it.

Rick...

* Reply:  144789

#: 144789 S15/Open Forum
    06-Jul-92  00:47:40
Sb: #144703-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Rick Harris 70224,1256

Rick,

I've seen it.  Thank you very much.  I really appreciate that.

Will

#: 144542 S15/Open Forum
    05-Jul-92  14:14:34
Sb: #144057-#Independence Declaration
Fm: Bruce Leiwant 72456,777
To: William F. Zachmann 72241,43 (X)

Will-

I think you should feel very proud.  Not just with the decision, which really
is the culmination of what I am sure were very difficult times, but with the
way you handled yourself while all this was going on.

I look forward to seeing you in print in other periodicals or (Books?)!

                                                      Bruce/2

* Reply:  144667

#: 144667 S15/Open Forum
    05-Jul-92  19:44:45
Sb: #144542-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Bruce Leiwant 72456,777 (X)

Bruce,

Thanks for the kind words.  Hopefully this will all work out well in the end.

Best regards,

Will

#: 144689 S15/Open Forum
    05-Jul-92  20:28:51
Sb: #144057-Independence Declaration
Fm: Clark D. Christensen 76226,3123
To: William F. Zachmann 72241,43

Will,
        I'm sorry to see this happen.  I intend to write to Mr. Ziff to
express my displeasure.  I have always enjoyed your column in PC Magazine.
The balance that it provided will be missed by this reader.  You have my best
wishes.

Clark Christensen

* Reply:  144790

#: 144790 S15/Open Forum
    06-Jul-92  00:47:44
Sb: #144689-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Clark D. Christensen 76226,3123

Clark,

Thanks.

Will

* Reply:  145032

#: 145032 S15/Open Forum
    06-Jul-92  13:26:17
Sb: #144790-#Independence Declaration
Fm: Cliff Garrett <<MS>> 76702,1531
To: William F. Zachmann 72241,43 (X)

This really isn't a reply to your message, but I am too lazy to create a new
message.

This is to Will Zachmann.

Please nip this in the bud.  You really need to clarify your position, and
clear up all the misunderstanding in the forums here and the other forums
where this rattle is occuring.  I do not mind reading this info, but please
clarify your position, so we don't have so much speculation and needless
anylization of your incomplete inconclusive post.

Educated folks want to know,

thanks,
       cliff

* Replies:  145038, 145155

#: 145038 S15/Open Forum
    06-Jul-92  13:46:27
Sb: #145032-Independence Declaration
Fm: mike widseth 71151,1430
To: Cliff Garrett <<MS>> 76702,1531

>>needless anylization of your incomplete inconclusive post.<<

Was that supposed to be "annihilation" or "analyzation"?

Educated folks want to know,

-Mike [Team OS/2]-

#: 145155 S15/Open Forum
    06-Jul-92  18:13:26
Sb: #145032-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Cliff Garrett <<MS>> 76702,1531

Cliff,

Go and read the threads over on ZNT:EDITOR and ZNT:PCWEEK on this topic.  If
you have any specific questions after you've read the material posted there,
I'll be happy to respond.

Will Zachmann

#: 144908 S15/Open Forum
    06-Jul-92  10:04:50
Sb: #144057-#Independence Declaration
Fm: Joe McGinn 71510,3015
To: William F. Zachmann 72241,43 (X)

Well, Ziff-Davis & PC-Week have gone from a credibility rating of about 2 (on
a scale of ten) right down to zero.  My congratulations to yourself for having
the fortitude to stand up for what you believe in.  A suggestion: what this
industry needs right now is a magazine that _objectively_ reports on real
issues and products.  Byte used to be such a publication, but recently they
seem to be jumping on the Windows bandwagon too (probably for the same reasons
as writers at Ziff-Davis).  I honestly can't think of any really objective
magazine except for Dr Jobbs Journal, but that's for programmers, not users.
Have you considered the possibility of starting a new magazine?  I think there
would be a huge market if you really pushed the objectivity idea - after all,
people have to get there info somewhere, and I don't know who they can trust
right now.

Joe McGinn Impact Research Group Ltd.

* Replies:  144944, 144990

#: 144944 S15/Open Forum
    06-Jul-92  11:41:44
Sb: #144908-#Independence Declaration
Fm: Peter Coffee (PC Week) 72631,113
To: Joe McGinn 71510,3015 (X)

May I, pretty please, suggest that we're talking about ZD as if it were a
monolithic organization when this is far from the truth?  When PC Mag, PC
Week, PC Computing, et alia get together, there is considerable diversity of
opinion as to what should be tested, against what criteria, based on what
model of the target reader.  It's really a waste of time to accuse many
different publications with independent editorial management of any kind of
Windows-oriented Groupthink.

Does anyone remember a few years back, when publications were accused of being
whores for IBM and Microsoft because we did give ample space to the
then-nascent OS/2?  How people said, essentially, "Why are you trying to make
us buy 4-MB machines when DOS works so well?"  How the attitude has changed.
Guys, we write about products with potential for solving readers' needs.
Period.  Sometimes that potential is a direct result of marketplace support --
we can't limit ourselves to considering strictly the technical elegance of a
platform and ignore developer support.  Let's be realistic?

* Replies:  145040, 145097, 145136

#: 145040 S15/Open Forum
    06-Jul-92  13:51:17
Sb: #144944-Independence Declaration
Fm: mike widseth 71151,1430
To: Peter Coffee (PC Week) 72631,113

Check out V2APPS.ZIP in the FILES area for a list of 32-bit developers. It was
incomplete (I noticed), but shows a good many companies have an interest.  FYI

-Mike [Team OS/2]-

#: 145097 S15/Open Forum
    06-Jul-92  15:33:53
Sb: #144944-Independence Declaration
Fm: Michael Wade 72651,126
To: Peter Coffee (PC Week) 72631,113

Hmmmmmmm,  So you are telling me that ZD doesn't like Will Z. writing bad
things about Windows because that is the market place opinion !????   I cannot
argue that ZD owns the magazine and should have a say so about the topics. But
if they are going to claim to be objective in these articles ( reviews and Op
Ed pieces ) then they had better be able to take the good with the bad. The
particular item that upsets me is not that they asked Will to write more about
Windows, but that when he says something bad about Windows they go ape!


If they think Will is being inaccurate or just plain biased, then they should
say so.  But given the story as told here, the problem seems to more of
corporate bias.

BTW, is 700,000 copies shipped not an indication that at least a few people
think OS/2 provides some of these solutions ?

#: 145136 S15/Open Forum
    06-Jul-92  17:12:05
Sb: #144944-Independence Declaration
Fm: Joe McGinn 71510,3015
To: Peter Coffee (PC Week) 72631,113

Peter,

My statement about the lack of objectivity in the computer-press applies to
many publications, not just PC-week or other ZD mags.  For example, I've been
reading Byte for five years, and it used to be pretty good, but lately I've
noticed the same kind of biased reporting people have been complaining about
in PC-week.  Take last months issue, where they had a two-page BS NT press
release printed as news - this is a magazine that, previously, it was
difficult to get a top-quality review unless you had a top-quality product,
and you got it into their hands and proved it.  Now they print anything that's
got MS stamped on it even though the product won't even be available for at
least 6 months.  People need a magazine that gives them the straight facts,
not a lot of "buy this just because it's a Windows product even if you're
perfectly productive with your DOS program".

If you know of any magazine that has this kind of objectivity, let me know,
and I'll be more than happy to take a look at it.

Joe McGinn

#: 144990 S15/Open Forum
    06-Jul-92  12:25:49
Sb: #144908-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Joe McGinn 71510,3015 (X)

Joe,

No, I've never thought of starting a magazine.  I think that would be very
difficult and require quite a lot of funds to get started.  It is an
interesting idea, though.

Will

#: 144420 S15/Open Forum
    05-Jul-92  09:40:14
Sb: #WEASELGATE!
Fm: Patrick Pearce(SCUDMAN) 70662,2714
To: All

        As we are all aware and much to our dismay,  Will Zachmann is going to
leave Ziff-Davis at the end of September.  This as a result of pressure to
have his column, under the PC Week section "OPINION", stiffled and redirected.

         I don't know about you folks but the last time I checked the word
"Opinion" in  Websters, it meant "a view, judgement, or appraisal formed in
the mind about a particular matter."  Will's column have always reflected just
that. The apparent actions of the management of PC Week smacks of newsreels
from 1938 and drones in brown shirts...
        As such I have decided to take upon myself the task of delivering to
Ziff-Davis publications in New York City written your concerns about this
situation.
        All those interested can private E-MAIL them to me and I will
personally take them to Ziff as I live only 25 miles north of the city.


Patrick D. Pearce

* Replies:  144533, 144626, 144723, 144841

#: 144533 S15/Open Forum
    05-Jul-92  14:08:49
Sb: #144420-#WEASELGATE!
Fm: Wayne Davison 75500,2225
To: Patrick Pearce(SCUDMAN) 70662,2714 (X)

I have already drafted a letter that will be on its way to Mr. Ziff as of
tomorrow! This kind of garbage shouldn't be tolerated, or else PC Magazine
should be sold to Microsoft and renamed Microsoft Magazine so that they can be
biased all they want towards Microsoft products!

* Replies:  144596, 144603

#: 144596 S15/Open Forum
    05-Jul-92  17:37:21
Sb: #144533-WEASELGATE!
Fm: Patrick Pearce(SCUDMAN) 70662,2714
To: Wayne Davison 75500,2225

I agree...hence the title of the thread.

Patrick

#: 144603 S15/Open Forum
    05-Jul-92  17:47:25
Sb: #144533-#WEASELGATE!
Fm: Dale Lewallen [PC/C] 76000,21
To: Wayne Davison 75500,2225

Wayne..

Not sticking up for anybody here, but it is interesting that you blame all of
this on PC Magazine when, in fact, it's all been happening at PC Week.

If you want your bullet to have any effect, perhaps you want your gun to be
aimed at the right target.

-Dale

* Replies:  144679, 144756, 144761, 144855

#: 144679 S15/Open Forum
    05-Jul-92  20:03:34
Sb: #144603-WEASELGATE!
Fm: Arthur Goikhman 72170,2053
To: Dale Lewallen [PC/C] 76000,21

Why would one Ziff Davis publication be different than another?

And aren't large scale editorial issues decided by the same
people at ZD?

Arthur

* Replies:  144766, 144767, 145160

#: 144766 S15/Open Forum
    05-Jul-92  23:21:36
Sb: #144679-WEASELGATE!
Fm: Stephen A. Gutknecht 72651,31
To: Arthur Goikhman 72170,2053

>>
    Why would one Ziff Davis publication be different than another?
    And aren't large scale editorial issues decided by the same people at ZD?

<<

Look at Computer Shopper some time, a ZD publication.  All of the reviews and
such are completely self-serving, always recommending you buy mail-order items
and providing mostly inaccurate technical comparisons.

Good for advertisers, but self-serving.  What used to serve people selling
used computers and orphaned computers (TI99, Commodore 128, etc.), now takes
advantage of ignorant customers buying their first computer.  I hear again and
again how people are convinced "it must be cheaper" without any regard to what
they are even shopping for.

Read some of the reviews in PC magazine; you get the impression that ""street
price"" is your local computer store.  NOT!  They always say "you should be
able to pick one up at street price of $xxx," where this amount is some
mail-order vendor selling at $20.00 over cost on a $1000 item.  Who supports
the items?!?  Who is there to assist a purchaser in using it for a specific
need?

I'm not saying that there isn't a market for low-ball pricing, but I wish to
point out an obvious problem.  These types of magazines appeal to the NEW
(IGNORANT) PURCHASER who most likely needs the most assistance.  The magazine
promotes what sells advertising space, not what helps the customer truly save
time and money.

(cont) ...

#: 144767 S15/Open Forum
    05-Jul-92  23:21:47
Sb: #144679-WEASELGATE!
Fm: Stephen A. Gutknecht 72651,31
To: Arthur Goikhman 72170,2053

(see previous message)

Much of what I said can be applied to ZD other publications, except on a
higher level concerning operating systems and application software.  I'm not
saying that all of the reviews are inaccurate and deceptive, just that little
is done to put things in perspective.  Computers are a productivity tool.  How
can a magazine spend 30 pages reviewing 17" monitors, and only spend a few
discussing a product like OS/2?!  I'm not saying that there isn't a need for
good technical comparisions, just that they serve to sell more advertising
space.  How are you going to sell new items showing people how to get more out
of their existing computer hardware or software?

There needs to be a balance between "quest for $$," and "what is good for the
customer."  We will all tolerate advertisements on their own pages, maybe even
a biased press release in a special section.  Should we tolerate self-serving
editorial and biased reviews?

Not mentioning something, such as OS/2, can also damage credibility for a
product.  And, obviously, credibility for a magazine.

Stephen Gutknecht

* Reply:  144947

#: 144947 S15/Open Forum
    06-Jul-92  11:46:30
Sb: #144767-WEASELGATE!
Fm: Peter Coffee (PC Week) 72631,113
To: Stephen A. Gutknecht 72651,31 (X)

I write a column for PC Week that is, so far as I know, unique: it is based
strictly on interviews with our Corporate Lab Partners, about three dozen
organizations chosen to match a statistical profile of our readers, and each
week presents the buying concerns of a contact at a CLP organization. We have
talked in that column about OS/2 -- positively -- and also about Windows --
both positively and negatively.  We have also talked about 17-inch monitors,
'cause that's what Unocal was concerned about that week. And the National
Oceanic and Atmospheric Administration wants more software support for 24-bit
color.  And Baxter Healthcare Corporation wants applications to work more
cooperatively with network management utilities.

We mention what readers really care about.  We do constant research to be sure
we're living up to that goal.  Your mileage may vary.

#: 145160 S15/Open Forum
    06-Jul-92  18:20:25
Sb: #144679-WEASELGATE!
Fm: Dale Lewallen [PC/C] 76000,21
To: Arthur Goikhman 72170,2053

Arthur..

AG>> "Why would one ZD publication be different than another? And aren't large
scale editorial issues decides by the same people at ZD?"

I don't say this with rancor, Arthur, so please don't misunderstand me, but,
I'm afraid most reading this have already made up their mind, regardless of
what is true.

To answer your direct question, each publication is different because it
addresses different readerships. PC Week's constituency is different from ours
(PC/Computing's). Also, no, large scale editorial issues aren't decided by the
same people at ZD. For the same reason that there are different mags for
different readerships--there just 'aint one point of view that works for
everyone.

-Dale

#: 144756 S15/Open Forum
    05-Jul-92  22:47:36
Sb: #144603-WEASELGATE!
Fm: Bruce Leiwant 72456,777
To: Dale Lewallen [PC/C] 76000,21

 >Not sticking up for anybody here, but it is interesting that you blame all
 >of this on PC Magazine when, in fact, it's all been happening at PC Week.

Dale-

I am perplexed by trying to understand the distinction.

I know you don't shoot the father for the crimes of the son, but you may blame
the father for not bringing up the son correctly.

In this case, the son works for the father's business and the father has a
*responsibility* to AND for the son actions.

Will is/was in your family, and though your message said "not sticking up for
anybody", I find it curious that you would not, simply based upon an attempt
at censorship of the press of any kind wether you agreed with Will's opinion
or not.

                                                   Bruce/2

* Replies:  144759, 145161

#: 144759 S15/Open Forum
    05-Jul-92  23:05:13
Sb: #144756-#WEASELGATE!
Fm: Ben Sano 72401,2736
To: Bruce Leiwant 72456,777

Bruce
I don't know how you have a problem with the difference PC Magazine is a
bi-monthly which mostly covers comparative hardware and software reviews.
PC-WEEK is a weekly newspaper that is mostly interested in industry news.

They are both owned and operated by Z-D but I think the 'chain of command'
splits at the first or second level and is independent from there down.

Will Z. has from the very beginning  been clear that PC Magazine is
blameless in this and the William Zipf Jr. is also.

Does that help?

--Ben

* Replies:  144774, 144851, 144880

#: 144774 S15/Open Forum
    06-Jul-92  00:26:08
Sb: #144759-WEASELGATE!
Fm: David Coffin 76200,674
To: Ben Sano 72401,2736 (X)

>> Will Z. has from the very beginning  been clear that PC Magazine is
blameless in this and the William Zipf Jr. is also.

I don't believe that at all.  I have clearly noticed distinct bias in at least
two Ziff Publications, PC Magazine and Computer Shopper (CS).  A few weeks
back I was at odds with several CS staff people over an article which
mentioned *current* upgrade paths from existing products.  One was Windows 3.1
(which is true) and the other was NT, which is not even in beta. There was no
mention of OS/2 which was available.  The Windows 3.1 and OS/2 2.0 issue of PC
magazine was clearly biased as well.  Particularly when you consider the
article written by the Editor-in-Chief, Micheal Miller, Comparisons between
the two operating enviorments.  Or how about the 17" monitor issue where each
monitor reviewed included numerous references to Windows.

Sorry, But the buying reader *is* being ripped-off by Ziff Publications. And
those who buy those publications to get objective reviews need to be aware of
this possible conflict of interest.

#: 144851 S15/Open Forum
    06-Jul-92  07:06:21
Sb: #144759-WEASELGATE!
Fm: Raymond Chuang 72441,3652
To: Ben Sano 72401,2736 (X)

Ben,

Then in this case Will Zachmann should quit his PC Week column IMMEDIATELY but
stay on at PC Magazine. After all, the columns in PC Magazine by their regular
columnists aren't exactly friendly to Microsoft, too.

Raymond Chuang

#: 144880 S15/Open Forum
    06-Jul-92  08:12:32
Sb: #144759-#WEASELGATE!
Fm: Bruce Leiwant 72456,777
To: Ben Sano 72401,2736 (X)

 I don't know how you have a problem with the difference PC Magazine is a
 bi-monthly which mostly covers comparative hardware and software reviews.
 PC-WEEK is a weekly newspaper that is mostly interested in industry news.

 They are both owned and operated by Z-D but I think the 'chain of command'
 splits at the first or second level and is independent from there down.

 Will Z. has from the very beginning  been clear that PC Magazine is
 blameless in this and the William Zipf Jr. is also.

 Does that help? ============================

Ben-

Not really.  You are talking frequency of publication, and publication target.
I am talking moral responsibility.

                                                              Bruce/2

* Reply:  144885

#: 144885 S15/Open Forum
    06-Jul-92  08:19:35
Sb: #144880-#WEASELGATE!
Fm: Ben Sano 72401,2736
To: Bruce Leiwant 72456,777 (X)

Bruce

OK, how is PC-Magazine morally responsible for the actions of the people who
work for PC-WEEK?

--Ben

* Reply:  145005

#: 145005 S15/Open Forum
    06-Jul-92  12:46:41
Sb: #144885-#WEASELGATE!
Fm: Bruce Leiwant 72456,777
To: Ben Sano 72401,2736 (X)

 >OK, how is PC-Magazine morally responsible for the actions of the people who
 >work for PC-WEEK?

 Ben It's not PCMag's responsibility... if you intrepreted that, either I was not
 as precise or you mis-intrepreted what I said.

 There's an expression I am sure you are familiar with, "The Buck Stops Here".

 In this case, *I* feel, and you can disagree, of course, that the "here" is
 the very end of the line, Mr. Ziff.

                                                                 Bruce/2

* Reply:  145057

#: 145057 S15/Open Forum
    06-Jul-92  14:38:53
Sb: #145005-WEASELGATE!
Fm: Ben Sano 72401,2736
To: Bruce Leiwant 72456,777 (X)

Bruce
I get it now.

--Ben

#: 145161 S15/Open Forum
    06-Jul-92  18:20:31
Sb: #144756-WEASELGATE!
Fm: Dale Lewallen [PC/C] 76000,21
To: Bruce Leiwant 72456,777 (X)

Bruce..

I'm sorry but I didn't really understand your message--perhaps it's because I
threw my back out and it really hurts.

No matter, I'll try to clarify what I meant when I said that I was "not
sticking up for anybody." I meant that _I_ didn't know the facts of the case.
I know what Will _said_, and I know that Sam Whitmore at PCWeek made a short
statement but I don't know who's right (and I suspect lots of people jumping
to support Will don't _know_ who's right.) I'm also not saying Will is not
telling the truth, but you know that it's possible to leave things out, put
different spins on things, etc. I'm certain that Will believes himself to be
right, even if he _might_ not be right.

Anyway, I was just trying to point out that I don't _know_ who's right and so
I wasn't defending anybody, neither Will nor PCWeek..

Does that help?

-Dale

#: 144761 S15/Open Forum
    05-Jul-92  23:08:35
Sb: #144603-WEASELGATE!
Fm: Wayne Davison 75500,2225
To: Dale Lewallen [PC/C] 76000,21

I'm not blaming it all on PC Magazine, but that's the magazine I read the
most, and there is hardly any OS/2 coverage in it, but there's plenty of
Windows coverage.

I have also seen people complaining on PC Magazines forum that PC Magazine
seems biased towards Microsoft and biased against IBM, so I'm talking about
what I know best.

I really don't know what exactly happened at PC Week, but it sounds like it's
just more of the same.

#: 144855 S15/Open Forum
    06-Jul-92  07:08:12
Sb: #144603-#WEASELGATE!
Fm: Marvin Nipper 70142,3166
To: Dale Lewallen [PC/C] 76000,21 (X)

<< but it is interesting that you blame all of this on PC Magazine when, in
fact, it's all been happening at PC Week.>>

Not hardly!  PC Mag has been every bit as biased.  I've written letters
because of the blatant bias.  And it's not just at the editorial level.  When
"Advisor" columns, written in response to legitimate questions from
"unsuspecting" users tell people to ignore OS/2, because Windoze (3.1) pretty
much offers the same thing (not even bothering to mention such things a
Multi-tasking, etc.), then I'd call that EXTREME bias, hardly a "balanced,
responsible, response".  It's one thing for IBM to have to fend off the
legitimate problems with OS/2, like some of the hardware support issues in the
initial GA release.  It's another thing entirely, when biased publications,
poison users minds with PURE GARBAGE, such that IBM has to spend all of it's
initial efforts just trying to CORRECT all the lies and misconceptions about
the product, before it can begin to truly market the product.

Needless to say, I have a STRONG opinion about your statement <G>.  I will
note further, that NONE of my letters to PC Mag, regarding their "reporting",
were EVER published.  It seems they're not too much into the "constructive
criticism" approach.
............Marvin

* Reply:  145162

#: 145162 S15/Open Forum
    06-Jul-92  18:20:37
Sb: #144855-WEASELGATE!
Fm: Dale Lewallen [PC/C] 76000,21
To: Marvin Nipper 70142,3166

Hi, Marvin.. It's nice to calmly share views about things, isn't it?

I was _specifically_ referring to the Zachmann incident. I won't argue with
you re: your opinions, nor will I even try to defend PC Magazine for their
editorial content. I was just pointing out in my original message in this
thread that a lot of people are blaming PCMagazine for the Zachmann thing
when, so far, it seems to be solely an issue between Will and PC Week. I'll
recant if that's not true but I've not seen anything from Will to support it..

-Dale

#: 144626 S15/Open Forum
    05-Jul-92  18:26:04
Sb: #144420-WEASELGATE!
Fm: Howard Weatherly [CTG] 71327,1575
To: Patrick Pearce(SCUDMAN) 70662,2714


Comrade Scudman,

When I saw Wills post I replied that time may not permit writing, but I am
beginning to believe that I should add my words to this "Weaselgate" matter.
When do expect to go? my time is slim this week as I am almost on my way out
the door, but will e-mail something next week if it fits into your schedule.

--Howard (Team OS/2)

* Reply:  144809

#: 144809 S15/Open Forum
    06-Jul-92  03:33:16
Sb: #144626-WEASELGATE!
Fm: Patrick Pearce(SCUDMAN) 70662,2714
To: Howard Weatherly [CTG] 71327,1575 (X)

Howard,

I will be in the city on thursday of this week. I'll make another trip in next
week if it's necessary.

Patrick

Forum !

* Reply:  145188

#: 145188 S15/Open Forum
    06-Jul-92  18:57:33
Sb: #144809-WEASELGATE!
Fm: Joe Subich 71350,1204
To: Patrick Pearce(SCUDMAN) 70662,2714


Patrick,

What word processor format can you handle or would you prefer an ASCII text
file.  Even though I'm vacationing this week (and trying to stay away from the
office computers), I will take time to put something on paper in this matter.
The policies at PCweak, Windows [nee PC] Magazine, and Computer Rip-off (and I
have received all three for several years) for editorial honesty, technical
quality, and now editorial freedom are totally screwed up.

Perhaps the loss of a gentleman with Mr. Zachmann's stature will serve as a
wake-up call to Mr. Ziff.  If not, I can only hope that Messers Dvorak,
Seymour, Salemi, and others will have the guts to follow (soon).  Otherwise, I
will be evaluating my subscriptions very carefully when they are due for
renewal late this fall.

     ... Joe

#: 144723 S15/Open Forum
    05-Jul-92  21:23:34
Sb: #144420-WEASELGATE!
Fm: Warren Zeigler 70662,1710
To: Patrick Pearce(SCUDMAN) 70662,2714

Patrick - (to take to ZD)

ZD is trying to grow - and is advertising the large lab they have set up. Why
bother? If I cannot trust the objectivity of ZD, I cannot afford the time to
read from ZD. I also cannot afford to argue against mis-information from ZD
that managers at work have gained - so I will post what has happened so far -
and the future results - at all compainies I work for/with.

I reccomend the same to others here. Fighting for sanity in PC hardware and
software purchases is hard enough. Let's get rid of ALL non-objective reports
that we can.

Warren Zeigler

#: 144841 S15/Open Forum
    06-Jul-92  06:34:22
Sb: #144420-#WEASELGATE!
Fm: Dave Bennett 75470,2351
To: Patrick Pearce(SCUDMAN) 70662,2714 (X)

Do you really believe that hauling a bunch of letters down from "OS/2 zealots"
is going to do the trick? I think not. Actually, the best way to act is to
stop purchasing any products from ANY company that advertises in a ZD
publication. If others are hurt, they'll either pull their ads in tacit
support of objectivity because their bottom line is being touched, or they'll
take the same side as MS and ask for special objectivity in their favor. A one
week boycott of any product in a ZD publication by the entire industry would
have a little more voice than a handful of pages.

dave

* Replies:  144863, 144965, 145006

#: 144863 S15/Open Forum
    06-Jul-92  07:18:43
Sb: #144841-#WEASELGATE!
Fm: Patrick Pearce(SCUDMAN) 70662,2714
To: Dave Bennett 75470,2351 (X)

David,

Intersting comment. So I went back to the hardcopies sent and did a complete
scan. In not one of the email messages is there a mention of OS/2. Secondly,
75 to 80% of the messages received are from individuals whom I have never
heard of.  I agree that a boycott should begin. So why don't YOU start a
thread suggesting just that. All I'm trying to do is support Will and possibly
help achieve a positive outcome for all of us.

Patrick

* Reply:  145191

#: 145191 S15/Open Forum
    06-Jul-92  19:03:30
Sb: #144863-WEASELGATE!
Fm: Bruce Leiwant 72456,777
To: Patrick Pearce(SCUDMAN) 70662,2714

Patrick-

I must have missed the initial announcement on this... are you collecting
CISMAIL letters to Ziff protesting the treatment of Will Z ?

#: 144965 S15/Open Forum
    06-Jul-92  12:02:58
Sb: #144841-#WEASELGATE!
Fm: CyberSim [E. Pinnell] 70031,435
To: Dave Bennett 75470,2351 (X)

Dave,

     I do not intend to renew my Ziff subscriptions. Screw 'em!

Eric Pinnell

* Reply:  145007

#: 145007 S15/Open Forum
    06-Jul-92  12:50:11
Sb: #144965-WEASELGATE!
Fm: Raymond Chuang 72441,3652
To: CyberSim [E. Pinnell] 70031,435

Eric,

How about doing a boycott of ZiffNet and ZiffNet/Mac?

Raymond Chuang

#: 145006 S15/Open Forum
    06-Jul-92  12:50:06
Sb: #144841-#WEASELGATE!
Fm: Raymond Chuang 72441,3652
To: Dave Bennett 75470,2351 (X)

Dave,

If you intend to boycott any company that advertises in a Ziff-Davis
publication, you're pretty much talking about boycotting the entire desktop
computer industry, sorry to say!! <g> And that includes most Macintosh
products (Z-D publishes MacUser and MacWeek).

Raymond Chuang

* Reply:  145109

#: 145109 S15/Open Forum
    06-Jul-92  15:47:03
Sb: #145006-WEASELGATE!
Fm: Dave Bennett 75470,2351
To: Raymond Chuang 72441,3652

So? The industry as a whole (manufacturers) would have to take a stand on
whether they are going to support unbiased reporting or not. As consumers we
can most effectively vote with our dollars, not our mouths or letters.

dave

ÿ
