
#: 210070 S10/Views:Zachmann [E]
    04-Jul-92  11:29:48
Sb: #Independence Declaration
Fm: William F. Zachmann 72241,43
To: All

I can think of no better occasion than the Fourth of July to declare
independence from those who would dictate the content of what I write.  Over
the past several months, I have been repeatedly subject to what I feel to be
inappropriate and improper pressure from PC Week in regard to my views on
Microsoft and Windows, IBM and OS/2.

I had hoped that this was a temporary aberration that would soon be corrected.
Unfortunately, that does not seem to be the case.  I have therefore sent
notice to the Ziff-Davis Publishing Company that I do not intend to renew my
agreement with them when its current term expires at the end of September.

I believe that Mr. William Ziff, Jr. is genuinely committed to editorial
integrity and independence.  Unfortunately, I think Mr. Ziff is being
ill-served by some of his employees who do not share that commitment.  I am
concerned that the regretable tendency to shape editorial content to please a
major advertiser (Microsoft in this case) which I have noted in some competing
publications is being imported into the Ziff-Davis Publishing Company.

If you share my concern, you may want to write to Mr. William Ziff, Jr., Ziff
Davis Communications, One Park Avenue, New York, NY, 10016 and let him know
what you think. Please feel free to repost this messages elsewhere if you
wish.

William F. Zachmann

* Replies:  210094, 210100, 210106, 210110, 210135, 210186, 210229, 
            210231, 210261, 210263, 210480, 210573, 210863

#: 210094 S10/Views:Zachmann [E]
    04-Jul-92  12:33:25
Sb: #210070-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: William F. Zachmann 72241,43 (X)

Will,

I read your "Independence Declaration" with great sadness.

Will this only involve PC Week, or will your column in PC Magazine also cease?

     Bruce

* Reply:  210146

#: 210146 S10/Views:Zachmann [E]
    04-Jul-92  17:23:14
Sb: #210094-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Bruce Biermann [ZiffNet] 72241,261 (X)

 >I read your "Independence Declaration" with great sadness.

 >Will this only involve PC Week, or will your column in PC Magazine also
 >cease?

Bruce,

I wrote it with great sadness.  My agreement with Ziff-Davis Publishing
Company covers my entire relation with them including PC Magazine.  I am not
at all happy about these events, but I do not feel I can continue to write for
them if I do not have a reliable assurance than I will be permitted to say
what I think ought to be said.  I have patiently sought such assurance for
weeks now with the only result being the emergence of more subtle ways to
muffle me, the latest being clear indications of an intention to, in effect,
design my column out of PC Week.

Were I simply to acquiesce to that, I would be setting a precedent of
compromising principles that I feel ought not to be compromised.  I have
therefore chosen, after much deliberation, to put my entire relation with Z-D
Publishing on the line at the sacrifice of substantial income to myself.

Will

* Replies:  210196, 211128

#: 210196 S10/Views:Zachmann [E]
    04-Jul-92  20:46:25
Sb: #210146-#Independence Declaration
Fm: Raymond Chuang 72441,3652
To: William F. Zachmann 72241,43 (X)

Will,

Personally, I think you should have a one-on-one talk with Bill Ziff, Jr.

Given the fact that your columns attract many readers to PC Week and PC
Magazine, your resignation from Ziff-Davis will create a major hole in the
writing of these magazines.

Question is, who can replace you? Are there people here in this forum who can
step in and write good columns like you do?

(Oh Haig--how about it?) <g>

Raymond Chuang

* Reply:  210260

#: 210260 S10/Views:Zachmann [E]
    05-Jul-92  06:33:13
Sb: #210196-#Independence Declaration
Fm: Haig Hovaness 70210,362
To: Raymond Chuang 72441,3652 (X)

Will Zachmann is a remarkably talented observer of the PC marketplace.  I have
enjoyed his writing for years, and his presence on PC-Magnet is what attracted
me to this forum.  If Will's editorial freedom has been improperly infringed
by editorial pressures, Z-D has made a grave error.

I think Ziff needs to act swiftly to put forward its own position.  Absent a
credible response to Will's statements, the value of the whole Z-D PC
publishing franchise will be damaged.

* Replies:  210273, 210326, 210334, 210575

#: 210273 S10/Views:Zachmann [E]
    05-Jul-92  08:12:31
Sb: #210260-#Independence Declaration
Fm: Ben Sano 72401,2736
To: Haig Hovaness 70210,362 (X)

Haig
It will take some strong evidence too as it is obvious who has something to
gain by lying here and who has something to lose by telling the truth.

I doubt that a creditable rebutal is possible.

--Ben<although if they were to ban MS advertising in Z-D computer magazines
for the next 3 months I might believe that they were serious>

* Reply:  210362

#: 210362 S10/Views:Zachmann [E]
    05-Jul-92  13:51:04
Sb: #210273-#Independence Declaration
Fm: Haig Hovaness 70210,362
To: Ben Sano 72401,2736 (X)

There is a fine line between the legitimate guidance excercised by an editor
over a columnnist and blatant interference in the writing of the column.  If
PC Week editors have crossed that line, they are at fault.  If Will is simply
resisting a change in subject matter, then he may not be entirely right.  By
going public with the dispute, Will has seriously escalated the conflict.
Whatever the outcome now, the damage will be considerable.  The failure to
contain this incident and reach an appropriate compromise reflects badly on
PC-Week editorial management.

* Reply:  210824

#: 210824 S10/Views:Zachmann [E]
    06-Jul-92  12:06:46
Sb: #210362-Independence Declaration
Fm: CyberSim [E. Pinnell] 70031,435
To: Haig Hovaness 70210,362 (X)

Haig,

    Wow, a first. I actually agree with you on this one.

Eric Pinnell

#: 210326 S10/Views:Zachmann [E]
    05-Jul-92  11:15:57
Sb: #210260-#Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Haig Hovaness 70210,362 (X)

Haig,

Eric Hippeau was a guest on the ZNT:SOURCES forum last week--I hope he shows
up here within the next few days and clarifies the entire situation.

(getting on soapbox)

Anyway, I doubt that Bill Gates himself was directly responsible for this
whole mess--my only suggestion is that Gates order the termination of any
employee of Microsoft and/or Waggoner Edstrom who tried to influence the
editors at PC Week magazine.

The implications of this could blow up into a major scandal, to say the
least.

(getting off soapbox)

Raymond Chuang

* Replies:  210349, 210367, 210413, 210540, 210784, 211129

#: 210349 S10/Views:Zachmann [E]
    05-Jul-92  12:46:34
Sb: #210326-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Raymond Chuang 72441,3652 (X)

Raymond,

Come on.  Why shouldn't Microsoft, IBM, Borland, et al. try to influence the
media?

The real question is why did the editors at PC Week allow themselves to be
influenced.

    Bruce

* Replies:  210351, 210385

#: 210351 S10/Views:Zachmann [E]
    05-Jul-92  13:09:59
Sb: #210349-Independence Declaration
Fm: Ben Sano 72401,2736
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Bruce
I think the real question is 'After the matter was brought to Mr. Zipf's
attenion. Why was it allowed to persist?'

Every organization has some folks who do the wrong thing.

In a functioning organization these people are corrected, moved or
terminated.

Why wasn't that done here?

--Ben

#: 210385 S10/Views:Zachmann [E]
    05-Jul-92  13:59:59
Sb: #210349-#Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Bruce Biermann [ZiffNet] 72241,261 (X)

We haven't shown that there was influence to the point that the Z-Man
believes. I am not doubting that Will *believes* it.. Just question if the
editors really think they did or if "independants" would conclude there was
influence peddling.. Let's get a special prosecutor.. Joan Brewer!

Rick

* Replies:  210423, 210452, 210517

#: 210423 S10/Views:Zachmann [E]
    05-Jul-92  15:47:39
Sb: #210385-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Rick Segal-Microsoft 76276,2706 (X)

Rick,

I thought Joan Brewer already was a "special prosecutor."  She is to me,
anyway.

The phone call from Microsoft to Zachmann is enough evidence for me to
indicate unacceptable influence.  For Will to get a call immediately after his
meeting with Sam, and for Microsoft to know the content of that meeting, well,
that is just inappropriate for a reputable publication.

If the editor of PC Week denies calling Microsoft and disclosing the
discussions he had with Will, then I will reexamine my views.  Please note, I
don't fault your employer at all.

    Bruce

* Replies:  210431, 210476

#: 210431 S10/Views:Zachmann [E]
    05-Jul-92  16:01:44
Sb: #210423-#Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Sorry, Bruce.. I am having a tough time thinking John Dodge would "bend over"
for Microsoft. Just doesn't fit. Too much real, shall we say, personalities,
involved. John, as I have said, is not one of my favorite press folk, but he
is just not the type to compromise his paper for an advertiser, esp. MS. Sam,
on the other hand, is also just flat not the type, sorry.. I will rag on Dodge
or PC-Week til the cows come home, but I would not want to debate either's Sam
or John's ethics as they are pretty high, in my opinion.. Both guys, in my
opinion, would resign rather than compromise their ethics.

All of the above is just my opinion. John, Sam, just take this too seriously
too be part of a kill Will cuz MS sez so plan..

This is what confuses me.. All the players (Will incl.) don't fit the plot..

Rick

* Replies:  210440, 211130

#: 210440 S10/Views:Zachmann [E]
    05-Jul-92  16:41:29
Sb: #210431-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Rick Segal-Microsoft 76276,2706 (X)

Rick,

I'm not dealing with the personalities because I don't know all the
participants.  I don't even know who at Microsoft called Will.  What I am
concerned with is the integrity and independence of a publication that I rely
on for news, opinion, and comparative testing.

    Bruce

* Reply:  210556

#: 210556 S10/Views:Zachmann [E]
    05-Jul-92  23:03:20
Sb: #210440-Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Okay.. I just repeat that I find this situation weird..

I'm done.. I'm sitting down now <G>

Rick

#: 211130 S10/Views:Zachmann [E]
    06-Jul-92  23:36:18
Sb: #210431-#Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Rick Segal-Microsoft 76276,2706 (X)

Yes, I honestly think we need to look for some sort of misunderstanding; but
until Sam or the someone at Microsoft is able to explain why Will received
that phone call, I believe Will is justified in being public in demanding
answers.  He's just doing to Z-D what Z-D does to IBM or MS whenever given
half a chance--forcing accountability and demonstrating respect for "the
people's right to know."  A separate issue is "what will the people do?"

I'm somewhat concerned that the topic of MS advertising as a blunt instrument
and their policy towards other companies and aggressiveness in PR has still
received almost no serious press coverage.  MS SEEMS to operate in almost a
moral vacuity with impunity.

I won't put you on the spot, Rick, by asking about any of this--I have too
much respect for you personally...

#: 210476 S10/Views:Zachmann [E]
    05-Jul-92  19:11:54
Sb: #210423-#Independence Declaration
Fm: Monte Davis 71450,3542
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Agreed... absent any other explanation for the timing of that phone call, I'd
say that alone is damning. Forget about editorial policy, advertisers'
pressure, and the rest of it -- heck, forget publishing and journalistic
integrity for the moment. In *any business, if I talk to my boss about how I'm
handling a "third party" outside the company, with the usual assumptions about
privacy, and have reason to think he's on the phone to that third party the
minute I leave his office... I'm outtathere.

(Then again, I've been freelance for 19 of the last 20 years, so WTFDIK?)

#: 210452 S10/Views:Zachmann [E]
    05-Jul-92  17:33:55
Sb: #210385-#Independence Declaration
Fm: Patrick Pearce (SCUDMAN) 70662,2714
To: Rick Segal-Microsoft 76276,2706 (X)

Rick,

<Let's get a special prosecutor.. Joan Brewer!>

Bow shot....well taken! Not bad <G>

#: 210517 S10/Views:Zachmann [E]
    05-Jul-92  21:10:44
Sb: #210385-Independence Declaration
Fm: Charles Hart 72755,500
To: Rick Segal-Microsoft 76276,2706 (X)

 >Let's get a special prosecutor.. Joan Brewer!

Old Chinese proverb:  "Be careful of what you wish for:  You just might get
it!"

#: 210367 S10/Views:Zachmann [E]
    05-Jul-92  13:51:50
Sb: #210326-#Independence Declaration
Fm: Haig Hovaness 70210,362
To: Raymond Chuang 72441,3652 (X)

Unfortunately, Will has decided to go nuclear with this thing, and it is
probably going to get into the general business press.  Right or wrong, PC
Week blew it big-time by letting the controversy reach this unfortunate stage.
Just when things are coming together nicely for Z-D, they risk their
reputation for integrity on a tussle that a single well-worded memo could have
resolved.  What a shame.

* Replies:  210412, 210460, 210901

#: 210412 S10/Views:Zachmann [E]
    05-Jul-92  14:53:48
Sb: #210367-#Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Haig Hovaness 70210,362 (X)

Haig,

I hate to say this, but Will Zachmann going public with this could only mean
one thing: hello pink slip. (no grin)

Given Earle's description of William Ziff, Jr. being a VERY private man, I
personally think that is not impossible.

Raymond Chuang

* Reply:  210580

#: 210580 S10/Views:Zachmann [E]
    05-Jul-92  23:51:56
Sb: #210412-Independence Declaration
Fm: earle robinson [ibmeur] 76004,1762
To: Raymond Chuang 72441,3652 (X)

Please note that I do not know bill ziff.  I was recounting his reputation,
which is that he is not publicity hungry, i.e. wishes his privacy.
   -er

#: 210460 S10/Views:Zachmann [E]
    05-Jul-92  18:05:55
Sb: #210367-#Independence Declaration
Fm: Patrick Pearce (SCUDMAN) 70662,2714
To: Haig Hovaness 70210,362 (X)

Haig...

<Unfortunately, Will has decided to go nuclear with this thing,...>

Does that me I get to give Will my forum Alias? <G>

Patrick

* Reply:  210825

#: 210825 S10/Views:Zachmann [E]
    06-Jul-92  12:06:58
Sb: #210460-Independence Declaration
Fm: CyberSim [E. Pinnell] 70031,435
To: Patrick Pearce (SCUDMAN) 70662,2714 (X)

Naw,

    It means will have to call Will "Nukehead" or "Mushroom Cloud"<G>.

Eric Pinnell

#: 210901 S10/Views:Zachmann [E]
    06-Jul-92  15:08:26
Sb: #210367-Independence Declaration
Fm: Duke Lane 76004,2356
To: Haig Hovaness 70210,362 (X)

HH: "Unfortunately, Will has decided to go nuclear with this thing, and it is
probably going to get into the general business press. Right or wrong, PC Week
blew it big-time by letting the controversy reach this unfortunate stage. Just
when things are coming together nicely for Z-D, they risk their reputation for
integrity on a tussle that a single well-worded memo could have resolved. What
a shame."

----------

Haig, I agree with you 1000%.

--Duke

<pinch> Yup

#: 210413 S10/Views:Zachmann [E]
    05-Jul-92  14:57:18
Sb: #210326-Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Raymond Chuang 72441,3652 (X)

Raymond, Eric Hippeau was the guest on the Computer Shopper forum last week.
                                -- T.

#: 210540 S10/Views:Zachmann [E]
    05-Jul-92  22:50:26
Sb: #210326-#Independence Declaration
Fm: Wayne Robertson (SAMC) 76546,560
To: Raymond Chuang 72441,3652 (X)

Raymond,

At the risk of sounding a little simplistic, I expect vendors of all sizes to
put pressure on all types of organizations and people.  Even I get a fair
amount of "pressure" from a wide variety of vendors to purchase or endorse
products for my company.  This I expect.

However, that does not mean I will buy everything in sight just to please a
vendor.  The same goes for publications.  I expect advertisers to try to
influence and I also expect publication management to tell them fly a kite or
someting similar.

-Wayne

* Reply:  210669

#: 210669 S10/Views:Zachmann [E]
    06-Jul-92  07:05:23
Sb: #210540-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Wayne Robertson (SAMC) 76546,560 (X)

Wayne,

That type of pressure is called "salesmanship." <grin>

Actually, IF what Will said is true, then we're talking about compromising the
supposed editorial independence of PC Week itself.

(Personally, I think Microsoft has gotten so influential that it's kind of
hard to AVOID them in any discussion of the desktop computer industry)

Raymond Chuang

#: 210784 S10/Views:Zachmann [E]
    06-Jul-92  11:11:01
Sb: #210326-#Independence Declaration
Fm: Gordon McComb 73155,353
To: Raymond Chuang 72441,3652 (X)

<...order the termination of any employee of Microsoft and/or Waggoner-Edstrom
who tried to influence the editors at PC Week Magazine.>

Actually, what's so unusual about this?  I guess it comes down to the type of
influence that was attempted.  Microsoft's position with the press is
inherently unstable, and it would be difficult to apply pressure in any way
that wouldn't backfire.  For example, could MS effectively cancel ads in ZD
publications?  I can see the higher-ups at Borland and WordPerfect jumping up
and down at that thought.  MS would have to be _really_ stupid to do something
like this.

Or, could MS have inferred that they'd withhold vital pre-release info to ZD
publications?  Again, it would be like shooting themselves in the foot.  MS
has become masters at manipulating the press by providing very early beta of
products and by being "open" to select members of that press (Microsoft has
done this since at least 1983, when Pam Edstrom invited me up to MS for
meetings with everyone -- including Mr. G -- and I have to admit I've had a
generally favorable view of the company since).  To discard this effective
approach would be suicidal.

I'm not saying something strange didn't happen between MS and ZD, but I doubt
it was anything as simple as canceling advertising or making it tough for PCW
or PCM magazine to get their hands on pre-release MS products. That's far too
simplistic, and it doesn't make sense.

-- Gordon

* Reply:  211051

#: 211051 S10/Views:Zachmann [E]
    06-Jul-92  20:52:52
Sb: #210784-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Gordon McComb 73155,353

Gordon,

I think what has happened is that Mr. Zachmann feel wronged by PC Week because
he felt that PC Week's editorial department was in possible collusion with
somebody in the Microsoft Marketing Department.

I hope this mess gets sorted out before something even MORE serious happens.

Raymond Chuang

#: 211129 S10/Views:Zachmann [E]
    06-Jul-92  23:36:13
Sb: #210326-#Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Raymond Chuang 72441,3652

I'm in favor of any industry self-examination.  It seems a little too wild and
woolly, with too little accountability and respect for ethics.  A free press
is necessary to enforce ethics through normative pressures--and when the press
is compromised, ethical accountability is no longer as effective.

Some examples that cause me personally to be concerned are that Z-D is jointly
sponsoring, with Microsoft, an initiative to make "Windows Compatibility" the
hardware standard, and that Z-D published for Microsoft a booklet of some kind
to accompany Windows 3.1.  Depending on how Z-D is compensated for these
partnerships, and depending on how Z-D employees share in the financial
well-being of Z-D as a whole, e.g. profit-sharing, there is at least the
potential for serious conflicts of interest...

#: 210334 S10/Views:Zachmann [E]
    05-Jul-92  12:13:11
Sb: #210260-#Independence Declaration
Fm: Keith Pleas 72331,2150
To: Haig Hovaness 70210,362 (X)

Haig:

Re: his presence on PC-Magnet is what attracted me to this forum

Me too.

* Reply:  210368

#: 210368 S10/Views:Zachmann [E]
    05-Jul-92  13:51:56
Sb: #210334-Independence Declaration
Fm: Haig Hovaness 70210,362
To: Keith Pleas 72331,2150 (X)

I still can't believe this is happening.

#: 210575 S10/Views:Zachmann [E]
    05-Jul-92  23:39:16
Sb: #210260-Independence Declaration
Fm: Frank Ivan 75300,1406
To: Haig Hovaness 70210,362 (X)

Haig,

Well said.  My PC magazine subscription is up for renewal (July was the last
issue).  I think thats one check  I am not going to be writting anytime soon.

Cheers - Frank

#: 211128 S10/Views:Zachmann [E]
    06-Jul-92  23:36:06
Sb: #210146-#Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: William F. Zachmann 72241,43 (X)

Will, what principles would be compromised if you didn't take this action?  I
honestly believe there are a lot of people who don't understand and think it
would be worth your while to elaborate on the principles themselves...

* Reply:  211170

#: 211170 S10/Views:Zachmann [E]
    07-Jul-92  01:03:32
Sb: #211128-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Dave Whittle [IBM] 70303,1352

Dave,

In the narrow sense, the key principle is that when someone who is not an
employee of a publication writes an opinion column, the opinions expressed
ought to be those of the writer, not those of the editors of the publication.

In a broader sense, the principle is that readers ought to be able to assume
that what they read in a publication generally represents the honest views and
assessments of those who write them rather than be dictated by other interests
behind the scenes.

In the broadest sense, the principle is of freedom of expression, not only in
the strictly legal definition thereof, but in what that principle is generally
understood to mean -- the right of people to say what they think.

Will

#: 210100 S10/Views:Zachmann [E]
    04-Jul-92  13:22:49
Sb: #210070-#Independence Declaration
Fm: Patrick Pearce (SCUDMAN) 70662,2714
To: William F. Zachmann 72241,43 (X)

Will,

I feel like the kid in the movie about the Chicago Black Sox..."Say it ain't
so Will... Say it ain't so!"

Well, we'll just have to avalanche Mr. Ziif with letters....

What's that they say "How do we do it....VOLUME, VOLUME, VOLUME!"

I hereby call this whole affair "WEASELGATE!" and humbly pick up the banner
for truth, justice, and the American way!

* Reply:  210139

#: 210139 S10/Views:Zachmann [E]
    04-Jul-92  17:19:17
Sb: #210100-#Independence Declaration
Fm: CyberSim [E. Pinnell] 70031,435
To: Patrick Pearce (SCUDMAN) 70662,2714 (X)

Scud,

    Inform the Provisional Wing that we mobilize against Ziff.<no G>

Fidel

* Reply:  210155

#: 210155 S10/Views:Zachmann [E]
    04-Jul-92  17:41:29
Sb: #210139-Independence Declaration
Fm: Patrick Pearce (SCUDMAN) 70662,2714
To: CyberSim [E. Pinnell] 70031,435 (X)

Fidel,

        The order has been given.  The STAELTH SCUDJET is loaded with
leaflettes for a mid-day Monday drop over Manhattan.

Scud

#: 210106 S10/Views:Zachmann [E]
    04-Jul-92  13:52:43
Sb: #210070-Independence Declaration
Fm: Ben Sano 72401,2736
To: William F. Zachmann 72241,43 (X)

Will
I wish I could say I'm supprised but when no one was fired at PC-WEEK I
figured that this would have to be the outcome.

--Ben

#: 210110 S10/Views:Zachmann [E]
    04-Jul-92  15:00:25
Sb: #210070-#Independence Declaration
Fm: Orville Fudpucker[SysOp] 72241,105
To: William F. Zachmann 72241,43 (X)

Aw Rats!  I sure hate to hear that, but I appreciate your stab at integrity.

I hope that's it's not irrecovable, and that all can be made well again (but
of course, it won't be quite the same)

Gee, I'm just about to finally get a subscription to PC Week and see what it's
all about.  :-(

Other than that, how's the fourth?

* Replies:  210147, 210911

#: 210147 S10/Views:Zachmann [E]
    04-Jul-92  17:23:18
Sb: #210110-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Orville Fudpucker[SysOp] 72241,105 (X)

 >I hope that's it's not irrecovable, and that all can be made well again
 >(but of course, it won't be quite the same)

Whether or not all can be made well again depends, at this point, on the
reaction from Ziff-Davis.

 >Other than that, how's the fourth?

Rainy.

* Replies:  210541, 210902

#: 210541 S10/Views:Zachmann [E]
    05-Jul-92  22:50:31
Sb: #210147-Independence Declaration
Fm: Wayne Robertson (SAMC) 76546,560
To: William F. Zachmann 72241,43 (X)

William,

I was very wrong.  I told my child that the only fireworks were down at the
local high school.  I didn't think of ZiffNet!<g>

-Wayne

#: 210902 S10/Views:Zachmann [E]
    06-Jul-92  15:08:32
Sb: #210147-#Independence Declaration
Fm: Duke Lane 76004,2356
To: William F. Zachmann 72241,43 (X)


 >Other than that, how's the fourth?

Rainy.
 >> Other than that, how's the fourth?
 > Rainy.

Greetings from the Texas Republic. Don't ask me the same question, you won't
enjoy the answer....<G>

--Duke (aka Lobster-man)

* Reply:  210947

#: 210947 S10/Views:Zachmann [E]
    06-Jul-92  18:07:58
Sb: #210902-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Duke Lane 76004,2356 (X)

Hiyah, Duke!  How's married life treating you?  Felicitaciones!  We should
talk again some time soon, no?

Will

* Reply:  210995

#: 210995 S10/Views:Zachmann [E]
    06-Jul-92  19:16:18
Sb: #210947-#Independence Declaration
Fm: Duke Lane 76004,2356
To: William F. Zachmann 72241,43 (X)

We should talk again sometime soon, yes. Married life is no different than
living in sin except for the name change. ;-D

--Duke

* Reply:  211011

#: 211011 S10/Views:Zachmann [E]
    06-Jul-92  19:55:47
Sb: #210995-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Duke Lane 76004,2356

Duke,

Will you be at the Win/OS2 show in Boston in August?

Will

#: 210911 S10/Views:Zachmann [E]
    06-Jul-92  16:07:39
Sb: #210110-Independence Declaration
Fm: earle robinson [ibmeur] 76004,1762
To: Orville Fudpucker[SysOp] 72241,105 (X)

>other thanthat, how's the fourth?

Like the very famous french skit about the marquise who learns of complete
catastrophe at here home.  At each new one, she asks, "so, other than that, how
are things?", and the invariable answer is, "tout va bien madame la marquise,
sauf....":  the horse died, the house burned down, her son drowned, etc. etc.
Thus, there is the expression used 'tout va bien, madame la marquise!'.
   -er

#: 210135 S10/Views:Zachmann [E]
    04-Jul-92  17:14:11
Sb: #210070-#Independence Declaration
Fm: Raymond Chuang 72441,3652
To: William F. Zachmann 72241,43 (X)

Will,

I'm sorry you're leaving!! But do hang around CIS, at least on the CIS:IBMOS2
forum. B^(

Raymond Chuang

* Reply:  211131

#: 211131 S10/Views:Zachmann [E]
    06-Jul-92  23:36:25
Sb: #210135-Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Raymond Chuang 72441,3652

Come on, this drama is still in its infancy.  Far too early for swan songs.
Z-D has time to resolve this and turn it into something positive for the
entire industry...Letting Will go wouldn't be that something...

#: 210186 S10/Views:Zachmann [E]
    04-Jul-92  20:17:25
Sb: #210070-#Independence Declaration
Fm: Todd Hicks 76376,1302
To: William F. Zachmann 72241,43 (X)

Will,

Well it is certainly regrettable that it has come down to this. While many
here (myself included) did not always agree with your opinions, there is no
doubt (for me at least) that your presence here along with your columns
generated the some of the most interesting and thought provoking discussions
of the computer industry that I have ever seen. I hope you will continue to
frequent this forum even after your term with Ziff-Davis comes to an end.

--Todd

* Reply:  210192

#: 210192 S10/Views:Zachmann [E]
    04-Jul-92  20:37:50
Sb: #210186-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Todd Hicks 76376,1302 (X)

Thanks, Todd.

#: 210229 S10/Views:Zachmann [E]
    05-Jul-92  00:06:27
Sb: #210070-#Independence Declaration
Fm: Koll Simonds - GDI 70144,1540
To: William F. Zachmann 72241,43 (X)

Something Cliff Shohl said in his book comes to mind:  Whenever you join any
community you must give up _something_.

You'll do fine as your talent as a writer more-or-less dictates it.

Regards,

Koll

* Reply:  210243

#: 210243 S10/Views:Zachmann [E]
    05-Jul-92  03:20:27
Sb: #210229-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Koll Simonds - GDI 70144,1540 (X)

 >Something Cliff Shohl said in his book comes to mind:  Whenever you join
 >any community you must give up _something_.

Like integrity?

* Replies:  210275, 210844

#: 210275 S10/Views:Zachmann [E]
    05-Jul-92  08:26:35
Sb: #210243-#Independence Declaration
Fm: Marilyn Ratcheson 76702,260
To: William F. Zachmann 72241,43 (X)

No, not integrity.

This is nuts.   How the domination of the industry by any single company, be
it Microsoft, IBM or whoever else is out there trying helps us, escapes me.
Now, I don't blame any of them for trying, and perhaps we benefit to some
extent as a result of their trying, so long as no one succeeds in knocking out
all competition.

But those of us who have only 24 hours in a day which requires dedicating at
least twice that to stay in reasonable touch with what is happening and also
do our jobs, must rely on the press for a good deal of our information.

If editorial integrity is seriously compromised, our effectiveness is
seriously curtailed.  We positively, absolutely need healthy differences of
opinions in the press, as free of undue pressure by any of the big players as
is reasonably possible.  You play a crucial role in the industry and in
society at large.

Even forgetting advertising revenues and their potentially pernicious impact
on editorial policy, I can envision a scenario in which Sam Whitmore and the
PTB at Ziff might be overly influenced by Microsoft without being fully aware
of it.  It's gotta be really tough to maintain objectivity in an industry in
which we get so passionately involved with our tools. Golly gee, in what other
industry do we find people working for successful vendors whose titles are
Evangelist?

Ok, so perhaps complete objectivity is an impossible dream.  Independence,
however, is an essential goal for a serious publication.  And independence is
accomplished in part by allowing responsible columnists with differing points
of view relative freedom of expression.

As I said over on PCWeek, this is truly a sad turn of events.  At best it is
an unfortunate misunderstanding and we readers are deprived of your talents,
something which is bad enough.  At worst we are in real trouble. -Marilyn

* Replies:  210306, 210386

#: 210306 S10/Views:Zachmann [E]
    05-Jul-92  10:09:41
Sb: #210275-#Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Marilyn Ratcheson 76702,260 (X)

Nicely said, Marilyn.  I think Editorial and Advertising should get a divorce!
                                        -- T.

* Replies:  210321, 210661, 211133

#: 210321 S10/Views:Zachmann [E]
    05-Jul-92  10:38:22
Sb: #210306-Independence Declaration
Fm: Marilyn Ratcheson 76702,260
To: Theresa Carey [ZiffNet] 72241,237 (X)

In a perfect world there would have been no marriage in the first place, T.
But it occurs to me that in this theoretically perfect world, PC Week couldn't
even exist, and PC Mag would cost us closer to $35 an issue than a year.
Owell, I guess we are stuck with what we have, and hoping the best instincts
of those in a position to influence prevail.         -Marilyn

#: 210661 S10/Views:Zachmann [E]
    06-Jul-92  06:43:39
Sb: #210306-#Independence Declaration
Fm: Neil Rubenking [PCMAG] 72241,50
To: Theresa Carey [ZiffNet] 72241,237 (X)

T.,
       Haven't you noticed?  They're practically separated already.  The
Advertising people think the Editorial people are techno-geeks, and the Ed
folks think the Ad folks are unethical PR-mongers.  DON'T invite them to the
same party!
       - N.

* Reply:  210705

#: 210705 S10/Views:Zachmann [E]
    06-Jul-92  08:33:35
Sb: #210661-#Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Neil Rubenking [PCMAG] 72241,50

Neil --

OK, I won't!  I'm a nerdly techno-geek and I'm PROUD!           -- T.

* Reply:  210821

#: 210821 S10/Views:Zachmann [E]
    06-Jul-92  12:06:04
Sb: #210705-#Independence Declaration
Fm: CyberSim [E. Pinnell] 70031,435
To: Theresa Carey [ZiffNet] 72241,237 (X)

Theresa,

    Gee, I always thought you were sort of a techno-party-wench<G>.

Eric Pinnell

* Reply:  210859

#: 210859 S10/Views:Zachmann [E]
    06-Jul-92  13:14:10
Sb: #210821-#Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: CyberSim [E. Pinnell] 70031,435

What an honor!  Techno-party-wench.  Can we add "Amazon Mother of Two" to the
title?
                                        -- T.

* Reply:  210941

#: 210941 S10/Views:Zachmann [E]
    06-Jul-92  17:29:46
Sb: #210859-#Independence Declaration
Fm: Keith Pleas 72331,2150
To: Theresa Carey [ZiffNet] 72241,237 (X)

Theresa:

Uh, I don't think you want "Amazon" in the title, particularly if you
know it's derivation! <g>

* Replies:  211057, 211075

#: 211057 S10/Views:Zachmann [E]
    06-Jul-92  20:56:35
Sb: #210941-Independence Declaration
Fm: Charles Hart 72755,500
To: Keith Pleas 72331,2150 (X)

 >Uh, I don't think you want "Amazon" in the title, particularly if you
 >know it's derivation! <g>

Ah, but perhaps she does - knowing full well the origin!  The mental image
staggers the mind.....

#: 211075 S10/Views:Zachmann [E]
    06-Jul-92  21:25:08
Sb: #210941-#Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Keith Pleas 72331,2150 (X)

Keith, back when I played on Cal's varsity volleyball team, we referred to
ourselves collectively as Amazons.  "Tall, powerful, aggressive woman" was the
definition we liked.
                                        -- T.

* Reply:  211181

#: 211181 S10/Views:Zachmann [E]
    07-Jul-92  01:50:53
Sb: #211075-Independence Declaration
Fm: Keith Pleas 72331,2150
To: Theresa Carey [ZiffNet] 72241,237

Theresa:

Well, take your "tall, powerful, aggressive woman" one step further back.
The Greek fable tells that they cut of their right breasts so as not to
interfere with their use of the bow.

From: a (without) + mas (breast)

#: 211133 S10/Views:Zachmann [E]
    06-Jul-92  23:36:32
Sb: #210306-Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Theresa Carey [ZiffNet] 72241,237

There is much more to compromised influence and conflict of interest than
having Editorial and Advertising in the same reporting structure.  It all
boils down to this:

Are there avenues or loopholes whereby a PC Week employee can benefit
materially from the success or failure of any company if that employee is in a
position to contribute to that very success or failure?

If so, there is a very real potential for compromise, extortion, undue
influence, conflict of interest, or ethical trauma.

Some obvious examples: Employees leaving a magazine to work for an industry
vendor, stock ownership, bribes, kickbacks, boondoggles, freebies, envelopes
full of cash left on desks of those who write "well," joint ventures with
vendors, spouses or close relatives working for vendors, etc. It takes some
pretty aggressive steps to avoid such conflicts, or they will creep into any
organization all but unconciously...

#: 210386 S10/Views:Zachmann [E]
    05-Jul-92  14:00:06
Sb: #210275-#Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Marilyn Ratcheson 76702,260 (X)

Nicely put.. From one of the "evangelists", I would hope that all of us in the
industry could come up with some kind of standards of contact charter to
follow.. This is truly sad..

Rick

* Reply:  211134

#: 211134 S10/Views:Zachmann [E]
    06-Jul-92  23:36:37
Sb: #210386-Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Rick Segal-Microsoft 76276,2706 (X)

From another evangelist: AMEN BROTHER SEGAL!

#: 210844 S10/Views:Zachmann [E]
    06-Jul-92  12:30:12
Sb: #210243-#Independence Declaration
Fm: Koll Simonds - GDI 70144,1540
To: William F. Zachmann 72241,43 (X)

I guess I'm thinking the unpopular.  We understand what has happened.  And I
agree, ZD fumbled.  I don't think the MS guy was out of line - any vendor
exploits every line they can - it's their job.  However, I wouldn't think PCWk
would be classified as a "line to be exploited"!

That being said, there are as many questions now unanswered as before the
declaration.  Like what was the pressure - the MS call?  Your stuff coming
back with more red ink on it than black?  I'm curious.  Not that I would think
you would pack-up and leave over one indescrestion - you mention two months of
stuff.  There's more?

Koll

* Reply:  210948

#: 210948 S10/Views:Zachmann [E]
    06-Jul-92  18:08:08
Sb: #210844-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Koll Simonds - GDI 70144,1540 (X)

 >There's more?

Koll,

There's more, but I think I've already posted enough of the details in the
threads here for anyone to make up his or her own mind about what they think
of all this.

Will

#: 210231 S10/Views:Zachmann [E]
    05-Jul-92  00:25:49
Sb: #210070-#Independence Declaration
Fm: Marc C. Matthews 70006,461
To: William F. Zachmann 72241,43 (X)

William,

As a long time reader of PC and PC Week, I must say it makes me wonder about
the objectivity of the Ziff publications after hearing your story. I have
always considered your articles as the devils advocate to balance out some of
the good natured overzealous attitude some of the other writers have. Without
your opinions gracing the pages, I would think both publications will be off
balance.

I certainly hope that you find a less restrictive forum for your insights. The
last thing we need is another publication with a case of Windows myopia. It
has its place (indeed, I am using it now), but comptetion is healthy, and a
truly unbiased publication would provide all of the available options to its
readers.

Question...Is there a Fax number we could use to voice our opinions to Mr.
Ziff? Would cancelling my subscriptions help?

-Dave

* Reply:  210244

#: 210244 S10/Views:Zachmann [E]
    05-Jul-92  03:20:36
Sb: #210231-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Marc C. Matthews 70006,461 (X)

Marc,

I don't offhand know what FAX number would be best to use.  I would, however,
urge you *NOT* to cancel your subscription to PC Magazine.  My problems have
been primarily with PC Week, not with PC Magazine.  It remains possible that
all this can be resolved happily.  I'm not terribly optimistic about that, but
I do not rule out that possibility, either.  That really is up to Z-D at this
point.

If they want to get retaliatory toward me for having gone public on this, then
we will all know what they are about.  My own view is that I have been
extremely patient, having endured over two months of this nonsense without a
satisfactory resolution.  To make it a public issue was an option to me back
in April.

I have done so now only because it became clear to me that I was not getting
anywhere with a behind the sceens approach. It also became increasingly clear
to me that Ziff-Davis Publishing Company Chairman and CEO Eric Hippeau was
part of the problem for me rather than part of the solution.

Only then did I decide to take the steps that I have taken.

Will

* Reply:  210250

#: 210250 S10/Views:Zachmann [E]
    05-Jul-92  05:52:09
Sb: #210244-#Independence Declaration
Fm: Todd Hicks 76376,1302
To: William F. Zachmann 72241,43 (X)

Over the past 1.5 years or so, I've noticed quite a turnover in PC Week
columnists. I was surprised to see Cheryl Currid go to Infoworld and Carole
Patton's Windows column did not last long. While I know you can't speak for
those people, I wonder if you had some general knowledge as to whether other
columnists experienced the same kind of problems with Ziff that you are.

--Todd

* Reply:  210266

#: 210266 S10/Views:Zachmann [E]
    05-Jul-92  07:58:12
Sb: #210250-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Todd Hicks 76376,1302 (X)

Todd,

It is a well-known fact that high turnover in an organization is a common
symptom of management problems.  Not only has the turnover of columnists at PC
Week been very high for the past year or two, but the turnover of editorial
employees appears to have been quite high as well.

Will

* Replies:  210327, 210921

#: 210327 S10/Views:Zachmann [E]
    05-Jul-92  11:16:05
Sb: #210266-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: William F. Zachmann 72241,43 (X)

Will,

If that is the case, I suggest that you resign ONLY from PC Week. Strike a new
deal where you only stay with PC Magazine, because let's face it, Michael J.
Miller, Bill Machrone, John C. Dvorak and Jim Seymour take as many shots at
Microsoft as you do in their regular columns <grin>. Have THEY been threatened
by MS recently?

Raymond Chuang

#: 210921 S10/Views:Zachmann [E]
    06-Jul-92  16:12:29
Sb: #210266-Independence Declaration
Fm: Jeff Winchell 76066,533
To: William F. Zachmann 72241,43 (X)

My understanding is that people commonly bounce between various IDG and ZD
pubs with occasional flings with other pubs in the same geographical area.

#: 210261 S10/Views:Zachmann [E]
    05-Jul-92  06:33:23
Sb: #210070-#Independence Declaration
Fm: Haig Hovaness 70210,362
To: William F. Zachmann 72241,43 (X)

I have to believe that this is some kind of misunderstanding that has gotten
out of control.  Surely Z-D must understand the damaging consequences of
creating even the *appearance* of advertiser interference with editorial
content.  I sincerely hope that cooler heads prevail and that we can continue
to enjoy reading your excellent work in Ziff publications.

* Replies:  210267, 210270, 210416

#: 210267 S10/Views:Zachmann [E]
    05-Jul-92  07:58:19
Sb: #210261-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Haig Hovaness 70210,362 (X)

 >I have to believe that this is some kind of misunderstanding that has
 >gotten out of control.  Surely Z-D must understand the damaging
 >consequences of creating even the *appearance* of advertiser interference
 >with editorial content.  I sincerely hope that cooler heads prevail and
 >that we can continue to enjoy reading your excellent work in Ziff
 >publications.

Haig,

I sincerely hope that you are correct.  Nothing that I've heard from ZiffDavis
recently, however, gives me any grounds for optimism.  That is, in fact, a
primary reason why I've felt it necessary to take these steps.

All the best,

Will

#: 210270 S10/Views:Zachmann [E]
    05-Jul-92  08:11:22
Sb: #210261-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Haig Hovaness 70210,362 (X)

Haig,

We agree on something!!!  For Ziff-Davis to allow advertiser interference (or
the appearance of such) in any of its publications tarnishes them all. I
sincerely hope that editors like Miller, Dreyfuss, and others are speaking
with Ziff-Davis management.

    Bruce

* Replies:  210328, 210774

#: 210328 S10/Views:Zachmann [E]
    05-Jul-92  11:16:10
Sb: #210270-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Bruce,

See my message to Will where I suggest ONLY staying with PC Magazine.

Raymond Chuang

#: 210774 S10/Views:Zachmann [E]
    06-Jul-92  10:47:37
Sb: #210270-#Independence Declaration
Fm: J.C. Love [AsstOp] 72241,1006
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Bruce -

I've been repeatedly impressed by the public stance that PC Week takes in
separating its editorial and marketing groups.  Marketing cannot gain
admittance to Spencer's parties, for example (and they don't like it one
little bit).

However, both groups are ultimately managed at a single pyramid apex. It seems
that Will feels that the problem lies at that point.

                                                 jc

#: 210416 S10/Views:Zachmann [E]
    05-Jul-92  15:06:11
Sb: #210261-#Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Haig Hovaness 70210,362 (X)

Haig:

What percentage of the people who read PCWeek or PCMag do you think will ever
hear of *any* of this?

For all of ZiffNet's fun and dandiness, it represents less than the hair on a
gnat's butt compared to the readership of the two books.

There is, alas, no damaging consequence if nobody knows what happened but a
few people herein.

* Replies:  210451, 210505, 210538

#: 210451 S10/Views:Zachmann [E]
    05-Jul-92  17:33:50
Sb: #210416-#Independence Declaration
Fm: Patrick Pearce (SCUDMAN) 70662,2714
To: Ross M. Greenberg 72461,3212 (X)

Ray,

<There is, alas, no damaging consequence if nobody knows what happened but a
few people herein.>

Just like the files on the JFK murder which the US Justice Dept. continues to
suppress and continues to withold the full truth from us all...it is the
secret murder at the heart of the American Dream.

Patrick

* Reply:  210467

#: 210467 S10/Views:Zachmann [E]
    05-Jul-92  18:39:11
Sb: #210451-#Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Patrick Pearce (SCUDMAN) 70662,2714 (X)

Let's try to put things in perspective here just a tad, Patrick.

Yes, I think it is awful that, apparently, a controversial columnist would
find pressure enough against his stance that he would feel forced to quit to
maintain his integrity.

But, all in all, I really don't put the loss of one trade journalist at the
same level as a potential coverup of the murder of the US head of state.

I mean, nice as Will is, let's be serious.....

* Reply:  210610

#: 210610 S10/Views:Zachmann [E]
    06-Jul-92  03:29:51
Sb: #210467-#Independence Declaration
Fm: Patrick Pearce (SCUDMAN) 70662,2714
To: Ross M. Greenberg 72461,3212 (X)

Analogy Ross...Analogy...not a comparison.

Patrick

* Reply:  210644

#: 210644 S10/Views:Zachmann [E]
    06-Jul-92  06:13:31
Sb: #210610-Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Patrick Pearce (SCUDMAN) 70662,2714 (X)

But too strong an analogy, Patrick, far too strong....

#: 210505 S10/Views:Zachmann [E]
    05-Jul-92  20:53:13
Sb: #210416-#Independence Declaration
Fm: Haig Hovaness 70210,362
To: Ross M. Greenberg 72461,3212 (X)

I think there is a better than even chance that this will be picked up (or
leaked) to the business press.  Microsoft and Ziff need publicity like this
like Dan Quayle needs a spelling bee.

* Replies:  210569, 210571, 210595, 210640, 210707

#: 210569 S10/Views:Zachmann [E]
    05-Jul-92  23:14:42
Sb: #210505-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Haig Hovaness 70210,362 (X)

Haig,

By making that statement on a public board (after all, any CIS user who joins
ZiffNet can read this board), I won't be surprised if the mainstream press
gets a hold of this in a few days.

Raymond Chuang

#: 210571 S10/Views:Zachmann [E]
    05-Jul-92  23:29:03
Sb: #210505-#Independence Declaration
Fm: Stan Spotts 76525,1060
To: Haig Hovaness 70210,362 (X)

Isn't that a spelling beee?

* Reply:  211018

#: 211018 S10/Views:Zachmann [E]
    06-Jul-92  20:14:16
Sb: #210571-Independence Declaration
Fm: Haig Hovaness 70210,362
To: Stan Spotts 76525,1060

No, that's spellinge be.

#: 210595 S10/Views:Zachmann [E]
    06-Jul-92  00:51:53
Sb: #210505-Independence Declaration
Fm: earle robinson [ibmeur] 76004,1762
To: Haig Hovaness 70210,362 (X)

Gee, how could they miss it.  Will planted his message in several fora on the
CompuServe side, too.   -er

#: 210640 S10/Views:Zachmann [E]
    06-Jul-92  06:13:08
Sb: #210505-#Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Haig Hovaness 70210,362 (X)

Haig, do you imagine that any ZD pub is gonna say spit about this?

And, well, I guess you can consider it as honor among thieves: I doubt very
much that any competing pub will print info on this since they all have their
own skeletons to keep in their respective closets.

Besides what makes you think that PCWeek is the only pub with, perhaps, undue
advertiser influence.

Try an experiment: you're a columnist for a ZD book now, right?  Try
mentioning this in your next col and see what happens.

* Replies:  210767, 210864, 211019

#: 210767 S10/Views:Zachmann [E]
    06-Jul-92  10:30:25
Sb: #210640-#Independence Declaration
Fm: Frank Ivan 75300,1406
To: Ross M. Greenberg 72461,3212 (X)

Ross,

Maybe you should send a message to Spencer Katt.  Think you'll get a tee shirt
or a mug?

* Reply:  210953

#: 210953 S10/Views:Zachmann [E]
    06-Jul-92  18:10:44
Sb: #210767-Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Frank Ivan 75300,1406 (X)

Writing on this forum is as close to Spencer as you need get....

#: 210864 S10/Views:Zachmann [E]
    06-Jul-92  13:28:49
Sb: #210640-#Independence Declaration
Fm: Greg Comeau@Comeau Comp 72331,3421
To: Ross M. Greenberg 72461,3212 (X)

>Haig, do you imagine that any ZD pub is gonna say spit about this?

They won't.  Nor at this point will Will have any chance at a shot of
hanging around either, even if Earle was incorrect and Will is not being
premature about this.  Remember what happened to us both at UNIX Today! ?
Remember what just happened to me over on BIX?  And so on.   Stories are all
different but OTOH they are all the same, just the names have changed.
This is no longer what happened or didn't happen, but now unfortunately
strictly what Will did because "they" (the only opinion that counts) say
that he did.

I hope I am all wrong in this case and that instead Will can leave when it
should be naturally or mutually time for him to leave.

* Replies:  210871, 210940, 210957

#: 210871 S10/Views:Zachmann [E]
    06-Jul-92  13:36:33
Sb: #210864-Independence Declaration
Fm: Ben Sano 72401,2736
To: Greg Comeau@Comeau Comp 72331,3421 (X)

Greg

I have not doubt whatsoever that you are right.

Sure as there is cow sh!t in Bovina.

--Ben

#: 210940 S10/Views:Zachmann [E]
    06-Jul-92  17:29:33
Sb: #210864-Independence Declaration
Fm: Keith Pleas 72331,2150
To: Greg Comeau@Comeau Comp 72331,3421 (X)

Greg:

Uh, what happened to you both at "UNIX Today!" (now "Open Systems Today!")?
And what's going on over in BIX?  I dropped that service a long time ago;
am I missing something?

#: 210957 S10/Views:Zachmann [E]
    06-Jul-92  18:11:04
Sb: #210864-Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Greg Comeau@Comeau Comp 72331,3421 (X)

Yeah, I see a lot of similarity between what has apparently happened to Will
and to others (including ourselves) when the reed refuses to bend over after
bending.....

#: 211019 S10/Views:Zachmann [E]
    06-Jul-92  20:14:25
Sb: #210640-Independence Declaration
Fm: Haig Hovaness 70210,362
To: Ross M. Greenberg 72461,3212

The effect of adding gasoline to a fire is not mysterious, Ross.  I think we
owe it to Will, Z-D, and ourselves to try to get a sensible resolution of this
disagreement.  The challenge is not to make things worse.

#: 210707 S10/Views:Zachmann [E]
    06-Jul-92  08:35:13
Sb: #210505-Independence Declaration
Fm: D Moskowitz CONSULT/UNIX 76701,100
To: Haig Hovaness 70210,362 (X)

Haig, actually, the spelling bee might do Quayle a bit of good!  ;-))

David

#: 210538 S10/Views:Zachmann [E]
    05-Jul-92  22:50:20
Sb: #210416-#Independence Declaration
Fm: Wayne Robertson (SAMC) 76546,560
To: Ross M. Greenberg 72461,3212 (X)

Ross,

I agree with you that the people on these forums are only a very small portion
of the total readership.  However, one thing struck when I read your message
is that the people here tend to be consultants or head of large sites which
this an important group.

-Wayne

* Reply:  210642

#: 210642 S10/Views:Zachmann [E]
    06-Jul-92  06:13:19
Sb: #210538-Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Wayne Robertson (SAMC) 76546,560 (X)

Wayne, even if these onliners are consultants and were to start badmouthing
everything having to do with ZD, it would make no difference. The demographics
upon which the advertisers choose their media wouldn't change at all.  Nor
would the sub base.

#: 210263 S10/Views:Zachmann [E]
    05-Jul-92  06:52:18
Sb: #210070-#Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: William F. Zachmann 72241,43 (X)

Will, I'm truly sorry you had to have this particular experience -- it'll
leave a sour taste in your mouth, unfortuneately, for quite a while to come.

However, when you next shave, you'll be able to look at that handsome face in
the mirror and say "Gads, that fellah has integrity!"

* Replies:  210268, 210271

#: 210268 S10/Views:Zachmann [E]
    05-Jul-92  07:58:23
Sb: #210263-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Ross M. Greenberg 72461,3212 (X)

Ross,

Does that mean the next step for me will be to move to Bovina?  <G>

Will

* Reply:  210274

#: 210274 S10/Views:Zachmann [E]
    05-Jul-92  08:12:35
Sb: #210268-#Independence Declaration
Fm: Ben Sano 72401,2736
To: William F. Zachmann 72241,43 (X)

William

No it means that the next step for you is to remove your beard.<g>

--Ben

* Reply:  210286

#: 210286 S10/Views:Zachmann [E]
    05-Jul-92  09:10:26
Sb: #210274-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Ben Sano 72401,2736 (X)

Ben,

My beard has been off for several months already.  Maybe you mean that the
next step is for me to grow it back again?  <g>

Will

* Reply:  210352

#: 210352 S10/Views:Zachmann [E]
    05-Jul-92  13:10:55
Sb: #210286-#Independence Declaration
Fm: Eric G. Harrison 74270,3457
To: William F. Zachmann 72241,43 (X)

Will, I am sorry to see that you will be leaving ZD; However, I am a little
confused.  In other forums (IBMOS2) you have been saying that PCW wanted you
to concentrate in the OS/2 area.  Now it seems that something the management
has done has gone over the line (someone mentioned MS in the debates).  Why do
you feel it's necessary to leave?  Don't jump on me, I just want to understand
what's really happening out there! - Eric.

* Reply:  210631

#: 210631 S10/Views:Zachmann [E]
    06-Jul-92  05:28:53
Sb: #210352-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Eric G. Harrison 74270,3457 (X)

Eric,

PC Week, in effect, required that I narrow my focus to Windows and related
issues last fall -- *not* to OS/2.  You recollection of what I said over on
IBMOS2 is incorrect.  It was made clear to me that unless I agreed to do that,
my column would have been dropped at the end of last year.  I agreed to do so
with the understanding that OS/2 was a related issue and that I could continue
to write about both (and Unix as well).

When I did so, however, I began to have problems.  On April 23 PC Week Editor
in Chief Sam Whitmore said I was "losing my credibility" because of my "lack
of objectivity" in what I was writing about Windows and OS/2.  He made it
clear that he did not want me to continue writing the sort of stuff I'd been
writing about Windows and OS/2.  He several times mentioned Carole Patton's
column and its fate with the clear implication (clear to me, at least) that my
column would suffer a similar fate if I did not shape up.

It was upon returning from that meeting with Sam that I received the phone
call from the individual at Microsoft who told me about how they'd recently
heard that I was going to be taking a more favorable view of Microsoft and of
Windows in my column.  In response to Sam's pressure, I wrote the May 4, 1992
column where I pointed out some problems and limitations with OS/2.  I had no
problem getting that column printed.

Two weeks later, I intentionally and deliberately wrote a column for the May
18, 1992 issue in which I discussed a very similar set of problems with
Windows 3.1.  I received a phone call from PC Week Editor Eric Lundquist
saying the column "didn't work" for him and asking me to write another on
another topic.  I had a lengthy discussion with him in which I refused to do
so and argued that my column should run as submitted.  He finally agreed to
mark it up with his problems/objections.  While a virtually idential column
about OS/2 had gone through without difficulty two weeks before, Eric was all

[More...]

* Reply:  210632

#: 210632 S10/Views:Zachmann [E]
    06-Jul-92  05:28:57
Sb: #210631-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: William F. Zachmann 72241,43 (X)

[Part 2 of message 210631]

over this one like ants at a picnic questioning my statements.  I stood my
ground and the column was eventually, but quite obviously reluctantly,
printed.

That's a little bit more of the background about why I feel it is necessary to
leave.

Will

* Replies:  210652, 211095

#: 210652 S10/Views:Zachmann [E]
    06-Jul-92  06:22:17
Sb: #210632-#Independence Declaration
Fm: Peter Coffee (PC Week) 72631,113
To: William F. Zachmann 72241,43 (X)

I can't believe this discussion of internal PC Week meetings is taking place
in a public forum.  You were quick to correct me when I suggested that you had
an employment relationship with PC Week -- fine, call it a client/contractor
relationship if you prefer, is that any excuse?

I have been a PC Week columnist for most of my three years with the paper,
first in the Software section and more recently on the Op-Ed page.  I have
written things that castigated every one of our major advertisers on at least
one occasion.  Editors have never tried to influence content.  They have made
many useful suggestions as to making columns more interesting to read.

Why am I reminded of the final scenes in Dustin Hoffman's portrayal of Lenny
Bruce when he gets up on stage and reads from the transcripts of his trials?
When the messenger starts to think of himself as the message, audiences are
quick to go elsewhere.

* Replies:  210728, 210964, 211135

#: 210728 S10/Views:Zachmann [E]
    06-Jul-92  08:48:54
Sb: #210652-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Peter Coffee (PC Week) 72631,113 (X)

Peter,

I cannot believe that you can claim to be upset about my discussing what I
(and I suspect many others) consider to be inappropriate and improper pressure
applied to a columnist and yet remain silent about the fact that such pressure
was applied.  That is the moral equivalent of telling a victim of family abuse
they ought to remain silent because to speak of it is disloyalty to the
family.

I am not an employee of PC Week.  I am an independent businessman in a
relation between equals as defined by my agreement with Ziff-Davis.  Nothing
in that agreement requires that I suffer abuse silently.  Despite what I
consider to be undignified and shabby treatment I have patiently tried for
over *two months* to resolve this matter internally.  It was, in fact, an
insulting and imperious demand from Eric Hippeau that was the occasion for my
final decision not to renew my agreement and to break my silence on the
matter.

Congratulations to you if you have never been subject to such pressure.  I
was.  I have been, on and off, at least since I wrote the column about Bill
Gates memo last summer and it got worse as time went on.  Perhaps you've just
never written anything to offend the wrong people.

As to Sam Whitmore & Co., I would remind them of an old saying that has always
struck me as one that ought always to be kept in mind:  If you don't want
anybody to know about it, don't do it.

Will

#: 210964 S10/Views:Zachmann [E]
    06-Jul-92  18:15:06
Sb: #210652-#Independence Declaration
Fm: Randy Johnson 73067,2150
To: Peter Coffee (PC Week) 72631,113

Peter,

Your showing your colors and they seem to be yellow, I hope I'm wrong.  You
seem to be just trying to look good to your superiors.  Who cares whats right
or wrong.  And when it gets close to the pocketbook, it gets harder and harder
to see clearly.

Randy

* Replies:  211070, 211162

#: 211070 S10/Views:Zachmann [E]
    06-Jul-92  21:17:48
Sb: #210964-Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Randy Johnson 73067,2150 (X)

Randy,

Boo! Hiss!! Peter Coffee is one of the more rational folks in this biz. He
also would scream foul faster than many others.  Even with my pickin on
PC-Week, Peter is respected.. The yellow remark is not called for.. He is good
enough not to have to worry about getting a job..

Rick

#: 211162 S10/Views:Zachmann [E]
    07-Jul-92  00:38:28
Sb: #210964-Independence Declaration
Fm: Wayne Robertson (SAMC) 76546,560
To: Randy Johnson 73067,2150 (X)

Randy,

>>Your showing your colors and they seem to be yellow, I hope I'm wrong.<<

I am confused by a statement like that.  Peter makes statements that he hasn't
been the victim of pressure from ZD management and you convict him immediately
of parroting the party line.

One of the interesting things about this whole discussion is that those of us
not staff or contributors to PC Week are outsiders and it is difficult to know
what really happend.  Because of that I have no choice but to believe Peter,
Will and Sam.  Some of the stories contradict each other and who can tell what
the true story is?  If Will Z. is correct, then a serious breach of journalism
ethics has occurred.  However, my contact with PC Week staff has never given
any indication of vendor pressure.  If and when I have/see evidence to the
contrary then I will lean one way or the other.

Will says he got a call from a MS person willing to help him with his
re-education - we cannot say it didn't happen.  Same goes for Peter Coffee and
Sam Whitmore - do you have evidence that any of they are toeing the party line
regardless of the facts?

-Wayne

#: 211135 S10/Views:Zachmann [E]
    06-Jul-92  23:36:42
Sb: #210652-#Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Peter Coffee (PC Week) 72631,113

Peter, you point out the moral dilemma anyone faces who finally decides not to
compromise any more in the name of "loyalty."  Different people draw the lines
in different places--I faced some criticism for being disloyal when I spoke
out against the content of the memo summarizing Akers remarks last year also.
You chastize Will for going public with "discussions of internal PC Week
meetings," yet in effect, that is what is forcing Will into this position to
begin with!  I believe it is very much an excuse.  Will has a right to seek
redress in the public arena for private wrongs suffered.  If he's wrong, it'll
be HIS credibility to suffer...

* Reply:  211171

#: 211171 S10/Views:Zachmann [E]
    07-Jul-92  01:03:37
Sb: #211135-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Dave Whittle [IBM] 70303,1352

Dave,

Note too the meetings between folks at PC Week and myself are *not* internal
PC Week meetings.  I am not and never have been an employee of PC Week or
Ziff-Davis.  I am an external and independent individual who writes an opinion
column for PC Week.

Will

#: 211095 S10/Views:Zachmann [E]
    06-Jul-92  22:35:44
Sb: #210632-#Independence Declaration
Fm: Mike Henry 76376,157
To: William F. Zachmann 72241,43 (X)

Will - was the Windows column published in the 5/18 PCWeek or in another?

Assuming that the events took place as you described them (and I'm not saying
that I doubt it) I'll join the others here in expressing my sadness for the
circumstances and my admiration for your integrity.

* Reply:  211153

#: 211153 S10/Views:Zachmann [E]
    07-Jul-92  00:13:15
Sb: #211095-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Mike Henry 76376,157

 >Will - was the Windows column published in the 5/18 PCWeek or in another?

Mike,

Yes.  After I refused to back down and steadfastly defended what I wrote in it
(and pointed out that *all* the problems I'd mentioned in it had been
explicitly acknowledged by folks at Microsoft [I'd made sure of that before I
wrote the column since I expected that PC Week would not want to print it])
the column on Windows 3.1 problems *did* (after much contentious discussion
between Eric Lundquist and myself) appear in the May 18, 1992 issue of PC Week
as originally intended.

Will

#: 210271 S10/Views:Zachmann [E]
    05-Jul-92  08:11:29
Sb: #210263-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Ross M. Greenberg 72461,3212 (X)

Ross,

Geez, I never thought I'd see the day when you, Haig, Will, Ben, and I all
agreed on something.

    Bruce

* Replies:  210307, 210342

#: 210307 S10/Views:Zachmann [E]
    05-Jul-92  10:12:19
Sb: #210271-#Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Add me to the list of unlikely agree-ers.  Has Earle chimed in yet?  It could
be a sweep!
                                        -- T.

* Reply:  210391

#: 210391 S10/Views:Zachmann [E]
    05-Jul-92  14:12:36
Sb: #210307-#Independence Declaration
Fm: earle robinson [ibmeur] 76004,1762
To: Theresa Carey [ZiffNet] 72241,237 (X)

I agree about integrity, but not how will has gone about being so.  First, I
wonder why he didn't wait until his meeting with whitmore on july 13th.
Second, going over someone's head is a perilous procedure, and best done
privately rather than in public view.  Finally, since the problems concerned
pc week, arguably something less serious, at least in its editorial side
--technical seems more sound-- than pc magazine.

As I said, it has come down to two choices:  either whitmore is replaced,
'promoted' in ziff terms, or zachmann leaves.  Can management replace an
editor-in-chief because a columnist complains, demands his head?

From all I understand the ziff group is very private, very paternalistic too.
No interviews by bill ziff on 'the lifetime of the rich and famous' or
interviews in people magazine.  This kind of public airing of dirty laundry
will be particularly resented, in my opinion.

I still wonder why will didn't wait until after his meeting on july 13th, and
didn't try to reason with bill ziff directly.

All of this will titillate not a few people, will elicit many messages of
support.  How many of those people would be so suicidal if confronted with
similar problems?
   -er

* Replies:  210444, 210488, 210518, 211136

#: 210444 S10/Views:Zachmann [E]
    05-Jul-92  16:43:34
Sb: #210391-#Independence Declaration
Fm: Vijay Kulkarni 70144,245
To: earle robinson [ibmeur] 76004,1762 (X)

This is from PCWEEK forum:

 Sam Whitmore:
 Will and I agreed to meet in early July to continue the discussions,
 but Will cancelled the meeting.

 William F. Zachmann:
 Sam's message is flatly untrue in saying that I cancelled the meeting in
 question.  In fact, it remains on my calendar for Monday, July 13 at noon.

* Reply:  210593

#: 210593 S10/Views:Zachmann [E]
    06-Jul-92  00:51:42
Sb: #210444-#Independence Declaration
Fm: Sam Whitmore 76701,257
To: Vijay Kulkarni 70144,245 (X)



Vijay:

The meeting that Will cancelled was scheduled for July 2. (Will, why didn't
you clarify that for everyone?) I had asked my assistant to reschedule for the
week of the 13th, but when I left work Friday I hadn't heard whether Will
could make it then. We all know now that he can.

Sam

* Replies:  210603, 210745, 210822, 210972

#: 210603 S10/Views:Zachmann [E]
    06-Jul-92  02:05:57
Sb: #210593-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Sam Whitmore 76701,257

The meeting was only briefly scheduled for July 2nd.  I initially told Sheryl
that would be all right but, only a few hours later, double checked my
calendar and found I already had a conflicting appointment scheduled that day.
I phoned her back and, after a bit of back and forth, we confirmed the 13th.
All that took place early last week.  I did not cancel any meeting as you well
know. I merely rescheduled it.

#: 210745 S10/Views:Zachmann [E]
    06-Jul-92  09:39:24
Sb: #210593-Independence Declaration
Fm: Vijay Kulkarni 70144,245
To: Sam Whitmore 76701,257

Thanks for the clarification.

#: 210822 S10/Views:Zachmann [E]
    06-Jul-92  12:06:21
Sb: #210593-#Independence Declaration
Fm: CyberSim [E. Pinnell] 70031,435
To: Sam Whitmore 76701,257

Sam,

    It sounds to me like you've got a case of "severe personality conflicts"
going on here.  Maybe you should get a an arbtitrator or better yet take this
up with all parties in from of Mr. Ziff. I for one cannot fathom why you would
want your columnist to concentrate on Windows related issues, when there is a
crying need for SOMEBODY to write about OS/2.
     Don't be surprised if IBM comes stomping up to your door mad as hell.
I've heard rumors that they are not too amused at the idea of Microsoft
dictating editorial policy. Regrdless of the facts, this situation is rapidly
turning into a first class fiasco. If you don't settle this equitably, it will
have a very adverse impact on Ziff publications.

Eric Pinnell

* Replies:  211002, 211046

#: 211002 S10/Views:Zachmann [E]
    06-Jul-92  19:25:40
Sb: #210822-#Independence Declaration
Fm: Koll Simonds - GDI 70144,1540
To: CyberSim [E. Pinnell] 70031,435

What do you mean "arbitrator"?  This sounds like a management decision.

I don't know.  What does the independent contractor's agreement say on these
matters?

Koll

* Reply:  211058

#: 211058 S10/Views:Zachmann [E]
    06-Jul-92  20:56:44
Sb: #211002-#Independence Declaration
Fm: Charles Hart 72755,500
To: Koll Simonds - GDI 70144,1540 (X)

Disclaimer:  I do not know the contents of the contract Will has with Ziff.

That said, I would be very surprised if Ziff allowed any contract to be used
for an independent contractor other than one their legal beagles had written -
or at least red-penciled enough so that they might as well have done so from
scratch.

That being the case, I would hazard a guess that any mention of arbitration
contained therein is presented only from the view of Ziff and the use of same
will be solely at the discretion of Ziff.  All of ours read that way,
anyway....

<g>

* Reply:  211154

#: 211154 S10/Views:Zachmann [E]
    07-Jul-92  00:13:22
Sb: #211058-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Charles Hart 72755,500

Charles,

There is no language of any sort in my agreement with Ziff-Davis Publishing
Company with regard to the arbitration of disputes.  There is also no language
in the agreement that in any way requires that the agreement itself be kept
confidential.  Neither is there any wording that requires that any discussions
that I might have with Ziff-Davis personnel concerning the publication of my
columns be kept confidential.

The latter are matters between Ziff-Davis and myself, an outside party.  They
are not matters internal to Ziff-Davis. The agreement explicitly states that I
am *not* a Ziff-Davis employee.

Will

#: 211046 S10/Views:Zachmann [E]
    06-Jul-92  20:52:26
Sb: #210822-#Independence Declaration
Fm: Raymond Chuang 72441,3652
To: CyberSim [E. Pinnell] 70031,435

Eric,

The BIG question mark is how fast will this mess end up in the wider mass
media outside ZiffNet and CIS, notably NewsBytes, then AP Online, etc?

Raymond Chuang

* Reply:  211091

#: 211091 S10/Views:Zachmann [E]
    06-Jul-92  22:30:47
Sb: #211046-Independence Declaration
Fm: Orville Fudpucker[SysOp] 72241,105
To: Raymond Chuang 72441,3652

I myself think that we would be better served if someone did NOT make a Paul
Revere run to the wider mass media with self serving blathering on the
subject.

#: 210972 S10/Views:Zachmann [E]
    06-Jul-92  18:16:30
Sb: #210593-Independence Declaration
Fm: James Gleick 76416,2553
To: Sam Whitmore 76701,257

I've missed one point in your comments on Zachmann, though you said you were
discussing two "options" for his column in the future.

Is he free to continue his usual pro-OS2, anti-Windows stuff?  Or has PC Week
asked him to do something different?

#: 210488 S10/Views:Zachmann [E]
    05-Jul-92  19:40:07
Sb: #210391-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: earle robinson [ibmeur] 76004,1762 (X)

Earle,

I don't know where you get the idea that I want to have Sam Whitmore fired or
that it is somehow "him or me."  That isn't the issue at all.  What I wanted
was simply to be free to write what I think ought to be written without
interference.  That doesn't require anybody firing anybody that I can see. Why
do you think it does?

Will

* Reply:  210597

#: 210597 S10/Views:Zachmann [E]
    06-Jul-92  00:51:59
Sb: #210488-#Independence Declaration
Fm: earle robinson [ibmeur] 76004,1762
To: William F. Zachmann 72241,43 (X)

That's the way it scans from where I'm sitting.  You say, 'write bill ziff to
protest how pc week is treating you'.  The senior editorial fellow there is
whitmore.  Of course, you also mentioned hippeau, who is chmn & ceo of ziff
publishing.  And, you say you are leaving all ziff publications unless the
write-in campaign sways bill ziff.  What other conclusion can I draw?  Unless
you plan to leave anyway, and this is a grand-opera exit?   -er

* Reply:  210605

#: 210605 S10/Views:Zachmann [E]
    06-Jul-92  02:25:29
Sb: #210597-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: earle robinson [ibmeur] 76004,1762 (X)

 >And, you say you are leaving all ziff publications unless the
 >write-in campaign sways bill ziff.

No.  What I said is that I have notified Z-D Publishing Co. that I do not
intend to renew my agreement with them after it expires at the end of
September.

* Reply:  210624

#: 210624 S10/Views:Zachmann [E]
    06-Jul-92  05:06:08
Sb: #210605-Independence Declaration
Fm: earle robinson [ibmeur] 76004,1762
To: William F. Zachmann 72241,43 (X)

Well, what you wrote implies that you wish to no longer write for any ziff
publication.  At least that is how I saw the following quote from one of your
messages:

"I wrote it with great sadness.  My agreement with Ziff-Davis Publishing
Company covers my entire relation with them including PC Magazine.  I am not at
all happy about these events, but I do not feel I can continue to write for
them if I do not have a reliable assurance than I will be permitted to say what
I think ought to be said.  I have patiently sought such assurance for weeks now
with the only result being the emergence of more subtle ways to muffle me, the
latest being clear indications of an intention to, in effect, design my column
out of PC Week.

Were I simply to acquiesce to that, I would be setting a precedent of
compromising principles that I feel ought not to be compromised.  I have
therefore chosen, after much deliberation, to put my entire relation with Z-D
Publishing on the line at the sacrifice of substantial income to myself."
   -er

#: 210518 S10/Views:Zachmann [E]
    05-Jul-92  21:10:53
Sb: #210391-#Independence Declaration
Fm: Charles Hart 72755,500
To: earle robinson [ibmeur] 76004,1762 (X)

Something about the public issues being debated here does not ring true.  No
one with any business sense takes matters such as this public unless they have
already decided that they want to resign and this is the best way to do a high
visibility exit on the basis of "integrity".

Advertisers *always* try to influence reviews and columns, this is not news.
If an editor slipped over the line in order to please advertising, it would
not be the first time - and the procedure to handle the situation is well
known.

Why is this a big deal?

* Replies:  210653, 211137

#: 210653 S10/Views:Zachmann [E]
    06-Jul-92  06:26:01
Sb: #210518-#Independence Declaration
Fm: Peter Coffee (PC Week) 72631,113
To: Charles Hart 72755,500 (X)

Thank you for injecting a note of sanity into this surreal discussion. Will's
presentation of the issues casts doubt on the credibility of everyone else at
PC Week, so it's doubly important to see these points made by an independent
observer.

Much obliged.

* Reply:  210965

#: 210965 S10/Views:Zachmann [E]
    06-Jul-92  18:15:16
Sb: #210653-Independence Declaration
Fm: Randy Johnson 73067,2150
To: Peter Coffee (PC Week) 72631,113

Peter,

Your own responses have cast doubts on your credibility!

Randy (Give me a break)

#: 211137 S10/Views:Zachmann [E]
    06-Jul-92  23:36:52
Sb: #210518-Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Charles Hart 72755,500

It is a big deal because it points out potential ethical problems with the
industry as a whole.  In the two months I've been active on IBMOS2, EDITOR,
and PCWEEK, I've seen many of the discussions center around disagreements over
what constitutes fair and ethical behavior in this industry, bias in the
media, fair marketing, the importance of astute observers, etc. etc.  We have
seen discussions of a wide variety of business practices, with opinions
varying all over the map.  From my vantage point, I'd say this industry is
struggling right now with more than operating systems wars--it's struggling
with wars over ethics and principles.  This incident is one more manifestation
in that war....and we are all the poorer for not having agreement on the
issues or even on whether it is acceptable to openly disagree on the issues
and discuss them publicly...

#: 211136 S10/Views:Zachmann [E]
    06-Jul-92  23:36:47
Sb: #210391-Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: earle robinson [ibmeur] 76004,1762 (X)

It is never suicidal to do what one feels is right, as opposed to expedient...

#: 210342 S10/Views:Zachmann [E]
    05-Jul-92  12:28:30
Sb: #210271-#Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Bruce, the one thing more important to me than anything else is the ability to
actually *trust* in what someone has said as being a factual representation of
their best beliefs.  Whether over a drink or through the pages of a magazine,
integrity of one's word is the only thing one has to go on.

I've destroyed at least one of my careers by deciding that my own integrity is
more important than a few dollars.

It is sad to have to now, if I believe Will (which I do based upon personal
contact with him), have to entirely discount everything in a Ziff Davis
publication as being tainted by the almighty advertising dollar.

But, I do agree with you: it is odd what strange bedfellows this kinda stuff
makes.....

* Reply:  210519

#: 210519 S10/Views:Zachmann [E]
    05-Jul-92  21:11:04
Sb: #210342-#Independence Declaration
Fm: Charles Hart 72755,500
To: Ross M. Greenberg 72461,3212 (X)

 >It is sad to have to now, if I believe Will (which I do based upon personal
 >contact with him), have to entirely discount everything in a Ziff Davis
 >publication as being tainted by the almighty advertising dollar.

Ross, what planet did you wake up on this morning?  If it's this one, then you
*must* know that Ziff exists for one purpose and one purpose only:  To sell
advertising.  The fact that they must include a little editorial content to
cause us to by the magazine is a necessary evil.  Note that they have
successfully launched at least one other publication recently with almost *no*
editorial content (sorry, Mr. Beem) and they know they don't really need that
much in the other publications.

There is *no* commercial for-profit magazine that you can trust implicitly and
I know of no non-profit magazines - but I will entertain the concept that one
might exist. Maybe.

The fact that Will was pressured is unfortunate, but a fact of life.  Some
quit, others resist and stay.  The world goes on.....

* Replies:  210570, 210574, 210641, 210806, 210867, 210985, 211138

#: 210570 S10/Views:Zachmann [E]
    05-Jul-92  23:28:59
Sb: #210519-#Independence Declaration
Fm: Stan Spotts 76525,1060
To: Charles Hart 72755,500 (X)

..and because it's SOP for the trade press to operate this way, it should just
be accepted and we should blithly skip along and ignore it?

Speaking of planets, as you did with Ross, what planet do you come from where
cynicism is more freely available than air?

Pressure by an advertiser to get the best placement in the mag I can
understand.  Buckling under to pressure to change the editorial content is
quite another thing.  Microsoft may as well just buy the magazine, or get some
bozo's like the ones that killed _OS/2 & Windows_ magazines focus to do it.
Nah, there's already a _Windows_ mag because of that - what would Ziff call it
then?

* Replies:  210585, 210630, 211003

#: 210585 S10/Views:Zachmann [E]
    06-Jul-92  00:04:18
Sb: #210570-#Independence Declaration
Fm: Frank Ivan 75300,1406
To: Stan Spotts 76525,1060 (X)

Stan,

>what would Ziff call it than?

How about Microsoft Week or just MSWeek.

* Reply:  210611

#: 210611 S10/Views:Zachmann [E]
    06-Jul-92  03:29:55
Sb: #210585-Independence Declaration
Fm: Patrick Pearce (SCUDMAN) 70662,2714
To: Frank Ivan 75300,1406 (X)

Better yet..."WeaselWeek"! <G>

#: 210630 S10/Views:Zachmann [E]
    06-Jul-92  05:28:32
Sb: #210570-#Independence Declaration
Fm: Charles Hart 72755,500
To: Stan Spotts 76525,1060 (X)

 >..and because it's SOP for the trade press to operate this way, it should
 >just be accepted and we should blithly skip along and ignore it?

Yep.  Since we all know it, it's no longer a factor.

 >Speaking of planets, as you did with Ross, what planet do you come from
 >where cynicism is more freely available than air?

Understanding things as they are is not cynicism, it's facing reality. Those
who do not are doomed to tilt at windmills forever.

 >Pressure by an advertiser to get the best placement in the mag I can
 >understand.  Buckling under to pressure to change the editorial content is
 >quite another thing.

Look, please don't make the error others have of shooting the messenger, but
the editorial content of the publication is *not* very necessary for it to
sell.  See Computer Shopper and the like.  We simply feel that PC Mag and PW
Week are "different" and they are, in that their editorial content is
_greater_ than the other advertising vehicles - but not by all that much.

 >Microsoft may as well just buy the magazine, or get some bozo's like the
 >ones that killed _OS/2 & Windows_ magazines focus to do it. Nah, there's
 >already a _Windows_ mag because of that - what would Ziff call it then?

Was there not a thread about that here already?  I did not read it, but the
title sure looked like this subject.

* Replies:  210696, 210718, 210868

#: 210696 S10/Views:Zachmann [E]
    06-Jul-92  07:56:09
Sb: #210630-#Independence Declaration
Fm: Steven J. Vaughan-Nichol 72241,464
To: Charles Hart 72755,500 (X)

Editoral content isn't important in Computer Shopper?  Wrong! Clearly you
haven't been reading it.  Over a year ago, ZD decided to improve Shopper's
editoral content.  Something must have gone right, since as these changes were
implemented, Shopper's circulation has increased by leaps and bounds. Hardily
what you would expect if Shopper was just an advertizing vehicle.

Steven

* Replies:  210783, 210791

#: 210783 S10/Views:Zachmann [E]
    06-Jul-92  11:10:42
Sb: #210696-#Independence Declaration
Fm: Gordon McComb 73155,353
To: Steven J. Vaughan-Nichol 72241,464 (X)

I made the same observation about Shopper in another forum about six months
ago, and I had given up on the magazine about six months before that.  After
some Shopper editors and contributors jumped on my ass for what I said, I
bought a more recent copy, and found that -- indeed! -- it had improved. Now
I'm back to being a regular reader. However, if I'm any indication, I feel
that CS lost a lot of believers, and the comments from myself and Charles may
be typical of what happens when a publication goes down the wrong path (even
if it's only for a while <g>).  It's hard to regain trust in people who have
previously given up hope.

At any rate, I agree with Charles: magazines are advertising vehicles, pure
and simple.  I have yet to meet a publisher who decided to launch a magazine
because he/she was interested in publishing great editorial.  In my 14 years
at this, it's always been the lure of the advertising base.

_However_, if great editorial can come from said advertising vehicle, then so
much the better.  One does not necessarily guarantee the other.

-- Gordon

* Reply:  210861

#: 210861 S10/Views:Zachmann [E]
    06-Jul-92  13:21:07
Sb: #210783-Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Gordon McComb 73155,353 (X)

Gordon, thanks for having an open mind.  The current crop of Shopper editors
is a lot of fun to work with.  That's my persepective from out here in
freelance world anyway <grin>.  If you want to stop by the Shopper forum and
discuss suggestions for improving things, feel free to type GO ZNT:COMPSHOP
and join in.
                                        -- T.

#: 210791 S10/Views:Zachmann [E]
    06-Jul-92  11:16:33
Sb: #210696-#Independence Declaration
Fm: Charles Hart 72755,500
To: Steven J. Vaughan-Nichol 72241,464 (X)

You know people who actually *read* the editorial content of Computer Shopper?
Browse, maybe - read most of the history of computers per the old editor, sure
- but read the thing for serious?

Na, can't be - sounds like the current polls for President where they take
1000 people who will *talk* to the pollsters and extrapolate to the country.

You do a poll?

<g>

* Replies:  210935, 210986

#: 210935 S10/Views:Zachmann [E]
    06-Jul-92  16:42:20
Sb: #210791-#Independence Declaration
Fm: Steven J. Vaughan-Nichol 72241,464
To: Charles Hart 72755,500 (X)

I write for Shopper, and a host of other mags, Byte, PC Sources, PC/Computing,
etc. etc., and I'm surprised to say that I hear from more Shopper readers than
all the other magazines combined. I'm even more surprised to say that
Shopper's readers, or at least the ones who find me, actually read the
magazine cover to cover.  Seriously.  Don't ask me to explain it, because I
can't. I'm just glad they do!

Steven [Shopper]

* Reply:  210993

#: 210993 S10/Views:Zachmann [E]
    06-Jul-92  19:05:29
Sb: #210935-Independence Declaration
Fm: Charles Hart 72755,500
To: Steven J. Vaughan-Nichol 72241,464

Ok, that's the second data point indicating that Shopper readers actually
exist.  Thanks for sharing that information.

Now for the bad part, as seen by the advertizers:  Reading the editorial
matter reduces the time the subscriber has to look at the advertizements, so
perhaps you are too successful?

<g>

#: 210986 S10/Views:Zachmann [E]
    06-Jul-92  18:56:24
Sb: #210791-#Independence Declaration
Fm: Bill Machrone [PCMAG] 72241,15
To: Charles Hart 72755,500 (X)

Hey, I actually get mail in response to my column in Shopper! I'm continually
amazed, since I have a hard enough time even finding the darn page.

- Bill

* Replies:  211000, 211081

#: 211000 S10/Views:Zachmann [E]
    06-Jul-92  19:22:21
Sb: #210986-Independence Declaration
Fm: Charles Hart 72755,500
To: Bill Machrone [PCMAG] 72241,15

That's *three* data points.  Is this a trend, you think?

Na.....

<g>

#: 211081 S10/Views:Zachmann [E]
    06-Jul-92  21:32:47
Sb: #210986-Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Bill Machrone [PCMAG] 72241,15

Bill, you're on 703 in the July Shopper.  I'm on 714.  Yo!  Neighbor! <g>
                                        -- T.

#: 210718 S10/Views:Zachmann [E]
    06-Jul-92  08:41:23
Sb: #210630-#Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Charles Hart 72755,500 (X)

Charles, have you looked at Computer Shopper in the last year?  The number and
quality of editorial pages has grown, as has the subscriber base.  Newstand
sales are among the highest of any computer publication.

C'mon over to the Computer Shopper forum (ZNT:COMPSHOP) if you want to talk
directly to the editors and contributors for the magazine.
                                        -- T.

* Replies:  210792, 211047

#: 210792 S10/Views:Zachmann [E]
    06-Jul-92  11:16:43
Sb: #210718-#Independence Declaration
Fm: Charles Hart 72755,500
To: Theresa Carey [ZiffNet] 72241,237 (X)

Um, apparently the subscriber records are not available to anyone - I have
been a subscriber on and off (currently: on) for several years so I am aware
of the editorial content of the publicatuion.  To my mind it has not improved
particularly from the days Patch ran the thing - the *quantity* is up, agreed,
so that it's more of an irritant in finding the advertizement you want.

I still can not believe anyone reads the editorial content of the magazine
with any regularity.  The circulation has increased because the publication
provides the advertizements, period.  It would sell just as well with *no*
editorial (oh, maybe the price listings if that counts as editorial), IMHO.

We could settle the bet, of course, by CS putting out a normal looking issue
with no editorial to distract the shoppers and checking the newsstand sales.
But that's too logical.

* Reply:  210857

#: 210857 S10/Views:Zachmann [E]
    06-Jul-92  13:12:34
Sb: #210792-#Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Charles Hart 72755,500 (X)

Well, Charles, given the feedback I get from my little column and the other
articles that have run in Shopper under my byline in the last several months,
I'm inclined to believe that people do read the editorial copy.  I doubt the
Ziff management would be investing so much in writers for the magazine if it
wasn't making a difference.

                                        -- T.

* Replies:  210912, 210990

#: 210912 S10/Views:Zachmann [E]
    06-Jul-92  16:07:50
Sb: #210857-#Independence Declaration
Fm: earle robinson [ibmeur] 76004,1762
To: Theresa Carey [ZiffNet] 72241,237 (X)

Agreed!  There has been an immense improvement in the editorial stuff in
computer shopper.   -er

* Reply:  211048

#: 211048 S10/Views:Zachmann [E]
    06-Jul-92  20:52:36
Sb: #210912-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: earle robinson [ibmeur] 76004,1762 (X)

Earle,

Yes, I definitely enjoy Computer Shopper nowadays--the articles are of a
surprisingly high quality.

Raymond Chuang

#: 210990 S10/Views:Zachmann [E]
    06-Jul-92  19:04:44
Sb: #210857-#Independence Declaration
Fm: Charles Hart 72755,500
To: Theresa Carey [ZiffNet] 72241,237 (X)

Let's agree that I'm biased because I buy the magazine for the advertizements
and you're biased because you write for it (congratulations! - but I sure
missed your column in my "browsing") and agree to respectfully disagree - Ok?

* Reply:  211076

#: 211076 S10/Views:Zachmann [E]
    06-Jul-92  21:26:03
Sb: #210990-Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Charles Hart 72755,500

You're missing out on some great stuff, Charles!  Give yourself another half
hour with the magazine and check out some of the words that break up the big
blocks of ads. <grin>
                                        -- T.

#: 211047 S10/Views:Zachmann [E]
    06-Jul-92  20:52:31
Sb: #210718-#Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Theresa Carey [ZiffNet] 72241,237 (X)

Theresa,

Well, considering the size of Computer Shopper, that magazine is kind of hard
to miss <grin>.

Heck, at Fry's Electronics more space is devoted to displaying Computer
Shopper than any other magazine. ;D

Raymond Chuang

* Reply:  211079

#: 211079 S10/Views:Zachmann [E]
    06-Jul-92  21:29:24
Sb: #211047-Independence Declaration
Fm: Theresa Carey [ZiffNet] 72241,237
To: Raymond Chuang 72441,3652

Yes, Raymond, many people have noticed that.            -- T.

#: 210868 S10/Views:Zachmann [E]
    06-Jul-92  13:29:36
Sb: #210630-#Independence Declaration
Fm: Greg Comeau@Comeau Comp 72331,3421
To: Charles Hart 72755,500 (X)

> >..and because it's SOP for the trade press to operate this way, it should
> >just be accepted and we should blithly skip along and ignore it?
>
>Yep.  Since we all know it, it's no longer a factor.

Of course it's a factor.  What learned helplessness pills are you taking?

> >Speaking of planets, as you did with Ross, what planet do you come from
> >where cynicism is more freely available than air?
>
>Understanding things as they are is not cynicism, it's facing reality. Those
>who do not are doomed to tilt at windmills forever.

Maybe I'm not understanding what you are saying, but I feel you prescribing
that one should not even try.  I'll definitely disagree.

* Reply:  210992

#: 210992 S10/Views:Zachmann [E]
    06-Jul-92  19:05:18
Sb: #210868-#Independence Declaration
Fm: Charles Hart 72755,500
To: Greg Comeau@Comeau Comp 72331,3421 (X)

 > > >..and because it's SOP for the trade press to operate this way, it
should
 > > >just be accepted and we should blithly skip along and ignore it?
 > >
 > >Yep.  Since we all know it, it's no longer a factor.

 >Of course it's a factor.  What learned helplessness pills are you taking?

I fail to understand the question, perhaps illustrating your point by
inadvertence.  But then, your statement illustrates that you did not
understand my point, kindly returning the favor.  Let me try again, simce my
shorthand was obviously not clear:

       A factor known to all can be discounted if warranted by whatever weight
the individual desires or feels appropriate, thus making the main point the
full and complete disclosure of the factor to all with a need to know.  You
know, the "efficient market" theory on which the stock market is supposed to
operate?

 > > >Speaking of planets, as you did with Ross, what planet do you come from
 > > >where cynicism is more freely available than air?

 > >Understanding things as they are is not cynicism, it's facing reality.
 > > Those who do not are doomed to tilt at windmills forever.

 >Maybe I'm not understanding what you are saying, but I feel you prescribing
 >that one should not even try.  I'll definitely disagree.

If you feel tilting at windmills is enjoyable, far be it for me to try to
dissuade you.  Personally, I try to attack problems that have a reasonable
chance at a positive solution.  The current one clearly does not.

* Reply:  211065

#: 211065 S10/Views:Zachmann [E]
    06-Jul-92  21:16:06
Sb: #210992-Independence Declaration
Fm: John Oellrich [AT&T] 72611,1452
To: Charles Hart 72755,500

Greg,

I just read your last message to Charles Hart and I can't figure out whether
it was an example of polymorphism or multiple inheritance. I do know it
demonstrated abstraction, however I didn't see any hint of friends.

John

PS Maybe you should go back to a pure procedural language for awhile. You
know, give that grey matter a rest <g>.

#: 211003 S10/Views:Zachmann [E]
    06-Jul-92  19:25:49
Sb: #210570-#Independence Declaration
Fm: Koll Simonds - GDI 70144,1540
To: Stan Spotts 76525,1060

> ..and because it's SOP for the trade press to operate this way, it should >
just be accepted and we should blithly skip along and ignore it?

There's always Consumer Reports.  What should be done - have >legislation<
extend to journalism?!

You can, as well, always start your own rag.  Maybe Will will.

Who was that guy who quit Car & Driver to start the upscale rag "Automobile"
How many issues did it run?

Koll

* Reply:  211056

#: 211056 S10/Views:Zachmann [E]
    06-Jul-92  20:56:28
Sb: #211003-Independence Declaration
Fm: Charles Hart 72755,500
To: Koll Simonds - GDI 70144,1540 (X)

 >Who was that guy who quit Car & Driver to start the upscale rag "Automobile"

David E. Davis, if memory serves.

 >How many issues did it run?

Last issue I saw was about three-four months ago - but in this part of the
country the magazines can be somewhat old when they hit the stands.....

<g>

#: 210574 S10/Views:Zachmann [E]
    05-Jul-92  23:39:05
Sb: #210519-#Independence Declaration
Fm: Wayne Robertson (SAMC) 76546,560
To: Charles Hart 72755,500 (X)

Charles,

There a number of publications that have no advertising in them but, of
course, the pain is a subscription rate of 3 figures per year.  I subscribe to
one and I do find the advertising useful in addition to making all these
magazines affordable.

-Wayne

* Reply:  210627

#: 210627 S10/Views:Zachmann [E]
    06-Jul-92  05:27:57
Sb: #210574-Independence Declaration
Fm: Charles Hart 72755,500
To: Wayne Robertson (SAMC) 76546,560 (X)

Certainly - I subscribe to several of these artifacts usually because they are
refereed and one can _usually_ trust what one reads - but not always. Even
they can make an error in judgement, but it's always just that - no outside
influences (if you don't count peer pressure, of course) affect the
publication of reports.

#: 210641 S10/Views:Zachmann [E]
    06-Jul-92  06:13:13
Sb: #210519-#Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Charles Hart 72755,500 (X)

Yes, I'm aware of the relationship between income and advertising.

However, in some books, such as Computer Reseller News, when a major
advertiser tried something similar to what we've heard about here, the editor
refused to buckle under and the advertiser was told to go advertise elsewhere.

There is a fragile trust between the public and the editorial creators of a
magazine that is easy to destroy.

* Replies:  210654, 210674, 211004

#: 210654 S10/Views:Zachmann [E]
    06-Jul-92  06:32:30
Sb: #210641-#Independence Declaration
Fm: Peter Coffee (PC Week) 72631,113
To: Ross M. Greenberg 72461,3212 (X)

>>>...a trust...that is easy to destroy.

And it's startling to see how quickly people are apparently willing to forget
the evidence of their own years of reading PC Week and accept one person's
claim that his editors' comments reflected cowardice rather than
craftsmanship.  The more you care about an issue, the easier it is to bristle
at someone else's efforts to help you make your message more effective and to
accuse that other party of ulterior motives.  The hardest thing, sometimes, is
to treat your own copy as raw material and to work with your editor in the
joint task of fitting the style of the paper and the needs of its target
reader.

* Reply:  210683

#: 210683 S10/Views:Zachmann [E]
    06-Jul-92  07:36:05
Sb: #210654-Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Peter Coffee (PC Week) 72631,113 (X)

Peter, my postings are also based upon personal experience in a variety of
trade publications, including some ZD ones.

Although I could see the possibility of Zachmann's editor giving him editorial
direction towards making the col more readable both in style or content (right
or wrong in their opinion, that is the editor's job), I can also see the
requirement by the publisher to the editor to tone down a very public and very
insistent columnist that attacks, on a regular basis, one of the book's major
advertisers.

There is a difference between writing an objective review and writing a
subjective column.

I see both possibilities (more readable versus more enjoyable to the
advertiser) as being possible.

#: 210674 S10/Views:Zachmann [E]
    06-Jul-92  07:11:04
Sb: #210641-#Independence Declaration
Fm: Charles Hart 72755,500
To: Ross M. Greenberg 72461,3212 (X)

I have been accused of being a cynic, but perhaps that's what's required in
this instance.  Ziff is in business to make money.  The vast majority of the
money comes from advertisers.  If there is a question as to who to please, how
can you doubt that the advertisers will be first on the list?

Anything else just doesn't compute.....

<g>

* Replies:  210686, 211139, 211190

#: 210686 S10/Views:Zachmann [E]
    06-Jul-92  07:36:19
Sb: #210674-Independence Declaration
Fm: Ross M. Greenberg 72461,3212
To: Charles Hart 72755,500 (X)

Charles, there is a difference between short term profit versus long term.

Ultimately, you must please the audience, or they go read somebody else's
advertising....

#: 211139 S10/Views:Zachmann [E]
    06-Jul-92  23:37:03
Sb: #210674-Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Charles Hart 72755,500

There will always be advertisers--the only question is "Do you have an
obligation to serve  them or your readers?"  Magazines exist for readers, not
for advertisers, because advertisers exist to please those same customers.
It's when the magazines and advertisers ignore the customers best interests
that things start to go haywire...

#: 211190 S10/Views:Zachmann [E]
    07-Jul-92  04:11:33
Sb: #210674-Independence Declaration
Fm: Cole Loftus [C81] 76360,1320
To: Charles Hart 72755,500

Charles-

Advertising money is due to circulation--you need readers to get it, and their
perception of your rag will influence their desire to read it.  So pleasing
readers *does* compute.

-Cole

#: 211004 S10/Views:Zachmann [E]
    06-Jul-92  19:25:57
Sb: #210641-#Independence Declaration
Fm: Koll Simonds - GDI 70144,1540
To: Ross M. Greenberg 72461,3212

> However, in some books, such as Computer Reseller News, when a major
advertiser > tried something similar to what we've heard about here, the
editor refused to > buckle under and the advertiser was told to go advertise
elsewhere.

> There is a fragile trust between the public and the editorial creators of a
> magazine that is easy to destroy.

This is all based on the assumption that any given contributor to any pub has
some soft of *entitlement* to say anything they please - regardless of
management's wishes.

John Dvorak could go start-raving-mad (had to pick an example, John.  No
offense...:) and started writing non stop about GeoWorks and bashing BOTH Win
and OS/2 for being resource hogs written in C.  Does he have a RIGHT to do
that.  Certinaly he has a right to try.  But the owners of the publication
 (seeing they kindda did invest the capital) should have the final say.

Whether that makes for the better magazine, the marketplace will tell.

Koll

* Replies:  211132, 211191

#: 211132 S10/Views:Zachmann [E]
    06-Jul-92  23:36:29
Sb: #211004-Independence Declaration
Fm: John C. Dvorak [PCMAG] 72241,47
To: Koll Simonds - GDI 70144,1540

Hey, use the middle initial Koll!  What would be so "stark-raving-mad" about
non-stop promotion of Geoworks?  It's pretty damned good. Win AND OS/2 ARE
resource hogs written in "C".  I think you've stumbled on to something.  Let's
see what happens. <heading to word processor>

#: 211191 S10/Views:Zachmann [E]
    07-Jul-92  04:11:40
Sb: #211004-Independence Declaration
Fm: Cole Loftus [C81] 76360,1320
To: Koll Simonds - GDI 70144,1540

Koll-

The issue is not the writer's *right* to say what he wishes, but whether the
editorial policy is one of fairness, which serves the reader, or one of
serving the advertiser, and eschews the needs of the reader.

-Cole

#: 210806 S10/Views:Zachmann [E]
    06-Jul-92  11:27:00
Sb: #210519-#Independence Declaration
Fm: John Oellrich [AT&T] 72611,1452
To: Charles Hart 72755,500 (X)

Charles,

>>Ross, what planet did you wake up on this morning?  If it's this one, then
you *must* know that Ziff exists for one purpose and one purpose only:  To
sell advertising<<

Actually I would ask what planet you woke up on. Yes Ziff is in the business
of making money, thru adverts, subscriptions, .... Advertising does make up
the lions share. But to sell ads, you need readers, to get readers you have to
provide content that is of value to the reader. If the content is suspect you
lose readers, when you lose readers, you loose advertisers. When you talk of
PC Week which solely derives its revenues from ads it sells based on its
supposedly influential reader base it could be devastating.

Partiality will have a deleterious effect on other advertisers as well. If IBM
or Borland or Lotus beleives that partiality exists they ain't going to
continue to grace the pages with their ads.

John

* Reply:  210988

#: 210988 S10/Views:Zachmann [E]
    06-Jul-92  19:04:19
Sb: #210806-#Independence Declaration
Fm: Charles Hart 72755,500
To: John Oellrich [AT&T] 72611,1452 (X)

 >Yes Ziff is in the business of making money, thru adverts, subscriptions,
 >..... Advertising does make up the lions share.

Subscriptions (and newsstand sales) are only used to provide a base
circulation figure that can be audited.  Think of magazines that sell
subscriptions as controlled circulation types that qualify the reader on a
current economic basis instead of whatever purchasning influence he/she might
have.

 >But to sell ads, you need readers, to get readers you have to provide
 >content that is of value to the reader.

Verily, verily.  Of *course* content is needed to get readers.  I say the
content is the *advertizements* for more of the readers than you are willing
to admit.

 >When you talk of PC Week which solely derives its revenues from ads it sells
 >based on its supposedly influential reader base it could be devastating.

Within thirty days this will not be remembered by anyone not directly
involved.  PW Week will go on as it always has, infuriating some for the
apparently arbitrary subscription requirements and pleasing the vast majority
of those who even know about it by allowing them into the exclusive group that
receives the rag.  The sun will still rise and set as usual, and more
importantly the exact same advertisers will spend the exact same amount on PC
Week.

Some things never change, and one is that you truly can not fight a group that
does not believe there is a problem.....

* Reply:  211044

#: 211044 S10/Views:Zachmann [E]
    06-Jul-92  20:37:22
Sb: #210988-Independence Declaration
Fm: John Oellrich [AT&T] 72611,1452
To: Charles Hart 72755,500 (X)

Charles,

I think you are the one that makes the mistake. We all chuckle about the lack
of accuracy in a PC Week or an InfoWorld, but if it was ever proven that its
editorial staff colluded with a vendor, you can chuck it all. People
understand inaccuracy in a weekly, they do not like being had by anyone.

John

#: 210867 S10/Views:Zachmann [E]
    06-Jul-92  13:29:24
Sb: #210519-#Independence Declaration
Fm: Greg Comeau@Comeau Comp 72331,3421
To: Charles Hart 72755,500 (X)

>There is *no* commercial for-profit magazine that you can trust implicitly and
>I know of no non-profit magazines - but I will entertain the concept that one
>might exist. Maybe.

Although I have been unfortunate to have 1st hand exposure of such things
over the years (2nd, 3rd, etc too), your statement here is grossly exaggerated.

* Reply:  210991

#: 210991 S10/Views:Zachmann [E]
    06-Jul-92  19:04:54
Sb: #210867-#Independence Declaration
Fm: Charles Hart 72755,500
To: Greg Comeau@Comeau Comp 72331,3421 (X)

YMMV, and if so I am pleased you have been so lucky.  I have not, and my
comments are based on my direct experience.

* Reply:  211071

#: 211071 S10/Views:Zachmann [E]
    06-Jul-92  21:17:54
Sb: #210991-Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Charles Hart 72755,500

Your
Milage
May
Vary

??

That's my YMMV guess..

Rick

#: 210985 S10/Views:Zachmann [E]
    06-Jul-92  18:53:23
Sb: #210519-#Independence Declaration
Fm: Bill Machrone [PCMAG] 72241,15
To: Charles Hart 72755,500 (X)

Now wait a flimflam minute, here. If you're implying that Corporate Computing
has "almost *no* editorial content," I object strenuously. Having lived
through the most difficult and expensive comparison test ever done, I can
vouch for the effort that went into not only the testing, but some fairly
negative comments about big vendors and advertisers. We've always had the
freedom to make those calls, and we always will.

One of the advantages of being big and successful is that no one advertiser
can hurt you by boycotting.

- Bill

* Replies:  210999, 211049, 211148

#: 210999 S10/Views:Zachmann [E]
    06-Jul-92  19:22:14
Sb: #210985-Independence Declaration
Fm: Charles Hart 72755,500
To: Bill Machrone [PCMAG] 72241,15

Ah, Ha!  Gigged a big one with that comment, it seems.  I wondered when I got
no comment at all from Mr. Beem, to whom it was intended as you will recall.

Perhaps we need to define "editorial content" as I use it:  By that I mean the
computer columnists writing regular by-lined columns in one traditional place
in the magazine with their picture at the head of the column - you know,
"editorial commentary and opinion about the important issues of the day"
stuff, not articles about the various press releases issued this last month
(and no, CC is not really bad about that so far) and especially not big
comparisons of products that are apparently simple compilations of spec
sheets.  While compiling spec sheets (and yes, I know how hard that is to do -
I've heard the PC Week gripe about the non-responsiveness of vendors) is of
value to many corporate users, by no stretch of the imagination is it
"informed editorial commentary" - and that's what I am looking for when I say
"editorial content".

And, since he as not responded (burned out by the message volume, I would
guess) I must admit that the first article by Mr. Beem was one of the two from
the magazine that I captured for immediate use - so I was a bit harsh on him.
The other was that neat article on travel agency robots (as a small sideline I
administer a travel agency - don't ask me how my conglomerate came to own it,
please) which had several errors in the data (appeared it was researched some
time ago, right?) about the companies but was still useful as a starting point
- which is more than I can say for any other mag.

#: 211049 S10/Views:Zachmann [E]
    06-Jul-92  20:52:41
Sb: #210985-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: Bill Machrone [PCMAG] 72241,15

Bill,

Personally, I think Will should renegotiate his contract so he only does
columns for PC Magazine--I find Will's columns more thoughtful in PC Magazine,
for starters.

Raymond Chuang

#: 211148 S10/Views:Zachmann [E]
    06-Jul-92  23:38:51
Sb: #210985-Independence Declaration
Fm: John C. Dvorak [PCMAG] 72241,47
To: Bill Machrone [PCMAG] 72241,15

A "flimflam minute?"  Is that some new high tech measurement?

#: 211138 S10/Views:Zachmann [E]
    06-Jul-92  23:36:58
Sb: #210519-Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Charles Hart 72755,500

Ross seems to live on the same planet I do--one in which many in this human
race value principles of fairness, concern for others, truth, and decency
above greed, necessary evils, facts of life, and other capitulations to
cynacism and despair...

We believe what we choose to believe, Charles, and enjoy peace of mind or
troubled spirits in varying degrees based on the choices we make...

#: 210480 S10/Views:Zachmann [E]
    05-Jul-92  19:17:39
Sb: #210070-#Independence Declaration
Fm: J.C. Love [AsstOp] 72241,1006
To: William F. Zachmann 72241,43 (X)

I read your personal declaration of independence early this morning and
decided that the best response would be to go run.  So I did. Seventeen miles
in the mountains and in the heat gave me time to think about events.

Your action is not unexpected, Will.  You've been oh so careful in your public
comments regarding rumors of Microsoft's pressure on you via PC Week's
management.  General news articles in PC Week seem to have a Microsoft slant,
so it appears to me that you're not the only one in the midst of pressure and
conflict.

It appears to be easy for readers to fail to understand that you have
consistently not bashed Microsoft, nor have you promoted IBM.  You've
evaluated present facts (not to be confused with future facts <g>) and made
some well-reasoned assessments of the impact of those facts on future events.
You've been consistent and fair.  You've taken heat because your assessments
are not what Microsoft wants to hear.

Sam Whitmore's public response to you appears to me to be seizing an
opportunity to watch a problem go away.  It seems to me that a publication
purporting to report on an industry needs to be absolutely unintimidated by
individual companies.  It seems like there's a parallel with Caesar's wife
here somewhere.

The whole affair is obviously disturbing to a large segment of participants
here.  Everyone, including me, respects your refusal to compromise your
integrity (I know something about how painful that can be).  No matter what
happens at PC Week, I hope that your columns in PC Magazine can continue
beyond the end of September, and that your presence here will continue
uninterrupted.

                                                 jc

* Replies:  210499, 210520

#: 210499 S10/Views:Zachmann [E]
    05-Jul-92  20:14:13
Sb: #210480-Independence Declaration
Fm: William F. Zachmann 72241,43
To: J.C. Love [AsstOp] 72241,1006 (X)

John,

Thanks both for the kind words and for a reasonable and objective view of the
matter.

All the best,

Will

#: 210520 S10/Views:Zachmann [E]
    05-Jul-92  21:11:12
Sb: #210480-#Independence Declaration
Fm: Charles Hart 72755,500
To: J.C. Love [AsstOp] 72241,1006 (X)

 >Everyone, including me, respects your refusal to compromise your integrity
 >(I know something about how painful that can be).

Not everyone.  Some think it would have been more effective in the long run to
continue the fight internally.  To make the problem public as he has donw will
solve nothing, as Ziff can not be seen to respond to the desires of a
disaffected employee.  To do so would invite others to attempt the same
pressure play, not something any prudent management invites.

* Replies:  210531, 210587, 210775, 211140

#: 210531 S10/Views:Zachmann [E]
    05-Jul-92  22:11:54
Sb: #210520-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Charles Hart 72755,500 (X)

Charles,

What a crock!  I often "respond to the desires of a disaffected employee." My
doing so does not encourage "others to attempt the same pressure play."

Contrary to your statement, prudent management acknowledges and deals with
dissatisfied employees.

    Bruce

* Replies:  210558, 210626, 210634

#: 210558 S10/Views:Zachmann [E]
    05-Jul-92  23:03:31
Sb: #210531-#Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Most of the time and on average, dealing with "management" issues in a public
forum is not as effective as privately because both sides get stuck in a peace
with honor, face saving thing.. This is the unfortunate side effect. It takes
much more effort to tone it down, relax, and chat, when it is public..

Rick

* Replies:  210588, 210747, 210923

#: 210588 S10/Views:Zachmann [E]
    06-Jul-92  00:44:36
Sb: #210558-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Rick Segal-Microsoft 76276,2706 (X)

Rick,

Had I thought there remained even the slightest chance of a quiet, private,
behind the scenes, satisfactory resolution of this matter I would not have
made a public issue of it.  The matter came to a head two months ago on April
23 and had been going on for months before that (even before I'd been required
to shift the focus of my PC Week column to "Windows and its competitors" last
fall).

Until the April 23 incident, I didn't even protest matters directly in
private.  I kept trying to accomodate in a manner that was consistent with my
own sense of integrity.  It was only after the April 23 incident that I began
to resist efforts to dictate what I wrote about and how I wrote it.  Only
after two months of repeated aggravation and clear indications that matters
weren't going to get any better (and likely worse) did I take the steps that I
did.

Will

* Reply:  210704

#: 210704 S10/Views:Zachmann [E]
    06-Jul-92  08:28:17
Sb: #210588-#Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: William F. Zachmann 72241,43 (X)

Will (and all)

For the record, there is no doubt in my mind that you truly feel ZD is not
playing nice. No doubt and I am not questioning your feelings in the least.

There is also no doubt that MS complains when they feel things are not fair
(right or wrong).  I was up here complaining about some of your columns and
some of PC-Weeks treatment of my company.  You held your ground well, we went
back and forth, and generally we agree to disagree on many things. Up to this
point, no issue, game being played about the way one would expect.

Then it gets weird. In my years doing this stuff, I have seen/
watched/encountered many folks at ZD. I *only* make the observation that, in
my opinion, those that I know appear to have the ethics that would make
crumbling before an advertiser just not possible. Joel Shore of CRN, Gary
Beach of Computerworld, Sam/John of ZD.. These people all seem, in my opinion
to try very hard to play it straight and keep some sense of balance and
standards in place. I only observe, Will, that I can clearly see any major
advertiser going to any publication and expecting to pressure but in many
cases, there are people with high ethics/standards that prevent the
complaining from turning into influence.

I think John Dodge slimed me in Katt. That was not Pro-MS and some will say I
deserved it. I think the guy is a crumb for doing it. A crumb for calling
Microsoft to complain about me talking bad about PC-Week.  I also think he
would resign in a second if he was feeling pressured to do something that
wasn't playing straight. His tatics are typical PC-Week trash BUT he is a man
with ethics and I doubt he would stand for influence peddling.. Rick

* Replies:  210823, 211141

#: 210823 S10/Views:Zachmann [E]
    06-Jul-92  12:06:36
Sb: #210704-#Independence Declaration
Fm: CyberSim [E. Pinnell] 70031,435
To: Rick Segal-Microsoft 76276,2706 (X)

Rick,

    When did Katt slime you? What issue?

Eric Pinnell

* Replies:  210873, 210888

#: 210873 S10/Views:Zachmann [E]
    06-Jul-92  13:37:25
Sb: #210823-#Independence Declaration
Fm: Chuck Ebbert 76306,1226
To: CyberSim [E. Pinnell] 70031,435

The Katt slimed Rick in the current issue.  Go ZNT:PCWNEWS and read all about
it!

* Reply:  210897

#: 210897 S10/Views:Zachmann [E]
    06-Jul-92  14:57:03
Sb: #210873-Independence Declaration
Fm: Patrick Pearce(LIFE CARE 70662,2714
To: Chuck Ebbert 76306,1226

<The Katt slimed Rick in the current issue.  Go ZNT:PCWNEWS and read all about
it!>


                WE'RE FAMOUS   !!!!!!!!!!!!!!!!!!!!!!!!!

#: 210888 S10/Views:Zachmann [E]
    06-Jul-92  14:42:45
Sb: #210823-#Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: CyberSim [E. Pinnell] 70031,435

Current issue.. Does this mean I'm important enough to rate or just an easy
target <G>

* Replies:  210900, 210914

#: 210900 S10/Views:Zachmann [E]
    06-Jul-92  15:08:21
Sb: #210888-#Independence Declaration
Fm: Patrick Pearce(LIFE CARE 70662,2714
To: Rick Segal-Microsoft 76276,2706 (X)

Rick,

What IS your Currant Rate?

* Reply:  210998

#: 210998 S10/Views:Zachmann [E]
    06-Jul-92  19:17:42
Sb: #210900-Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Patrick Pearce(LIFE CARE 70662,2714

You can get me for $100 per hour or a decent dinner. Homemade mashed potatos
with the lumps and I give up the source code...

Rick

#: 210914 S10/Views:Zachmann [E]
    06-Jul-92  16:07:59
Sb: #210888-#Independence Declaration
Fm: earle robinson [ibmeur] 76004,1762
To: Rick Segal-Microsoft 76276,2706 (X)

You may smile, but I found the column wholly offensive, as well as wholly
false.  The editor of pc week owes you an apology.   -er

* Replies:  211050, 211072

#: 211050 S10/Views:Zachmann [E]
    06-Jul-92  20:52:46
Sb: #210914-Independence Declaration
Fm: Raymond Chuang 72441,3652
To: earle robinson [ibmeur] 76004,1762 (X)

Earle,

Actually, I thought that Mr. Segal was actually pretty reasonable--but the
OS/2 crowd did get a wee bit fanatic a few weeks ago.

Raymond Chuang

#: 211072 S10/Views:Zachmann [E]
    06-Jul-92  21:18:00
Sb: #210914-Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: earle robinson [ibmeur] 76004,1762 (X)

I don't smile and will eat a box of floppy disks if I get an appology..

It was not fair and a cheap shot at me that I don't believe I deserve..

Part of the game, I guess.. 8-(

Rick

#: 211141 S10/Views:Zachmann [E]
    06-Jul-92  23:37:14
Sb: #210704-#Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Rick Segal-Microsoft 76276,2706 (X)

Rick, when did Dodge slime you and what did he say?  Did I miss that one or
was it before I knew you?

* Reply:  211161

#: 211161 S10/Views:Zachmann [E]
    07-Jul-92  00:31:23
Sb: #211141-Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Dave Whittle [IBM] 70303,1352

Check out this weeks Katt..

#: 210747 S10/Views:Zachmann [E]
    06-Jul-92  09:41:28
Sb: #210558-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Rick Segal-Microsoft 76276,2706 (X)

Rick,

What you say about trying to resolve differences privately is very true, but I
think Will made a good faith attempt to do that.  Maybe Sam Whitmore feels
otherwise.

   Bruce

* Reply:  210831

#: 210831 S10/Views:Zachmann [E]
    06-Jul-92  12:07:55
Sb: #210747-Independence Declaration
Fm: Rick Segal-Microsoft 76276,2706
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Beats me, Bruce.. Lots of good people getting wrapped up in a lot of emotion
that seems, at best, to be miguided, and at worst damaging to all involved..

Rick

#: 210923 S10/Views:Zachmann [E]
    06-Jul-92  16:12:34
Sb: #210558-Independence Declaration
Fm: Jeff Winchell 76066,533
To: Rick Segal-Microsoft 76276,2706 (X)

Public negotiating works in sports. I suppose its possible in computer
publishing. There are about a million or two readers of those two ZD
magazines, so I guess it could be possible here. Precedents have to be
established sometime.

#: 210626 S10/Views:Zachmann [E]
    06-Jul-92  05:27:49
Sb: #210531-#Independence Declaration
Fm: Charles Hart 72755,500
To: Bruce Biermann [ZiffNet] 72241,261 (X)

 >What a crock!  I often "respond to the desires of a disaffected employee."
 >My doing so does not encourage "others to attempt the same pressure play."

 >Contrary to your statement, prudent management acknowledges and deals with
 >dissatisfied employees.

Congratulations on adopting an enlightened attitude toward your employees. Is
there any rational reason why such a policy was not applied to Will?

* Reply:  210748

#: 210748 S10/Views:Zachmann [E]
    06-Jul-92  09:41:33
Sb: #210626-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Charles Hart 72755,500 (X)

Charles,

>Is there any rational reason why such a policy was not applied to Will?

You will have to ask Sam and Eric that question.

   Bruce

* Reply:  210793

#: 210793 S10/Views:Zachmann [E]
    06-Jul-92  11:16:49
Sb: #210748-Independence Declaration
Fm: Charles Hart 72755,500
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Yes, I was gently told you had no responsibility in that area by another. My
apology for taking you as a participant in the fiasco and thanks for the
comment.

#: 210634 S10/Views:Zachmann [E]
    06-Jul-92  05:33:29
Sb: #210531-#Independence Declaration
Fm: Charles Hart 72755,500
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Please disregard previous message - it was written before I read one from Will
advising that he was not and had never been an employee of Ziff.  My apology
for jumping to the conclusion that he was/had been an employee.

So, why do not you apply that enlightened policy you mentioned in your message
to your contract workers?  While they have no employment rights under law, one
would think that if only for the sake of appearance you would apply the policy
across the board, no?

* Replies:  210656, 210749

#: 210656 S10/Views:Zachmann [E]
    06-Jul-92  06:35:36
Sb: #210634-#Independence Declaration
Fm: Ben Sano 72401,2736
To: Charles Hart 72755,500 (X)

Charles

Another piece of information you should have is that Burce Biermann is not
an employee of Ziff either. He is (I believe) a member of the Ziffnet staff
and an unpaid one at that.

--Ben

* Reply:  210675

#: 210675 S10/Views:Zachmann [E]
    06-Jul-92  07:11:09
Sb: #210656-Independence Declaration
Fm: Charles Hart 72755,500
To: Ben Sano 72401,2736 (X)

Ok, correction noted.  A scorecard would be helpful, but I left mine at home
today.....

<g>

#: 210749 S10/Views:Zachmann [E]
    06-Jul-92  09:41:38
Sb: #210634-#Independence Declaration
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Charles Hart 72755,500 (X)

Charles,

As Ben said, I am not an employee of Ziff-Davis or any related company.  Do
you think Sam Whitmore might want my resume?

    Bruce

* Reply:  210794

#: 210794 S10/Views:Zachmann [E]
    06-Jul-92  11:17:02
Sb: #210749-Independence Declaration
Fm: Charles Hart 72755,500
To: Bruce Biermann [ZiffNet] 72241,261 (X)

*I* am not an employee of Ziff, so I have absolutely no insight as to their
current hiring requirements.

Nevertheless, it never hurts to ask.  Send him an Email message.....

#: 210587 S10/Views:Zachmann [E]
    06-Jul-92  00:44:29
Sb: #210520-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Charles Hart 72755,500 (X)

Charles,

I am not and never have been a Ziff employee.

Will

* Replies:  210628, 210662

#: 210628 S10/Views:Zachmann [E]
    06-Jul-92  05:28:05
Sb: #210587-#Independence Declaration
Fm: Charles Hart 72755,500
To: William F. Zachmann 72241,43 (X)

 >I am not and never have been a Ziff employee.

I understand what you are saying and believe your facts as stated.

Nevertheless, your column appears in PC Mag and PW Week in such a manner as to
suggest that you are an employee.  Take a poll - I bet you will be surprised
at the non-Ziffnet readers who think you are a Ziff employee.

Thanks for the response.

* Replies:  210676, 210850

#: 210676 S10/Views:Zachmann [E]
    06-Jul-92  07:12:48
Sb: #210628-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Charles Hart 72755,500 (X)

Charles,

I have my own business, Canopus Research, through which I do computer and
communications industry market and technology research and analysis.  I do
consulting for vendors, users and the financial community.  I also have a
lively business as a public speaker.  My columns for Ziff-Davis publications
have been handled through an agreement between Ziff-Davis Publishing Company
and myself that has been in effect since September of 1988.

Will

#: 210850 S10/Views:Zachmann [E]
    06-Jul-92  13:02:02
Sb: #210628-#Independence Declaration
Fm: earle robinson [ibmeur] 76004,1762
To: Charles Hart 72755,500 (X)

Perhaps to the naive.  The masthead shows zachmann, like a number of other
columnists and regular reviewers, as 'contributing editors'.   -er

* Reply:  210989

#: 210989 S10/Views:Zachmann [E]
    06-Jul-92  19:04:30
Sb: #210850-Independence Declaration
Fm: Charles Hart 72755,500
To: earle robinson [ibmeur] 76004,1762 (X)

I admit, I was "naive" in this matter - when later introspection caused me to
suddenly realize that even Ziff could not afford to have all those
heavyweights on an exclusive service arrangement, employment or not.

Thinking now, I bet there are only (say) three actual full time editorial
employees of PW Week, as an example.....

#: 210662 S10/Views:Zachmann [E]
    06-Jul-92  06:43:44
Sb: #210587-Independence Declaration
Fm: Neil Rubenking [PCMAG] 72241,50
To: William F. Zachmann 72241,43 (X)

Will,
       But were you ever a member of the Abraham Lincoln Brigade?
               - Nil

P.S. I must admit, my initial reaction to the huge number of messages in
Editorial was to *SKIP* S10 entirely.  So I didn't see what was going on 'til
someone else pointed me this way.  I hate to see ya go - are you SURE you
can't just drop PC Week by itself??

#: 210775 S10/Views:Zachmann [E]
    06-Jul-92  10:47:42
Sb: #210520-Independence Declaration
Fm: J.C. Love [AsstOp] 72241,1006
To: Charles Hart 72755,500 (X)

Beg your pardon, Charles.  You are right that I should not have pretended to
have spoken for everyone.  Others whose opinions I respect including you,
Peter Coffee, and Earl Robinson feel differently.  And those opinions have a
great deal of validity.

I know Will personally, indeed, I count him among my friends, and believe that
he saw no other means to maintain his integrity.  I'm sure he thought long and
hard before taking such an action - Will, in my experience, is a careful man.

But, again, I should not have spoken for others, and I apologize.

                                                 jc

#: 211140 S10/Views:Zachmann [E]
    06-Jul-92  23:37:08
Sb: #210520-Independence Declaration
Fm: Dave Whittle [IBM] 70303,1352
To: Charles Hart 72755,500

Nonsense.  I wouldn't be here if "prudent management" at IBM had your opinion
of things. If management can't judge between "pressure plays" and refusal to
compromise integrity, then management doesn't deserve the responsibility of
ensuring that outstanding talent be given an opportunity to express itself.

#: 210573 S10/Views:Zachmann [E]
    05-Jul-92  23:35:45
Sb: #210070-Independence Declaration
Fm: Frank Ivan 75300,1406
To: William F. Zachmann 72241,43 (X)

Will,

It is sad that Ziff Davis should allow this to happen.  I have noted what I
believe to be just the bias you point out.  Unfortunally in the long run such
bias will only serve to harm the very industry that both PC Week and Microsoft
depend upon for their very existance.  By fostering the notion that small
systems can not be dependable, the entire industry is hurt.  It is especially
sad to see Microsoft resort to dirty tricks (not just toward you but toward
the entire industry) for a short term profit.  Its time for Mr. Gates to put
somthing back into the industry.

I suppose Ziff Davis must also try to make a proffit, but, I suspect that any
short term profit they derive by allowing one advertiser to set policy will be
shorter than even they imagine.  After all, you don't see CP/M week any more
most if not all the Apple II publications are gone.  Maybe they should rename
it Microsoft Week.

In any event, good luck - ain't it a b*tch being right?  Keep us posted where
we can read your articals. Cheers, Frank

#: 210863 S10/Views:Zachmann [E]
    06-Jul-92  13:28:35
Sb: #210070-#Independence Declaration
Fm: Greg Comeau@Comeau Comp 72331,3421
To: William F. Zachmann 72241,43 (X)

>I can think of no better occasion than the Fourth of July to declare
>independence from those who would dictate the content of what I write.  Over
>the past several months, I have been repeatedly subject to what I feel to be
>inappropriate and improper pressure from PC Week in regard to my views on
>Microsoft and Windows, IBM and OS/2.
>...I am
>concerned that the regretable tendency to shape editorial content to please a
>major advertiser (Microsoft in this case) which I have noted in some competing
>publications is being imported into the Ziff-Davis Publishing Company.

Speaking out loud, I must state that this is odd: when I have spoken of
such things over the past 2 or so years I have repeatedly been told
such things do not occur (even when I am talking of different subjects!) so
many times that I simply cannot believe what you state since I have been told
not to.

* Reply:  210872

#: 210872 S10/Views:Zachmann [E]
    06-Jul-92  13:36:39
Sb: #210863-Independence Declaration
Fm: Ben Sano 72401,2736
To: Greg Comeau@Comeau Comp 72331,3421 (X)

Greg

That sentence hurt my head.

The idea hurt too but for other reasons and other places.


--Ben
<C++ is still OK though, and I still don't like 'c', don't want this
agreement to go too far, oh and vi is better then emacs>

#: 210388 S10/Views:Zachmann [E]
    05-Jul-92  14:07:13
Sb: #Tyranny and Independence
Fm: Tony Rosati 76662,3440
To: Will Zachmann 72241,43 (X)

Dear Will and All Others Lurking...


I was truly sad to hear about your decision not to renew your relationship
with Z-D. Further, I was quite ticked off by the way the Z-D mamnagement at PC
Week treated you, as per your recent threads on this topic.

One of the important "draws" about this country is its history of press
freedom, which bases itself on Editorial Freedom. The Peter Zenger case, from
pre-revolutionary days (I believe) has been marked as the inception of this
particular freedom. I am repulsed and enraged that sanctum sactorum of
Editorial Opinion has been chipped away in a periodical that prints for an
industry that is on the verge of setting another precedent in our freedoms and
rights! I may not be wealthy or influential or gifted in political ways, but I
have enough intelligence to realize when something smells foul. If all you say
is true (and I feel confident in assuming your truthfulness), then I can only
say that Z-D takes its own financial well-being in its own hands when it
insults the intelligence of its readers. How dare they tinker with the
independence of thought that is supposed to occur within the Editorial Staff!
Even worse, how dare they do so without confessing to it publically!? If Z-D
wants PC Week to be solely Microsoft-riented, then they should have publically
said so, and given Will said notice and an option to stop writing for PC Week.
However, that didn't happen. As such, I, a user and a MIS for my department,
will wait to see what Z-D does. If I am not satisfied, then EVERY SINGLE
PERSON I ENCOUNTER WHO WANTS TO HEAR WILL KNOW OF MY DISPLEASURE AND OF MY
RECOMMENDATION TO IGNORE PC WEEK, free subscription or not!

In a time when our civil liberties are slashed and cut at every corner, when
our politicians care not to truly listen to our pleas and when the wealthy
seem to dominate our way of life, I think it is time to remind those willful

  [>> Continued in next msg]

* Replies:  210389, 210457, 210522

#: 210389 S10/Views:Zachmann [E]
    05-Jul-92  14:07:21
Sb: #210388-Tyranny and Independence
Fm: Tony Rosati 76662,3440
To: Tony Rosati 76662,3440 (X)

  [>> Continued from previous msg]

enough to trample on everyone's freedom that they cannot continue to do so
without the light of day shining on their activities.

I am not one to stand on a soapbox, delivering sermons to any and all who
would hear. However, I have a horrid distaste for such stealth maneuvers by
those who would dictate how I think/read/act. I feel this is one of those
times.

Will, good luck in whatever you do and for whatever forum you write for. I,
for one, wait to hear if I should shred my subscription to PC Week or not.

Tony :<

#: 210457 S10/Views:Zachmann [E]
    05-Jul-92  17:47:53
Sb: #210388-#Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: Tony Rosati 76662,3440 (X)

Tony..

Of course, after that very moving speech, you _do_ know the facts on both
sides of the issue, don't you? _I_ certainly don't know the facts of the
story, other than what Will has said here, but you've very quickly become
prosecutor, judge, and jury, all at once..

I guess we hear what we really want to hear and ignore the rest.

I, too, would be saddened if what Will says is true. I'm also not calling Will
a liar, by any means. But how can we say what happened here when we've really
just heard Will's side of it. How can you _know_ what happened here without
getting both sides of the story?

-Dale

* Replies:  210464, 210473, 210493

#: 210464 S10/Views:Zachmann [E]
    05-Jul-92  18:11:29
Sb: #210457-#Tyranny and Independence
Fm: Ben Sano 72401,2736
To: Dale Lewallen 76000,21 (X)

Dale

It is both customary and reasonable for the burden of proof to fall on the
person to whom lying or silence would be an advantage rather then to the
one who by lying would be a hurt.

By this principle I accept Will's statements until refuted by reasonable
evidence from PC-WEEK.

Got some facts to throw into the matter?

Copies of relevent documents would be nice, if you have them I will give you
my FAX number.

--Ben

* Replies:  210559, 210563

#: 210559 S10/Views:Zachmann [E]
    05-Jul-92  23:03:35
Sb: #210464-Tyranny and Independence
Fm: Rick Segal-Microsoft 76276,2706
To: Ben Sano 72401,2736 (X)

Umm.. didn't Sam deny it? That's not silence.. What would you expect them to
do? Just askin, no flame..

Rick

#: 210563 S10/Views:Zachmann [E]
    05-Jul-92  23:10:33
Sb: #210464-#Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: Ben Sano 72401,2736 (X)

Ben..

BS>> "It is customary...burden of proof to fall on the person to whom lying or
silence would be an advantage.."

Um, OK, I remember it as "Innocent until proven guilty," but I'm definitely no
lawyer.

BS>> "Got some facts to throw into the matter? Copies of relevent documetns
would be nice, if you have them I will give you my FAX number."

Ah, this ranks right up there with "What are _your_ credentials?"

No, Ben, I never said that I knew any facts of this story, _other_ than what
Will said in his postings. In fact, I don't _know_ that Will is being honest
or objective although I have no reason to doubt it either. You know, when you
yell at the kids for fighting and one says "He hit me" and the other says "No,
he hit _me_!"

Why would I know anything more than you do? My question to Mr. Rosati, and
I'll pose it to you as well: Do you _know_ PC Week's side of the story? Or do
you _think_ you know PC Week's side of the story because of what Will said?

-Dale

* Replies:  210576, 210589, 210967

#: 210576 S10/Views:Zachmann [E]
    05-Jul-92  23:40:18
Sb: #210563-#Tyranny and Independence
Fm: Ben Sano 72401,2736
To: Dale Lewallen 76000,21 (X)

Dale
 >I rememer it as 'innocent until proven guilty' but I'm definitly not a
 >lawyer

I'm not a lawyer either but since this feels more like a civil rather then a
criminal matter (no one was bribed right?) I think the phrase is 'weight of
evidence'.

I don't know PC-WEEKS side of the story I'm ASKING for PC-WEEKS side of the
story with documents if possible.

I thought that was the point.

If you don't have any evidence perhaps others will.

--Ben

* Replies:  210584, 210658, 210978

#: 210584 S10/Views:Zachmann [E]
    05-Jul-92  23:59:42
Sb: #210576-Tyranny and Independence
Fm: Wayne Robertson (SAMC) 76546,560
To: Ben Sano 72401,2736 (X)

Ben,

You may want facts from the PC Week side of the story but I believe in a
previous message you said you didn't believe Sam Whitmore shortly after the
message was posted by Will Zachmann.

How can we believe that you are interested in hearing both sides of the story?

-Wayne

#: 210658 S10/Views:Zachmann [E]
    06-Jul-92  06:41:32
Sb: #210576-#Tyranny and Independence
Fm: Peter Coffee (PC Week) 72631,113
To: Ben Sano 72401,2736 (X)

Documents? Ben, good buddy, we don't keep formal minutes of meetings. That
doesn't work in a weekly publication.  If you want to go with the civil
standard of "preponderance of the evidence," I offer for your inspection the
hundreds of pages of PC Week.  Remember the flack we took when we reported on
incompatibilities between Win 3.0 and Win 3.1? Remember Paul Sherer's cover
story that appeared on the show-floor issue at the first Atlanta Windows
World, with a headline to the effect of "Corporate Users Fed Up With Windows
Weaknesses"?  The best question asked so far in these threads has been, "Why
would one columnist be subject to this kind of pressure and not the rest of
the paper?"  It makes no sense, and even in civil proceedings a motive is kind
of important.

* Replies:  210681, 210682, 210766

#: 210681 S10/Views:Zachmann [E]
    06-Jul-92  07:24:26
Sb: #210658-Tyranny and Independence
Fm: Ben Sano 72401,2736
To: Peter Coffee (PC Week) 72631,113 (X)

Peter
 >we don't keep formal minutes of meetings.

Since the time and date are well know and the dispute is over a phone call,
Since you folks probably have a phone system with logging billing I am SURE
that if such a loging tape exists the existance or non-existance of such a
call to MS in a two hour period could be verified. Hey this is one of the
things computers are GOOD FOR. I certainly have written one of two phone log
extraction programs in the past (one in COBOL) so I know what can be done.

 >the best question asked so far in these threads has bee "Why would one
  columnist be subject to this kind of pressue and not the rest'

If you have frequented both the OS/2 and Windows sections on Usenet you
would realize that Will Z's steadfast belief in OS/2 has pretty much cast
him in the role of 'great satan' in the eyes of quite a few Microsoft
employees. Of course when he is gone another 'great satan' will arise,
possibly not so great but large enough to be the lightening rod.

earl's observation that for awhile now MS's people have been acting like a
cult is not with out truth to it.

--Ben

#: 210682 S10/Views:Zachmann [E]
    06-Jul-92  07:24:32
Sb: #210658-Tyranny and Independence
Fm: Ben Sano 72401,2736
To: Peter Coffee (PC Week) 72631,113 (X)

Peter

The hundreds of pages of PC-WEEK are are your best method of regaining your
creditablity but I'm less then certain that they are evidence here there are
certainly some folks on IBMOS2, many of whom I would not easily put in the
'crackpot' catagory who consider the pages of PC-WEEK as the strongest
evidence that what Will says is true.

--Ben

#: 210766 S10/Views:Zachmann [E]
    06-Jul-92  10:24:55
Sb: #210658-#Tyranny and Independence
Fm: Frank Ivan 75300,1406
To: Peter Coffee (PC Week) 72631,113 (X)

Peter,

No offense, but, Will is about the only columinst at PC Week or PC Magazine
pointing out effectivly OS/2's strengths and calling for a real protected mode
OS.  He was the only one really doing MS any damage.  Quite frankly when I
read either publication I really get the feeling you guys are afraid of
stepping on Bill Gates' toes.  Yea, windows may have weakness's but its the
best we have seems to be the gist.  The only question asked is when will MS
make it better, not should it be replaced.

Let me quote from Page 265 of the July 92 PC Week from the column on memory
managers.  "The ultimate answer (if you ignore the possibility of building
DPMI support into DOS and letting applications developers use DOS extenders to
tap into extended memory, something that is a stong possibility in future
versions of DOS, is to move to an operating system such as OS/2 or an
operating environment such as Windows that runs in protected mode, enabling
programs to access directly the vast resources of extended memory on 286, 386,
and 486 PC's.  The downside, of couse, is that application programs must be
rewritten to take advantage of these environments. Unless we're willing to
give up our favorite DOS applications as we know them, we're likely to be
wrestling with the problem of limited memory for some time to come."

(Yes - it never closed the paren).  Obviously who ever wrote that (Rick Ayre
and Laura Cox) nor their editor has any concept of what OS/2 can do or is
willing to parrot the MS line.  In either case what was published just doesn't
give all the facts (neither are they presented in side bars).

In other words Peter, Will was the guy doing MS the most damage. Also remenber
- it is DOS and these days Windows sales that are MS's cash cows. They supply
the money to develope other products.  Boosting OS/2 over DOS really has the
potential to hurt MS.

* Replies:  210810, 210968

#: 210810 S10/Views:Zachmann [E]
    06-Jul-92  11:31:20
Sb: #210766-#Tyranny and Independence
Fm: Peter Coffee (PC Week) 72631,113
To: Frank Ivan 75300,1406 (X)

>>>Boosting OS/2...has the potential to hurt MS.

Bill Gates has asserted, many times, that Microsoft makes more money per copy
sold of OS/2 than of Windows.  The battle is over who will define the
industry's direction.  I have noted, despite my preference for OS/2 as an
operating platform, that the Windows API is unassailable for perhaps the next
decade or so as the target toward which mass-market applications will be
written -- whether running on top of DOS, OS/2, or NT.  So let's not drag in
questions of who was hurting whom -- they might not turn out to support the
prevailing wisdom, and then we'd have to go back to being reasonable.

* Reply:  210969

#: 210969 S10/Views:Zachmann [E]
    06-Jul-92  18:15:45
Sb: #210810-Tyranny and Independence
Fm: Randy Johnson 73067,2150
To: Peter Coffee (PC Week) 72631,113

Peter,

>Bill Gates has asserted, many times, that Microsoft makes more money per copy
sold of OS/2 than of Windows.<

Maybe only in the short term, (I doubt that though) but not in the long range.
That's one of the reasons he is doing (or is permiting to be done) all that he
can do to stop OS/2.

Randy

#: 210968 S10/Views:Zachmann [E]
    06-Jul-92  18:15:38
Sb: #210766-Tyranny and Independence
Fm: Randy Johnson 73067,2150
To: Frank Ivan 75300,1406 (X)

Frank,

I think you're on the right track.

Randy

#: 210978 S10/Views:Zachmann [E]
    06-Jul-92  18:22:32
Sb: #210576-#Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: Ben Sano 72401,2736 (X)

Ben..

RE: "weight of evidence" and this being more civil than criminal.. OK, that's
fair..

BS>> "If you don't have any evidence perhaps others will.."

Ben, I'm truely curious: why would you ask of me to see (and FAX to you)
documents that I might have while you're willing to take Will's word for it? I
dunno', it just seems like you might be holding the parties to two different
standards?

Thanks for your reply..

-Dale

* Reply:  211005

#: 211005 S10/Views:Zachmann [E]
    06-Jul-92  19:38:44
Sb: #210978-#Tyranny and Independence
Fm: Ben Sano 72401,2736
To: Dale Lewallen 76000,21 (X)

Dale
Indeed I am holding the parties to different standards.

This is possible because the situation is not symetric.

The party who if they were to lie would benefit must prove the truth, the
party who would not benefit is presumed to be telling the truth.

Evidence of course can change this such as  if you can show a way that Will
would benefit by saying that PC-WEEK had tried to censor him when indeed it
had not.

Simple I would think.

* Reply:  211167

#: 211167 S10/Views:Zachmann [E]
    07-Jul-92  00:51:57
Sb: #211005-Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: Ben Sano 72401,2736 (X)

Ben..

BS>> "Simple, I would think.."

Alas, we politely disagree there, too. I'm afraid that the whole thing isn't
_that_ simple, were that it was.. <sigh>

Thanks for your comments on the issue..

-Dale

#: 210589 S10/Views:Zachmann [E]
    06-Jul-92  00:44:40
Sb: #210563-#Tyranny and Independence
Fm: William F. Zachmann 72241,43
To: Dale Lewallen 76000,21 (X)

Dale,

Why don't *you* tell us PC Week's side of the story, then.  I'd really be
interested to hear that.  I'd be VERY interest to hear anyone from Z-D call me
a liar or claim that I am making this up.

Will

* Replies:  210663, 210979

#: 210663 S10/Views:Zachmann [E]
    06-Jul-92  06:44:17
Sb: #210589-#Tyranny and Independence
Fm: Peter Coffee (PC Week) 72631,113
To: William F. Zachmann 72241,43 (X)

Will, I think you know perfectly well that Dale is with PC Computing, not PC
Week.  And I am not calling you deceitful or delusional -- just suggesting
that you're interpreting events in the worst possible way, and going public
with your interpretations in a way that makes the situation much more
difficult to resolve.

* Reply:  211147

#: 211147 S10/Views:Zachmann [E]
    06-Jul-92  23:37:42
Sb: #210663-Tyranny and Independence
Fm: Dave Whittle [IBM] 70303,1352
To: Peter Coffee (PC Week) 72631,113

Yes, he is, Peter.  But why?  What's in it for Will if he's mistaken?  I'd
really like to discover that Will is indeed interpreting events wrongly and
that this can be viewed as an aberration.  But I fear there's more to it than
that.  I'd certainly expect to have heard more substantive information and
rebuttal from PC Week by now...

#: 210979 S10/Views:Zachmann [E]
    06-Jul-92  18:22:37
Sb: #210589-Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: William F. Zachmann 72241,43 (X)

Hi, Will.. I thought I'd get a message from you..

WZ>> "Why don't *you* tell us PC Week's side of the story, then.  I'd really
be interested to hear that.  I'd be VERY interest to hear anyone from Z-D call
me a liar or claim that I am making this up."

How would I know what PC Week's side of the story was? As you well know (for
the lurkers), I work for a completely separate Ziff publication--PC/Computing.
C'mon, Will, I was just asking a forum member if he _knew_ what PCWeek's side
was.

Also, I would never imply that you're lying. I believe that you think yourself
to be completely without fault here. I just don't know what the other side of
this story is. I hope you don't believe me to be defending PCWeek. Hardly. Yet
I don't _know_ who's right, here. Forgive me, but just because you said it,
doesn't _necessarily_ make it true, does it? It may well be, but it might not
be..

-Dale

#: 210967 S10/Views:Zachmann [E]
    06-Jul-92  18:15:32
Sb: #210563-#Tyranny and Independence
Fm: Randy Johnson 73067,2150
To: Dale Lewallen 76000,21 (X)

Dale,

It's clear to me as a reader that most ZD publications have a bias in favor of
MS.  That's my opinion.  It also seems that ZD employees seem to be trying to
cover their bottom sides and look loyal to the boss.  If you throw a rock into
a pack of dogs only the one you hit yelps.

Randy

* Reply:  211168

#: 211168 S10/Views:Zachmann [E]
    07-Jul-92  00:52:03
Sb: #210967-Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: Randy Johnson 73067,2150 (X)

Randy..

RJ>> "It's clear to me as a reader that most ZD publications have a bias in
favor of MS. That's my opinion."

And I believe you have every right to your opinion. I don't believe that most
ZD pubs have a bias toward MS. That's my opinion.

RJ>> "It also seems that ZD employees seem to be trying to cover their bottom
sides and look loyal to the boss."

Um, could be, but I doubt it. My boss doesn't participate in this forum and I
don't work for PC Week. I'll pose to you the same question I asked of others.
It's the only issue that I've been concerned about of late. It's a simple
question, really:

Do you _know_ (ie: can you prove) that Will is right? If you don't know, why
do you automatically take his word for it? Do you _know_ that any collusion
took place? Will himself doesn't have any proof that collusion took place,
though he certainly suspects it..

-Dale

#: 210473 S10/Views:Zachmann [E]
    05-Jul-92  19:03:35
Sb: #210457-#Tyranny and Independence
Fm: Tony Rosati 76662,3440
To: Dale Lewallen 76000,21 (X)

Never said I knew all of the facts. However, I did say in my little soapbox
liturgy that I had taken Will at his word. But, regardless of what motivated
the managament at PC Week to pressure Will, they were out of line. Editorial
and management should _talk_ to one another, advising each of what is going
on, and if necessary, oreoare each other for flak, if it occurs. However, it
is the implied duty of any publication's Editorial Board to write their
opinion independently. Any effort to skew those opinions, contradicts the very
basis of American editorial journalism; it fetters the press and gives it the
image of a puppet, speaking the part written for it by others (whether
internal or external). The mere fact that Will felt pressured is enough to
question the Z-D management tactics at PC Week. Will writes an opinion column.
He has remarked on more than one occasion of his problems over the last two
months regarding his column, and several threads have occured here and in
other fora regarding said issue. By these comments I can only conclude that
something(s) certain people at PC Week have done are making Will feel that
what he writes is anathema to the management. As such, this constitutes an
undue influence. The defining measure is how Will feels; he has remarked that
after over two months of trying to deal with this, he finally couldn't take it
anymore. It is his perception of what the management is doing.

Perhaps the management isn't aware of what they were doing to Will. Certainly
the fact that the readership weren't aware all along that there were problems
between Will and the PC Week management could lend that point of view
credence. Right now, none of us knows what is the management's point of view
on this issue. That is why I am waiting to hear. If they explain themselves
sufficiently, or reconcile with Will, then I will be glad to see that the
American tradition of independent journalism has withstood another

  [>> Continued in next msg]

* Replies:  210474, 210564, 210678

#: 210474 S10/Views:Zachmann [E]
    05-Jul-92  19:03:47
Sb: #210473-Tyranny and Independence
Fm: Tony Rosati 76662,3440
To: Tony Rosati 76662,3440


  [>> Continued from previous msg]

attack. But, if they fail to convince the readership and to reconcile with
Will, then I suspect very few people will trust the material that appears in
PC Week anymore.

Tony :<

#: 210564 S10/Views:Zachmann [E]
    05-Jul-92  23:10:38
Sb: #210473-#Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: Tony Rosati 76662,3440

Tony..

Thanks for your cogent reply to my question. I don't argue with you in
priciple. It's the issue of having _already_ decided that PC Week was at
fault.

TS>> "If they [PCWeek] explain themselves sufficiently, or reconcile with
Will, then I will be glad to see that the American tradition of independent
journalism has withstood another ["test," I think but was on the next
message..]

The impression I got from your first message was that you had already made up
your mind that PC Week was guilty. Now you say "If they reconcile." It just
seems a bit inconsistent, that's all..

-Dale

* Reply:  210832

#: 210832 S10/Views:Zachmann [E]
    06-Jul-92  12:08:01
Sb: #210564-#Tyranny and Independence
Fm: CyberSim [E. Pinnell] 70031,435
To: Dale Lewallen 76000,21 (X)

Dale,

     It is entirely possible that the pressure from Microsoft is not direct.
Suppose, for example, that MS employees complaint to the advertising
department how "unfairly" Will was treating them. They get an earlful, and
pass along their complaints to either the editorial department or their higher
ups in advertising.
     Not wishing to affects its advertising revenue, Mr Ziff says "ok, maybe
we'll get Will to tone it down a little to jeep everyone happy".  Will, OTOH<
feels this is pressure and totally unacceptable.  Sam is caught between a rock
and a hard place, and wants to carry out his superior's wishes.  The net
result: KABOOM!

Eric Pinnell

* Replies:  210930, 210980

#: 210930 S10/Views:Zachmann [E]
    06-Jul-92  16:13:15
Sb: #210832-Tyranny and Independence
Fm: John Oellrich [AT&T] 72611,1452
To: CyberSim [E. Pinnell] 70031,435

Eric,

If I were to guess on what might be an effective lever on PC Week, I don't
know that advertsing would be it. Too easy to replace. However access to MS
Executives could be a fairly effective lever. Am not saying, by any stretch,
that either is the case. Just trying to figure what would be the editorial
equivalent to a lever long enuf to move the Earth.

John

#: 210980 S10/Views:Zachmann [E]
    06-Jul-92  18:22:45
Sb: #210832-Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: CyberSim [E. Pinnell] 70031,435

Eric..

Your hypothetical point is well-taken. It's also possible that that's not what
happened at all. The _only_ point I was trying to make is that very few people
actually _know_ who's right, at least at this point. I know that I have no
facts whatsoever in the matter, other than what Will has said. Is he right
just because he says so?

-Dale

#: 210678 S10/Views:Zachmann [E]
    06-Jul-92  07:20:43
Sb: #210473-#Tyranny and Independence
Fm: Ross M. Greenberg 72461,3212
To: Tony Rosati 76662,3440

Tony: don't get trade journalism confused with real journalism.

There are more than a few publications which are lacking in the editorial
integrity your would expect normally in a non-trade book: look at Microsoft
Systems Journal, for example -- you know it comes from Microsoft, but don't
you expect *everything* in there to be factual.  Would you find it unusual if
something false were published therein?  The publisher, Microsoft, has only
one interest in *everything* they print and that it to promote their own
product.

A book I used to work for has a publisher who tried to kill an unfavorable
review I wrote of a potential advertisor's product.  He did not succeed in
killing that review, but I do note that he is still there, I am not, the book
is making gobs of money, and their reviews follow many of the other trade
press which state "don't say anything nasty about an advertisor's products".

When the publisher makes editorial decisions, they will forever be towards
whatever the publisher can get away with to help the advertisors spend more
money.

The fact that Will went public with his problem in the only thing unusual in
this instance:  like sausages and laws, the creation of a magazine is
something which should never be witnessed by those with a faint stomach.

* Reply:  210687

#: 210687 S10/Views:Zachmann [E]
    06-Jul-92  07:41:17
Sb: #210678-#Tyranny and Independence
Fm: Ben Sano 72401,2736
To: Ross M. Greenberg 72461,3212 (X)

Ross

I don't have any trouble believing any of this. Remember I have a friend who
used to write for 'Health Week' a sister magazine of the one the the bang.

--Ben

* Reply:  210952

#: 210952 S10/Views:Zachmann [E]
    06-Jul-92  18:10:38
Sb: #210687-#Tyranny and Independence
Fm: Ross M. Greenberg 72461,3212
To: Ben Sano 72401,2736 (X)

(they did lose the bang, finally, btw).

Yeah, the Health Week people were pretty good journalists, too, from what I
recall.

* Reply:  211006

#: 211006 S10/Views:Zachmann [E]
    06-Jul-92  19:38:50
Sb: #210952-Tyranny and Independence
Fm: Ben Sano 72401,2736
To: Ross M. Greenberg 72461,3212

Ross
I'm not sure if he was a GOOD journalist but he was a REAL one.

They had to stop him from pursuing the Gallo HIV controversy in their pages.


--Ben

#: 210493 S10/Views:Zachmann [E]
    05-Jul-92  19:44:04
Sb: #210457-#Tyranny and Independence
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Dale Lewallen 76000,21 (X)

Dale,

>But how can we say what happened here when we've really just heard Will's
side of it.

That's what I'm asking the editors of PC Week.  Is Will's allegation true and
has the integrity of PC Week been compromised?  Or, is Will lying? The silence
since Sam's initial response does not bode well for the weekly I have held in
high regard.

Some might say it's none of my business whether the allegation is true.  I'd
respond by saying I base decisions and recommendations on what PC Week prints.
The integrity and independence of PC Week is vital to me. Stonewalling the
accusation will not restore my faith PC Week, but actually lower my opinion of
the publication and those who work for it.

     Bruce

* Reply:  210565

#: 210565 S10/Views:Zachmann [E]
    05-Jul-92  23:10:48
Sb: #210493-#Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: Bruce Biermann [ZiffNet] 72241,261 (X)

Bruce..

Thanks for your reply..

I respect your willingness to _wait_ until the matter has been refuted or
denied before making a decision. As I noted earlier, _if_ what Will says
happened did happen (remembering that Will might be interpreting things to his
advantage--we all tend to, right?), then I will be upset, justifiably so, just
as others here already are.

On the other hand, other than Sam's brief note here, we've not heard the other
side of it. I'd personally like to wait until we do.

Oh, for what it's worth, I've been at two Ziff pubs in the last 4.5 years (PC
Week and now PC/Computing) and have _never_ been pressured, or even asked to
change something to accomodate an advertiser. Not to say that it can't, just
has never happened to me..

-Dale

* Replies:  210590, 210596, 210834

#: 210590 S10/Views:Zachmann [E]
    06-Jul-92  00:44:45
Sb: #210565-#Tyranny and Independence
Fm: William F. Zachmann 72241,43
To: Dale Lewallen 76000,21 (X)

Dale,

Why do you suppose Sam went silent all of a sudden, Dale?  Do you seriously
think that I would sacrifice the major portion of my income for no good reason
at all?

Will

* Reply:  210981

#: 210981 S10/Views:Zachmann [E]
    06-Jul-92  18:22:52
Sb: #210590-Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: William F. Zachmann 72241,43 (X)

Will..

WZ>> "Why do you suppose Sam went silent all of sudden, Dale? Do you seriously
think that I would sacrifice the major portion of my income for no good reason
at all?"

But Will, why are you asking me to "suppose?" I don't _know_ why he is going
"silent" but your message asks me to hypothesize about the reason. It
certainly looks funny but it doesn't automatically mean that he's wrong and
you're right..

Also, no, I don't believe you would give up what is probably a good chunk of
your income. I also don't know why you did it other than your statements here
on the various CIS fora..

-Dale

#: 210596 S10/Views:Zachmann [E]
    06-Jul-92  00:51:54
Sb: #210565-#Tyranny and Independence
Fm: Sam Whitmore 76701,257
To: Dale Lewallen 76000,21 (X)



Hello everybody!

As for the "silence" that Bruce refers to...geez, it's Sunday, for gosh sakes!
<g> I was on here yesterday! <g> I know, that seems like an eternity because
of all the volume. What can I say? I'm only going to be able to be on here
once a day, and there's no way I can respond to every single message. But I
will pick my spots, because it's important that you see that PC Week is not
going to act as if it has something to hide, because it just doesn't, pure and
simple.

All I can say is, I nor anyone at PC Week called Microsoft that day or any
other day regarding Will's column, and I repeat what I said yesterday, that
Microsoft has not nor are they now pressuring me, PC Week or Ziff-Davis
regarding the tone or content of Will's column. I can't be any clearer than
that. I think you folks should listen to Charles Hart and Earle the ibmeur...I
think they're on to something!! <g>

Sam

* Replies:  210633, 210751, 210966, 211096

#: 210633 S10/Views:Zachmann [E]
    06-Jul-92  05:29:02
Sb: #210596-Tyranny and Independence
Fm: William F. Zachmann 72241,43
To: Sam Whitmore 76701,257

 >All I can say is, I nor anyone at PC Week called Microsoft that day or any
 >other day regarding Will's column, and I repeat what I said yesterday, that
 >Microsoft has not nor are they now pressuring me, PC Week or Ziff-Davis
 >regarding the tone or content of Will's column.

Am I to infer from that that you do so solely at your own initiative?

#: 210751 S10/Views:Zachmann [E]
    06-Jul-92  09:41:54
Sb: #210596-Tyranny and Independence
Fm: Bruce Biermann [ZiffNet] 72241,261
To: Sam Whitmore 76701,257

Sam,

Thank you for your response.

Am I to assume the timing of the phone call from Microsoft to Will was just a
coincidence?  I also find it curious that the phone call seemed to indicate
knowledge of your meeting with Will.

I readily admit I did not witness the phone call and I am relying on Will's
word.  The reason I'm convinced Will's recollection is accurate is that his
story is identical to what he privately told a small group in San Jose a
couple months ago. At that dinner, he expressed a strong desire to resolve
this matter in a way that was acceptable to both him and PC Week. He had no
reason to distort the facts.

Possibly speaking for many of us on this forum, I hope you and Will keep your
scheduled meeting next week.  Maybe you and Will can laugh at all of us who
are so concerned and worked up over this situation.

    Bruce

#: 210966 S10/Views:Zachmann [E]
    06-Jul-92  18:15:23
Sb: #210596-Tyranny and Independence
Fm: Randy Johnson 73067,2150
To: Sam Whitmore 76701,257

Sam,

I see right through you.  My lie detector needle is going crazy.

Randy (I'm not blind)

#: 211096 S10/Views:Zachmann [E]
    06-Jul-92  22:35:49
Sb: #210596-Tyranny and Independence
Fm: Mike Henry 76376,157
To: Sam Whitmore 76701,257

Just what was it about Will's columns that PC Week didn't like?  From what
I've read here so far that issue has not yet been addressed by PC Week and it
seems rather pertinent to those of us that are trying to look at this
objectively.

#: 210834 S10/Views:Zachmann [E]
    06-Jul-92  12:08:15
Sb: #210565-#Tyranny and Independence
Fm: CyberSim [E. Pinnell] 70031,435
To: Dale Lewallen 76000,21 (X)

Dale,

     Re: Not being pressured. Maybe it's the fact tha you're 6' 14" and weigh
as much as your average freight train. They be vewwy vewwy afwaid.<G>.

Eric Pinnell

* Reply:  210982

#: 210982 S10/Views:Zachmann [E]
    06-Jul-92  18:23:02
Sb: #210834-#Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: CyberSim [E. Pinnell] 70031,435

Eric..

RE: my size.. um, well, that's possible I guess. How'd you know that?

-Dale

* Reply:  211007

#: 211007 S10/Views:Zachmann [E]
    06-Jul-92  19:38:59
Sb: #210982-#Tyranny and Independence
Fm: Ben Sano 72401,2736
To: Dale Lewallen 76000,21 (X)

Dale
 >my size.. um, well, that's possible I guess. How'd you know that?

The USGS in Palo Alto has you on their maps as a geologic feature<g>

--Ben

* Replies:  211083, 211166

#: 211083 S10/Views:Zachmann [E]
    06-Jul-92  21:39:59
Sb: #211007-Tyranny and Independence
Fm: Theresa Carey [ZiffNet] 72241,237
To: Ben Sano 72401,2736 (X)

Ben, Dale and my husband Kent are about the same size.  When he and Lysa came
over for dinner, she thought she'd been trapped in a Tall People's Convention.
We were nice and tried not to scare her.
                                        -- T.

#: 211166 S10/Views:Zachmann [E]
    07-Jul-92  00:51:54
Sb: #211007-Tyranny and Independence
Fm: Dale Lewallen 76000,21
To: Ben Sano 72401,2736 (X)

Ben..

BS>> "The USGS in Palo Alto has you on their maps as a geologic feature.."

Wow. What can I say, that was a truly cool comment! <g> I'm honored!

-Dale

#: 210522 S10/Views:Zachmann [E]
    05-Jul-92  21:11:27
Sb: #210388-#Tyranny and Independence
Fm: Charles Hart 72755,500
To: Tony Rosati 76662,3440

If we are going to talk of historical editorial freedom, then let's be
precise.  The individuals you enshrine *owned* the press they were publishing,
and that's always been the basis of the freedom you speak so glibly about:
Mr. Ziff has the absolute right (subject to adverse libel claims) to editorial
freedom, but his employees do *not*!  They have always been and continue to be
subject to whatever *he* thinks is appropriate and legal to print.  You may
not like it, but the owner of the press has absolute power to decide what is
published......

* Reply:  210591

#: 210591 S10/Views:Zachmann [E]
    06-Jul-92  00:44:50
Sb: #210522-#Tyranny and Independence
Fm: William F. Zachmann 72241,43
To: Charles Hart 72755,500 (X)

Gee, Charles, I'm sure it's attitudes like yours that have made America great.
You argue that owners of publications have every right to censor those who
write in them, that all magazines should routinely be expected to have their
editorial content influenced by advertisers, and that we all ought to take
that for granted.  Tell me, do you fly a black flag on the Fourth of July?

* Replies:  210629, 210679, 210786, 211165

#: 210629 S10/Views:Zachmann [E]
    06-Jul-92  05:28:18
Sb: #210591-Tyranny and Independence
Fm: Charles Hart 72755,500
To: William F. Zachmann 72241,43 (X)

You are shooting the messenger again - poor form in any forum.

You have been in the business long enough to know that the owner of the press
is the one with the financial responsibility for what is printed.  The owner
indeed has the "freedom" to print whatever he can afford to and not the
employees or independent contractors working for the publication.  Argue with
the publisher about the content and one indeed will soon find oneself looking
for other suitable employment.  TANSTAAFL, fortunately.

This is Business 101, not some dark secret never before exposed.  Your tactic
of taking the matter public before it was resolved at the highest levels
indicates you had decided to leave anyway and are simply twitting Ziff at this
point.  Nothing wrong with that as it's your life and your decision - just
made the scroll rate here jump a bit <g>.

You wrote a fine column, and I am sorry you made the decision to leave without
carrying the battle you perceived to be required all the way through to
completion.  Had you done so, I have a feeling you would have been surprised
at the outcome - but since I am not involved and you have decided to not renew
your agreement we will never know......

#: 210679 S10/Views:Zachmann [E]
    06-Jul-92  07:20:53
Sb: #210591-Tyranny and Independence
Fm: Ross M. Greenberg 72461,3212
To: William F. Zachmann 72241,43 (X)

>...You argue that owners of publications have every right to censor those who
write in them, that all magazines should routinely be expected to have their
editorial content influenced by advertisers, and that we all ought to take
that for granted. Tell me, do you fly a black flag on the Fourth of July?

He's right, Will.  "Freedom of the Press" is only freedom from the government
imposing their wish on what gets printed.

I do expect that all of the trade books will be influenced by their major
advertisers: else, we'd be seeing lots of articles extolling the virtures of
UNIX and other operating systems in these books instead of the
WinAppOfTheMonthClub we're seeing....

#: 210786 S10/Views:Zachmann [E]
    06-Jul-92  11:11:11
Sb: #210591-Tyranny and Independence
Fm: Gordon McComb 73155,353
To: William F. Zachmann 72241,43 (X)

While I don't like it any more than you do, what Charles says is true: freedom
of the press belongs to the person who owns the printing press. There are some
publishers who will hold editorial independence higher than others, and will
not buckle to influence by advertisers.  And there will be some who act merely
as agents of advertisers, and print what is in effect advertorials -- but
without the disclaimer.

I assume you will be starting your own newsletter (if you already have one
please forgive my ignorance).  With your own publication, you'll own that
printing press, and you'll be free to say anything.  This is exactly what I do
now, and I find the freedom exhilarating.  The cost: it's exhausting work.

-- Gordon

#: 211165 S10/Views:Zachmann [E]
    07-Jul-92  00:44:04
Sb: #210591-Tyranny and Independence
Fm: Cole Loftus [C81] 76360,1320
To: William F. Zachmann 72241,43 (X)

Will-

I didn't note any reference by Charles to influence "by advertisers".  I agree
with him that the owner of the rag is the final authority as to what goes into
it; that's free enterprise.  I leave it to the market to sort out the truth
from the pandering to advertisers--with free speech, the difference shouldn't
stay hidden for long.  Which is why I support you for making this public when
it couldn't be worked out.

-Cole



Forum !

ÿ
