
#: 7898 S15/Open Forum
    04-Jul-92  11:35:01
Sb: #Independence Declaration
Fm: William F. Zachmann 72241,43
To: All

I can think of no better occasion than the Fourth of July to declare
independence from those who would dictate the content of what I write.  Over
the past several months, I have been repeatedly subject to what I feel to be
inappropriate and improper pressure from PC Week in regard to my views on
Microsoft and Windows, IBM and OS/2.

I had hoped that this was a temporary aberration that would soon be corrected.
Unfortunately, that does not seem to be the case.  I have therefore sent
notice to the Ziff-Davis Publishing Company that I do not intend to renew my
agreement with them when its current term expires at the end of September.

I believe that Mr. William Ziff, Jr. is genuinely committed to editorial
integrity and independence.  Unfortunately, I think Mr. Ziff is being
ill-served by some of his employees who do not share that commitment.  I am
concerned that the regretable tendency to shape editorial content to please a
major advertiser (Microsoft in this case) which I have noted in some competing
publications is being imported into the Ziff-Davis Publishing Company.

If you share my concern, you may want to write to Mr. William Ziff, Jr., Ziff
Davis Communications, One Park Avenue, New York, NY, 10016 and let him know
what you think. Please feel free to repost this messages elsewhere if you
wish.

William F. Zachmann

* Replies:  7906, 7907, 7908, 7911, 7915, 7926, 7928, 7932, 7938, 7971, 
            7981, 7984

#: 7906 S15/Open Forum
    04-Jul-92  12:04:47
Sb: #7898-#Independence Declaration
Fm: Wayne Kovsky 76164,3504
To: William F. Zachmann 72241,43 (X)

Will, you have my support, and I will send a letter to Mr. Ziff saying so.  I
have been a subscriber to PC Magazine since its initial issue, and I have been
an on-again off-again subscriber to PC Week since it was introduced.  I have
been troubled by the obvious bias that I have seen creeping into these
publications, and I have found your PC Magazine columns in particular to be
one of the only counters to this trend.

I would truly hate to see you not writing for PC Week (and by extension, I
presume not writing for PC Magazine at some time in the future).  I am not a
current subscriber to PC Week, having been disgusted with some of its
editorial excesses, so my voice relating to that particular publication will
carry little or no weight.  However, if I learn that Will Zachmann will not be
a featured writer for PC Magazine in the future, I will instantly cancel my
since-issue-number-1 subscription, and I will encourage all of my friends, and
all members of my local user's group, to do the same.  I believe that most of
them will need little encouragement, because we are already Will Zachmann
fans, and we are also increasingly dismayed with the editorial direction
Ziff-Davis seems to be taking.

Good luck, Will, and I hope that long-established standards of responsible
journalism (and therefore, you) will prevail in this dispute.

* Reply:  7916

#: 7916 S15/Open Forum
    04-Jul-92  17:27:02
Sb: #7906-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Wayne Kovsky 76164,3504

Wayne,

Thank you for your support.  I would like to see a positive outcome between
Ziff-Davis and myself but it is hard to be optimistic at this point.  At any
rate, it is now up to them.

All the best,

Will Zachmann

#: 7907 S15/Open Forum
    04-Jul-92  12:07:57
Sb: #7898-#Independence Declaration
Fm: Alan DuBoff(Bunker Hill) 76662,660
To: William F. Zachmann 72241,43 (X)

Will,

I appreciate your ability to stand up for what you believe in. If it was not
for people like you, we might not have ANY honest journalism in this world.

The fact that microsoft thinks they can dictate not only the computing
environment we use but the information that becomes available to us as well
is very sad. Of course them dictating that we use all ms applications is
just a short way down the road, and then what type of food we eat (after
they get involved in mr. bill grocery chains no doubt...<g>), and on and on.

I will write to Mr. Ziff and let him know that it is dissapointing for a
publishing company like his to have this issue happening.

Keep up the great work and good luck with the future wherever you end up
writing, I KNOW you will find a place that fits you well, your articles are
too good to not get published somewhere.

ajd

* Reply:  7917

#: 7917 S15/Open Forum
    04-Jul-92  17:27:10
Sb: #7907-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Alan DuBoff(Bunker Hill) 76662,660

Alan,

Thank you for your support.  It is very much appreciated at what is, for me, a
quite difficult and awkward moment.  I had hoped to be able to resolve all
these matters quietly but, unfortunately, have been frustrated in my efforts
to do so.  My choice to make a public issue of all this was one that was made
reluctantly and sadly.  I did feel, however, that I ought not to acquiesce
silently to efforts to muzzle what I had to say about Microsoft and Windows,
IBM and OS/2, even though it means sacrificing substantial income from
ZiffDavis in the process.

Will

* Reply:  7924

#: 7924 S15/Open Forum
    05-Jul-92  00:46:17
Sb: #7917-Independence Declaration
Fm: Alan DuBoff(Bunker Hill) 76662,660
To: William F. Zachmann 72241,43

Will,

Have you ever thought about writing a book ? You of all people would be in a
great position to write about this akward time that developers and users
have gone through. Since books seem to generate a much higher income for
writers, it might be a good thing for you, AND you could still write for
magazines while you do it...<g>

ajd

* Reply:  7929

#: 7929 S15/Open Forum
    05-Jul-92  03:23:21
Sb: #7924-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Alan DuBoff(Bunker Hill) 76662,660 (X)

Alan,

I have thought about ideas for several books and actually wrote one 10 years
ago.  I didn't publish it though.  We'll just have to see what the future
brings.

All the best,

Will

#: 7908 S15/Open Forum
    04-Jul-92  12:36:02
Sb: #7898-Independence Declaration
Fm: Steve Mastrianni [PSS] 71501,1652
To: William F. Zachmann 72241,43 (X)

Oh heck, I was getting pretty tired of PC Mag anyway. That gives me a reason
to finally drop my subscription.

* Reply:  7939

#: 7939 S15/Open Forum
    05-Jul-92  08:05:13
Sb: #7908-Independence Declaration
Fm: Arthur Goikhman 72170,2053
To: Steve Mastrianni [PSS] 71501,1652 (X)

I thought that the special advertising section in the last one
was good<g>.  Other than that, it is kind of empty

#: 7911 S15/Open Forum
    04-Jul-92  14:06:08
Sb: #7898-#Independence Declaration
Fm: Charlie Choc 71221,1203
To: William F. Zachmann 72241,43 (X)

Will,

Sorry to see you go. I used to read your column before I lined the birdcage
with PC Week, guess I can save some time now. (P.S. I don't even have a bird,
but I think I will get one).

Charlie...

* Reply:  7918

#: 7918 S15/Open Forum
    04-Jul-92  17:27:14
Sb: #7911-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Charlie Choc 71221,1203

Charlie,

Thanks.

Will

#: 7915 S15/Open Forum
    04-Jul-92  17:19:55
Sb: #7898-#Independence Declaration
Fm: Paul Flatt 71022,1013
To: William F. Zachmann 72241,43 (X)

Will,

It was just a week ago I wrote a letter to PC Mag complaining about the not so
independent guide to computing, PC Mag.  Like others have said, if PC Mag
should be published without Will Z then my subscription is done.  I have been
a subscriber for 7-8 years and have noticed a definite bias in its articles
away from OS/2 toward windows.  When OS/2 first came out and Microsoft was
behind it, PC Mag had many articles on how to program it and what it would
mean for all users.  As the Microsoft IBM split deepened the OS/2 columns were
replaced with windows columns.  When OS/2 2.0 was released there was only a
quick short article about what it can and can't do.  In all the reviews they
always mention that virtually no OS/2 2.0 specific programs yet exist but
hundreds of windows 3.0/3.1 programs already exist.  Only in passing do they
say that virtually all existing DOS programs, most windows 3.0 programs,  and
virtually all OS/2 1.x programs run under 2.0.  This makes OS/2 2.0 capable
running vastly more programs than windows 3.0 or 3.1.

Mr Ziff will get another letter shortly concerning my displeasure.  Should you
find yourself no longer in PC Mag, I wish you the best in whatever falls your
way.

* Reply:  7919

#: 7919 S15/Open Forum
    04-Jul-92  17:44:25
Sb: #7915-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Paul Flatt 71022,1013

Paul,

Thank you for your support.  My view is that personal computer publications
generally have not done a very good job in representing a balanced view of IBM
and Microsoft, Windows and OS/2.  My own view is that I have been doing both
PC Week and PC Magazine a service by balancing out their coverage. Needless to
say, my efforts on their behalf do not seem to have been fully appreciated.
<g>

All the best,

Will

Forum !

* Reply:  8004

#: 8004 S15/Open Forum
    06-Jul-92  01:47:22
Sb: #7919-#Independence Declaration
Fm: hari ramachandran 73117,71
To: William F. Zachmann 72241,43 (X)

Will,

Sorry to hear that things have come to this pass. Not sorry that you are
taking PC Week & PC Mag to task, but that you have had to do this in order to
keep your integrity.

I have to say that the most self-serving comment I have heard out of PC Mag
has been their justification for not covering OS/2 2.0's beta versions: "We
only cover products that are available". Now that that excuse is gone, they
happily cover NT alpha code to a greater extent even, than OS/2 GA. I wonder
what excuse that comes under ...

       "Some products that are of immense interest to the majority of our
       readers are indeed covered ahead of time to prepare them for the
       future"

Sheesh! I probably should apply for editor at PC Mag :^> The above is the kind
of comment they use - conveniently forgetting that they could have used this
very argument even more forcefully for covering OS/2 betas earlier this year!

Good luck on the future, and let's hope ZD learn some sense through all this.

hari

* Reply:  8007

#: 8007 S15/Open Forum
    06-Jul-92  02:28:19
Sb: #8004-Independence Declaration
Fm: William F. Zachmann 72241,43
To: hari ramachandran 73117,71

Hari,

Thank you for your support.

Will

#: 7926 S15/Open Forum
    05-Jul-92  00:57:04
Sb: #7898-Independence Declaration
Fm: Bill Kenning 70254,1604
To: William F. Zachmann 72241,43

Mr. Zachmann--Now that you've officially cut the ties to Ziff, I hope to see
you write some for the 'IBM OS/2 Developer' magazine and OS/2 Monthly.  Maybe
it wouldn't pay your worth, but you are very respected in the OS/2 community.
I also enjoyed your articles on many other subjects.  Its a damn shame that
Ziff has no editorial integrity.
Some time ago I suggested a write-in campaign to BYTE magazine to try and
obtain your services as a columnist for them.  They seem to have a lot of
integrity.  Hopefully I will see your column reappear in some of these
magazines.
I intend to write a letter to the editor as well as one to the Ziff-Davis
board.  I probably will also lobby for BYTE to obtain your services.  I wish
to thank your for your integrity, technical expertise, and journalistic works.
Best of luck...a loyal follower.
Regards...


Forum !

* Reply:  7930

#: 7930 S15/Open Forum
    05-Jul-92  03:23:27
Sb: #7926-#Independence Declaration
Fm: William F. Zachmann 72241,43
To: Bill Kenning 70254,1604 (X)

Bill,

Well, ties between Z-D and me aren't exactly cut off yet.  My agreement with
Z-D runs through the end of September and, though I'm not very optimistic on
this point, perhaps they will respond to my notification that I do not intend
to renew the agreement by changing the conditions that led to my decision. If
not, I think I will probably be able to find another venue for my columns
eventually.  We'll just have to wait to see how it all turns out.

Best regards,

Will

* Reply:  7983

#: 7983 S15/Open Forum
    05-Jul-92  21:20:25
Sb: #7930-Independence Declaration
Fm: Bill Kenning 70254,1604
To: William F. Zachmann 72241,43

I really don't expect Ziff-Davis to 'back down'...They just appear to be too
tied to uSoft.  Really disgusting as PC Magazine bills itself as 'The
Independent Guide to Personal Computing'.  I hope the readers can apply
pressure to force Ziff-Davis back to a more neutral editorial tact.  If they
want to just represent Windoze/Windoze NT they should either state so or spin
off another publication.  I somewhat expect to see bias in a magazine like
"Windows Magazine" published by Ziff's competitor CMP Publications.  But Ziff
should not bill itself as one thing and then sell out to special interests.
I *really* hope you can broaden your work to other magazines even if you do
renew with Ziff.  I really like your work.  I think the suggestion of a book
is a good idea, but would really like to see your byline in some OS/2
magazines as well as Windoze type magazines.  Your message has always been
even handed.  I don't know if your contract prohibits such publication, but I
hope it doesn't.  Best Wishes.
Regards...

* Reply:  8002

#: 8002 S15/Open Forum
    06-Jul-92  00:48:34
Sb: #7983-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Bill Kenning 70254,1604

Bill,

Thank you for your support.

Will

#: 7928 S15/Open Forum
    05-Jul-92  02:36:07
Sb: #7898-Independence Declaration
Fm: Bernd Kunrath 100015,2526
To: William F. Zachmann 72241,43 (X)

Hi Will, you've done good things for us and OS/2. Believe me there are some
people in Germany who know you, and want to help you. So i'll tell Mr. Ziff
that there would be some people over here canceling their subscription of
PC-Magazine and PC-Professional (German name of the mag.), if they don't let
their writers write what they mean ! Good luck, hope Mr. Ziff will help you
too; maybe there'll be a change in mind on PC-Magazine, since IBM ads are
getting more and maybe mayn more in future... <g>. Ciao, Bernd <calling from
the wild south of germany> sorry sysop

#: 7932 S15/Open Forum
    05-Jul-92  06:10:06
Sb: #7898-#Independence Declaration
Fm: Frank Castellucci 72261,2700
To: William F. Zachmann 72241,43 (X)


So what? Your quitting? Is that anyway to win issues Will?

Don't you see by doing so you are CONFORMING? What if every developer who has
hung in the OS/2 development world ( smaller than a breadbox ) quit?

You have the opportunity to put into print anything you want right now, you
may be the only independandt voice doing so. And what, you can't take the
heat?

You want support? Stay in there and fight. Otherwise go cry in someone else's
beer.

Frank V. Castellucci C.O.L. Systems Inc.

* Replies:  7937, 7944, 7957, 7985

#: 7937 S15/Open Forum
    05-Jul-92  08:01:20
Sb: #7932-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Frank Castellucci 72261,2700 (X)

Frank,

If I am to be denied the ability to say what I feel ought to be said, what is
the point in "hanging in there"?  I am sure I can find other publications
where my views can be freely expressed if necessary.  In what way am I
"continuing the fight" if, in effect, I passively agree to being chained up
with a muzzle on?  Your logic escapes me.

Will

* Reply:  7989

#: 7989 S15/Open Forum
    05-Jul-92  23:16:03
Sb: #7937-Independence Declaration
Fm: Frank Castellucci 72261,2700
To: William F. Zachmann 72241,43 (X)


Will,

Based on your editorials, I can't see where you have been denied anything.
Perhaps you can enlighten me ( us? ).

No one said to passively do anything. Quite the opposite is what I would
support. Keep telling your story until they throw you out, and then tell the
world why.

Frank

#: 7944 S15/Open Forum
    05-Jul-92  08:45:45
Sb: #7932-Independence Declaration
Fm: Stephen Gutknecht 72651,31
To: Frank Castellucci 72261,2700 (X)

>  You want support? Stay in there and fight. Otherwise go cry in someone
else's beer.   (end quote)

You obviously ignore the fact that this is his PERSONAL decision, and he has
pondered his alternatives.  As an outside observer, it is clear that he has
provided Ziff with time for a resolution.  Many a great man have given up more
for principal.

Stephen Gutknecht

#: 7957 S15/Open Forum
    05-Jul-92  13:36:38
Sb: #7932-#Independence Declaration
Fm: Dave Peckham 71730,731
To: Frank Castellucci 72261,2700 (X)

Speak for yourself when you say "cry in someone else's beer".  Looking at the
replies here, it looks like Will is very welcome to express his concerns.

You assume that we share your opinion.  It looks like you are wrong.

Dave

* Replies:  7970, 7990

#: 7970 S15/Open Forum
    05-Jul-92  18:44:51
Sb: #7957-Independence Declaration
Fm: Alan Cobb 73170,3543
To: Dave Peckham 71730,731

Dave,

 >Speak for yourself when you say "cry in someone else's beer".
 >You assume that we share your opinion.  It looks like you are wrong.

Right on.  Its as if someones wife stumbles in the door after she's been
raped, and then she is told to quit whining and dripping blood on the floor.
Sheeeesh.

Alan Cobb

* Reply:  8001

#: 8001 S15/Open Forum
    05-Jul-92  23:29:08
Sb: #7970-Independence Declaration
Fm: Frank Castellucci 72261,2700
To: Alan Cobb 73170,3543


Alan,

> Right on. Its as if someones wife stubles in the door after she's been >
raped, and then she it told to quit whining and dripping blood on the > floor.
> Sheeesh.

I don't see the analogy here. Do you respond as though you have been raped
whenever you meet resistance to your opinions?

Have you ever been in a position that Will describes as being in ZF? How did
you respond?

Frank Castellucci

#: 7990 S15/Open Forum
    05-Jul-92  23:16:08
Sb: #7957-Independence Declaration
Fm: Frank Castellucci 72261,2700
To: Dave Peckham 71730,731


Dave,

I don't assume that anyone share in my opinion. I responded to Will's open
request for support to Will. Whether I am wrong or right is irrelevant, it is
my opinion.

I also welcome Will and his concerns, especially when they appear in print.
That is where he is strongest.

Frank

#: 7985 S15/Open Forum
    05-Jul-92  21:33:49
Sb: #7932-Independence Declaration
Fm: Bill Kenning 70254,1604
To: Frank Castellucci 72261,2700 (X)

I think Mr. Zachmann will voice his own opinions as long as he has a contract.
But one thing that upsets me is how PC Magazine is trying to control the
public's thinking using columnists who are supposedly independent authors.
That's ok if the columnists or their articles are identified as an editorials,
but its something else if you force authors to be bias in their independent
columns and do not state your editorial policy.  PC Magazine bills itself as
'The Guide to Independent Personnal Computing'.  That banner suggests/means
neutrality unless the article is clearly identified as an editorial.  I'm not
a real uptight liberal on freedom of the press, but this appears to be one
case where the press ownership is definitely *bias* and trying to shape public
opinion without presenting their opinion as either an editorial or a
recommendation.  If Ziff wants to promote an editorial platform they can be
upfront about it.
Don't be so hard on Will.  How would you like to be potentially unemployed
based on your stand on an issue ? Pretty scary.  If Ziff considers their
publications to be an agenda for promoting Windoze/Windoze NT or uSoft they
should be up front about it and not manipulate their employees and try to
shape public opinion with a hidden agenda.
Regards...

* Reply:  7991

#: 7991 S15/Open Forum
    05-Jul-92  23:16:14
Sb: #7985-Independence Declaration
Fm: Frank Castellucci 72261,2700
To: Bill Kenning 70254,1604


Bill,

I appreciate your reply. But, is PC-Whatever the only publication that try to
control the public's thinking? I don't think so.

Because OS/2 vs. MS - Windows and Windows/NT has taken on such an emotional
battle, PC-Whatever is what we ( OS/2 - Windows - Windows/NT ) tend to focus
on as it reports on the battle. The question is whether or not the reporting
is done in earnest or is shrouded by favoritism.

My opinions and believes have either landed me in the street, or had the
effect of changing what I was fighting against. Each time I faced the chance
that I would be 'unemployed', which is not easy as I have 2 kids, a wife, and
mortgage to support.

Frank



Forum !

#: 7938 S15/Open Forum
    05-Jul-92  08:04:00
Sb: #7898-#Independence Declaration
Fm: Arthur Goikhman 72170,2053
To: William F. Zachmann 72241,43 (X)

So it wasn't a rumor, after all.  It seems sad that
even such a lonely voice in the defense of OS/2 was not tolerated.

Perhaps we'll see a letter campaign to dwarf the one in response to
the April 28th issue.  I'm certainly working on it<g>

Arthur Goikhman
Soft & GUI Inc

* Reply:  7945

#: 7945 S15/Open Forum
    05-Jul-92  08:58:57
Sb: #7938-Independence Declaration
Fm: William F. Zachmann 72241,43
To: Arthur Goikhman 72170,2053 (X)

Arthur,

No, it wasn't a rumor after all.  I'd hoped to be able to work things out
quietly, behind the scenes, but after over two months trying to do without a
positive outcome, I decided to bring the issue out in public.

Although they'd backed off temporarily on my PC Week column (and even that
only after some real struggles on my part insisting that what I wrote see
print) it became apparent to me that what was coming next was simply a
somewhat more subtle move to hamstring my column by defining its subject
matter so as to exclude discussion of Windows and OS/2 or simply to design my
column out of PC Week altogether.

It also became clear to me that Ziff-Davis Chairman and CEO Eric Hippeau was
not part of the solution for me but, more likely, part of the problem.  I
therefore decided to take the steps that I have taken.

Will

* Reply:  8035

#: 8035 S15/Open Forum
    06-Jul-92  09:15:06
Sb: #7945-Independence Declaration
Fm: Ian Ameline [SL] 70400,2356
To: William F. Zachmann 72241,43 (X)

William,

   I think that ZD is really pursuing a counterproductive strategy
in selling out to any one vendor. As soon as their readers realize that
they're seeing controlled editorial opinion disguised as fact, they'll stop
reading it.

   As a long time reader of your column, I wish you well in you search for a
less constrained venue for your words. Where ever you wind up publishing,
I'll subscribe.

Regards,
Ian Ameline,
(Not representing C-Set/2 development or IBM in this case)

P.S. Your original note is up on IBM's internal BBS systems too.

#: 7971 S15/Open Forum
    05-Jul-92  18:45:01
Sb: #7898-Independence Declaration
Fm: Alan Cobb 73170,3543
To: William F. Zachmann 72241,43 (X)

Will,

Hey dude, this is really heavy stuff!  I'd like to hear (or read) in detail
some of what has been going on there behind the scenes.  (Maybe you could put
it in an ASCII file and upload it, so it could be spread around).  Sort of an
expose on how Microsoft (or other big advertisers) can systematically put
pressure on supposedly independent publications. Why are they so threatened by
this?  Just this afternoon I was wondering what Bill Gates would look like in
a Nazi uniform, with a swastika on the front of his Lexus :-).

What is the Ziff justification for muzzling you?  Do they flat out admit they
are getting heat from their slave masters in Redmond?  Or do they have real
evidence that people are burned out on your slant and column? I suppose if
they had numbers to show that PC Week readers think you're flipped out (I
don't) and are tired of reading you, then it would be more understandable.
Personally, I always read your column in PC Week, along with page 1, and the
Katt.  I just skim most of the rest.

Alan Cobb

#: 7981 S15/Open Forum
    05-Jul-92  20:41:32
Sb: #7898-Independence Declaration
Fm: Rick Fishman 72251,750
To: William F. Zachmann 72241,43

Will, I just cancelled my subscription to ZiffNet last week. It looks like PC
Week is next - and PC Mag to follow.

I have the utmost respect for you as a writer as well as someone who lays it
on the line. I will convey that feeling along with my negative feelings toward
Ziff (re their treatment of Microsoft vs. IBM) to Mr. Ziff.

Good luck. I'm sure I will be reading your stuff elsewhere after September...

Rick

#: 7984 S15/Open Forum
    05-Jul-92  21:23:51
Sb: #7898-Independence Declaration
Fm: Warren Zeigler 70662,1710
To: William F. Zachmann 72241,43

Will -

Thanks for setting the record straight. I intend on "posting" a photocopy at
local businesses. I am also calling to cancel my PC Week subscription.

We all really appreciate the honesty you have shown on this - and other -
topics.

Mr. William Ziff may have good intentions, but if in reality he is climbing in
bed w/ Bill Gates - the result is a tainting of both. No one can believe
anything from ZD - or anything about MS - anymore. The only question that is
truely valid in either case is "What did it cost to get those words written?",
not "What does this mean to my company?". PC Labs - and all ZD pubs -
credability is now 0. There is no way to recover. They might as well sell the
lab. It is really sad.

Warren R. Zeigler

* Reply:  8056

#: 8056 S15/Open Forum
    06-Jul-92  11:52:42
Sb: #7984-#Independence Declaration
Fm: Peter Coffee (PC Week) 72631,113
To: Warren Zeigler 70662,1710 (X)

Unlike the majority of participants here, I *have* met Bill Ziff.  I have also
met Bill Gates.  And the notion of either one "climbing in bed" with the other
is ludicrous beyond description.  They are two of the most intimidatingly
intelligent people I've ever known, and each has achieved overwhelming
dominance in his chosen field based on doing what he thought his market would
like best.  The fantasy level in this thread is reaching world-record
levels...

* Replies:  8068, 8071, 8092

#: 8068 S15/Open Forum
    06-Jul-92  13:52:43
Sb: #8056-Independence Declaration
Fm: Wayne Kovsky 76164,3504
To: Peter Coffee (PC Week) 72631,113

Peter, the "intimidating intelligence" of the participants has nothing
whatsoever to do with whether they might (or might not) be colluding to
advance the market dominance of their respective enterprises.  And, history is
filled with the stories of people who did in fact "build a better mousetrap"
to achieve dominance in a field, but who also subsequently used sneaky,
underhanded, immoral, and often outright illegal means to perpetuate that
dominance, even when their products would have continued to succeed on their
own merits.  I can't see that your post has added a single thing to this
discussion, other than to illustrate your predictable bias on this issue.

On the other hand, your recent "defense" here (quotations because you rejected
the notion that you had done anything wrong that needed defending) of your
mis-use of the C Set/2 tools, leading to your misinforming all of PC Week's
readers about the quality of those tools, is <precisely> the kind of bias and
irresponsible journalism that many of us are fed up with from Ziff-Davis.  It
is one thing to make a mistake in reviewing a product (and via that mistake,
to slander the product); it is another to refuse to accept responsiblity for
having made the mistake; and it is reprehensible journalistic ethics to refuse
to make any public admission of the error and to correct the impression you
have erroneously left with your readers.

You may find it surprising that so many people here have been such strong
supporters of Will Zachmann's stand, and that so many of us have seen evidence
that we independently  (most of us don't know one another except via these
brief messages) have ascribed to Ziff-Davis' favoritism toward Microsoft - but
if you do, I think it may be because your own fantasy level is reaching
world-record levels...

#: 8071 S15/Open Forum
    06-Jul-92  14:18:40
Sb: #8056-Independence Declaration
Fm: Arthur Goikhman 72170,2053
To: Peter Coffee (PC Week) 72631,113

Fine.  But how to explain the pressure that was put on Bill
Zachmann?
Or was that fantasy also?

#: 8092 S15/Open Forum
    06-Jul-92  18:39:14
Sb: #8056-Independence Declaration
Fm: Warren Zeigler 70662,1710
To: Peter Coffee (PC Week) 72631,113

Peter - you are denying the facts.

Pressure from MS to change the reviews hurts MS credability, and pressure to
writters in ZD pubs (even just a few) totally destroys credability. The buck
MUST stop at the top, and it's obvious some representatives of the two
companies are engaging in reputation destroying activities. You may like the
leaders, but in fact they blew it - even if they did not order the actions.
They ARE responsible.

Warren R. Zeigler

PS - Intelligence neither means goodness or even competence - just the ability
to associate. (Not to brag - but Mensa says my IQ is not to different from
those you mentioned.) An "intimidating IQ" is another phrase for abuse of
power and abuse of ANY relationship. I've met Bill Gates, too. He spoke to the
press right before me for 20 minutes - on how OS/2 is MS's great direction. If
he impresses you, fine. For me, his actions and words do not meet. You can
have him.

ÿ
