

                   ELECTRONIC SURVEILLANCE

                       Are you bugged?



              (C) Copyright 1993 Michael E. Enlow



----------------------------------------------------------

                            DISCLAIMER



This document was written by an expert, quite knowledgeable in 

the methods and techniques of good, successful investigation. 

The author has based this material solely upon his discoveries 

and experiences in the trade but is not an attorney. Thus no legal 

advice is offered herein.



Be cautioned therefore, that this document neither asserts the 

legality of any of the methods described herein, nor does it 

advocate any usage of techniques without first seeking competent 

legal advice and adherence to the law.



The author, editor, and service providers, unequivocally disclaim 

any responsibility for damages resulting from the use of any of the 

techniques or the consequences of implementing anything contained 

herein. This writing is provided strictly for informational purposes 

only.



---------------------------------------------------------------



(This is an abstract from The Inside Secrets, a newsletter

catering to detectives, attorneys, law enforcement officers

and professionals around the world.  Want to know how the

pro's bug, tap phones, and use other things to hear what

you're saying.)



I'm now going to show you just how widespread illegal

electronic surveillance, or bugging really is.  But, let me

begin by saying. . .



MY INTENTION IS NOT TO SHOW YOU WAYS YOU MAY DO ILLEGAL

ELECTRONIC SURVEILLANCE, BUT ONLY TO INFORM YOU OF HOW IT IS

DONE, ON WHAT SCALE, AND WHAT YOU CAN DO TO PROTECT YOUR

RIGHTS.  I, THEREFORE, DISCLAIM ANY AND ALL LIABILITY FOR

YOUR MISUSE OF ANY OF THE TECHNIQUES AND/OR CONCEPTS OUTLINED

WITHIN THIS ISSUE AND FURTHER ISSUES OF THE INSIDE SECRETS

NEWSLETTER.



Do you get it?  If you take it upon yourself to use the

information I share with you and do something illegal, then

you pay the price.  I am warning you in advance.  I am not an

attorney and do not claim to be rendering legal advice.  If

you consider using any of the concepts I disclose, you should

consult your attorney to insure they are legal in your

jurisdiction.  With that behind us, let's move on.



Do you know there are only about three to four hundred court

orders issued each year for electronic surveillance

applications in the U.S.?  Yet, there are hundreds (if not

thousands) of electronic surveillance equipment suppliers. I

wonder how they manage to stay in business?



Well, my friend, I'll tell you.  They make a lot of money

selling electronic surveillance equipment.  Their customers

are Federal, State, and Local Law Enforcement Agencies,

corporations, and a few private investigators, who often

illegally use these devices in their investigations--but

you'll never know it...



A very popular book on electronic surveillance came out in

1967, and it listed some of the buyers of electronic

surveillance gear.  Everyone was quite surprised to find Avis

Rent-A-Car, various hotel chains, Coca-Cola, several life

insurance companies, and the like, were allegedly spending

millions for specialized bugging devices.  But to find out

that Walt Disney was a major customer . . .? Hmmm....



In my career, I have discovered numerous illegal electronic

surveillance applications.  Bugs are everywhere; they're in

small businesses, large corporations, people's homes,

conventions, everywhere!  In fact, if you don't believe me,

you can hear for yourself.  Use a programmable police scanner

to scan the 35 to 50 megahertz bands.  You'll almost always

find some very strange transmissions. (Things mother wouldn't

have wanted you to hear.)



Let me tell you more about electronic surveillance.  There

are many ways of using electronics for surveillance, but

first lets take a look at what's called hardwiring.



Hardwiring is basically the same as having an everyday

microphone plugged into a tape recorder.  When you speak into

the microphone, everything you say is sent through the

microphone's wire and recorded onto a tape.



Then, there are electronic transmitters which intercept the

signal via microphone and transmit it as a radio signal to a

receiver of some kind.  (Sort of like a miniature radio

station.)



There are also more advanced long range listening devices

like the laser mic, the shotgun microphone, the parabolic

microphone, and others which can pick up a whisper for long

ranges (sometimes even miles away).



To elaborate on a few types of electronic surveillance

applications and the ways to protect yourself from them, I'll

expound and tell of a couple of case scenarios.



First let's discuss. . .



                         HARDWIRING



As I said earlier, this type of electronic interception

requires the use of wire to carry the sound to you or some

other listening device.  There are many ways hardwiring is

done.  Wires the size of a human hair can be used to transmit

a signal from a microphone.  They can be painted over,

implanted under carpet, in an air condition duct, or behind

baseboards, etc., to conceal them from view.



At one end of the wire is the microphone, and on the other a

tape recorder or even someone who is listening with a set of

headphones.  This method of electronic interception is the

oldest in the industry, yet still practiced today.



To make everything a little more complicated, there is also a

conductive paint that closely resembles fingernail polish,

which will transmit the minute electrical impulses from the

microphone to a recorder or headphones.



There are so many different hardwire applications that I will

not attempt to cover them all.  I will just emphasize a bit

by sharing with you a couple we've discovered in our

countermeasures work.



Once, in checking a certain client's business for bugs, we

located a very cleverly installed hard-wire system.

Obviously someone had access to the office for a considerable

length of time, or maybe did a little breaking and entering

to get into the office.



Anyway, this particular application was a small microphone

element about a quarter inch in diameter (found at all Radio

Shack stores) placed in a small hole in a picture frame.  A

hole drilled into the rear of the picture frame held the

microphone in place.  A small eighth inch hole continued

through the frame to allow the sound waves to reach the

microphone.  A couple of fine wires running from the

microphone to the wall were thumb tacked there.   At this

point, conductive paint, as described above, continued down

the seams of the paneling walls to the baseboard.  Behind the

baseboard the conductive paint joined with an old set of

unused telephone wires.



A recorder was concealed in the basement near the phone box.

Every sound made in our client's office was being taped

using a long play tape recorder.  Many times agents will

change the play and record speed of tape recorders by

alternating the internal components.  This enables a standard

tape recorder to record from 4 to 15 hours on one side of a

tape.



Let me tell you of another clever hardwire I discovered. We

received a call from a lady who, believing that she was

bugged, requested a "bug-sweep" of her home to detect any

illegal electronic surveillance devices.  After a very

thorough sweep b y several of my agents, they found nothing.

My agents told her there were no electronic surveillance

devices on the premises.  My men really did a thorough sweep

and search.



A few days later the lady called again and said she knew

without a doubt that she was bugged.  She insisted we must

have missed something.  This time I went to the location and

ran every test we had equipment to run.  Still--no bug.

Then, I began the next countermeasures procedure, a physical

inspection of the entire house from attic to basement.



As I was searching, I noticed something very unusual.  The

stereo, situated in the center of the home, was on and the

cassette deck was playing.  Closer inspection showed that it

was recording!  However, there wasn't a microphone plugged

into the microphone jack and it didn't have an internal

microphone.  I stopped the tape and played it back. There was

a perfect recording of our client and myself as I was

questioning her during my search.



I checked the back of the stereo and there it was!  I noticed

one of the speaker wires was routed into the cabinet of the

stereo.  I disassembled the stereo and the wire was connected

to the microphone jack on the inside and connected to a

speaker.  A SPEAKER WAS BEING USED TO CONDUCT MICROPHONE

SIGNALS TO THE TAPE RECORDER!  It worked like a charm!



On top of this, the husband had changed the record/play speed

of the recorder to accommodate eight hours of recording.

This was one of the most sophisticated "home-made" jobs I had

ever seen!  Every night while the wife was working, as a

nurse, h e was reviewing everything that happened at home the

day before -- overhearing her telephone calls, and her

visitors. I have to credit this guy, it was quite a design.



                    ARE YOU BUGGED?



My best advice on detecting any type of hard wire

installation is to look for any alteration in the carpet

where wiring may have been routed under the carpet.  Watch

for any unusual sets of wires near and around your telephone

wiring.  (You should always be familiar with the type and

number of wires near your outside telephone connection box,

and watch out for any new wires that may appear.)



Keep notice of the baseboards around the floor and note any

unusual scratches in the paint, or other indications that the

base board has been removed.  Be cautious of any metal

objects that may be part of a conductor for electricity.

This could b e part of a hot-wire for a bug.  Let me

illustrate this for you:



As you can see, many types of metals carry current and can be

used as a decoy for wiring.  This type installation will out-

wit most private detective countermeasure sweeps and

searches, particularly in hard-wire systems.



Another type of hard-wire system is a direct telephone tap.

This only requires a standard tape recorder with both a

microphone and remote control jack with an "auto recording

control."  These are about $25.00 and are available at any

Radio Shack or other electronic supply store.



The "auto recording control" is a small box about three

inches square and has two wires coming out of it.  It also

has two switches on top of it to set it for record or

playback mode.  There is a gray wire which plugs directly

into any extra telephone jack or it can be cut and spliced

into the telephone line.  The other wire, with two plugs,

connects to the tape recorder.  The small plug goes to the

remote jack of the tape recorder and the other, larger plug,

to the microphone jack on the recorder.  One simply presses

the record button on the recorder and you're all set.



The auto recording control will keep the recorder inactive

until the phone is in use.  Once the phone is lifted from the

cradle, the auto recorder control activates the recorder to

clearly record both sides of the conversation.  As soon as

the phone is placed back on the hook, the recorder stops

recording and waits for the next incoming or outgoing call.

This feature prevents the tape recorder from playing

constantly and allows for the recorder to only be active

during calls.



Most people who use this method of bugging will plug the auto

recording control into an extra telephone jack in the home or

business, and conceal the recorder underneath a bed or behind

some other object to conceal it.



However, in those cases where there are no extra jacks, they

will cut the telephone jack wire coming out of the auto

recording control and strip away the insulation from the red

and green wires.  Then, they will splice these colored wires

into the phone wire.



Nearly all phone systems operate on a single grey or white

cable.  Once the insulation is removed the cable contains a

red, green, yellow, and black wire.  This cable carries

approximately 40 to 50 volts and will seldom shock if handled

improperly, (unless of course, the phone rings which sends

about 110 volts or so down the line) allowing for amateur

surveillance applications.



Once the insulation is stripped away, these two wires, the

red and green, should be matched with the red and green in

the telephone wire and then properly taped to insure no

static will occur.  In 99% of the applications we've found,

we seldom find them with static, clicks, hums, or any other

noise that would alert the subject of a bug.  We have seen

instances where people have used bubble gum to seal the wires

once spliced.  (The FEDS love finding fingerprints in bubble

gum.  It makes their job so easy...)



Here's another tactic that has been used in phone tapping.

We've seen cases where extensions of people's phones are

installed at other locations where the tap can be easily

accessible.  Generally, the person doing the bugging will

design a plan to get the phone company to have a new line

with the same number installed (an extension) in a

predetermined location, often under the guise of an "office

extension."  Then, they connect the recording device, and

monitor calls for several weeks.  Before the person being

bugged receives their phone bill reflecting the added charge

for the new phone line, the culprit is long gone. . .



                      THE CORDLESS PHONE



Cordless phones are in near every American home.  Sure they

are convenient to carry around with us, but they can easily

transmit both side of your phone calls to anyone with a

police scanner for up to a mile away!



          BEWARE OF DISCUSSING CONFIDENTIAL BUSINESS

                     ON CORDLESS PHONES!



The box in which your cordless phone was purchased usually

warns you that these phones are transmitters.  Yet, every day

millions of people, both at work and home, continue to use

them, spreading their business through the airwaves.  There

is little you can do to stop people from hearing your calls,

short of purchasing a scrambling device.  Even then the party

to whom you are talking would also have to have a matching

descrambling device to understand you.  This would so

restrict the use of your cordless phone to the point that you

may as well use a regular telephone.



Cordless phones are easily intercepted.  For your own

security, I'll share how it is done.  Again, I am not an

attorney and highly recommend you consult with a competent

attorney should you decide to use this technique for

information gathering...



It works like this.  Nearly all cordless phones (with the

exception of the new 900 megahertz phones) transmit in the

46.00 to 47.00 megahertz band.  To intercept the cordless

phone, the investigator will use the search feature on the

scanner and program 46.00 as the low and 47.00 as the high

and touch the search/scan key.  If a cordless phone is in use

in the area it will lock in on that frequency.  He or she

can, then, hear both sides of the conversation crystal clear

for up to a mile.  The use of a good low-band antenna with

the scanner will increase the reception range of a cordless

phone even further.



Many private investigators will drive by a subject's home

searching these frequencies, and obtain "inside information"

that will provide leads that later help them to document

evidence.



It is arguable whether this is an invasion of privacy or a

violation of federal law because of the notice on the carton

in which this type telephone is purchased.  It clearly states

they are not private.  Many investigators and attorneys argue

that people waive their rights to the expectation of privacy

when they use such a telephone.



                  TO GO A STEP FURTHER. . .



There is also a device called an "auto scanner recording

control" which will allow a police scanner to be connected to

a tape recorder.  It activates the recorder to begin

recording--only when the cordless phone is in use.

Investigators will determine the exact frequency of the

subject's phone, and then place a battery powered scanner

with the scanner recorder control in a water-tight baggie or

other container, conceal the equipment in hedges, culverts,

etc., near the subject's home or office.  Later he or she

will retrieve the equipment along with the "juicy info" of

the targets telephone conversations!  And to go a step

further, the investigator will often use a long-play recorder

that will record hours of conversation.



Surveillance companies and spy shops sell recorders that will

record up to 10 hours of conversation on a single cassette

tape.  If you are a business man who often uses a tape

recorder for business, this may be a real help to you.



   >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><

   > INTEC Investigative Technology recently bought  <

   > the entire plans line of famous surveillance    <

   > genius John Wilson.  For a free copy of the plan<

   > to modify a tape recorder for long play, call   <

   > our Fax-Vault from your fax and get document    <

   > number 120 at 601-876-9740 or 6757              <

   > Another free service of INTEC!                  <

   ><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

The concepts mentioned above are only the "tip of the

iceberg" of what is happening in illegal electronic

surveillance.  I could write an entire book on just this

topic.  Since we have only so much space to write each month,

I will have to continue this topic in future issues.

However, if you have specific questions or comments, you may

call my office or send a fax, and we will try to answer your

questions.



Please don't be so foolish as to believe, "It couldn't happen

to you," or you may find a lot of your deals going sour.

Perhaps, someone may even decide your secrets are worth more

than your bank account....



   BEWARE:  IT IS HAPPENING MORE THAN YOU WOULD BELIEVE!



I have turned down many multi-thousand dollar jobs to do

industrial spying, and if I am getting these offers, so are

many others.  You can never be too careful.



There are devices which will help you to detect illegal

telephone taps, transmitters, and conventional hard-wire

bugs, but the best protection is to follow a few rules:



     a. Never say anything on the phone you wouldn't want to

        say in a courtroom.



     b. Never trust anyone. If what you say could hurt you

        and your business, shut-up.



     c. If you must discuss very confidential business,

        create a loud background noise that will hinder the

        less expensive electronic devices, i.e., a radio or

        television with loud volume, a fan running in the

        same room, etc., and talk quietly.  You would be

        amazed at how effective this background noise is

        against electronic invasion of your privacy.



     d. When discussing very delicate issues, never meet in

        anyone's office.  Meet in public places and be sure

        to be observant of any bulges which could be

        concealed tape recorders, etc.



Until next time. . . .



Michael E. Enlow, Legal Investigator



P.S.  Please don't hesitate to call if you have questions

      or send e-mail to michael@enlow.com.



*****************************************************************

NOTE:



To retrieve a copy of our complete "insider" catalog of books, 

newsletters, special reports, and the famous John Wilson catalog 

of high-tech, electronic surveillance and countermeasure gadgetry,

along with schematics and very simple construction plans, send 

e-mail to catalog@enlow.com. The catalog will be automatically 

e-mailed back to you.



INTEC Investigative Technology

voice: (601) 783-6037

fax: (601) 783-2111

Internet: info@enlow.com

Anonymous FTP: enlow.com (198.92.134.50) 