(*----------------------------------------------------------------------*)
(*               ASCII character set definitions                        *)
(*----------------------------------------------------------------------*)

const
  NUL  = 0;         (* NULL Character  *)
  ETX  = 3;         (* ETX = ^C        *)
  ENQ  = 5;         (* ENQ Character   *)
  ACK  = 6;
  BELL = 7;         (* BELL Character  *)
  BS   = 8;         (* Backspace Char  *)
  HT   = 9;         (* Horizontal Tab  *)
  LF   = 10;        (* Line Feed       *)
  VT   = 11;        (* Vertical Tab    *)
  FF   = 12;        (* Form Feed       *)
  CR   = 13;        (* Carriage Return *)
  SO   = 14;        (* Start grahics   *)
  SI   = 15;        (* End graphics    *)
  XON  = 17;        (* XON  Character  *)
  XOFF = 19;        (* XOFF Character  *)
  CAN  = 24;
  SUB  = 26;        (* EOF Character   *)
  ESC  = 27;        (* Escape          *)
  SP   = 32;        (* Space           *)
  DEL  = 127;       (* DEL  Character  *)

