cc86  ABS.C
masm ABS.mac\;
rm ABS.mac
cc86  ATOI.C
masm ATOI.mac\;
rm ATOI.mac
cc86  ATOIB.C
masm ATOIB.mac\;
rm ATOIB.mac
cc86  AVAIL.C
masm AVAIL.mac\;
rm AVAIL.mac
cc86  CALLOC.C
masm CALLOC.mac\;
rm CALLOC.mac
cc86  CLEARERR.C
masm CLEARERR.mac\;
rm CLEARERR.mac
cc86  CSEEK.C
masm CSEEK.mac\;
rm CSEEK.mac
cc86  CSYSLIB.C
masm CSYSLIB.mac\;
rm CSYSLIB.mac
cc86  CTELL.C
masm CTELL.mac\;
rm CTELL.mac
cc86  DTOI.C
masm DTOI.mac\;
rm DTOI.mac
cc86  EXIT.C
masm EXIT.mac\;
rm EXIT.mac
cc86  FCLOSE.C
masm FCLOSE.mac\;
rm FCLOSE.mac
cc86  FEOF.C
masm FEOF.mac\;
rm FEOF.mac
cc86  FERROR.C
masm FERROR.mac\;
rm FERROR.mac
cc86  FGETC.C
masm FGETC.mac\;
rm FGETC.mac
cc86  FGETS.C
masm FGETS.mac\;
rm FGETS.mac
cc86  FOPEN.C
masm FOPEN.mac\;
rm FOPEN.mac
cc86  FPRINTF.C
masm FPRINTF.mac\;
rm FPRINTF.mac
cc86  FPUTC.C
masm FPUTC.mac\;
rm FPUTC.mac
cc86  FPUTS.C
masm FPUTS.mac\;
rm FPUTS.mac
cc86  FREAD.C
masm FREAD.mac\;
rm FREAD.mac
cc86  FREE.C
masm FREE.mac\;
rm FREE.mac
cc86  FREOPEN.C
masm FREOPEN.mac\;
rm FREOPEN.mac
cc86  FSCANF.C
masm FSCANF.mac\;
rm FSCANF.mac
cc86  FWRITE.C
masm FWRITE.mac\;
rm FWRITE.mac
cc86  GETARG.C
masm GETARG.mac\;
rm GETARG.mac
cc86  GETCHAR.C
masm GETCHAR.mac\;
rm GETCHAR.mac
cc86  ISALNUM.C
masm ISALNUM.mac\;
rm ISALNUM.mac
cc86  ISALPHA.C
masm ISALPHA.mac\;
rm ISALPHA.mac
cc86  ISASCII.C
masm ISASCII.mac\;
rm ISASCII.mac
cc86  ISATTY.C
masm ISATTY.mac\;
rm ISATTY.mac
cc86  ISCNTRL.C
masm ISCNTRL.mac\;
rm ISCNTRL.mac
cc86  ISCONS.C
masm ISCONS.mac\;
rm ISCONS.mac
cc86  ISDIGIT.C
masm ISDIGIT.mac\;
rm ISDIGIT.mac
cc86  ISGRAPH.C
masm ISGRAPH.mac\;
rm ISGRAPH.mac
cc86  ISLOWER.C
masm ISLOWER.mac\;
rm ISLOWER.mac
cc86  ISPRINT.C
masm ISPRINT.mac\;
rm ISPRINT.mac
cc86  ISPUNCT.C
masm ISPUNCT.mac\;
rm ISPUNCT.mac
cc86  ISSPACE.C
masm ISSPACE.mac\;
rm ISSPACE.mac
cc86  ISUPPER.C
masm ISUPPER.mac\;
rm ISUPPER.mac
cc86  ISXDIGIT.C
masm ISXDIGIT.mac\;
rm ISXDIGIT.mac
cc86  ITOA.C
masm ITOA.mac\;
rm ITOA.mac
cc86  ITOAB.C
masm ITOAB.mac\;
rm ITOAB.mac
cc86  ITOD.C
masm ITOD.mac\;
rm ITOD.mac
cc86  ITOO.C
masm ITOO.mac\;
rm ITOO.mac
cc86  ITOU.C
masm ITOU.mac\;
rm ITOU.mac
cc86  ITOX.C
masm ITOX.mac\;
rm ITOX.mac
cc86  LEFT.C
masm LEFT.mac\;
rm LEFT.mac
cc86  LEXCMP.C
masm LEXCMP.mac\;
rm LEXCMP.mac
cc86  MALLOC.C
masm MALLOC.mac\;
rm MALLOC.mac
cc86  OTOI.C
masm OTOI.mac\;
rm OTOI.mac
cc86  PAD.C
masm PAD.mac\;
rm PAD.mac
cc86  POLL.C
masm POLL.mac\;
rm POLL.mac
cc86  PUTCHAR.C
masm PUTCHAR.mac\;
rm PUTCHAR.mac
cc86  PUTS.C
masm PUTS.mac\;
rm PUTS.mac
cc86  RENAME.C
masm RENAME.mac\;
rm RENAME.mac
cc86  REVERSE.C
masm REVERSE.mac\;
rm REVERSE.mac
cc86  REWIND.C
masm REWIND.mac\;
rm REWIND.mac
cc86  SIGN.C
masm SIGN.mac\;
rm SIGN.mac
cc86  STRCAT.C
masm STRCAT.mac\;
rm STRCAT.mac
cc86  STRCHR.C
masm STRCHR.mac\;
rm STRCHR.mac
cc86  STRCMP.C
masm STRCMP.mac\;
rm STRCMP.mac
cc86  STRCPY.C
masm STRCPY.mac\;
rm STRCPY.mac
cc86  STRLEN.C
masm STRLEN.mac\;
rm STRLEN.mac
cc86  STRNCAT.C
masm STRNCAT.mac\;
rm STRNCAT.mac
cc86  STRNCMP.C
masm STRNCMP.mac\;
rm STRNCMP.mac
cc86  STRNCPY.C
masm STRNCPY.mac\;
rm STRNCPY.mac
cc86  STRRCHR.C
masm STRRCHR.mac\;
rm STRRCHR.mac
cc86  TOASCII.C
masm TOASCII.mac\;
rm TOASCII.mac
cc86  TOLOWER.C
masm TOLOWER.mac\;
rm TOLOWER.mac
cc86  TOUPPER.C
masm TOUPPER.mac\;
rm TOUPPER.mac
cc86  UNGETC.C
masm UNGETC.mac\;
rm UNGETC.mac
cc86  UNLINK.C
masm UNLINK.mac\;
rm UNLINK.mac
cc86  UTOI.C
masm UTOI.mac\;
rm UTOI.mac
cc86  XTOI.C
masm XTOI.mac\;
rm XTOI.mac
masm call.mac\;
masm cend.mac\;
