; Submit file to compile a single Small-C/Plus file
; file from the current drive.  The resulting .OBJ
; file is left on drive M:
;
; The compilation takes place on drive M:
;
; Usage:
; 
;   cc-c file                     : no optimisation
;   cc-c file opt                 : optimise code
;   cc-c file opt -c              : compact optimisation
;
era m:$1.*
<y
pip m:=$1.c
m:
cc0 -m $1
era m:$1.c
z$2 $3 $1
zmac $1=$1
era m:$1.asm
b:
