; Submit file to compile and link a single Small-C/Plus
; file from the current drive, with the result going to
; drive B:
;
; The compilation takes place on drive M:
;
; Usage:
; 
;   cc file                     : no optimisation
;   cc file opt                 : optimise code
;   cc file opt -c              : compact optimisation
;
era m:$1.*
<y
pip m:=$1.c
m:
cc0 $1
era m:$1.c
z$2 $3 $1
zmac $1=$1
era $1.asm
zres b: clib $1
submit m:clib.sub
