/*
 * This file is automatically generated.  Do not edit.
 */
#define VERSION "0.6"
#define GIT_BRANCH "master"
#define GIT_HASH "9db72e929c9ba98ea5ca9ffb72a684b534b770ec"
#define GIT_HASH_SHORT "9db72e9"
#define GIT_DATE "2023-04-03 00:27:21 +0000"
