I don't listen to weakies!
*
I don't want to be immortal through my works;
I want to be immortal through not dying.
*
A man is only as good as the tool he uses.
*
The marvels of today's modern technology
include the development of a soda can, which when
discarded will last forever...and a $7,000 car which
when properly cared for will rust out in two or three years.
*
Heisenberg may have been hereQbut it is uncertain.
*
Be afraid.  Be very afraid.
*
Turn off the computer and go to bed.
*
The next system crash is just a 1/60 of a second away.
*
Seek simplicity, and distrust it.
*
God ever arithmetizes.
*
Back off, buddy.  I'm a scientist.
*
Chess is a sea in which a gnat may drink and an elephant may bathe.
*
Difficulties mastered are opportunities won.
*
Great spirits have always encountered
violent opposition from mediocre minds.
*
The journey of a thousand miles begins with a single step.
*
Life is a journey, not a destination.
*
Trifles make perfection, but perfection itself is no trifle.
*
Nothing is particularly hard if you divide it into small jobs.
*
He who rides a tiger cannot dismount.
*
Consider nothing as impossible before it has come to pass.
*
Don't ignore details.  Lick them.
*
Problems are the price of progress.
*
There is always one moment when the door opens and lets the future in.
*
Give me the right word and the right accent and I will move the world.
*
It is better to know some of the questions than all of the answers.
*
Time is the devourer of all things.
*
"Twinkle, twinkle, little star,
I don't wonder what you are
For by spectroscopic ken
I know that you are hydrogen."
                  -Author unknown
*
The human animal differs from the lesser primates
in his passion for lists of "Ten Best".
*
As far as the laws of mathematics refer to reality,
they are not certain; and as far as they are certain,
they do not refer to reality.
                        - Albert Einstein
*
Cauliflower is nothing but Cabbage with a College Education.
                        -- Mark Twain
*
Weiner's Law of Libraries:
There are no answers, only cross references.
*
When two people are under the influence of the
most violent, most insane,  most delusive,
and most transient of passions, they are
required to swear that they will remain in that excited,
abnormal, and exhausting condition
continuously until death do them part.
            -- George Bernard Shaw
*
"Why is that we rejoice at a birth and grieve at a funeral?
Is it because we are not the one involved?"
                              -Mark Twain
*
"Woe is the isolationist who tries to turn the cogs of his own engine
while ignoring the machinations about him."
*
If you pick up a starving dog and make him prosperous, he will not bite
you.  This is the principal difference between a dog and a man.
                           -- Mark Twain
*
Principle of Conservation of Ignorance:
A false notion once arrived at is not easily dislodged.
*
Principle of Maximum Simplicity:
Everything should be made as simple as possible--but no simpler.
                           -- Albert Einstein
*
Principle of Dynamic Queuing Theory:
The other line always moves faster.
*
Principle of State Queuing Theory:
The other line is always shorter.
*
There was a young fellow named Fisk
Whose fencing was agile and brisk,
So fast was his action
The Fitzgerald contraction
Diminished his sword to a disk.
*
If a thing is not worth doing, it is not worth doing well.
*
Chess, like music, has the power to make men happy.
*
Men and nations will act rationally when
all other possiblities have been exhausted.
*
For every action there is an equal and opposite government program.
*
If A = B and B = C, then A = C, except where void or prohibited by law.
*
Too much of a good thing is WONDERFUL.
                          -- Mae West
*
One good reason why computers can do more work than people is
that they never have to stop and answer the phone.
*
The average woman would rather have beauty than brains,
because the average man can see better than he can think.
*
On the heights it is warmer than one thinks in the valleys.
*
Nudists are people who wear one-button suits.
*
America may be unique in being a country which has leapt from
barbarism to decadence without touching civilization.
                     -- John O'Hara
*
Some men are discovered; others are found out.
*
Words must be weighed, not counted.
*
By failing to prepare, you are preparing to fail.
*
Your mind understands what you have been taught;
your heart, what is true.
*
Creditors have much better memories than debtors.
*
You shouldn't try to teach a pig to sing.
You waste your time and it annoys the pig.
*
He who invents adages for others to peruse takes
along a rowboat when going on a cruise.
*
Mistakes are oft the stepping stones to failure.
*
The attacker must vanquish; the defender need only survive.
*
To criticize the incompetent is easy;
it is more difficult to criticize the competent.
*
He who has imagination without learning has wings but no feet.
*
Men seldom show dimples to girls who have pimples.
*
One man tells a falsehood, a hundred repeat it as true.
*
Even a hawk is an eagle among crows.
*
Even the smallest candle burns brighter in the dark.
*
Let a fool hold his tongue and he will pass for a sage.
*
A woman is like a highway:
soft shoulders and dangerous curves.
*
Those who can, do; those who can't, simulate.
*
Those who can, do; those who can't, write.
Those who can't write go to the State Department.
*
Laugh, and the world ignores you.  Crying doesn't help either.
*
No amount of genius can overcome a preoccupation with detail.
*
You will feel hungry again in another hour.
*
The computer loves you and has a wonderful plan for your life.
*
Many are called, few are chosen.  Fewer still get to do the choosing.
*
God made the integers; all else is the work of Man.
--- or ---
Man made God;  all else is the work of integers.
*
He who hesitates is miles away from the next freeway exit.
*
Time is nature's way of making sure that
everything doesn't happen at once.
*
The future isn't what it used to be. (It never was.)
*
If God had wanted you to go around nude,
He would have given you bigger hands.
*
It is better to have loved and lost than just to have lost.
*
Making predictions is always difficult, especially about the future.
*
All that glitters has a high refractive index.
*
A foolish consistency is the hobgoblin of little minds.
*
Quantity is no substitute for quality,
but it's the only one we've got.
*
The more things change, the more they'll never be the same again.
*
Those who can, do; those who can't, teach.
Those who can't teach, administrate.
*
It is better to remain silent and be thought a fool than to
open one's mouth and remove all doubt.
*
The proof is left to the student as a pudding.
*
The student is in the pudding as an exercise.
*
The exercise is proof of the student.
*
Never confuse motion for action. 
                  -- Benjamin Franklin
*
Will Rodgers never met Howard Cosell.
*
WARNING -- This system is now being controlled by IBM.
*
I would rather have a bottle in front of
me than a frontal lobotomy.
*
The pudding is in the student.
 The student needs some exercise.
*
Girls don't give hugs if your code has bugs.
*
Random stomping seldom catches bugs.
*
I'd give my right arm to be ambidextrous...
*
Feature: a desirable attribute of a program.
Bug: an undesireable attribute of a program
to be fixed in the near future.
Beature: an undesireable attribute of a program which
will not be fixed no matter how hard you beg.
Fug: a desirable attribute of a program which 
has been repaired, thereby making a new bug.
*
Computer scientists can do anything except chemistry
and accounting, and that is by choice.
*
Ignorance is the ally of deception.
*
Sometimes the problem isn't the high cost of living,
but the cost of high living.
*
Beauty is only skin deep, but ugly goes all the way to the bone.
*
A man of means means more than a man who's mean.
*
When you have eliminated the impossible, whatever remains,
however improbable, must be the truth.
                   --  Sherlock Holmes
*
Never argue with a fool. Others may
not be able to tell the difference.
*
If it jams, force it; if it breaks, it needed replacing anyway.
*
Anything that isn't nailed down is mine.
Anything I can pry loose isn't nailed down.
*
The probability of the bread falling jelly-side down is
directly proportional to the cost of the carpet.
*
It is morally wrong to allow a sucker to hold on to his money.
*
The person who can smile when something goes wrong has
obviously thought of someone to blame it on.
*
Things are more like they are now 
than they have ever been before.
*
The difference between capitalism and
socialism is that in capitalism,  man exploits man,
while in socialism it's the other way around.
*
One picture is worth a thousand reels of magnetic tape.
*
Subtlety is the art of saying what you think,
and getting out of the way before it is understood.
*
I know you believe you understand what
you think I said, but I'm not sure you realize what
you heard is not what I really meant.
*
To the systems programmers, the customers
and users serve only as a test load.
*
The reasonable man adapts himself to the
world as it exists; the unreasonable man persists
in trying to adapt the world to himself. Therefore,
all progress depends on the unreasonable man.
*
Out of intense complexities, intense simplicities emerge.
*
TOMORROW HAS BEEN CANCELED, DUE TO AN ERROR NOTED ELSEWHERE.
*
Before they made you they broke the mold.
*
A whole hog is better than no hog at all.
*
Necessity is the mother of strange bedfellows.
*
To one with a hammer everything is a nail.
*
Few things are harder to put up with than
the annoyance of a good example.
*
Before God and the bus driver we are all equal.
*
Appliances must carry energy-efficiency labels, but
so far the government doesn't require them on people.
*
When a fellow says it hain't the money but
the principle o' the thing, its th' money.
*
A home is the place where part of the family
waits until the others have returned with the car.
*
We'd all like to vote for the best man,
but he's never a candidate.
*
The man who does not read good books has
no advantage over the man who can't read.
*
If it weren't for optimists, pessimists
would never know how unhappy they are.
*
Vanity is quite often the greatest enemy of competence.
*
Personally I am always ready to learn,
although I do not always like being taught. 
                   -- Sir Winston Churchill
*
BIT - The quantum of misinformation.
*
MICROPROCESSOR - Twenty years of architectural
bungling concentrated onto a single chip.
*
COMPUTER SCIENCE - A study akin to numerology
and astrology, but lacking the precision of the
former and the success of the latter.
*
One incompetent manager can negate the
work of dozens of excellent engineers.
*
This place is a hotbed of inertia.
*
Whoever dies with the most toys wins.
*
The college lecture is the process whereby the
notes of the professor become the notes of
the student without passing through the minds of either.
*
I ain't met a broad yet that don't understand
a slap across the face or a slug from a 45.
                   -- Mike Hammer
*
To beat the grass is to risk startling the snake.
*
Your situation is as precarious as piled eggs.
*
Too many evil deeds ruin the doer.
*
An easy life saps one's will.
*
A dog is a dog unless he is facing you; then he is Mr. Dog.
                        -- Haitian Proverb
*
Take care of the luxuries and the necessities
will take care of themselves.
*
Nuke the gay whales.
*
The universe is laughing behind your back.
*
If you suspect a man, don't employ him.
*
Committee: an organism with 3 or more bellies and no brain.
*
It's not reality that's important, but how you perceive things.
*
Like winter snow on summer lawn,
time past is time gone.
*
Deprive a mirror of its silver and
even the Czar won't see his face.
*
Troglodytism does not necessarily imply a low cultural level.
*
You cannot kill time without injuring eternity.
*
How you look depends on where you go.
*
Just because something is scientifically
true, doesn't mean it's not weird.
*
Even if you win the rat race, you're still a rat.
*
A man who turns green has eschewed protein.
*
Sin has many tools, but a lie is
the handle which fits them all.
*
With clothes the new are best, with friends the old are best.
*
He is truly wise who gains wisdom from another's mishap.
*
Today is the first day of the rest of your life, or
today is the last day of your life so far.
*
The early worm gets the bird.
